### ISSUE TITLE
Indexers unavailable due to failures for more than 6 hours: altHUB (Prowlarr)	

### ISSUE THREAD

**Issue by alamoudimoh** [Prowlarr/Prowlarr#1012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i open sonarr/ any of the *arr the indexer altHUB will report failure if connected through prowlarr, but will work fine if directly maintained into*arr

below is the response from altHUB 

Hi. No issues outside of the hardware migration, have you checked the status page?
Are you using RSS feeds?

### Expected Behavior

to work normally

### Environment

```markdown
Version
0.2.0.1678
Package Version
0.2.0.1678 by michiel@vanbaak.eu
.NET
Yes (6.0.3)
DB Migration
15
Database
Sqlite 3.37.2
AppData directory
/usr/local/prowlarr
```

### What branch are you running?

Master

### Trace Logs?

`2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2022-05-20 22:03:26.9|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2022-05-20 22:03:26.9|Trace|HttpClient|Req: [GET] https://prowlarr.servarr.com/v1/update/develop?version=0.2.0.1678&os=bsd&arch=X64&runtime=netcore&runtimeVer=6.0.3&dbType=SQLite&active=true
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'firstdayofweek' defaultValue:'0'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'calendarweekcolumnheader' defaultValue:'ddd M/D'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'shortdateformat' defaultValue:'MMM D YYYY'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'longdateformat' defaultValue:'dddd, MMMM D YYYY'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'timeformat' defaultValue:'h(:mm)a'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'plexclientidentifier' defaultValue:'15fa89a5-7628-440f-88db-9bc6cd59afb6'
2022-05-20 22:03:26.9|Trace|ConfigService|Writing Setting to database. Key:'plexclientidentifier' Value:'15fa89a5-7628-440f-88db-9bc6cd59afb6'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'rijndaelpassphrase' defaultValue:'5ef506ed-862b-4bcd-9391-47adc2c20706'
2022-05-20 22:03:26.9|Trace|ConfigService|Writing Setting to database. Key:'rijndaelpassphrase' Value:'5ef506ed-862b-4bcd-9391-47adc2c20706'
2022-05-20 22:03:26.9|Trace|ConfigService|Using default config value for 'hmacpassphrase' defaultValue:'a49d6dc2-c94b-4b6d-b7e7-2da6cf048385'
2022-05-20 22:03:26.9|Trace|ConfigService|Writing Setting to database. Key:'hmacpassphrase' Value:'a49d6dc2-c94b-4b6d-b7e7-2da6cf048385'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'rijndaelsalt' defaultValue:'64db8474-96d0-427b-852c-ab80a02fa429'
2022-05-20 22:03:27.0|Trace|ConfigService|Writing Setting to database. Key:'rijndaelsalt' Value:'64db8474-96d0-427b-852c-ab80a02fa429'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'hmacsalt' defaultValue:'6f236287-4055-4bae-a278-4dd1f9e3966c'
2022-05-20 22:03:27.0|Trace|ConfigService|Writing Setting to database. Key:'hmacsalt' Value:'6f236287-4055-4bae-a278-4dd1f9e3966c'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-05-20 22:03:27.0|Trace|EventAggregator|Publishing ConfigSavedEvent
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-05-20 22:03:27.0|Trace|ServerSideNotificationService|Getting server side health notifications
2022-05-20 22:03:27.0|Trace|HttpClient|Req: [GET] https://prowlarr.servarr.com/v1/notification?version=0.2.0.1678&os=bsd&arch=X64&runtime=netcore&branch=develop
2022-05-20 22:03:27.0|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-20 22:03:27.0|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-05-20 22:03:27.0|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2022-05-20 22:03:27.0|Trace|Http|Res: 161 [PUT] /api/v1/config/host: 202.Accepted (177 ms)
2022-05-20 22:03:27.0|Debug|Api|[PUT] /api/v1/config/host: 202.Accepted (177 ms)
2022-05-20 22:03:27.4|Trace|HttpClient|Res: [GET] https://prowlarr.servarr.com/v1/update/develop?version=0.2.0.1678&os=bsd&arch=X64&runtime=netcore&runtimeVer=6.0.3&dbType=SQLite&active=true: 200.OK (569 ms)
2022-05-20 22:03:27.4|Trace|ServerSideNotificationService|Getting server side health notifications
2022-05-20 22:03:27.4|Trace|HttpClient|Req: [GET] https://prowlarr.servarr.com/v1/notification?version=0.2.0.1678&os=bsd&arch=X64&runtime=netcore&branch=develop
2022-05-20 22:03:27.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-20 22:03:27.5|Trace|HttpClient|Res: [GET] https://prowlarr.servarr.com/v1/notification?version=0.2.0.1678&os=bsd&arch=X64&runtime=netcore&branch=develop: 200.OK (481 ms)
2022-05-20 22:03:27.5|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-05-20 22:03:27.5|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-05-20 22:03:27.5|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-05-20 22:03:27.5|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-05-20 22:03:27.5|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-05-20 22:03:27.5|Trace|Http|Req: 162 [GET] /api/v1/health (from 192.168.8.100)
2022-05-20 22:03:27.5|Trace|Http|Res: 162 [GET] /api/v1/health: 200.OK (1 ms)
2022-05-20 22:03:27.5|Debug|Api|[GET] /api/v1/health: 200.OK (1 ms)
2022-05-20 22:03:27.8|Trace|HttpClient|Res: [GET] https://prowlarr.servarr.com/v1/notification?version=0.2.0.1678&os=bsd&arch=X64&runtime=netcore&branch=develop: 200.OK (384 ms)
2022-05-20 22:03:27.8|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-05-20 22:03:27.8|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-05-20 22:03:27.8|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-05-20 22:03:27.8|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-05-20 22:03:27.8|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-05-20 22:03:27.8|Trace|Http|Req: 163 [GET] /api/v1/health (from 192.168.8.100)
2022-05-20 22:03:27.8|Trace|Http|Res: 163 [GET] /api/v1/health: 200.OK (0 ms)
2022-05-20 22:03:27.8|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2022-05-20 22:03:31.6|Trace|Http|Req: 164 [POST] /api/v1/indexer/test (from 192.168.8.100)
2022-05-20 22:03:31.6|Trace|IndexerHttpClient|Req: [GET] https://althub.co.za/api?t=caps&apikey=(removed)
2022-05-20 22:03:31.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-20 22:03:31.9|Trace|IndexerHttpClient|Res: [GET] https://althub.co.za/api?t=caps&apikey=(removed) 403.Forbidden (338 ms)
2022-05-20 22:03:31.9|Warn|IndexerHttpClient|HTTP Error - Res: [GET] https://althub.co.za/api?t=caps&apikey=(removed) 403.Forbidden
2022-05-20 22:03:31.9|Debug|NewznabCapabilitiesProvider|Failed to get Newznab API capabilities from https://althub.co.za

[v0.2.0.1678] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://althub.co.za/api?t=caps&apikey=(removed)   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 115
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxied(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 50
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Newznab\NewznabCapabilitiesProvider.cs:line 60
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

2022-05-20 22:03:31.9|Warn|Newznab|Unable to connect to indexer

[v0.2.0.1678] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://althub.co.za/api?t=caps&apikey=(removed)   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 115
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxied(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 50
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Newznab\NewznabCapabilitiesProvider.cs:line 60
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.<>c__DisplayClass4_0.<GetCapabilities>b__0() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Newznab\NewznabCapabilitiesProvider.cs:line 36
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Newznab\NewznabCapabilitiesProvider.cs:line 38
   at NzbDrone.Core.Indexers.Newznab.Newznab.get_PageSize() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Newznab\Newznab.cs:line 32
   at NzbDrone.Core.Indexers.Newznab.Newznab.GetRequestGenerator() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Newznab\Newznab.cs:line 36
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 438
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

2022-05-20 22:03:31.9|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.2.0.1678] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-05-20 22:03:32.0|Trace|ProwlarrErrorPipeline|Handling Exception
2022-05-20 22:03:32.0|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[v0.2.0.1678] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-05-20 22:03:32.3|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
2022-05-20 22:03:32.3|Trace|Http|Res: 164 [POST] /api/v1/indexer/test: 400.BadRequest (686 ms)
2022-05-20 22:03:32.3|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (686 ms)
2022-05-20 22:03:35.5|Trace|Http|Req: 165 [GET] /api/v1/health (from 192.168.8.100)
2022-05-20 22:03:35.5|Trace|Http|Req: 166 [GET] /api/v1/system/status (from 192.168.8.100)
2022-05-20 22:03:35.5|Trace|Http|Res: 165 [GET] /api/v1/health: 200.OK (1 ms)
2022-05-20 22:03:35.5|Debug|Api|[GET] /api/v1/health: 200.OK (1 ms)
2022-05-20 22:03:36.5|Trace|Http|Res: 166 [GET] /api/v1/system/status: 200.OK (1008 ms)
2022-05-20 22:03:36.5|Debug|Api|[GET] /api/v1/system/status: 200.OK (1008 ms)
2022-05-20 22:03:38.2|Trace|Http|Req: 167 [GET] /api/v1/log/file (from 192.168.8.100)
2022-05-20 22:03:38.2|Trace|Http|Res: 167 [GET] /api/v1/log/file: 200.OK (2 ms)
2022-05-20 22:03:38.2|Debug|Api|[GET] /api/v1/log/file: 200.OK (2 ms)
2022-05-20 22:03:42.6|Trace|Http|Req: 168 [GET] /logfile/prowlarr.trace.txt (from 192.168.8.100)`

[AB#3168](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3168)

**Comment by DevYukine** [comment]
Updater Your Prowlarr to latest version & restart it then remove and readd althub, they changed the url of where there api is located 👍

**Comment by alamoudimoh** [comment]
> Updater Your Prowlarr to latest version & restart it then remove and readd althub, they changed the url of where there api is located 👍

ur last statement fixed it without update, i had just to take a look at the url, thanks

btw... in FreeBSD it is kida hard to update prowlarr, unlike sonarr

**Comment by bakerboy448** [comment]
For posterity - fixed with https://github.com/Prowlarr/Prowlarr/commit/ed46c5c86d24d8a5a57bfd7a21cb5a865f7406bf
