### ISSUE TITLE
yggtorrent change domain

### ISSUE THREAD

**Issue by Reupireup** [Prowlarr/Prowlarr#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hello all,

According to their homepage, yggtorrent change their domain extension from www5.yggtorrent.la to www5.yggtorrent.fi
From now, the default yggtorrent prowlarr configuration is www5.yggtorrent.la.
From the last domain name change, I know I can change edit /var/lib/prowlarr/Definitions/yggtorrent.yml applying the new url (https://github.com/Prowlarr/Prowlarr/issues/948#issuecomment-1095035587), but the default config must be adapted for new users.

### Expected Behavior

connection to yggtorrent working

### Environment

```markdown
- OS: 
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

[Error] Cardigann: An error occurred while processing indexer feed. https://www5.yggtorrent.la/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date 

[v0.3.0.1730] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: **Got redirected to another domain. Try changing the indexer URL to https://www5.yggtorrent.fi/**.

   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.CheckIfLoginIsNeeded(HttpResponse response) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 939

   at NzbDrone.Core.Indexers.Cardigann.Cardigann.CheckIfLoginNeeded(HttpResponse httpResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 154

   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 385

   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 298

   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 175

[AB#3227](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3227)

**Comment by Qstick** [comment]
Just went in on indexers repo

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/97eff767e6a13835ff8e571fcde94777debec6e2
