### ISSUE TITLE
NzbDrone[...]ApplicationService server is currently unavailable

### ISSUE THREAD

**Issue by berkgercek** [Prowlarr/Prowlarr#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to update sonarr / radarr during a first time set up of prowlarr on dietpi (installed using the dietpi-launcher system), I have added three trackers and then attempt to update the apps to reflect this. The update fails with the following error message:

```
NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:7878/api/v3/indexer'
```

### Expected Behavior

I would expect a successful sync of the downstream apps with the three trackers I added (RARBG, Nyaa, 1337x, all of which were added using the prowlarr templates)

### Steps To Reproduce

0. Build dietpi with deluge / prowlarr / sonarr / radarr
1. Add aforementioned 3 trackers
2. Add Radarr/Sonarr with hard-coded IP (static on local network)
3. Attempt to run "Sync app indexers"

### Environment

```markdown
- OS: DietPi 8.5.1
- Prowlarr: 0.3.0.1730
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

```

2022-06-06 22:22:32.4|Info|ReleaseSearchService|Searching indexer(s): [Rarbg] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2030, 2050, 2040, 2060, 2045]
2022-06-06 22:22:35.1|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- Category: Label plugin not activated
2022-06-06 22:22:38.7|Info|ReleaseSearchService|Searching indexer(s): [Nyaa.si] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2020]
2022-06-06 22:22:38.7|Info|Cardigann|Adding request: https://nyaa.si/?q=&f=0&c=1_0&s=id&o=desc
2022-06-06 22:22:38.8|Info|Cardigann|Adding request: https://nyaa.si/?q=&p=2&f=0&c=1_0&s=id&o=desc
2022-06-06 22:22:52.9|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://localhost:8989/api/v3/indexer'
2022-06-06 22:24:05.2|Info|Cardigann|Adding request: https://nyaa.si/?q=&p=2&f=0&c=1_0&s=id&o=desc
2022-06-06 22:24:18.5|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://localhost:7878/api/v3/indexer'
2022-06-06 22:44:33.7|Info|Microsoft.Hosting.Lifetime|Application is shutting down...
2022-06-06 22:44:35.3|Info|ConsoleApp|Exiting main.
2022-06-06 22:45:08.0|Info|Bootstrap|Starting Prowlarr - /opt/prowlarr/Prowlarr - Version 0.3.0.1730
2022-06-06 22:45:23.2|Info|AppFolderInfo|Data directory is being overridden to [/mnt/dietpi_userdata/prowlarr]
2022-06-06 22:45:34.5|Info|AppFolderInfo|Data directory is being overridden to [/mnt/dietpi_userdata/prowlarr]
2022-06-06 22:45:38.9|Info|MigrationController|*** Migrating data source=/mnt/dietpi_userdata/prowlarr/prowlarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-06-06 22:45:42.6|Info|MigrationController|*** Migrating data source=/mnt/dietpi_userdata/prowlarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-06-06 22:45:46.7|Info|Microsoft.Hosting.Lifetime|Application is shutting down...
2022-06-06 22:45:47.6|Fatal|ConsoleApp|EPIC FAIL!

[v0.3.0.1730] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 77
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Console\ConsoleApp.cs:line 43


2022-06-06 22:46:27.1|Info|Bootstrap|Starting Prowlarr - /opt/prowlarr/Prowlarr - Version 0.3.0.1730
2022-06-06 22:46:30.2|Info|AppFolderInfo|Data directory is being overridden to [/mnt/dietpi_userdata/prowlarr]
2022-06-06 22:46:53.8|Info|AppFolderInfo|Data directory is being overridden to [/mnt/dietpi_userdata/prowlarr]
2022-06-06 22:46:57.9|Info|MigrationController|*** Migrating data source=/mnt/dietpi_userdata/prowlarr/prowlarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-06-06 22:47:02.1|Info|MigrationController|*** Migrating data source=/mnt/dietpi_userdata/prowlarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-06-06 22:47:06.8|Info|Microsoft.Hosting.Lifetime|Now listening on: http://[::]:9696
2022-06-06 22:47:13.0|Info|CommandExecutor|Starting 3 threads for tasks.
2022-06-06 22:47:24.4|Info|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2022-06-06 22:47:24.4|Info|Microsoft.Hosting.Lifetime|Hosting environment: Production
2022-06-06 22:47:24.4|Info|Microsoft.Hosting.Lifetime|Content root path: /
2022-06-06 22:50:54.6|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5040, 5030, 5070]
2022-06-06 22:50:55.6|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2022-06-06 22:51:31.8|Info|Cardigann|Adding request: https://1337x.to/cat/TV/time/desc/1/
2022-06-06 22:52:02.3|Info|Cardigann|Adding request: https://1337x.to/cat/Music/time/desc/1/
2022-06-06 22:52:33.6|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://localhost:8989/api/v3/indexer'
2022-06-06 22:52:33.8|Info|ReleaseSearchService|Searching indexer(s): [Rarbg] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5030, 5040, 5045]
2022-06-06 22:52:39.2|Warn|HttpClient|HTTP Error - Res: [POST] http://localhost:8989/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2022-06-06 22:52:39.4|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://localhost:8989/api/v3/indexer]
2022-06-06 22:52:39.6|Info|ReleaseSearchService|Searching indexer(s): [Nyaa.si] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5070]
2022-06-06 22:52:39.6|Info|Cardigann|Adding request: https://nyaa.si/?q=&f=0&c=1_0&s=id&o=desc
2022-06-06 22:53:50.8|Info|Cardigann|Adding request: https://nyaa.si/?q=&p=2&f=0&c=1_0&s=id&o=desc
2022-06-06 22:54:19.4|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://localhost:8989/api/v3/indexer'
2022-06-06 22:54:20.3|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2070, 2030, 2010, 2040, 2060, 2045]
2022-06-06 22:54:20.3|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2022-06-06 22:54:46.9|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2070, 2030, 2010, 2040, 2060, 2045]
2022-06-06 22:54:46.9|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2022-06-06 22:54:59.1|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5040, 5030, 5070]
2022-06-06 22:54:59.1|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2022-06-06 22:55:03.6|Info|Cardigann|Adding request: https://1337x.to/cat/TV/time/desc/1/
2022-06-06 22:55:34.4|Info|Cardigann|Adding request: https://1337x.to/cat/TV/time/desc/1/
2022-06-06 22:55:46.0|Info|Cardigann|Adding request: https://1337x.to/cat/TV/time/desc/1/
2022-06-06 22:55:49.0|Info|Cardigann|Adding request: https://1337x.to/cat/Music/time/desc/1/
2022-06-06 22:55:58.4|Info|ReleaseSearchService|Searching indexer(s): [Rarbg] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2030, 2050, 2040, 2060, 2045]
2022-06-06 22:55:59.9|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://localhost:7878/api/v3/indexer'
2022-06-06 22:56:00.7|Info|ReleaseSearchService|Searching indexer(s): [Nyaa.si] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2020]
2022-06-06 22:56:00.8|Info|Cardigann|Adding request: https://nyaa.si/?q=&f=0&c=1_0&s=id&o=desc
2022-06-06 22:56:25.3|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:7878/api/v3/indexer'
2022-06-06 22:56:25.6|Info|ReleaseSearchService|Searching indexer(s): [Nyaa.si] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2020]
2022-06-06 22:56:25.7|Info|Cardigann|Adding request: https://nyaa.si/?q=&f=0&c=1_0&s=id&o=desc
2022-06-06 22:56:30.1|Info|Cardigann|Adding request: https://1337x.to/cat/Music/time/desc/1/
2022-06-06 22:56:37.4|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:8989/api/v3/indexer'
2022-06-06 22:56:40.3|Info|ReleaseSearchService|Searching indexer(s): [Rarbg] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5030, 5040, 5045]
2022-06-06 22:56:42.7|Warn|HttpClient|HTTP Error - Res: [POST] http://10.0.0.39:8989/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2022-06-06 22:56:42.8|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://10.0.0.39:8989/api/v3/indexer]
2022-06-06 22:56:43.2|Info|ReleaseSearchService|Searching indexer(s): [Nyaa.si] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5070]
2022-06-06 22:56:43.2|Info|Cardigann|Adding request: https://nyaa.si/?q=&f=0&c=1_0&s=id&o=desc
2022-06-06 22:56:45.7|Info|Cardigann|Adding request: https://1337x.to/cat/Music/time/desc/1/
2022-06-06 22:57:40.2|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://localhost:7878/api/v3/indexer'
2022-06-06 22:58:00.0|Info|Cardigann|Adding request: https://nyaa.si/?q=&p=2&f=0&c=1_0&s=id&o=desc
2022-06-06 22:58:05.5|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:7878/api/v3/indexer'
2022-06-06 22:58:16.2|Info|Cardigann|Adding request: https://nyaa.si/?q=&p=2&f=0&c=1_0&s=id&o=desc
2022-06-06 22:58:22.9|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:8989/api/v3/indexer'
2022-06-06 22:58:28.6|Info|Cardigann|Adding request: https://nyaa.si/?q=&p=2&f=0&c=1_0&s=id&o=desc
2022-06-06 22:58:56.2|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2070, 2030, 2010, 2040, 2060, 2045]
2022-06-06 22:58:56.2|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2022-06-06 22:59:00.2|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5040, 5030, 5070]
2022-06-06 22:59:00.2|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2022-06-06 22:59:52.5|Info|Cardigann|Adding request: https://1337x.to/cat/TV/time/desc/1/
2022-06-06 22:59:55.7|Info|Cardigann|Adding request: https://1337x.to/cat/TV/time/desc/1/
2022-06-06 23:00:34.5|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:7878/api/v3/indexer'
2022-06-06 23:00:34.7|Info|ReleaseSearchService|Searching indexer(s): [Nyaa.si] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2020]
2022-06-06 23:00:34.7|Info|Cardigann|Adding request: https://nyaa.si/?q=&f=0&c=1_0&s=id&o=desc
2022-06-06 23:00:35.9|Info|Cardigann|Adding request: https://1337x.to/cat/Music/time/desc/1/
2022-06-06 23:00:39.0|Info|Cardigann|Adding request: https://1337x.to/cat/Music/time/desc/1/
2022-06-06 23:00:40.0|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:8989/api/v3/indexer'
2022-06-06 23:00:40.3|Info|ReleaseSearchService|Searching indexer(s): [Rarbg] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5030, 5040, 5045]
2022-06-06 23:00:42.7|Warn|HttpClient|HTTP Error - Res: [POST] http://10.0.0.39:8989/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2022-06-06 23:00:42.8|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://10.0.0.39:8989/api/v3/indexer]
2022-06-06 23:00:43.1|Info|ReleaseSearchService|Searching indexer(s): [Nyaa.si] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5070]
2022-06-06 23:00:43.1|Info|Cardigann|Adding request: https://nyaa.si/?q=&f=0&c=1_0&s=id&o=desc
2022-06-06 23:02:07.7|Info|Cardigann|Adding request: https://nyaa.si/?q=&p=2&f=0&c=1_0&s=id&o=desc
2022-06-06 23:02:14.6|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:7878/api/v3/indexer'
2022-06-06 23:02:15.3|Info|Cardigann|Adding request: https://nyaa.si/?q=&p=2&f=0&c=1_0&s=id&o=desc
2022-06-06 23:02:22.9|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:8989/api/v3/indexer'
2022-06-06 23:02:23.3|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2070, 2030, 2010, 2040, 2060, 2045]
2022-06-06 23:02:23.4|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2022-06-06 23:03:07.2|Info|Cardigann|Adding request: https://1337x.to/cat/TV/time/desc/1/
2022-06-06 23:03:50.1|Info|Cardigann|Adding request: https://1337x.to/cat/Music/time/desc/1/
2022-06-06 23:04:03.2|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:7878/api/v3/indexer'
2022-06-06 23:04:03.4|Info|ReleaseSearchService|Searching indexer(s): [Nyaa.si] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2020]
2022-06-06 23:04:03.4|Info|Cardigann|Adding request: https://nyaa.si/?q=&f=0&c=1_0&s=id&o=desc
2022-06-06 23:04:15.6|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2022-06-06 23:04:57.6|Info|Cardigann|Adding request: https://nyaa.si/?q=&f=0&c=1_0&s=id&o=desc
2022-06-06 23:05:30.3|Info|Cardigann|Adding request: https://nyaa.si/?q=&p=2&f=0&c=1_0&s=id&o=desc
2022-06-06 23:05:43.3|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService server is currently unavailable. The operation has timed out.: 'http://10.0.0.39:7878/api/v3/indexer'
```

[AB#3238](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3238)

**Comment by berkgercek** [comment]
Additionally, a log from Sonarr regarding the request:

```

[v3.0.8.1507] System.Net.WebException: The operation has timed out.: 'http://10.0.0.39:9696/3/api?t=tvsearch&cat=5000,5070&extended=1&apikey=(removed)&offset=0&limit=100' ---> System.Net.WebException: The operation has timed out.
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <aed771a663ce4492b0d140f9adc4649b>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00016] in <aed771a663ce4492b0d140f9adc4649b>:0 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x00123] in <bb4bd9a0099f48de84455bcef8e9c0ae>:0 
   --- End of inner exception stack trace ---
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x001ec] in <bb4bd9a0099f48de84455bcef8e9c0ae>:0 
  at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookieContainer) [0x00086] in <bb4bd9a0099f48de84455bcef8e9c0ae>:0 
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00008] in <bb4bd9a0099f48de84455bcef8e9c0ae>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchIndexerResponse (NzbDrone.Core.Indexers.IndexerRequest request) [0x00076] in <f308258701c9443d9f77fbbaa937a672>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00000] in <f308258701c9443d9f77fbbaa937a672>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00044] in <f308258701c9443d9f77fbbaa937a672>:0 

2022-06-06 23:02:23.1|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
2022-06-06 23:03:14.2|Warn|MonoDebugCheck|Mono is not running with --debug switch
2022-06-06 23:12:43.5|Info|RssSyncService|Starting RSS Sync
2022-06-06 23:12:43.5|Warn|FetchAndParseRssService|No available indexers. check your configuration.
2022-06-06 23:12:43.5|Info|DownloadDecisionMaker|No results found
2022-06-06 23:12:43.5|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
```

**Comment by berkgercek** [comment]
After switching the "Full Sync" the issue semi-resolved and now some of the indexers appear on Sonarr / Radarr. Granted it's only 1337x on Radarr and 1337x/RARBG on Sonarr. Nyaa doesn't appear on either.

**Comment by bakerboy448** [comment]
If everything is on the same server you should be using localhost.

Regardless application timeouts are not a prowlarr bug
