### ISSUE TITLE
Value cannot be null. (Parameter 'returnType') Version 0.4.1.1838

### ISSUE THREAD

**Issue by deathbybandaid** [Prowlarr/Prowlarr#1046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Web interface has stopped functioning, and simply shows the message on screen:

![image](https://user-images.githubusercontent.com/18010545/176188607-ca2d0397-23a6-4a33-a395-d9336d2c5e72.png)

### Expected Behavior

Prior to this recent update, I'd not experienced any issue with prowlarr

### Steps To Reproduce

1. In the environment listed below

2. With this config:
````
<Config>
  <LogLevel>info</LogLevel>
  <UrlBase></UrlBase>
  <UpdateMechanism>BuiltIn</UpdateMechanism>
  <Branch>develop</Branch>
  <AuthenticationMethod>None</AuthenticationMethod>
  <ApiKey>REDACTED</ApiKey>
  <BindAddress>*</BindAddress>
  <Port>9696</Port>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>
  <LaunchBrowser>True</LaunchBrowser>
  <SslCertPath></SslCertPath>
  <SslCertPassword></SslCertPassword>
  <AnalyticsEnabled>False</AnalyticsEnabled>
  <UpdateAutomatically>True</UpdateAutomatically>
  <InstanceName>Prowlarr</InstanceName>
</Config>
````

3. Running with `/opt/Prowlarr/Prowlarr -nobrowser -data=/etc/Prowlarr/` via systemd
4.  See Tracelog

### Environment

```markdown
- OS: Ubuntu 21.10 x86_64 running in LXC
- Prowlarr: 0.4.1.1838
- Docker Install: No
- Using Reverse Proxy: Yes, error still exists on port 9696 though.
- Browser: Chromium, Firefox
```

### What branch are you running?

Develop

### Trace Logs?

````
2022-06-28 13:12:25.7|Info|Bootstrap|Starting Prowlarr - /opt/Prowlarr/Prowlarr - Version 0.4.1.1838
2022-06-28 13:12:25.8|Info|AppFolderInfo|Data directory is being overridden to [/etc/Prowlarr]
2022-06-28 13:12:26.1|Info|AppFolderInfo|Data directory is being overridden to [/etc/Prowlarr]
2022-06-28 13:12:26.3|Info|MigrationController|*** Migrating data source=/etc/Prowlarr/prowlarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-06-28 13:12:26.4|Info|MigrationController|*** Migrating data source=/etc/Prowlarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-06-28 13:12:26.5|Info|Microsoft.Hosting.Lifetime|Now listening on: http://[::]:9696
2022-06-28 13:12:26.7|Info|CommandExecutor|Starting 3 threads for tasks.
2022-06-28 13:12:27.4|Error|EventAggregator|IndexerFactory failed while processing [ApplicationStartedEvent]

[v0.4.1.1838] System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 60
   at NzbDrone.Core.Datastore.BasicRepository`1.All() in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 87
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.RemoveMissingImplementations() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 170
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Handle(ApplicationStartedEvent message) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 142
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


2022-06-28 13:12:27.5|Info|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2022-06-28 13:12:27.5|Info|Microsoft.Hosting.Lifetime|Hosting environment: Production
2022-06-28 13:12:27.5|Info|Microsoft.Hosting.Lifetime|Content root path: /
2022-06-28 13:12:27.5|Error|TaskExtensions|Task Error

[v0.4.1.1838] System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 60
   at NzbDrone.Core.Datastore.BasicRepository`1.All() in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 87
   at NzbDrone.Core.Indexers.IndexerFactory.All() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 48
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Active() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 153
   at NzbDrone.Core.Indexers.IndexerFactory.Active() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 93
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.GetAvailableProviders() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 91
   at NzbDrone.Core.Indexers.IndexerFactory.Enabled(Boolean filterBlockedIndexers) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 220
   at NzbDrone.Core.HealthCheck.Checks.IndexerCheck.Check() in D:\a\1\s\src\NzbDrone.Core\HealthCheck\Checks\IndexerCheck.cs:line 24
   at NzbDrone.Core.HealthCheck.HealthCheckService.<>c.<PerformHealthCheck>b__15_0(IProvideHealthCheck c) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 82
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.HealthCheck.HealthCheckService.PerformHealthCheck(IProvideHealthCheck[] healthChecks) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 82
   at NzbDrone.Core.HealthCheck.HealthCheckService.HandleAsync(ApplicationStartedEvent message) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 121
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in D:\a\1\s\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 121
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2022-06-28 13:12:32.7|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.4.1.1838] System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 60
   at NzbDrone.Core.Datastore.BasicRepository`1.All() in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 87
   at NzbDrone.Core.Indexers.IndexerFactory.All() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 48
   at Prowlarr.Api.V1.ProviderControllerBase`3.GetAll() in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 47
   at lambda_method76(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorize>
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-06-28 13:12:32.8|Warn|ProwlarrErrorPipeline|System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 60
   at NzbDrone.Core.Datastore.BasicRepository`1.All() in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 87
   at NzbDrone.Core.Indexers.IndexerFactory.All() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 48
   at Prowlarr.Api.V1.ProviderControllerBase`3.GetAll() in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 47
   at lambda_method76(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorize>
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[v0.4.1.1838] System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 60
   at NzbDrone.Core.Datastore.BasicRepository`1.All() in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 87
   at NzbDrone.Core.Indexers.IndexerFactory.All() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 48
   at Prowlarr.Api.V1.ProviderControllerBase`3.GetAll() in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 47
   at lambda_method76(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorize>
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-06-28 13:12:32.9|Fatal|ProwlarrErrorPipeline|Request Failed. GET /api/v1/indexer

[v0.4.1.1838] System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 60
   at NzbDrone.Core.Datastore.BasicRepository`1.All() in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 87
   at NzbDrone.Core.Indexers.IndexerFactory.All() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 48
   at Prowlarr.Api.V1.ProviderControllerBase`3.GetAll() in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 47
   at lambda_method76(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorize>
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-06-28 13:12:39.7|Info|Microsoft.Hosting.Lifetime|Application is shutting down...
2022-06-28 13:12:39.8|Info|ConsoleApp|Exiting main.
````

[AB#3322](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3322)

**Comment by Qstick** [comment]
Can you please run this on your DB and post results, this seems to be a migration 17 issue for some

```
SELECT Implementation, ConfigContract FROM Indexers
```

**Comment by deathbybandaid** [comment]
````
Newznab|NewznabSettings
Newznab|NewznabSettings
Newznab|NewznabSettings
Newznab|NewznabSettings
Newznab|NewznabSettings
Newznab|NewznabSettings
Newznab|NewznabSettings
Newznab|NewznabSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Rarbg|RarbgSettings
SubsPlease|NoAuthTorrentBaseSettings
TorrentParadiseMl|TorrentParadiseMlSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
````

**Comment by Qstick** [comment]
Perfect thanks

**Comment by vitobotta** [comment]
Hi! How to fix this issue? I have this in my table:

```
sqlite> SELECT Implementation, ConfigContract FROM Indexers;
Newznab|NewznabSettings
Newznab|NewznabSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Rarbg|RarbgSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
TorrentsCSV|NoAuthTorrentBaseSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
Cardigann|CardigannSettings
```

**Comment by deathbybandaid** [comment]
@vitobotta if autoupdates are enabled, no action should* be required. I was the new release tag via my rss feed reader today, and my prowlarr is back up.
