### ISSUE TITLE
DanishBytes get wrong download url

### ISSUE THREAD

**Issue by mbryde** [Prowlarr/Prowlarr#1066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you try and download any torrent from DanishBytes you can see in the logs it's trying to download the torrent from `/torrent/{ID}` but if you take the same url and just add a (s) too it then it works: `/torrents/{ID}`

### Expected Behavior

Should download the .torrent file from the indexer on the new url: `/torrents/{ID}`.

### Steps To Reproduce

1. Add DanishBytes to prowlarr
2. Search for any torrent using that indexer
3. try to download any torrent and it will fail

### Environment

```markdown
- OS: Ubuntu 22.04
- Prowlarr: 0.4.2.1879
- Docker Install: Docker version 20.10.17, build 100c701
- Using Reverse Proxy: Traefik
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

```
2022-07-14 11:42:19.5|Fatal|ProwlarrErrorPipeline|Request Failed. GET /5/download

[v0.4.2.1879] NzbDrone.Core.Exceptions.ReleaseUnavailableException: Downloading torrent failed
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://dbytes.org/torrent/download/52393.]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 115
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.Download(Uri link) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 222
<!DOCTYPE html>
<html class="no-js" lang="da">

<head>
    <meta charset="utf-8">
    <title>    Error 404: Page Not Found
 - DBy v0.96</title>

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Error">
    <meta property="og:title" content="DBy v0.96">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://dbytes.org/img/og.png">
    <meta property="og:url" content="https://dbytes.org">
    <meta name="csrf-token" content="">

    <link rel="shortcut icon" href="https://dbytes.org/favicon.ico" type="image/x-icon">
    <link rel="icon" href="https://dbytes.org/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="/css/app.css?id=(removed)=20">
    
</head>

<body>
    <section class="container content" id="content-area" style="min-height: 344px;">
        <div class="jumbotron shadowed">
            <div class="container">
                    <h1 class="mt-5 text-center">
        <i class="fas fa-question-circle text-warning"></i> Error 404: Page Not Found
    </h1>
    
    <div class="separator"></div>
    
    <p class="text-center">
        The Requested Page Cannot Be Found! Not Sure What Your Looking For But Check The
                Address And Try Again!
    </p>

                <p class="text-center">
                    <a href="https://dbytes.org" role="button" class="btn btn-labeled btn-primary">
                        <i class="fas fa-home"></i> Go Home
                    </a>
                </p>
            </div>
        </div>
    </section>
</body>

</html>

   --- End of inner exception stack trace ---
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.Download(Uri link) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 222
   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 160
   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in D:\a\1\s\src\Prowlarr.Api.V1\Indexers\NewznabController.cs:line 223
   at lambda_method228(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

[AB#3363](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3363)

**Comment by mbryde** [comment]
I may also add that Jackett handles it fine. Seemes odd since both appeares to use cardigann for this indexer.

**Comment by mbryde** [comment]
> What's your definition file look like?
> 
> That URL it's trying is not possible given the definition. https://github.com/Prowlarr/Indexers/blob/713fa6bffa610d83a925f39d8326f0aa4cb7261a/definitions/v6/danishbytes-api.yml#L99

Where do I find the definition file?

**Comment by bakerboy448** [comment]
So the site changed and requires `torrents` not `torrent` for the download url now?

**Comment by bakerboy448** [comment]
Also what's the URL jackett is using for the grab?

their definition is the same as ours, so what you're seeing frankly makes no sense.

**Comment by mbryde** [comment]
> So the site changed and requires `torrents` not `torrent` for the download url now?

Changing to `torrents` did indeed work like a charm. Works flawless now.

**Comment by bakerboy448** [comment]
Jackett's definition is still /torrent/ though...?

**Comment by garfield69** [comment]
Is it possible that the user does not have the rsskey loaded in their danishbytes-api indexer config?
this would explain the download attempt using `https://dbytes.org/torrent/download/52393.` which is incomplete since it is missing the rsskey at the end, hence site returns a 404 not found.
The use of `https://dbytes.org/torrents/download/52393` is the browser html way of downloading a danishbytes torrent for when an .rsskey is not provided.

**Comment by bakerboy448** [comment]
Closing based on Garfield's comments which is confirmed from the log.

@garfield69 thanks! I knew something looked funky/short with it, but didn't have a chance to look too in-depth yet and that knowledge of the html route helps!

Based on the definitions and the logs, this appears to be a user config issue and not a bug....can reopen if needed
