### ISSUE TITLE
AnimeWorld Indexer error 404

### ISSUE THREAD

**Issue by thisisusenet** [Prowlarr/Prowlarr#107]
**Describe the bug**
If I want to add the AnimeWorld Indexer and click on "Test" I get an error. This might happen because of the recent changes to the animeworld indexer. The browse site of animeworld is now the following: https://animeworld.cx/torrents?incldead=0&orderby=added&sort=desc%5D&perPage=25

**To Reproduce**
 Errormessage

**Expected behavior**
Testing the indexer should work without any errors.
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6604064/prowlarr.trace.txt)

**Errormessage**
```
2021-06-06 12:29:30.6|Info|Cardigann|Adding request: https://animeworld.cx/browse.php?search=&incldead=0&orderby=added&sort=desc
2021-06-06 12:29:30.8|Warn|Cardigann|HTTP Error - Res: [GET] https://animeworld.cx/browse.php?search=&incldead=0&orderby=added&sort=desc: 404.NotFound
2021-06-06 12:29:30.8|Warn|Cardigann|Unable to connect to indexer

[v0.1.0.361] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://animeworld.cx/browse.php?search=&incldead=0&orderby=added&sort=desc]
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 452
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 370
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 559
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

```

**Platform Information (please complete the following information):**
 - OS: Centos 7
 - Docker: No
 - .NET Version (System -> Status): 5.0.6
 - Prowlarr Version: 0.1.0.361
 - Prowlarr Branch: nightly

**Comment by Qstick** [comment]
Indexer update pushed to Prowlarr/Indexers, this should be fixed with your next definition update
