### ISSUE TITLE
Yggtorrent return error

### ISSUE THREAD

**Issue by eephyne** [Prowlarr/Prowlarr#1077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no result with yggtorrent and prowlarr show an errror

### Expected Behavior

showing result :)

### Steps To Reproduce

simply do a search throught prowlarr or sonarr/radarr and look at the log.

### Environment

```markdown
- OS: arch linux
Version
0.4.2.1879
Package Version
0.4.2.1879-ls60 by linuxserver.io
- Using Reverse Proxy: yes throught httpd
- Browser: chrome
```

### What branch are you running?

Master

### Trace Logs?
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-07-29 12:24:37.0|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-07-29 12:24:37.0|Trace|EventAggregator|Publishing ConfigSavedEvent
2022-07-29 12:24:37.0|Trace|HttpClient|Req: [GET] https://prowlarr.servarr.com/v1/update/develop?version=0.4.2.1879&os=linuxmusl&arch=X64&runtime=netcore&runtimeVer=6.0.6&dbType=SQLite&active=true
2022-07-29 12:24:37.0|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-07-29 12:24:37.0|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2022-07-29 12:24:37.0|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-07-29 12:24:37.0|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-07-29 12:24:37.0|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-07-29 12:24:37.0|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-07-29 12:24:37.0|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-07-29 12:24:37.0|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2022-07-29 12:24:37.0|Trace|Http|Res: 348 [PUT] /api/v1/config/host: 202.Accepted (39 ms)
2022-07-29 12:24:37.0|Debug|Api|[PUT] /api/v1/config/host: 202.Accepted (39 ms)
2022-07-29 12:24:37.1|Trace|Http|Req: 349 [GET] /api/v1/health (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:37.1|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-07-29 12:24:37.1|Trace|Http|Res: 349 [GET] /api/v1/health: 200.OK (3 ms)
2022-07-29 12:24:37.1|Debug|Api|[GET] /api/v1/health: 200.OK (3 ms)
2022-07-29 12:24:37.4|Trace|HttpClient|Res: [GET] https://prowlarr.servarr.com/v1/update/develop?version=0.4.2.1879&os=linuxmusl&arch=X64&runtime=netcore&runtimeVer=6.0.6&dbType=SQLite&active=true: 200.OK (349 ms)
2022-07-29 12:24:37.4|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-07-29 12:24:37.4|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-07-29 12:24:37.4|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-07-29 12:24:37.4|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-07-29 12:24:37.4|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-07-29 12:24:37.4|Trace|Http|Req: 350 [GET] /api/v1/health (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:37.4|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-07-29 12:24:37.4|Trace|Http|Res: 350 [GET] /api/v1/health: 200.OK (2 ms)
2022-07-29 12:24:37.4|Debug|Api|[GET] /api/v1/health: 200.OK (2 ms)
2022-07-29 12:24:38.8|Trace|Http|Req: 351 [GET] /api/v1/health (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:38.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-07-29 12:24:38.8|Trace|Http|Res: 351 [GET] /api/v1/health: 200.OK (3 ms)
2022-07-29 12:24:38.8|Debug|Api|[GET] /api/v1/health: 200.OK (3 ms)
2022-07-29 12:24:38.8|Trace|Http|Req: 352 [GET] /api/v1/system/status (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:38.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-07-29 12:24:38.8|Trace|Http|Res: 352 [GET] /api/v1/system/status: 200.OK (5 ms)
2022-07-29 12:24:38.8|Debug|Api|[GET] /api/v1/system/status: 200.OK (5 ms)
2022-07-29 12:24:41.0|Trace|Scheduler|Pending Tasks: 1
2022-07-29 12:24:41.0|Trace|CommandQueueManager|Publishing MessagingCleanup
2022-07-29 12:24:41.0|Trace|CommandQueueManager|Checking if command is queued or started: MessagingCleanup
2022-07-29 12:24:41.0|Trace|CommandQueueManager|Inserting new command: MessagingCleanup
2022-07-29 12:24:41.0|Trace|CommandExecutor|MessagingCleanupCommand -> CleanupCommandMessagingService
2022-07-29 12:24:41.0|Trace|CommandQueueManager|Marking command as started: MessagingCleanup
2022-07-29 12:24:41.0|Trace|CommandQueueManager|Cleaning up old commands
2022-07-29 12:24:41.0|Trace|CommandQueueManager|Updating command status
2022-07-29 12:24:41.0|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-07-29 12:24:41.0|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-07-29 12:24:41.1|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Messaging.Commands.MessagingCleanupCommand
2022-07-29 12:24:41.2|Trace|Http|Req: 353 [POST] /api/v1/indexer/testall (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:41.2|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-07-29 12:24:41.2|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-07-29 12:24:41.2|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-07-29 12:24:41.2|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-07-29 12:24:41.2|Trace|CommandExecutor|MessagingCleanupCommand <- CleanupCommandMessagingService [00:00:00.0069310]
2022-07-29 12:24:41.2|Trace|Cardigann|Getting Basic search
2022-07-29 12:24:41.2|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2022-07-29 12:24:41.2|Debug|Cardigann|Populating config vars
2022-07-29 12:24:41.2|Info|Cardigann|Adding request: https://www.sharewood.tv/filterTorrents?search=&description=&uploader=&sorting=created_at&direction=desc&qty=100&freeleech=
2022-07-29 12:24:41.2|Debug|Cardigann|Downloading Feed https://www.sharewood.tv/filterTorrents?search=&description=&uploader=&sorting=created_at&direction=desc&qty=100&freeleech=
2022-07-29 12:24:41.2|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2022-07-29 12:24:41.2|Trace|IndexerHttpClient|Req: [GET] https://www.sharewood.tv/filterTorrents?search=&description=&uploader=&sorting=created_at&direction=desc&qty=100&freeleech=
2022-07-29 12:24:41.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-07-29 12:24:41.2|Trace|Http|Req: 354 [GET] /api/v1/command (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:41.2|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-07-29 12:24:41.2|Trace|CommandQueueManager|Getting all commands
2022-07-29 12:24:41.2|Trace|Http|Res: 354 [GET] /api/v1/command: 200.OK (3 ms)
2022-07-29 12:24:41.2|Debug|Api|[GET] /api/v1/command: 200.OK (3 ms)
2022-07-29 12:24:41.3|Trace|Http|Req: 355 [POST] /signalr/messages?access_token=(removed)&id=(removed) (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:41.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: SignalR was successfully authenticated.
2022-07-29 12:24:41.3|Trace|Http|Res: 355 [POST] /signalr/messages?access_token=(removed)&id=(removed) 200.OK (5 ms)
2022-07-29 12:24:41.9|Trace|IndexerHttpClient|Res: [GET] https://www.sharewood.tv/filterTorrents?search=&description=&uploader=&sorting=created_at&direction=desc&qty=100&freeleech=: 200.OK (744 ms)
2022-07-29 12:24:41.9|Debug|Cardigann|Parsing
2022-07-29 12:24:41.9|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2022-07-29 12:24:42.0|Debug|Cardigann|Got 25 releases
2022-07-29 12:24:42.0|Trace|Cardigann|Getting Basic search
2022-07-29 12:24:42.0|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2022-07-29 12:24:42.0|Debug|Cardigann|Populating config vars
2022-07-29 12:24:42.1|Warn|Cardigann|Unable to connect to indexer

[v0.4.2.1879] System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Boolean'.
   at NzbDrone.Core.Indexers.Cardigann.CardigannBase.GetBaseTemplateVariables() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannBase.cs:line 301
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.GetQueryVariableDefaults(SearchCriteriaBase searchCriteria) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 136
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.GetSearchRequests(BasicSearchCriteria searchCriteria) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 127
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 450

2022-07-29 12:24:42.1|Trace|Http|Res: 353 [POST] /api/v1/indexer/testall: 400.BadRequest (911 ms)
2022-07-29 12:24:42.1|Debug|Api|[POST] /api/v1/indexer/testall: 400.BadRequest (911 ms)
2022-07-29 12:24:45.3|Trace|Http|Req: 356 [GET] /api/v1/log/file (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:45.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-07-29 12:24:45.3|Trace|Http|Res: 356 [GET] /api/v1/log/file: 200.OK (3 ms)
2022-07-29 12:24:45.3|Debug|Api|[GET] /api/v1/log/file: 200.OK (3 ms)
2022-07-29 12:24:47.4|Trace|Http|Req: 357 [GET] /logfile/prowlarr.trace.txt (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:47.4|Debug|Prowlarr.Http.Authentication.BasicAuthenticationHandler|AuthenticationScheme: Basic was successfully authenticated.
2022-07-29 12:24:47.4|Trace|Http|Res: 357 [GET] /logfile/prowlarr.trace.txt: 200.OK (5 ms)
2022-07-29 12:24:56.8|Trace|Http|Req: 358 [POST] /signalr/messages?access_token=(removed)&id=(removed) (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:24:56.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: SignalR was successfully authenticated.
2022-07-29 12:24:56.8|Trace|Http|Res: 358 [POST] /signalr/messages?access_token=(removed)&id=(removed) 200.OK (4 ms)
2022-07-29 12:25:09.1|Trace|Http|Req: 359 [GET] /logfile/prowlarr.trace.txt (from 92.*.*.61 Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36)
2022-07-29 12:25:09.1|Debug|Prowlarr.Http.Authentication.BasicAuthenticationHandler|AuthenticationScheme: Basic was successfully authenticated.

**Comment by bakerboy448** [comment]
- Info logs are invalid for bug reports

**Comment by eephyne** [comment]
> * Info logs are invalid for bug reports

Sorry, I updated to trace Logs. It's on my cellphone so sorry if it's not formatted well.

**Comment by bakerboy448** [comment]
Try removing and readding it

it doesn't look like there's any reason for it to be failing

https://github.com/Prowlarr/Prowlarr/blob/efffeebe7c2c09f48c9b400883b5ebc22cd0a9ed/src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs#L301

**Comment by eephyne** [comment]
indeed, removing and readding it worked, sorry for not trying this before sending issue here :/ .

Thank you
