### ISSUE TITLE
Film-Paleis.me Custom CF-like DDOS page

### ISSUE THREAD

**Issue by timmarinus** [Prowlarr/Prowlarr#1089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using indexer Film-Paleis.me (Dutch private indexer)

the test is not going through even though the DDOS protection is setup with flaresolverr.

Error message is: **Login failed: No form found on https://www.film-paleis.me/login.php using form selector form[action="takelogin.php"]**

See attachted log files for more details.

### Expected Behavior

Able to test the indexer and use it to search for downloads.

### Steps To Reproduce

1. Click on indexer
2. Click on test button

### Environment

```markdown
Version: 0.4.3.1921
Package Version: testing-f597ffc by hotio
.NET: Yes (6.0.6)
Docker: Yes
DB Migration: 21
Database: Sqlite 3.38.5
AppData directory: /config
Startup directory: /app/bin
Mode: Console
```

### What branch are you running?

Develop

### Trace Logs?

2022-08-07 17:36:14.8|Debug|Api|[POST] /api/v1/command: 201.Created (51 ms)
2022-08-07 17:36:14.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-07 17:36:14.8|Debug|Api|[GET] /api/v1/command: 200.OK (11 ms)
2022-08-07 17:36:14.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-07 17:36:14.8|Debug|Api|[GET] /api/v1/command: 200.OK (1 ms)
2022-08-07 17:36:17.1|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-07 17:36:17.1|Debug|Api|[GET] /api/v1/log/file: 200.OK (2 ms)
2022-08-07 17:36:18.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-07 17:36:18.0|Debug|Api|[GET] /api/v1/log/file: 200.OK (3 ms)
2022-08-07 17:36:22.5|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-07 17:36:22.5|Debug|Api|[POST] /api/v1/indexer/action/getUrls: 200.OK (4 ms)
2022-08-07 17:36:23.7|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-07 17:36:23.7|Debug|Cardigann|Populating config vars
2022-08-07 17:36:23.7|Info|Cardigann|Adding request: https://www.film-paleis.me/browse.php?search=&incldead=1
2022-08-07 17:36:23.7|Debug|Cardigann|Downloading Feed https://www.film-paleis.me/browse.php?search=&incldead=1
2022-08-07 17:36:23.9|Debug|FlareSolverr|CF Protection not detected, returning original response
2022-08-07 17:36:24.0|Debug|FlareSolverr|CF Protection not detected, returning original response
2022-08-07 17:36:24.0|Warn|Cardigann|Unable to connect to indexer

[v0.4.3.1921] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannConfigException: Login failed: No form found on https://www.film-paleis.me/login.php using form selector form[action="takelogin.php"]
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 240
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 165
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 382
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 291
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 455

2022-08-07 17:36:24.0|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.4.3.1921] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-08-07 17:36:24.1|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details

[v0.4.3.1921] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-08-07 17:36:24.2|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
2022-08-07 17:36:24.2|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (465 ms)
2022-08-07 17:36:28.7|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-07 17:36:28.7|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-07 17:36:28.7|Debug|Api|[GET] /api/v1/health: 200.OK (2 ms)
2022-08-07 17:36:28.7|Debug|Api|[GET] /api/v1/system/status: 200.OK (2 ms)
2022-08-07 17:36:31.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-07 17:36:31.8|Debug|Api|[GET] /api/v1/log/file: 200.OK (2 ms)

[AB#3421](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3421)

**Comment by depemco** [comment]
I also would like to see this working again. +1

**Comment by bakerboy448** [comment]
this still occuring on v0.4.4.1947 after refreshing indexer definitions?

**Comment by depemco** [comment]
> this still occuring on v0.4.4.1947 after refreshing indexer definitions?

I just tried this and it does not solve the problem. Still having the same issue.

**Comment by timmarinus** [comment]
As Depemco already said The issue still persists in this version, as of today most up to date version the bug is still there.

Can i provide you with some logs or can i do something to help you out.

**Comment by bakerboy448** [comment]
v0.4.5 and the relating proxy fixes didn't fix it right?

Fresh clean set of logs probs would not hurt

**Comment by timmarinus** [comment]
No the issues still persitst in version V0.4.5.1960
I included an new set of logs where i tested the connection of the indexer. 

[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/9551064/prowlarr.debug.txt)

**Comment by bakerboy448** [comment]
That's HTML not logs.

**Comment by timmarinus** [comment]
sorry my bad now the new file 
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/9551085/prowlarr.debug.txt)

**Comment by bakerboy448** [comment]
Bug reports require trace logs, not debug

**Comment by timmarinus** [comment]
Hereby the trace logs
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/9551119/prowlarr.trace.txt)

**Comment by depemco** [comment]
I think the problem is in the cloudflare DDoS-protection. Because the error says the form cannot be found.

**Comment by bakerboy448** [comment]
There's no cloudflare protection.

The site has their own custom rate limit and you are IP banned.

Not really a Prowlarr bug nor anything Prowlarr can do.

**Comment by timmarinus** [comment]
The page has not blocked me, outside of prowlarr i can succesfully login in a browser session. 

previously the website worked fine.

**Comment by bakerboy448** [comment]
Yeah it's the custom weird DDOS protection the site does.  I got hit with it even opening the site in my browser.

@Qstick did the special Dutch logic get ripped out when you rewrote CF detection?

**Comment by timmarinus** [comment]
Thanks for looking in to it, if i can test something for you guys or translate some of the dutch frases or responses in the log files, just ask and i will happy to test it.

**Comment by Qstick** [comment]
> Yeah it's the custom weird DDOS protection the site does. I got hit with it even opening the site in my browser.
> 
> @Qstick did the special Dutch logic get ripped out when you rewrote CF detection?

What Dutch logic?

**Comment by bakerboy448** [comment]
> What Dutch logic?

https://github.com/Prowlarr/Prowlarr/commit/e85ccd5808eca02f8d21ab85bfea8c396c6d7c04

**Comment by bakerboy448** [comment]
@Qstick this was fixed or nah?

**Comment by bakerboy448** [comment]
@Qstick bp

**Comment by depemco** [comment]
I think this issue can be closed, because the website film-paleis doesn’t exist anymore since a few weeks.
