### ISSUE TITLE
Unable to connect to indexer XML exceptions

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#11]
```
2021-2-27 22:03:37.9|Debug|Newznab|Downloading Feed https://api.omgwtfnzbs.me/api?t=search&extended=1&apikey=(removed)
2021-2-27 22:03:37.9|Trace|HttpClient|Req: [GET] https://api.omgwtfnzbs.me/api?t=search&extended=1&apikey=(removed)
2021-2-27 22:03:37.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-2-27 22:03:38.1|Trace|HttpClient|Res: [GET] https://api.omgwtfnzbs.me/api?t=search&extended=1&apikey=(removed) 302.Redirect (172 ms)
2021-2-27 22:03:38.1|Trace|HttpClient|Redirected to https://omgwtfnzbs.me/updates.php
2021-2-27 22:03:38.1|Trace|HttpClient|Req: [GET] https://omgwtfnzbs.me/updates.php
2021-2-27 22:03:38.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-2-27 22:03:38.3|Trace|HttpClient|Res: [GET] https://omgwtfnzbs.me/updates.php: 200.OK (168 ms)
2021-2-27 22:03:38.3|Debug|NewznabRssParser|Truncated response content (originally 1006 characters): <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" 
"http://www.w3.org/TR/html4/strict.dtd"><html> 
<head> 
<title>Updating Site - omgwtfnzbs.me</title> 
<style type='text/css'> 
body, html { 
height:90%; 
background: #151515; 
font: 12px 'Verdana'; 
} 
#container{ 
height:100%; 
text-align: center;  
} 
#logo { 
width: 500px; 
height: 140px; 
position:relative;
top:50%; 
margin-top:-77px;  
margin-left: auto;margin-right: auto; 
background: #151515; 
color:#2D2D2D; 
}
a:link {
    text-decoration:non
2021-2-27 22:03:38.3|Trace|Newznab|Unexpected Response content (1006 bytes): <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" 
"http://www.w3.org/TR/html4/strict.dtd"><html> 
<head> 
<title>Updating Site - omgwtfnzbs.me</title> 
<style type='text/css'> 
body, html { 
height:90%; 
background: #151515; 
font: 12px 'Verdana'; 
} 
#container{ 
height:100%; 
text-align: center;  
} 
#logo { 
width: 500px; 
height: 140px; 
position:relative;
top:50%; 
margin-top:-77px;  
margin-left: auto;margin-right: auto; 
background: #151515; 
color:#2D2D2D; 
}
a:link {
    text-decoration:none;
    color:grey;  
}
a:visited {
    text-decoration:none;
    color:grey; 
}
a:hover {
    text-decoration:none;
    color:grey;  
}
a:active {
    text-decoration:none;
    color:grey;  
}
</style> 
</head> 
<body> 
<div id="container"> 
<div id="logo"><img border="0" src="pics/eCUEd.gif" title="omgwtfnzbs.me" alt="updates"><br /><br /><center><a href="index">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updating a few things, please come back later.</center></a></div> 
</div> 

</body> 
</html>
			


2021-2-27 22:03:38.3|Warn|Newznab|Unable to connect to indexer

[v0.1.0.121] System.Xml.XmlException: The 'a' start tag on line 45 position 110 does not match the end tag of 'center'. Line 45, position 203.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 114
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Newznab\NewznabRssParser.cs:line 60
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 386
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 476
RequestUri: https://omgwtfnzbs.me/updates.php;StatusCode: OK;ContentType: text/html; charset=utf-8;ContentLength: 1006;ContentSample: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" 
"http://www.w3.org/TR/html4/strict.dtd"><html> 
<head> 
<title>Updating Site - omgwtfnzbs.me</title> 
<style type='text/css'> 
body, html { 
height:90%; 
background: #151515; 
font: 12px 'Verdana'; 
} 
#container{ 
height:100%; 
text-align: center;  
} 
#logo { 
width: 500px; 
height: 140px; 
position:relative;
top:50%; 
margin-top:-77px;  
margin-left: auto;margin-right: auto; 
background: #151515; 
color:#2D2D2D; 
}
a:link {
    text-decoration:none;
    color:grey;  
}
a:visited {
    text-decoration:none;
    color:grey; 
}
a:hover {
    text-decoration:none;
    color:grey;  
}
a:active {
    text-decoration:none;
    color:grey;  
}
</style> 
</head> 
<body> 
<div id="container"> 
<div id="logo"><img border="0" src="pics/eCUEd.gif" title="omgwtfnzbs.me" alt="updates"><br /><br /><center><a href="index">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updating a few things, please come back later.</center></a></div> 
</div> 

</body> 
</html>
```

**Comment by Qstick** [comment]
Not a bug, they are updating the site
