### ISSUE TITLE
error with EliteTorrent tracker

### ISSUE THREAD

**Issue by escaparrac** [Prowlarr/Prowlarr#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I added the Elitetorrent tracker.

The movies are there, but when I search, it shows that it's disabled because of an error.

"Indexers unavailable due to failures: EliteTorrent"

When I got to the events part, I can read: An error occurred while processing indexer feed. "https://www.elitetorrent.com/page/2/?s=pikachu&x=0&y=0: Object reference not set to an instance of an object."

On page 1 there is no error, but page 2 doesn't exist on the website.

### Expected Behavior

It should not give error or not check the page 2

### Steps To Reproduce

Clean install of prowlarr in Docker
Add the downloader
Add The Pirate Bay as tracker
Radarr downloads OK + Prowlarr search function works
Add EliteTorrent as tracker
Search doesn't work and errors are thrown

### Environment

```markdown
- OS: Debian 10
- Prowlarr: 0.4.4.1947-ls64 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/9378004/prowlarr.trace.txt)

[AB#3481](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3481)

**Comment by bakerboy448** [comment]
relevant log snippet

```
2022-08-19 00:13:59.9|Trace|IndexerHttpClient|Req: [GET] https://www.elitetorrent.com/page/2/?s=detective+pikachu&x=0&y=0
2022-08-19 00:13:59.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-08-19 00:14:00.6|Trace|Scheduler|Pending Tasks: 0
2022-08-19 00:14:00.9|Trace|IndexerHttpClient|Res: [GET] https://www.elitetorrent.com/page/2/?s=detective+pikachu&x=0&y=0: 302.Redirect (0 bytes) (955 ms)
2022-08-19 00:14:00.9|Trace|Cardigann|Attempting to re-auth based on indexer search response
2022-08-19 00:14:00.9|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IIndexer>
2022-08-19 00:14:00.9|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> -> IndexerStatusController
2022-08-19 00:14:00.9|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> <- IndexerStatusController
2022-08-19 00:14:00.9|Error|Cardigann|An error occurred while processing indexer feed. https://www.elitetorrent.com/page/2/?s=detective+pikachu&x=0&y=0

[v0.4.4.1947] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 190
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 165
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 382
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 314
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 175
FeedUrl: https://www.elitetorrent.com/page/2/?s=detective+pikachu&x=0&y=0

2022-08-19 00:14:00.9|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2022-08-19 00:14:00.9|Trace|Http|Req: 162 [GET] /api/v1/indexerStatus (from 192.168.1.121 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
2022-08-19 00:14:00.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-08-19 00:14:00.9|Trace|EventAggregator|Publishing IndexerQueryEvent
```
