### ISSUE TITLE
MIRCrew indexer fails

### ISSUE THREAD

**Issue by seth100** [Prowlarr/Prowlarr#1158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Indexer MIRCrew fails

### Expected Behavior

indexer MIRCrew does not fail

### Environment

```markdown
- OS: Ubuntu 22.04
- Prowlarr: 0.4.6.1969
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 105
```

### What branch are you running?

`develop`

### Trace Logs?

```
[v0.4.6.1969] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannConfigException: Error: Il form inviato non è valido. Prova a inviarlo di nuovo.
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.CheckForError(HttpResponse loginResult, IList`1 errorBlocks) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 565
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 469
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 165
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 382
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 314
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 455


[Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 

[v0.4.6.1969] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

[AB#3905](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3905)

**Comment by seth100** [comment]
Releted to #565

**Comment by bakerboy448** [comment]
- there is no master branch
- Trace logs are not optional for bug reports. Please read and follow the instructions in the bug report template that links to the wiki that explains how to get and provide trace logs
- A two line error saying to check the logs and 1 line of the issue is neither trace logs nor enough information

**Comment by bakerboy448** [comment]
Can reopen if/when trace logs are provided

**Comment by elbryan** [comment]
[logs_mircrew.txt](https://github.com/Prowlarr/Prowlarr/files/10330706/logs_mircrew.txt)

Adding logs myself. It appears that `NzbDrone` is unable to properly login with the running version of phpbb. I would suspect that other sources, running phpbb, won't work either.

It appears that #685 fixes this, but it doesn't like so.. or perhaps those changes got rejected at some other point?

**Comment by bakerboy448** [comment]
@elbryan those are not the trace logs that have been asked for and are required for all bugs.

`Error: Il form inviato non Ã¨ valido. Prova a inviarlo di nuovo.` which translates to `Error: The submitted form is invalid. Try sending it again.`

**Comment by elbryan** [comment]
[prowlarr_trace.log](https://github.com/Prowlarr/Prowlarr/files/10335170/prowlarr_trace.log)

@bakerboy448 attached trace logs.

**Comment by bakerboy448** [comment]
> [prowlarr_trace.log](https://github.com/Prowlarr/Prowlarr/files/10335170/prowlarr_trace.log)
> 
> 
> 
> @bakerboy448 attached trace logs.

Those are not prowlarr logs, that looks like a single line error from the console.  They are certainly not trace logs.

Please visit discord to discuss why you have difficulty following the 6 steps on the wiki to get and provide trace logs as previously asked for.

**Comment by elbryan** [comment]
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/10337396/prowlarr.trace.txt)

Attached more logs. Thanks for being such a nice human being on this planet. I am sure your kindness in life doesn't go unnoticed.

**Comment by pbassx92** [comment]
Hi, there is an error in the selector of the before of the download. It should be

selector: [id^=lnk_thanks]

**Comment by ilike2burnthing** [comment]
Working fine here. This was purposefully changed to allow repeated downloads - https://github.com/Jackett/Jackett/commit/259d98c140854122045a6dba2aa23c814510286e

**Comment by pbassx92** [comment]
Tried again and prowlarr with mircrew is still not working for me.
Trying with Firefox and when doing

document.querySelector('ul.post-buttons li:nth-last-child(1) a')
I get a reference to another hidden "<a>"
<a class="js-responsive-menu-link …nu-link dropdown-toggle" href="javascript:void(0);">

Doing
document.querySelector('ul.post-buttons li:nth-last-child(2) a')
correctly select the thanks button

**Comment by ilike2burnthing** [comment]
Have you changed from the default layout/style/theme? Or have you changed any account settings which would affect this?

Are you an elevated user (e.g. uploader, admin)? Are these your own uploaded torrents?

Please provide an HTML dump of a torrent page you haven't downloaded from, and another from which you have (you may want to redact any personal information such as your username and UID).

**Comment by Novocaine85** [comment]
Hello, here you can find a random page with a "like" (or thank you) not clicked and the same page with the "like" clicked.

Username and userid have been redacted. 
[mircrew.zip](https://github.com/Prowlarr/Prowlarr/files/11192657/mircrew.zip)

should you need other information in order to fix this please kindly let me know.

**Comment by bakerboy448** [comment]
no one downloads random zip files.

please share the logs in the manner specified in the wiki and answer the questions asked

**Comment by Novocaine85** [comment]
I've just followed @ilike2burnthing instructions on the reply above yours. 
I perfectly understand your security concerns, I'll try to send you a log as soon as I can.

**Comment by Novocaine85** [comment]
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/11193918/prowlarr.debug.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/11193919/prowlarr.trace.txt)
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/11193920/prowlarr.txt)

Please kindly ask should you need any other info. Please also link me your discord channel if you wish.

Thanks

**Comment by bakerboy448** [comment]
Enable the enhanced indexer logging in the hidden settings/development page will dump the indexer responses.  Wiki has slightly more specific details

**Comment by Novocaine85** [comment]
> Enable the enhanced indexer logging in the hidden settings/development page will dump the indexer responses. Wiki has slightly more specific details

[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/11194078/prowlarr.debug.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/11194079/prowlarr.trace.txt)
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/11194080/prowlarr.txt)

**Comment by ilike2burnthing** [comment]
Thanks, this worked for the search but the HTML is unfortunately still missing for the download block request of the torrent's details page.

Between me hitting download and it failing the trace log just has:

```
2023-04-10 22:25:48.1|Trace|Http|Req: 190 [POST] /api/v1/search (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.34)
2023-04-10 22:25:48.1|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-10 22:25:48.1|Debug|Cardigann|Populating config vars
2023-04-10 22:25:48.1|Trace|Cardigann|.Config.username got value "REMOVED"
2023-04-10 22:25:48.1|Debug|Cardigann|Setting username to "REMOVED"
2023-04-10 22:25:48.1|Trace|IndexerHttpClient|Req: [GET] https://mircrew-releases.org/viewtopic.php?t=81539&hilit=2023
2023-04-10 22:25:48.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-04-10 22:25:48.1|Trace|Http|Res: 190 [POST] /api/v1/search: 200.OK (17 ms)
2023-04-10 22:25:48.1|Debug|Api|[POST] /api/v1/search: 200.OK (17 ms)
2023-04-10 22:25:48.7|Trace|IndexerHttpClient|Res: [GET] https://mircrew-releases.org/viewtopic.php?t=81539&hilit=2023: 200.OK (67778 bytes) (571 ms)
2023-04-10 22:25:48.7|Error|GlobalExceptionHandlers|Task Error

[v1.3.2.3006] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.HandleRequest(RequestBlock request, Dictionary`2 variables, String referer) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 730
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DownloadRequest(Uri link) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 819
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.GetDownloadRequest(Uri link) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 200
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 136
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(ReleaseInfo release, IIndexer indexer, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 127
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 116
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 77
```

**Comment by ilike2burnthing** [comment]
My guess for `prowlarrfix`, based on https://github.com/Prowlarr/Prowlarr/issues/1158#issuecomment-1386187498, unfortunately doesn't work (and using `3` instead doesn't match any elements).

I would need to see the response HTML for the download block request.
