### ISSUE TITLE
RetroFlix indexer setup 404

### ISSUE THREAD

**Issue by benfishbus** [Prowlarr/Prowlarr#1159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot add new RetroFlix indexer. Log indicates:
```
NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [POST] at [https://retroflix.net/api/login]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 127
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.ExecuteAuth(HttpRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 413
   at NzbDrone.Core.Indexers.Definitions.SpeedAppBase.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\SpeedApp\SpeedAppBase.cs:line 85
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 380
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 314
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 453
<html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>nginx</center>

</body>

</html>
```

### Expected Behavior

Should just work

### Steps To Reproduce

Add Indexer > RetroFlix
Enter valid email address and password
Click 'Save'

### Environment

```markdown
- OS: Unraid
- Prowlarr: 0.4.7.2016
- Docker Install: yes (linuxserver)
- Using Reverse Proxy: no
- Browser: Firefox 105
```

### What branch are you running?

Develop

### Trace Logs?

I think the exception detail in the standard log provides enough detail, but will provide trace logs if they are needed.

[AB#3938](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3938)

**Comment by mynameisbogdan** [comment]
I'm getting a `hello world` on the first page.

**Comment by bakerboy448** [comment]
Not a prowlarr issue if the site is down

**Comment by benfishbus** [comment]
The website is at .club not .net
