### ISSUE TITLE
[YGG] Connection refused

### ISSUE THREAD

**Issue by BancarelValentin** [Prowlarr/Prowlarr#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

YGG indexers (both ia cookie or password) are KO

### Expected Behavior

YGG should work

### Steps To Reproduce

Add an ygg indexer (via user/pass or cookies) and test it.

### Environment

```markdown
- OS: Debian / Docker
- Using Reverse Proxy: Yes, traefik

Version:    0.4.7.2016
Package Version:    0.4.7.2016-ls71 by linuxserver.io 
.NET:    Yes (6.0.6)
Docker:    Yes
DB Migration:    21
Database:    Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

[v0.4.7.2016] System.Net.Http.HttpRequestException: Connection refused (www5.yggtorrent.fi:443)

 ---> System.Net.Sockets.SocketException (111): Connection refused

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)

   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)



[AB#3991](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3991)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

The site is running / not responding at that IP/port or your dns is resolving to a different ip than their server.
