### ISSUE TITLE
Unable to connect to Orpheus. Unexpected response status InternalServerError code from API request

### ISSUE THREAD

**Issue by Gandrushka** [Prowlarr/Prowlarr#1196]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

While trying to search anything on Oprheus or even test connection to Prowlarr - getting this message

Unable to connect to indexer. Unexpected response status InternalServerError code from API request

### Expected Behavior

Being able to search and getting testing the Orpheus to work

### Steps To Reproduce

1. Set all credentials
2. See the error message
3. Get the error message

### Environment

```markdown
- OS: Windows 8.1 (9600)
- Prowlarr: 0.4.9.2083
- Docker Install: no
- Using Reverse Proxy: no
```

### What branch are you running?

Develop

### Trace Logs?

2022-11-14 00:59:49.8|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'rijndaelpassphrase' defaultValue:'30fbbc6e-d22a-45e7-bff0-99f8bb020de4'
2022-11-14 00:59:49.8|Trace|ConfigService|Writing Setting to database. Key:'rijndaelpassphrase' Value:'30fbbc6e-d22a-45e7-bff0-99f8bb020de4'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'hmacpassphrase' defaultValue:'54c9fe49-c2e3-42f7-9517-b2f6ccb530f0'
2022-11-14 00:59:49.8|Trace|ConfigService|Writing Setting to database. Key:'hmacpassphrase' Value:'54c9fe49-c2e3-42f7-9517-b2f6ccb530f0'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'rijndaelsalt' defaultValue:'b976ab7d-7011-45aa-9fa5-87f0c3768ae5'
2022-11-14 00:59:49.8|Trace|ConfigService|Writing Setting to database. Key:'rijndaelsalt' Value:'b976ab7d-7011-45aa-9fa5-87f0c3768ae5'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'hmacsalt' defaultValue:'158a1861-e868-4b1d-850b-a2c766d217e3'
2022-11-14 00:59:49.8|Trace|ConfigService|Writing Setting to database. Key:'hmacsalt' Value:'158a1861-e868-4b1d-850b-a2c766d217e3'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-11-14 00:59:49.8|Trace|EventAggregator|Publishing ConfigSavedEvent
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2022-11-14 00:59:49.8|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2022-11-14 00:59:49.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-11-14 00:59:49.8|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-11-14 00:59:49.9|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-11-14 00:59:49.9|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2022-11-14 00:59:49.9|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2022-11-14 00:59:49.9|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-11-14 00:59:49.9|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2022-11-14 00:59:49.9|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2022-11-14 00:59:49.9|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2022-11-14 00:59:49.9|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2022-11-14 00:59:49.9|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2022-11-14 00:59:49.9|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-11-14 00:59:49.9|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2022-11-14 00:59:49.9|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2022-11-14 00:59:49.9|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2022-11-14 00:59:49.9|Trace|Http|Req: 738 [GET] /api/v1/health (from 192.168.31.100 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-11-14 00:59:49.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-11-14 00:59:50.0|Trace|Http|Res: 738 [GET] /api/v1/health: 200.OK (83 ms)
2022-11-14 00:59:50.0|Trace|Http|Res: 737 [PUT] /api/v1/config/host: 202.Accepted (418 ms)
2022-11-14 00:59:50.0|Trace|Http|Req: 739 [GET] /api/v1/health (from 192.168.31.100 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-11-14 00:59:50.0|Debug|Api|[GET] /api/v1/health: 200.OK (83 ms)
2022-11-14 00:59:50.0|Debug|Api|[PUT] /api/v1/config/host: 202.Accepted (418 ms)
2022-11-14 00:59:50.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-11-14 00:59:50.0|Trace|Http|Res: 739 [GET] /api/v1/health: 200.OK (18 ms)
2022-11-14 00:59:50.0|Debug|Api|[GET] /api/v1/health: 200.OK (18 ms)
2022-11-14 00:59:52.5|Trace|Http|Req: 740 [POST] /api/v1/indexer/action/getUrls (from 192.168.31.100 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-11-14 00:59:52.5|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-11-14 00:59:52.5|Trace|Http|Res: 740 [POST] /api/v1/indexer/action/getUrls: 200.OK (39 ms)
2022-11-14 00:59:52.5|Debug|Api|[POST] /api/v1/indexer/action/getUrls: 200.OK (39 ms)
2022-11-14 00:59:52.9|Trace|Scheduler|Pending Tasks: 0
2022-11-14 00:59:53.8|Trace|Http|Req: 741 [POST] /api/v1/indexer/test (from 192.168.31.100 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-11-14 00:59:53.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-11-14 00:59:53.9|Debug|Orpheus|Downloading Feed https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc
2022-11-14 00:59:53.9|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2022-11-14 00:59:53.9|Trace|IndexerHttpClient|Req: [GET] https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc
2022-11-14 00:59:53.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-11-14 00:59:54.1|Trace|IndexerHttpClient|Res: [GET] https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc: 302.Redirect (0 bytes) (171 ms)
2022-11-14 00:59:54.1|Trace|Orpheus|Attempting to re-auth based on indexer search response
2022-11-14 00:59:54.1|Trace|IndexerHttpClient|Req: [POST] https://orpheus.network/login.php: username=(removed)&password=(removed)&keeplogged=1
2022-11-14 00:59:54.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-11-14 00:59:54.9|Trace|IndexerHttpClient|Res: [POST] https://orpheus.network/login.php: 302.Redirect (0 bytes) (777 ms)
2022-11-14 00:59:54.9|Trace|IndexerHttpClient|Response content (0 bytes): 
2022-11-14 00:59:54.9|Trace|EventAggregator|Publishing IndexerAuthEvent
2022-11-14 00:59:54.9|Trace|EventAggregator|IndexerAuthEvent -> HistoryService
2022-11-14 00:59:54.9|Trace|EventAggregator|IndexerAuthEvent <- HistoryService
2022-11-14 00:59:54.9|Debug|Orpheus|Gazelle authentication succeeded.
2022-11-14 00:59:54.9|Trace|RateLimitService|Rate Limit triggered, delaying 'orpheus.network' for 1,014 sec
2022-11-14 00:59:56.0|Trace|IndexerHttpClient|Req: [GET] https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc
2022-11-14 00:59:56.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-11-14 00:59:56.4|Trace|IndexerHttpClient|Res: [GET] https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc: 500.InternalServerError (0 bytes)
 (413 ms)
2022-11-14 00:59:56.4|Warn|Orpheus|HTTP Error - Res: [GET] https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc: 500.InternalServerError (0 bytes)

2022-11-14 00:59:56.4|Trace|Orpheus|Unexpected Response content (0 bytes): 
2022-11-14 00:59:56.4|Warn|Orpheus|Unable to connect to indexer

[v0.4.9.2083] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status InternalServerError code from API request
   at NzbDrone.Core.Indexers.Gazelle.GazelleParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Gazelle\GazelleParser.cs:line 35
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 314
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 453
RequestUri: https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc;StatusCode: InternalServerError;ContentType: application/json; charset=utf-8;ContentLength: 0

2022-11-14 00:59:56.4|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.4.9.2083] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status InternalServerError code from API request
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-11-14 00:59:56.7|Trace|ProwlarrErrorPipeline|Handling Exception
2022-11-14 00:59:56.7|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status InternalServerError code from API request

[v0.4.9.2083] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status InternalServerError code from API request
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-11-14 00:59:57.1|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status InternalServerError code from API request
2022-11-14 00:59:57.1|Trace|Http|Res: 741 [POST] /api/v1/indexer/test: 400.BadRequest (3277 ms)
2022-11-14 00:59:57.1|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (3277 ms)
2022-11-14 00:59:58.9|Trace|Http|Req: 743 [GET] /api/v1/system/status (from 192.168.31.100 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-11-14 00:59:58.9|Trace|Http|Req: 742 [GET] /api/v1/health (from 192.168.31.100 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-11-14 00:59:58.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-11-14 00:59:58.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-11-14 00:59:58.9|Trace|Http|Res: 743 [GET] /api/v1/system/status: 200.OK (16 ms)
2022-11-14 00:59:58.9|Trace|Http|Res: 742 [GET] /api/v1/health: 200.OK (19 ms)
2022-11-14 00:59:58.9|Debug|Api|[GET] /api/v1/system/status: 200.OK (16 ms)
2022-11-14 00:59:58.9|Debug|Api|[GET] /api/v1/health: 200.OK (19 ms)
2022-11-14 01:00:00.4|Trace|Http|Req: 744 [GET] /api/v1/log/file (from 192.168.31.100 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-11-14 01:00:00.5|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-11-14 01:00:00.6|Trace|Http|Res: 744 [GET] /api/v1/log/file: 200.OK (118 ms)
2022-11-14 01:00:00.6|Debug|Api|[GET] /api/v1/log/file: 200.OK (118 ms)
2022-11-14 01:00:05.2|Trace|Http|Req: 745 [GET] /logfile/prowlarr.trace.txt (from 192.168.31.100 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-11-14 01:00:05.2|Debug|Prowlarr.Http.Authentication.NoAuthenticationHandler|AuthenticationScheme: None was successfully authenticated.

[AB#4060](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4060)

**Comment by Qstick** [comment]
Go back in and re-configure Orpheus with an API key

**Comment by Sharauskas** [comment]
Actually I'm getting the same **error** with _nightly_ build and API key

**Comment by lsaadeh** [comment]
also having this issue.

**Comment by bakerboy448** [comment]
Their API start working again yet?

**Comment by garfield69** [comment]
Orpheus have repaired their API

**Comment by bakerboy448** [comment]
thanks Garfield!

closing
