### ISSUE TITLE
Indexer - Cinemageddon - Unable to Add - Redirected to Domain

### ISSUE THREAD

**Issue by Junkbite** [Prowlarr/Prowlarr#120]
**Describe the bug**

cant setup Cinemageddon get `Unable to connect to indexer, check the log for more details`

**To Reproduce**

**Expected behavior**

**Screenshots**
```
Version
0.1.0.370
Package Version
0.1.0.370-ls4 by linuxserver.io
.NET
Yes (5.0.6)
Docker
Yes
DB Migration
7
```

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

```
2021-06-06 20:22:04.0|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2021-06-06 20:22:04.0|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-06-06 20:22:04.0|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2021-06-06 20:22:04.0|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-06 20:22:04.0|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-06-06 20:22:04.0|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2021-06-06 20:22:04.0|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2021-06-06 20:22:04.0|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2021-06-06 20:22:04.0|Trace|Http|Res: 74 [PUT] /api/v1/config/host: 202.Accepted (9 ms)
2021-06-06 20:22:04.0|Debug|Api|[PUT] /api/v1/config/host: 202.Accepted (9 ms)
2021-06-06 20:22:04.0|Trace|Http|Req: 75 [GET] /api/v1/health (from 192.168.1.64)
2021-06-06 20:22:04.0|Trace|Http|Res: 75 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:22:04.0|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:22:04.1|Trace|Http|Req: 76 [GET] /api/v1/health (from 192.168.1.64)
2021-06-06 20:22:04.1|Trace|Http|Res: 76 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:22:04.1|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:22:04.1|Trace|Http|Req: 77 [GET] /api/v1/health (from 192.168.1.64)
2021-06-06 20:22:04.1|Trace|Http|Res: 77 [GET] /api/v1/health: 200.OK (1 ms)
2021-06-06 20:22:04.1|Debug|Api|[GET] /api/v1/health: 200.OK (1 ms)
2021-06-06 20:22:04.1|Trace|Http|Req: 78 [GET] /api/v1/health (from 192.168.1.64)
2021-06-06 20:22:04.1|Trace|Http|Res: 78 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:22:04.1|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:22:06.6|Trace|Http|Req: 79 [POST] /api/v1/indexer (from 192.168.1.64)
2021-06-06 20:22:06.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-06-06 20:22:06.6|Debug|Cardigann|Populating config vars
2021-06-06 20:22:06.7|Info|Cardigann|Adding request: https://cinemageddon.net/browse.php?search=
2021-06-06 20:22:06.7|Debug|Cardigann|Downloading Feed https://cinemageddon.net/browse.php?search=
2021-06-06 20:22:06.7|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-06-06 20:22:06.8|Trace|HttpClient|Req: [GET] https://cinemageddon.net/browse.php?search=
2021-06-06 20:22:06.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-06 20:22:07.0|Trace|HttpClient|Res: [GET] https://cinemageddon.net/browse.php?search=: 302.Redirect (226 ms)
2021-06-06 20:22:07.0|Warn|Cardigann|Unable to connect to indexer

[v0.1.0.370] System.Exception: Got redirected to another domain. Try changing the indexer URL to file:///.
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.CheckIfLoginIsNeeded(HttpResponse response) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 789
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.CheckIfLoginNeeded(HttpResponse httpResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 130
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 430
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 346
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 496


2021-06-06 20:22:07.0|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.0.370] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method172(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-06-06 20:22:07.0|Trace|ProwlarrErrorPipeline|Handling Exception
2021-06-06 20:22:07.0|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method172(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[v0.1.0.370] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method172(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-06-06 20:22:07.0|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
2021-06-06 20:22:07.0|Trace|Http|Res: 79 [POST] /api/v1/indexer: 400.BadRequest (380 ms)
2021-06-06 20:22:07.0|Debug|Api|[POST] /api/v1/indexer: 400.BadRequest (380 ms)
2021-06-06 20:22:07.8|Trace|Scheduler|Pending Tasks: 0
2021-06-06 20:22:12.9|Trace|Http|Req: 80 [PUT] /api/v1/config/host (from 192.168.1.64)
2021-06-06 20:22:12.9|Trace|EventAggregator|Publishing ConfigFileSavedEvent
2021-06-06 20:22:12.9|Trace|EventAggregator|ConfigFileSavedEvent ~> ReconfigureLogging
2021-06-06 20:22:12.9|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-06-06 20:22:12.9|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2021-06-06 20:22:12.9|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
2021-06-06 20:22:12.9|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2021-06-06 20:22:12.9|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2021-06-06 20:22:12.9|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'60'
2021-06-06 20:22:12.9|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
```

**Comment by Qstick** [comment]
https://github.com/Prowlarr/Prowlarr/commit/d9e211472b2d8e88e1f50a07a6ce03fcd94f6da9 should fix, please test

**Comment by Junkbite** [comment]
on `0.1.0.382` i now get `Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.`

**Comment by Junkbite** [comment]
same error on `v0.1.0.393`
