### ISSUE TITLE
Catch and Handle System.Threading.Tasks.TaskCanceledException: The operation was canceled.

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#1217]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently when connections timeout an ugly unhelpful error message is thrown

Variations of
```
2022-11-28 09:33:05.8|Error|ApplicationService|An error occurred while talking to remote application.

[v0.4.10.2099] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 108
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 170
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 136
   at NzbDrone.Core.Applications.Sonarr.SonarrV3Proxy.Execute[TResource](HttpRequest request) in D:\a\1\s\src\NzbDrone.Core\Applications\Sonarr\SonarrV3Proxy.cs:line 162
   at NzbDrone.Core.Applications.Sonarr.SonarrV3Proxy.GetIndexers(SonarrSettings settings) in D:\a\1\s\src\NzbDrone.Core\Applications\Sonarr\SonarrV3Proxy.cs:line 44
   at NzbDrone.Core.Applications.Sonarr.Sonarr.GetIndexerMappings() in D:\a\1\s\src\NzbDrone.Core\Applications\Sonarr\Sonarr.cs:line 63
   at NzbDrone.Core.Applications.ApplicationService.<>c.<SyncIndexers>b__14_0(IApplication a) in D:\a\1\s\src\NzbDrone.Core\Applications\ApplicationService.cs:line 133
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction[TResult](Func`2 applicationAction, IApplication application) in D:\a\1\s\src\NzbDrone.Core\Applications\ApplicationService.cs:line 272
```

### Describe the solution you'd like

Catch the `System.Threading.Tasks.TaskCanceledException: The operation was canceled.` exception and log an error `Connection Timed out after {timeout} seconds to {site}. Likely IPv6 or DNS issues`

### Describe alternatives you've considered

Support issues with the existing error.

### Anything else?

Common to all Starrs and backport to Sonarr

[AB#4211](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4211)

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/f8082047a56adc74762f35d1e1e717417271a529
