### ISSUE TITLE
Stats page shows error `Sequence contains no elements`

### ISSUE THREAD

**Issue by w1ldg00se** [Prowlarr/Prowlarr#1231]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When going to the stats page it shows the loading screen for about 45 seconds and then just shows the text `Sequence contains no elements`.

### Expected Behavior

It should show me the indexer statistics.

### Steps To Reproduce

Click on Indexers, then on Stats.

### Environment

```markdown
- Prowlarr: 0.4.10.2105
- Docker Install: Yes, container lscr.io/linuxserver/prowlarr:nightly
- Using Reverse Proxy: traefik
```

### What branch are you running?

Nightly

### Trace Logs?

```
2022-12-11 12:20:36.0|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.4.10.2105] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at NzbDrone.Core.IndexerStats.IndexerStatisticsService.IndexerStatistics(DateTime start, DateTime end) in D:\a\1\s\src\NzbDrone.Core\IndexerStats\IndexerStatisticsService.cs:line 59
   at Prowlarr.Api.V1.Indexers.IndexerStatsController.GetAll(Nullable`1 startDate, Nullable`1 endDate) in D:\a\1\s\src\Prowlarr.Api.V1\Indexers\IndexerStatsController.cs:line 24
   at lambda_method85(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-12-11 12:20:36.1|Trace|ProwlarrErrorPipeline|Handling Exception
2022-12-11 12:20:36.2|Trace|IndexerHttpClient|Res: [GET] https://torrent-explosiv.hopto.org/selection.php?search=&blah=0&orderby=added&sort=desc: 200.OK (61506 bytes) (298 ms)
2022-12-11 12:20:36.1|Warn|ProwlarrErrorPipeline|System.InvalidOperationException: Sequence contains no elements

[v0.4.10.2105] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at NzbDrone.Core.IndexerStats.IndexerStatisticsService.IndexerStatistics(DateTime start, DateTime end) in D:\a\1\s\src\NzbDrone.Core\IndexerStats\IndexerStatisticsService.cs:line 59
   at Prowlarr.Api.V1.Indexers.IndexerStatsController.GetAll(Nullable`1 startDate, Nullable`1 endDate) in D:\a\1\s\src\Prowlarr.Api.V1\Indexers\IndexerStatsController.cs:line 24
   at lambda_method85(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-12-11 12:20:36.2|Debug|Cardigann|Parsing
2022-12-11 12:20:36.2|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2022-12-11 12:20:36.3|Debug|Cardigann|Got 15 releases
2022-12-11 12:20:36.3|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IIndexer>
2022-12-11 12:20:36.3|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> -> IndexerStatusController
2022-12-11 12:20:36.3|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> <- IndexerStatusController
2022-12-11 12:20:36.3|Trace|EventAggregator|Publishing IndexerQueryEvent
2022-12-11 12:20:36.3|Trace|EventAggregator|IndexerQueryEvent -> HistoryService
2022-12-11 12:20:36.3|Trace|EventAggregator|IndexerQueryEvent <- HistoryService
2022-12-11 12:20:36.3|Trace|EventAggregator|IndexerQueryEvent ~> ReleaseAnalyticsService
2022-12-11 12:20:36.3|Trace|EventAggregator|IndexerQueryEvent <~ ReleaseAnalyticsService
2022-12-11 12:20:36.3|Trace|Http|Req: 93 [GET] /api/v1/indexerStatus (from 10.0.1.11 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
2022-12-11 12:20:36.3|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2022-12-11 12:20:36.2|Fatal|ProwlarrErrorPipeline|Request Failed. GET /api/v1/indexerStats

[v0.4.10.2105] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at NzbDrone.Core.IndexerStats.IndexerStatisticsService.IndexerStatistics(DateTime start, DateTime end) in D:\a\1\s\src\NzbDrone.Core\IndexerStats\IndexerStatisticsService.cs:line 59
   at Prowlarr.Api.V1.Indexers.IndexerStatsController.GetAll(Nullable`1 startDate, Nullable`1 endDate) in D:\a\1\s\src\Prowlarr.Api.V1\Indexers\IndexerStatsController.cs:line 24
   at lambda_method85(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

[AB#4430](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4430)

**Comment by w1ldg00se** [comment]
Additional note: There are indexers for nzb and torrent configured. A few of them are manually disabled, 2 are currently automatically disabled because of errors.

**Comment by w1ldg00se** [comment]
Well, i did some investigation in the database:
```
sqlite> select Id, IndexerId, json_extract(Data, "$.elapsedTime") from History where json_extract(Data, "$.elapsedTime") > 1 group by IndexerId;
311433|12|667
311431|13|478
868383|14|
311426|15|243

``` 
showed no elapsedTime value for IndexerId 14.
So i selected the one entry that indexer had:
```
sqlite> select * from History where IndexerId = 14;
Id|IndexerId|Date|Data|EventType|DownloadId|Successful
868383|14|2022-05-17 16:56:26.5602312Z|{
  "imdbId": "",
  "tvdbId": "",
  "traktId": "",
  "rId": "",
  "tvMazeId": "",
  "season": "",
  "episode": "",
  "elapsedTime": "",
  "query": "",
  "queryType": "tvsearch",
  "categories": "5000,5040,5030,5070",
  "source": "Sonarr",
  "host": "sonarr",
  "queryResults": "0",
  "url": ""
}|3||0
```
After deleting this entry, the stats page works!
So could you maybe add some check that this constellation is just ignored and doesn't let the whole stats page fail?

**Comment by Qstick** [comment]
Thanks for digging into this.
