### ISSUE TITLE
myanonamouse seup error

### ISSUE THREAD

**Issue by Junkbite** [Prowlarr/Prowlarr#125]
**Describe the bug**

cant setup myanonamouse.. says to put in mam id. i only pasted the value into the input field from the cookies field in chrome. so not `mam_id=` but the raw hash after that (not including the semi colon at the end seperating cookies...)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**
```
Version
0.1.0.370
Package Version
0.1.0.370-ls4 by linuxserver.io
.NET
Yes (5.0.6)
Docker
Yes
DB Migration
7
```

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

```
2021-06-06 20:49:29.8|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2021-06-06 20:49:29.8|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2021-06-06 20:49:29.8|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2021-06-06 20:49:29.8|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-06-06 20:49:29.8|Trace|Http|Res: 137 [PUT] /api/v1/config/host: 202.Accepted (12 ms)
2021-06-06 20:49:29.8|Debug|Api|[PUT] /api/v1/config/host: 202.Accepted (12 ms)
2021-06-06 20:49:29.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-06 20:49:29.8|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-06-06 20:49:29.8|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2021-06-06 20:49:29.8|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2021-06-06 20:49:29.8|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-06-06 20:49:29.9|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-06-06 20:49:29.9|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-06-06 20:49:29.9|Trace|Http|Req: 138 [GET] /api/v1/health (from 192.168.1.64)
2021-06-06 20:49:29.9|Trace|Http|Res: 138 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:49:29.9|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:49:29.9|Trace|Http|Req: 139 [GET] /api/v1/health (from 192.168.1.64)
2021-06-06 20:49:29.9|Trace|Http|Res: 139 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:49:29.9|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:49:29.9|Trace|Http|Req: 140 [GET] /api/v1/health (from 192.168.1.64)
2021-06-06 20:49:29.9|Trace|Http|Res: 140 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:49:29.9|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:49:29.9|Trace|Http|Req: 141 [GET] /api/v1/health (from 192.168.1.64)
2021-06-06 20:49:29.9|Trace|Http|Res: 141 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:49:29.9|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-06 20:49:32.1|Trace|Http|Req: 142 [POST] /api/v1/indexer (from 192.168.1.64)
2021-06-06 20:49:32.1|Debug|MyAnonamouse|Downloading Feed https://www.myanonamouse.net/tor/js/loadSearchJSONbasic.php?tor[text]=&tor[srchIn][title]=true&tor[srchIn][author]=true&tor[searchType]=all&tor[searchIn]=torrents&tor[hash]=&tor[sortType]=default&tor[startNumber]=0&thumbnails=1&description=1&tor[cat][]=0
2021-06-06 20:49:32.1|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-06-06 20:49:32.1|Trace|HttpClient|Req: [GET] https://www.myanonamouse.net/tor/js/loadSearchJSONbasic.php?tor[text]=&tor[srchIn][title]=true&tor[srchIn][author]=true&tor[searchType]=all&tor[searchIn]=torrents&tor[hash]=&tor[sortType]=default&tor[startNumber]=0&thumbnails=1&description=1&tor[cat][]=0
2021-06-06 20:49:32.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-06 20:49:32.5|Trace|HttpClient|Res: [GET] https://www.myanonamouse.net/tor/js/loadSearchJSONbasic.php?tor[text]=&tor[srchIn][title]=true&tor[srchIn][author]=true&tor[searchType]=all&tor[searchIn]=torrents&tor[hash]=&tor[sortType]=default&tor[startNumber]=0&thumbnails=1&description=1&tor[cat][]=0: 403.Forbidden
Error, you are not signed in (405 ms)
2021-06-06 20:49:32.5|Warn|MyAnonamouse|HTTP Error - Res: [GET] https://www.myanonamouse.net/tor/js/loadSearchJSONbasic.php?tor[text]=&tor[srchIn][title]=true&tor[srchIn][author]=true&tor[searchType]=all&tor[searchIn]=torrents&tor[hash]=&tor[sortType]=default&tor[startNumber]=0&thumbnails=1&description=1&tor[cat][]=0: 403.Forbidden
Error, you are not signed in
2021-06-06 20:49:32.5|Warn|MyAnonamouse|Unable to connect to indexer

[v0.1.0.370] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://www.myanonamouse.net/tor/js/loadSearchJSONbasic.php?tor[text]=&tor[srchIn][title]=true&tor[srchIn][author]=true&tor[searchType]=all&tor[searchIn]=torrents&tor[hash]=&tor[sortType]=default&tor[startNumber]=0&thumbnails=1&description=1&tor[cat][]=0]
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 452
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 346
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 496
Error, you are not signed in


2021-06-06 20:49:32.5|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.0.370] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method142(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-06-06 20:49:32.5|Trace|ProwlarrErrorPipeline|Handling Exception
2021-06-06 20:49:32.5|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method142(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[v0.1.0.370] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method142(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-06-06 20:49:32.5|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
2021-06-06 20:49:32.5|Trace|Http|Res: 142 [POST] /api/v1/indexer: 400.BadRequest (451 ms)
2021-06-06 20:49:32.5|Debug|Api|[POST] /api/v1/indexer: 400.BadRequest (451 ms)
2021-06-06 20:49:38.7|Trace|Scheduler|Pending Tasks: 0
2021-06-06 20:49:39.0|Trace|Http|Req: 143 [PUT] /api/v1/config/host (from 192.168.1.64)
2021-06-06 20:49:39.1|Trace|EventAggregator|Publishing ConfigFileSavedEvent
2021-06-06 20:49:39.1|Trace|EventAggregator|ConfigFileSavedEvent ~> ReconfigureLogging
2021-06-06 20:49:39.1|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-06-06 20:49:39.1|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2021-06-06 20:49:39.1|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
2021-06-06 20:49:39.1|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2021-06-06 20:49:39.1|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2021-06-06 20:49:39.1|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-06-06 20:49:39.1|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'60'
2021-06-06 20:49:39.1|Trace|ConfigService|Using default config value for 'availabilitydelay' defaultValue:'0'
2021-06-06 20:49:39.1|Trace|ConfigService|Using default config value for 'importlistsyncinterval' defaultValue:'240'
```

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

![image](https://user-images.githubusercontent.com/55419169/120947671-d2c7b780-c705-11eb-991a-016d07ec6762.png)

`Session ID` not `mam_id`
available under security

**Comment by Junkbite** [comment]
you right. maybe should say under security like some other indexer setups do for clarity. thanks
