### ISSUE TITLE
Invalid column defintions when using postgresql

### ISSUE THREAD

**Issue by evanrich** [Prowlarr/Prowlarr#1250]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using postgresql as a database, updating the indexers throws errors:

```
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
  Exception data:
    Severity: ERROR
    SqlState: 42804
    MessageText: column "Redirect" is of type bigint but expression is of type boolean
    Hint: You will need to rewrite or cast the expression.
    Position: 53
    File: parse_target.c
    Line: 587
    Routine: transformAssignedExpr
Severity: ERROR;InvariantSeverity: ERROR;SqlState: 42804;MessageText: column "Redirect" is of type bigint but expression is of type boolean;Hint: You will need to rewrite or cast the expression.;Position: 53;File: parse_target.c;Line: 587;Routine: transformAssignedExpr
2022-12-21T11:16:06.434978008-08:00
```

looking at the database, the columns are declared as bigint with a default of 0, whereas the queries are using boolean datatypes.  I've tried changing the column types using pgadmin but doesn't seem to work

### Expected Behavior

It works.

### Steps To Reproduce

1.) use postgresql as a backend
2.) try to update an indexer
3.) save the indexer
4.) save fails

### Environment

```markdown
- OS: ubuntu 22.04
- Prowlarr: 1.0.0.2156
- Docker Install: Yes
- Using Reverse Proxy:
- Browser: chrome (latest)
```

### What branch are you running?

Nightly

### Trace Logs?

if these are required let me know, but seems pretty straight forward

[AB#4524](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4524)

**Comment by bakerboy448** [comment]
The db type field is indeed boolean

https://github.com/Prowlarr/Prowlarr/blob/c35f1212fbf9ae56d2ddccd7916bcf3487c8e3b5/src/NzbDrone.Core/Datastore/Migration/003_indexer_props.cs#L12

> looks like they migrated early or not followed the migration process properly - the code has that setting to be a boolean and will have done all along for the table that is

https://wiki.servarr.com/prowlarr/postgres-setup

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.
