### ISSUE TITLE
FlareSolverr: Proxy Health Check failed with latest flaresolverr v3.0.0

### ISSUE THREAD

**Issue by seth100** [Prowlarr/Prowlarr#1296]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

*Failed to test proxy: localhost* while testing FlareSolverr from Prowlarr.

FlareSolverr was working fine in the past, now the test is failing.

### Expected Behavior

FlareSolverr should work as expected!

### Environment

```markdown
- OS: Ubuntu 22.04
- Prowlarr: 1.1.0.2245
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: 108.0.2
```

### What branch are you running?

Nightly

### Trace Logs?

```
flaresolverr  | 2023-01-06 09:10:00 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
flaresolverr  | 2023-01-06 09:10:00 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
prowlarr      | [Error] FlareSolverr: Proxy Health Check failed 
prowlarr      | 
prowlarr      | [v1.1.0.2245] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
prowlarr      |  ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
prowlarr      |  ---> System.Net.Sockets.SocketException (125): Operation canceled
prowlarr      |    --- End of inner exception stack trace ---
prowlarr      |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
prowlarr      |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
prowlarr      |    at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
prowlarr      |    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
prowlarr      |    --- End of inner exception stack trace ---
prowlarr      |    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
prowlarr      |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
prowlarr      |    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 108
prowlarr      |    at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 170
prowlarr      |    at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 70
prowlarr      |    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 136
prowlarr      |    at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.Test() in D:\a\1\s\src\NzbDrone.Core\IndexerProxies\FlareSolverr\FlareSolverr.cs:line 191
prowlarr      | 
prowlarr      | 
prowlarr      | [Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 
prowlarr      | 
prowlarr      | [v1.1.0.2245] FluentValidation.ValidationException: Validation failed: 
prowlarr      |  -- Host: Failed to test proxy: localhost
prowlarr      |    at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
prowlarr      |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
prowlarr      |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
prowlarr      | --- End of stack trace from previous location ---
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
prowlarr      | --- End of stack trace from previous location ---
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
prowlarr      |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
prowlarr      |    at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
prowlarr      |    at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
prowlarr      |    at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
prowlarr      |    at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
prowlarr      |    at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
prowlarr      |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
prowlarr      |    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
prowlarr      |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
prowlarr      |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
prowlarr      |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
prowlarr      | 
prowlarr      | 
prowlarr      | [Warn] ProwlarrErrorPipeline: FluentValidation.ValidationException: Validation failed: 
prowlarr      |  -- Host: Failed to test proxy: localhost 
prowlarr      | 
prowlarr      | [v1.1.0.2245] FluentValidation.ValidationException: Validation failed: 
prowlarr      |  -- Host: Failed to test proxy: localhost
prowlarr      |    at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
prowlarr      |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
prowlarr      |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
prowlarr      | --- End of stack trace from previous location ---
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
prowlarr      | --- End of stack trace from previous location ---
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
prowlarr      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
prowlarr      |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
prowlarr      |    at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
prowlarr      |    at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
prowlarr      |    at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
prowlarr      |    at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
prowlarr      |    at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
prowlarr      |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
prowlarr      |    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
prowlarr      |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
prowlarr      |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
prowlarr      |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
prowlarr      | 
prowlarr      | 
prowlarr      | [Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
prowlarr      |  -- Host: Failed to test proxy: localhost 
flaresolverr  | 2023-01-06 09:10:01 INFO     Challenge not detected!
flaresolverr  | 2023-01-06 09:10:01 INFO     Response in 1.049 s
flaresolverr  | 2023-01-06 09:10:01 INFO     127.0.0.1 POST http://localhost:8191/v1 200 OK
```

[AB#4653](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4653)

**Comment by jojolll** [comment]
Hello,

Same problem detected on my instance, after installing the version (docker:nightly image of LinuxServer, prowlarr 1.1.0.2245).
I can see in flaresolver V3 logs the prowlarr query was sucessful.

After a downgrade to version 1.1.0.2230, the problem is solved and Flaresolver is working fine in prowlarr.

**Comment by Qstick** [comment]
https://github.com/Prowlarr/Prowlarr/commit/c28f9b6bcd07a516cfcf082685c8e8cfe1818347

**Comment by seth100** [comment]
> Thanks, this is likely something goofy with the timeout change from last night. What is the timeout set to in your Flaresolverr settings in Prowlarr?

`60`

**Comment by seth100** [comment]
> [c28f9b6](https://github.com/Prowlarr/Prowlarr/commit/c28f9b6bcd07a516cfcf082685c8e8cfe1818347)

thanks, it fixed the issues!
