### ISSUE TITLE
Prowlarr fails to log into CloudFlare protected indexer despite successful response from FlareSolverr

### ISSUE THREAD

**Issue by brewkunz** [Prowlarr/Prowlarr#1321]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Prowlarr fails to access a CloudFlare protected indexer (yggtorrent) despite receiving a successful response from FlareSolverr.

Prowlarr seems to not be able to find the login form in FlareSolverr's response.

### Expected Behavior

Prowlarr should be able to actually find the login form in FlareSolverr's response to log into the indexer.

### Steps To Reproduce

1. Add a CloudFlare protected indexer to prowlarr (yggtorrent in this case)
2. Add FlareSolverr as an indexer proxy for the previously added indexer.
3. Test the indexer, this should fail.

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 1.1.0.2289
- Docker Install: Yes
- Using Reverse Proxy: Yes

- FlareSolverr: 3.0.0, installed on the same machine.
```

### What branch are you running?

Nightly

### Prowlarr relevant logs :

```
2023-01-12 20:30:05.2|Debug|FlareSolverr|Cloudflare Detected, Applying FlareSolverr Proxy FlareSolverr to request https://www6.yggtorrent.lol/
2023-01-12 20:30:21.2|Warn|Cardigann|Unable to connect to indexer

[v1.1.0.2289] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannConfigException: Login failed: No form found on https://www6.yggtorrent.lol/ using form selector #user-login
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 253
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 180
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 374
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 285
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 447
```

### FlareSolverr relevant logs (removed response content) :
```
flaresolverr    | 2023-01-12 21:30:05 INFO     ReqId 140279955842816 127.0.0.1 POST http://localhost:8191/v1 200 OK
flaresolverr    | 2023-01-12 21:30:05 INFO     ReqId 140279738791680 Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
flaresolverr    | 2023-01-12 21:30:05 WARNING  ReqId 140279738791680 Request parameter 'userAgent' was removed in FlareSolverr v2.
flaresolverr    | 2023-01-12 21:30:05 DEBUG    ReqId 140279738791680 Launching web browser...
flaresolverr    | 2023-01-12 21:30:07 DEBUG    ReqId 140279730398976 Navigating to... https://www6.yggtorrent.lol/
flaresolverr    | 2023-01-12 21:30:12 INFO     ReqId 140279730398976 Challenge detected. Title found: Just a moment...
flaresolverr    | 2023-01-12 21:30:12 DEBUG    ReqId 140279730398976 Waiting for title: Just a moment...
flaresolverr    | 2023-01-12 21:30:20 DEBUG    ReqId 140279730398976 Waiting for title: DDOS-GUARD
flaresolverr    | 2023-01-12 21:30:20 DEBUG    ReqId 140279730398976 Waiting for selector: #cf-challenge-running
flaresolverr    | 2023-01-12 21:30:20 DEBUG    ReqId 140279730398976 Waiting for selector: .ray_id
flaresolverr    | 2023-01-12 21:30:20 DEBUG    ReqId 140279730398976 Waiting for selector: .attack-box
flaresolverr    | 2023-01-12 21:30:20 DEBUG    ReqId 140279730398976 Waiting for selector: #cf-please-wait
flaresolverr    | 2023-01-12 21:30:20 DEBUG    ReqId 140279730398976 Waiting for selector: #challenge-spinner
flaresolverr    | 2023-01-12 21:30:20 DEBUG    ReqId 140279730398976 Waiting for selector: #trk_jschal_js
flaresolverr    | 2023-01-12 21:30:20 DEBUG    ReqId 140279730398976 Waiting for selector: td.info #js_info
flaresolverr    | 2023-01-12 21:30:20 DEBUG    ReqId 140279730398976 Waiting for redirect
flaresolverr    | 2023-01-12 21:30:20 INFO     ReqId 140279730398976 Challenge solved!
flaresolverr    | 2023-01-12 21:30:21 DEBUG    ReqId 140279738791680 Response => POST /v1 body: {'status': 'ok', 'message': 'Challenge solved!', 'solution': {'url': 'https://www6.yggtorrent.lol/', 'status': 200, 'cookies': [{'domain': '.yggtorrent.lol', 'expiry': 1674333019, 'httpOnly': False, 'name': 'v3_promo_details', 'path': '/', 'secure': False, 'value': 'eyJjb3VudGRvd25fZGF0ZSI6IjAxLzEyLzIwMjMgMjM6NTk6NTkiLCJ0cyI6MTY3MzU2NDM5OX0='}, {'domain': '.yggtorrent.lol', 'expiry': 1673562618, 'httpOnly': True, 'name': 'ygg_', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'f5b6kcc7k9aiv1rv487e9a3laui9sdj4'}, {'domain': '.yggtorrent.lol', 'expiry': 1705091418, 'httpOnly': True, 'name': 'cf_clearance', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': '9NfvgnfGp81Uxziyfi2Ubshjz1shY7H0IlX0eVrD2rg-1673555418-0-160'}], 'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36', 'headers': {}, 'response': '....'}, 'startTimestamp': 1673555405284, 'endTimestamp': 1673555421126, 'version': '3.0.0'}
flaresolverr    | 2023-01-12 21:30:21 INFO     ReqId 140279738791680 Response in 15.842 s
flaresolverr    | 2023-01-12 21:30:21 INFO     ReqId 140279738791680 127.0.0.1 POST http://localhost:8191/v1 200 OK
```

### FlareSolverr relevant part of the html response :

```
...
<form action="/user/login" method="post" id="user-login">
...
```

**Comment by bakerboy448** [comment]
- not a flaresolverr issue
- YGG changed their site so the existing definition is broke
- YGG hate automation and have been / are taking additional measures to block or otherwise shutdown prowlarr and jackett....including so it's been said banning users for even asking about them or the Starr apps.
