### ISSUE TITLE
One specific movie indexer doesn’t sync with Radarr; others do

### ISSUE THREAD

**Issue by DanAykroyd256** [Prowlarr/Prowlarr#1353]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have 10 indexers set up in Prowlarr; shared between Movies and TV categories. All TV categories indexers sync fine to Sonarr, all Movie ones sync fine to Radarr, execept BitSearch

I’ve been going crazy trying to see what’s going on and fixing it. The indexer supports the Movie category, I have tried re-adding the indexer, connect app to Radarr, reinstalling, manually trying to sync a dozen times and it still doesn’t get sent to Radarr

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/64184474/214126347-ffd48139-deaa-45a7-aeae-c3d198a438f9.png">

### Expected Behavior

Radarr should receive this Movie indexer; similar as it does with the others

### Environment

```markdown
- OS: Windows
- Prowlarr: 1.1.0.2322
```

### What branch are you running?

Master

### Trace Logs?

**Radarr Log; after manually starting the Sync action in Prowlarr**

`2023-01-23 11:28:42.4|Info|RssSyncService|Starting RSS Sync
2023-01-23 11:28:43.7|Warn|Torznab|Indexer Torrent Downloads (Prowlarr) rss sync didn't cover the period between 23/01/23 13:28:11 and 23/01/23 14:28:43 UTC. Search may be required.
2023-01-23 11:28:44.1|Warn|Torznab|Indexer The Pirate Bay (Prowlarr) rss sync didn't cover the period between 23/01/23 13:12:42 and 23/01/23 13:37:14 UTC. Search may be required.
2023-01-23 11:28:51.1|Info|DownloadDecisionMaker|Processing 413 releases
2023-01-23 11:28:52.6|Info|RssSyncService|RSS Sync Completed. Reports found: 413, Reports grabbed: 0
2023-01-23 12:29:14.4|Info|RssSyncService|Starting RSS Sync
2023-01-23 12:29:15.3|Warn|Torznab|Indexer Torrent Downloads (Prowlarr) rss sync didn't cover the period between 23/01/23 14:28:43 and 23/01/23 15:29:15 UTC. Search may be required.
2023-01-23 12:29:23.6|Info|DownloadDecisionMaker|Processing 409 releases
2023-01-23 12:29:25.0|Info|RssSyncService|RSS Sync Completed. Reports found: 409, Reports grabbed: 0
2023-01-23 13:29:46.7|Info|RssSyncService|Starting RSS Sync
2023-01-23 13:29:48.3|Warn|Torznab|Indexer Torrent Downloads (Prowlarr) rss sync didn't cover the period between 23/01/23 15:29:15 and 23/01/23 16:29:48 UTC. Search may be required.
2023-01-23 13:29:48.8|Warn|Torznab|Indexer The Pirate Bay (Prowlarr) rss sync didn't cover the period between 23/01/23 14:04:10 and 23/01/23 15:16:15 UTC. Search may be required.
2023-01-23 13:29:55.5|Info|DownloadDecisionMaker|Processing 411 releases
2023-01-23 13:29:57.0|Info|RssSyncService|RSS Sync Completed. Reports found: 411, Reports grabbed: 0
2023-01-23 14:30:18.7|Info|RssSyncService|Starting RSS Sync
2023-01-23 14:30:20.2|Warn|Torznab|Indexer The Pirate Bay (Prowlarr) rss sync didn't cover the period between 23/01/23 15:16:15 and 23/01/23 17:14:10 UTC. Search may be required.
2023-01-23 14:30:20.3|Warn|Torznab|Indexer Torrent Downloads (Prowlarr) rss sync didn't cover the period between 23/01/23 16:29:48 and 23/01/23 17:30:20 UTC. Search may be required.
2023-01-23 14:30:27.5|Info|DownloadDecisionMaker|Processing 416 releases
2023-01-23 14:30:28.9|Info|RssSyncService|RSS Sync Completed. Reports found: 416, Reports grabbed: 0
2023-01-23 15:30:50.6|Info|RssSyncService|Starting RSS Sync
2023-01-23 15:30:51.6|Warn|Torznab|Indexer Torrent Downloads (Prowlarr) rss sync didn't cover the period between 23/01/23 17:30:20 and 23/01/23 18:30:51 UTC. Search may be required.
2023-01-23 15:30:52.3|Warn|Torznab|Indexer The Pirate Bay (Prowlarr) rss sync didn't cover the period between 23/01/23 17:14:10 and 23/01/23 18:14:38 UTC. Search may be required.
2023-01-23 15:30:59.3|Info|DownloadDecisionMaker|Processing 317 releases
2023-01-23 15:31:00.5|Info|RssSyncService|RSS Sync Completed. Reports found: 317, Reports grabbed: 0
2023-01-23 15:51:26.8|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.3.2.6857] FluentValidation.ValidationException: Validation failed: 
 -- : Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 205
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 68
   at lambda_method270(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/prowlarr/troubleshooting#arr-http-400-errors

https://wiki.servarr.com/prowlarr/faq#prowlarr-will-not-sync-x-indexer-to-app

**Comment by DanAykroyd256** [comment]
Thanks @bakerboy448. I’ve already read that FAQ before and I think I have all the needed requirements for the indexer to sync to Radarr (category, results return, etc.)

What do you suggest?

**Comment by bakerboy448** [comment]
> Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.

There are no results returned for the test search.

Again, please use Reddit and discord for support questions.

**Comment by DanAykroyd256** [comment]
@bakerboy448, just to let you know, that wasn’t the problem.

I went from the beta to the current master version (1.0.1.2220) and BitSearch synced to Sonarr on the first try; with the exact same settings (using the same databases and all; overwrote the beta installation with the master; on Windows).

You might want to keep this in mind as an error in the beta. Thanks.

**Comment by bakerboy448** [comment]
It's not a prowlarr error at all.

Your site failed to respond with results for the test/rss query in the configured categories and this didn't sync.   When you tried again later it did.

Common problem for nearly all public and a tiny handful of not-so-great private trackers.
