### ISSUE TITLE
Updaters always fail

### ISSUE THREAD

**Issue by alexreg** [Prowlarr/Prowlarr#1354]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Updaters always fail to complete. (The version remains the same even upon manually restarting Prowlarr.)

The status and log messages seem to suggest the update worked, but this is not the case.

### Expected Behavior

The update should succeed, and the new (updated) version of Prowlarr should launch.

### Steps To Reproduce

1. Navigate to `http://prowlarr/system/updates`.
2. Click the button `Install Latest`.
3. Watch the updater appear to proceed, but never actually complete. Prowlarr does not restart.

### Environment

```markdown
- OS: macOS 13.1
- Prowlarr: 1.0.1.2220
- Docker Install: N.A.
- Using Reverse Proxy: no
- Browser: Safari 16.2
```

### What branch are you running?

Master

### Trace Logs?

```
2023-01-24 00:41:35.5|Info|InstallUpdateService|Deleting old update files
2023-01-24 00:41:35.6|Info|InstallUpdateService|Downloading update 1.1.1.2377
2023-01-24 00:41:47.2|Info|Auth|Auth-Success ip 127.0.0.1 username 'admin'
2023-01-24 00:41:47.3|Info|Auth|Auth-Success ip 127.0.0.1 username 'admin'
2023-01-24 00:41:51.6|Info|InstallUpdateService|Verifying update package
2023-01-24 00:41:51.7|Info|InstallUpdateService|Update package verified successfully
2023-01-24 00:41:51.7|Info|InstallUpdateService|Extracting Update package
2023-01-24 00:41:53.6|Info|InstallUpdateService|Update package extracted successfully
2023-01-24 00:41:53.6|Info|BackupService|Starting Backup
2023-01-24 00:41:59.2|Info|InstallUpdateService|Preparing client
2023-01-24 00:42:00.5|Info|InstallUpdateService|Starting update client /var/folders/cp/qx0df5kx497_rygnyvv9xl8m0000gn/T/prowlarr_update/Prowlarr.Update
2023-01-24 00:42:00.5|Info|InstallUpdateService|Prowlarr will restart shortly.
```

[AB#4796](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4796)

**Comment by bakerboy448** [comment]
- for future reference info logs are not the required trace logs
- Definitely need the updater logs for this

https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files
https://wiki.servarr.com/prowlarr/troubleshooting#update-logs-location

**Comment by bakerboy448** [comment]
If there are no updater logs then your system is killing the update client and it's not likely a prowlarr issue.

You may need to code sign the updater binary like the prowlarr binary is needed?

**Comment by MAscooby** [comment]
> If there are no updater logs then your system is killing the update client and it's not likely a prowlarr issue.

I'm seeing the same issues in Radarr, Readarr, etc. so it's likely not specific to Prowlarr.

> You may need to code sign the updater binary like the prowlarr binary is needed?

If that's part of the bundle I'd expect it to be covered already, no? And I'm definitely no expert on macOS code signing BTW ... :-)

The trace logs above and on my system seem to indicate successful download, unpack, move, and chmod so what's being killed and when?

**Comment by alexreg** [comment]
@bakerboy448 Yeah, it's probably more generic indeed. Like @MAscooby said however, the updater binary surely ought to be signed when I sign the root Prowlarr app? I run `sudo codesign -fvs "Local Developer" --deep /Applications/Prowlarr.app` to self-sign the app. So, I'm likewise a little confused why all the log messages seem to indicate success until the point at which the updater should run (but doesn't).

**Comment by bakerboy448** [comment]
Any luck on identifying what is killing the updater executable?
Does this issue occur with Radarr/Readarr/Lidarr/Sonarr v4?

**Comment by alexreg** [comment]
@bakerboy448 To be fair I wouldn't know where to begin there. But my suspicion is that this is an issue concerning the new signing policy on M1 Macs (everything absolutely has to be signed or it doesn't run). For manual updates I can circumvent this by self-signing after update, but it's not ideal. Are you the maintainers able to sign the app bundles? Perhaps that will fix this issue too.

And yes, this occurs with Radarr too. In fact recently I've been getting the following error for Prowlarr, although not for Radarr.

> Startup folder not writable by user 'alex'

**Comment by mbinkhorst** [comment]
It seems this is related to Gatekeeper?

From my logs of OSX Ventura on an M2, prowlarr 1.5.2.3484:
```
2023-06-20 14:30:38.9|Error|InstallUpdateService|Update process failed

[v1.5.2.3484] NzbDrone.Core.Update.UpdateFolderNotWritableException: Cannot install update because startup folder '/private/var/folders/f3/41wzn8bj3js2rhrwk94xlg4r0000gn/T/AppTranslocation/A9D5E2AA-66FC-459A-B930-958714300975/d/Prowlarr.app/Contents/MacOS' is not writable by the user 'michel'.
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in ./Prowlarr.Core/Update/InstallUpdateService.cs:line 93
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in ./Prowlarr.Core/Update/InstallUpdateService.cs:line 283


2023-06-20 14:30:38.9|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v1.5.2.3484] NzbDrone.Core.Messaging.Commands.CommandFailedException: Startup folder not writable by user 'michel'
 ---> NzbDrone.Core.Update.UpdateFolderNotWritableException: Cannot install update because startup folder '**/private/var/folders/f3/41wzn8bj3js2rhrwk94xlg4r0000gn/T/AppTranslocation/A9D5E2AA-66FC-459A-B930-958714300975/d/Prowlarr.app/Contents/MacOS**' is not writable by the user 'michel'.
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in ./Prowlarr.Core/Update/InstallUpdateService.cs:line 93
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in ./Prowlarr.Core/Update/InstallUpdateService.cs:line 283
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in ./Prowlarr.Core/Update/InstallUpdateService.cs:line 289
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Prowlarr.Core/Messaging/Commands/CommandExecutor.cs:line 85
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Prowlarr.Core/Messaging/Commands/CommandExecutor.cs:line 44
```

Quitting the apps, moving them to a different location, then starting them again makes it download the update again, but not actually apply it.

https://eclecticlight.co/2022/09/06/dont-run-that-app-where-it-landed-how-translocation-can-cause-crashes/

**Comment by alexreg** [comment]
@mbinkhorst Yes, that sounds very plausible.

**Comment by MAscooby** [comment]
@bakerboy448 is the external bug in some common system that the arr's are using, or something else?

**Comment by bakerboy448** [comment]
It's a Mac / Mac security issue. Not a prowlarr issue

**Comment by MAscooby** [comment]
I'm confused by that. Every other app's auto updater works just fine?

**Comment by MAscooby** [comment]
To clarify, if it's just that signing won't be happening and we need to self sign that's certainly fine, but I thought self signing the updater wasn't working.

**Comment by alexreg** [comment]
@bakerboy448 I'm not sure I get what you say that. Mac's policy is that all apps should be signed in order to work smoothly. If not, the burden is on the software vendor to provide an update that deals with Mac's security policy. Right now, the automatic updater simply doesn't work because of this security policy. Having to do manual updates and resign every time is a real pain, to say the least.

**Comment by bakerboy448** [comment]
Apple's process to be able to sign the executables and requiring someone on the team to link their real world identity to the apps...plus apple's historical actions and policy that would not be conducive to the Starr App Ecosystem means there's not a whole lot that will change on this front.

**Comment by alexreg** [comment]
@bakerboy448 Ah, I see. Do you think you could integrate a manual signing process into the auto-updater though, perhaps?

**Comment by bakerboy448** [comment]
It's something the user would need to do...so not sure how that would be done.
