### ISSUE TITLE
Kinozal.tv Invalid torrent file specified

### ISSUE THREAD

**Issue by GoldGshok** [Prowlarr/Prowlarr#1391]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Prowlarr can't download valid torrent file from kinozal.tv. 
When i try send to download client anything from kinozal i can get error in log 
`MonoTorrent.TorrentException: Invalid torrent file specified`

Then i save torrent file from prowlarr and open it in notebook. And i see html block from site, it's not torrent file.

If i go to the site from browser and download torrent file and then open it in notebook file looks like torrent file.

I think prowlarr can't authorize in the site, or see file not there.

p.s. Authorization credentials are filled correct in indexer

### Expected Behavior

Kinozal torrent files saved as valid

### Steps To Reproduce

Scenario 1
1. Search movie 'Black Panther' in prowlarr
2. Try send to download client
3. Get error in logs

Scenario 2
1. Search movie 'Black Panther' in prowlarr
2. Save torrent file to computer
3. Open file as text in notebook

### Environment

```markdown
- OS: Kubuntu 22.01
- Prowlarr: 1.0.1.2220-ls4 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 109.0.5414.119 (Official Build) (64-bit)
```

### What branch are you running?

Master

### Trace Logs?

2023-02-03 17:10:40.4|Info|Cardigann|Adding request: https://kinozal.tv/browse.php?c=0&s=&g=0&v=0&d=0&w=0&t=0&f=0
2023-02-03 17:11:56.3|Info|Cardigann|Adding request: https://kinozal.tv/browse.php?c=0&s=&g=0&v=0&d=0&w=0&t=0&f=0
2023-02-03 17:11:59.3|Info|Cardigann|Adding request: https://kinozal.tv/browse.php?c=0&s=&g=0&v=0&d=0&w=0&t=0&f=0
2023-02-03 17:12:00.7|Info|ReleaseSearchService|Searching indexer(s): [Kinozal] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2023-02-03 17:12:00.7|Info|Cardigann|Adding request: https://kinozal.tv/browse.php?c=0&s=&g=0&v=0&d=0&w=0&t=0&f=0
2023-02-03 17:12:02.8|Info|ReleaseSearchService|Searching indexer(s): [Kinozal] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5050, 5070]
2023-02-03 17:12:02.8|Info|Cardigann|Adding request: https://kinozal.tv/browse.php?c=0&s=&g=0&v=0&d=0&w=0&t=0&f=0
2023-02-03 17:12:16.0|Info|ReleaseSearchService|Searching indexer(s): [RuTracker, NoNaMe Club, MegaPeer, Kinozal] for Term: [Ñ‡ÐµÑ€Ð½Ð°Ñ Ð¿Ð°Ð½Ñ‚ÐµÑ€Ð°], Offset: 0, Limit: 100, Categories: []
2023-02-03 17:12:16.0|Info|ReleaseSearchService|Searching indexer(s): [RuTracker, NoNaMe Club, MegaPeer, Kinozal] for Term: [Ñ‡ÐµÑ€Ð½Ð°Ñ Ð¿Ð°Ð½Ñ‚ÐµÑ€Ð°], Offset: 100, Limit: 100, Categories: []
2023-02-03 17:12:16.0|Info|Cardigann|Adding request: https://nnmclub.to/forum/tracker.php
2023-02-03 17:12:16.0|Info|Cardigann|Adding request: https://megapeer.vip/browse.php?search=%25%F7%E5%F0%ED%E0%FF+%25%EF%E0%ED%F2%E5%F0%E0&cat=0&age=&stype=0&sort=0&ascdesc=0
2023-02-03 17:12:16.0|Info|Cardigann|Adding request: https://kinozal.tv/browse.php?c=0&s=%F7%E5%F0%ED%E0%FF+%EF%E0%ED%F2%E5%F0%E0&g=0&v=0&d=0&w=0&t=0&f=0
2023-02-03 17:12:16.2|Info|Cardigann|Adding request: https://nnmclub.to/forum/tracker.php
2023-02-03 17:12:16.2|Info|Cardigann|Adding request: https://megapeer.vip/browse.php?search=%25%F7%E5%F0%ED%E0%FF+%25%EF%E0%ED%F2%E5%F0%E0&cat=0&age=&stype=0&sort=0&ascdesc=0
2023-02-03 17:12:16.2|Info|Cardigann|Adding request: https://kinozal.tv/browse.php?c=0&s=%F7%E5%F0%ED%E0%FF+%EF%E0%ED%F2%E5%F0%E0&g=0&v=0&d=0&w=0&t=0&f=0
2023-02-03 17:13:26.4|Error|Cardigann|CardigannIndexer (kinozal): Exception with InfoHash block with hashSelector li:first-child and titleSelector div.b
2023-02-03 17:13:28.6|Error|Cardigann|CardigannIndexer (kinozal): Exception with InfoHash block with hashSelector li:first-child and titleSelector div.b
2023-02-03 17:13:29.1|Error|GlobalExceptionHandlers|Task Error

[v1.0.1.2220] MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Download.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(ReleaseInfo release, IIndexer indexer, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 144
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 116
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 77

[AB#4835](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4835)

**Comment by bakerboy448** [comment]
- info logs are not the trace logs that are required for bug reports
- This issue was previously seen on discord; not a prowlarr issue, you'll need to ask tracker staff why they are presumably redirecting to the login page for a grab with valid credentials

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/550b9b58df541e697631c4f489445c6db6e9034c Included in v1.2.1254+ should now have trace logging that may help with context on this

[ensure logged torrent contents does not contain any credentials or keys that may not be cleansed yet]

**Comment by msergein** [comment]
I also have the same problem
judging by the log, when trying to get a torrent, a redirect to the login page occurs:
```
2023-02-21 19:30:50.6|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/get_srv_details.php?action=2&id=(removed) 200.OK (226 bytes) (263 ms)
2023-02-21 19:30:50.6|Debug|Cardigann|CardigannIndexer (kinozal): handleRequest() remote server returned OK
2023-02-21 19:30:50.6|Trace|IndexerHttpClient|Req: [GET] https://kinozal.tv/download.php?id=(removed)
2023-02-21 19:30:50.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-21 19:30:50.9|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/download.php?id=(removed) 302.Redirect (0 bytes) (265 ms)
2023-02-21 19:30:50.9|Trace|IndexerHttpClient|Redirected to https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161
2023-02-21 19:30:50.9|Trace|IndexerHttpClient|Req: [GET] https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161
2023-02-21 19:30:50.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-21 19:30:51.1|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161: 200.OK (3553 bytes) (277 ms)
2023-02-21 19:30:51.1|Debug|Cardigann|CardigannIndexer (kinozal): Selector div.b could not match any elements.
2023-02-21 19:30:51.2|Error|Cardigann|CardigannIndexer (kinozal): Exception with InfoHash block with hashSelector li:first-child and titleSelector div.b
2023-02-21 19:30:51.2|Trace|IndexerHttpClient|Req: [GET] https://kinozal.tv/download.php?id=(removed)
2023-02-21 19:30:51.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-21 19:30:51.4|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/download.php?id=(removed) 302.Redirect (0 bytes) (262 ms)
2023-02-21 19:30:51.4|Trace|IndexerHttpClient|Redirected to https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161
2023-02-21 19:30:51.4|Trace|IndexerHttpClient|Req: [GET] https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161
2023-02-21 19:30:51.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-21 19:30:51.7|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161: 200.OK (3553 bytes) (265 ms)
```
request executed from raddar

my system:
Fedora Linux 36 (Workstation Edition)

Prowlarr running in docker:
Version: 1.1.3.2521
Package version: 1.1.3.2521-ls5 by linuxserver.io 
.NET: Yes (6.0.13)

**Comment by bakerboy448** [comment]
please provide logs from `1.2.2.2699`+ - logging has been improved/increased and a few other changes

**Comment by msergein** [comment]
I'm sorry, I didn't see that you already asked the previous user to update the version. Updated docker image, now version 1.2.2.2699
logs:
```
2023-02-21 19:55:10.0|Trace|Http|Req: 61 [GET] /3/download?apikey=(removed)&link=SzdPY2ZXVW80K1psMGluZ2dIb2d6NkZ4NHpmeFQzTHhVaGJrNzdPWkZqN2Y3eXo1UHlwVkc5QUhFRER0bmhySGNOUVhXL0xOVWxncndGczJDSHdaV3c9PQ&file=Avatar+(Extended+version)+2009+DUB%2C+Sub+BDRip (from 127.0.0.1 Radarr/4.3.2.6857 (alpine 3.17.2))
2023-02-21 19:55:10.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-21 19:55:10.0|Trace|DownloadService|Attempting download of https://kinozal.tv/download.php?id=(removed)
2023-02-21 19:55:10.0|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-02-21 19:55:10.0|Debug|Cardigann|Populating config vars
2023-02-21 19:55:10.1|Debug|Cardigann|CardigannIndexer (kinozal): handleRequest() requestLinkStr= https://kinozal.tv/get_srv_details.php
2023-02-21 19:55:10.1|Trace|RateLimitService|Rate Limit triggered, delaying 'kinozal.tv' for 1.950 sec
2023-02-21 19:55:12.0|Trace|IndexerHttpClient|Req: [GET] https://kinozal.tv/get_srv_details.php?action=2&id=(removed)
2023-02-21 19:55:12.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-21 19:55:12.3|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/get_srv_details.php?action=2&id=(removed) 200.OK (226 bytes) (277 ms)
2023-02-21 19:55:12.3|Debug|Cardigann|CardigannIndexer (kinozal): handleRequest() remote server returned OK
2023-02-21 19:55:12.3|Trace|RateLimitService|Rate Limit triggered, delaying 'kinozal.tv' for 1.717 sec
2023-02-21 19:55:14.0|Trace|IndexerHttpClient|Req: [GET] https://kinozal.tv/download.php?id=(removed)
2023-02-21 19:55:14.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-21 19:55:14.3|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/download.php?id=(removed) 302.Redirect (0 bytes) (307 ms)
2023-02-21 19:55:14.3|Trace|IndexerHttpClient|Redirected to https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161
2023-02-21 19:55:14.3|Trace|RateLimitService|Rate Limit triggered, delaying 'kinozal.tv' for 1.688 sec
2023-02-21 19:55:16.0|Trace|IndexerHttpClient|Req: [GET] https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161
2023-02-21 19:55:16.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-21 19:55:16.3|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161: 200.OK (3553 bytes) (285 ms)
2023-02-21 19:55:16.3|Debug|Cardigann|CardigannIndexer (kinozal): Selector div.b could not match any elements.
2023-02-21 19:55:16.3|Error|Cardigann|CardigannIndexer (kinozal): Exception with InfoHash block with hashSelector li:first-child and titleSelector div.b
2023-02-21 19:55:16.3|Trace|RateLimitService|Rate Limit triggered, delaying 'kinozal.tv' for 1.690 sec
2023-02-21 19:55:18.0|Trace|IndexerHttpClient|Req: [GET] https://kinozal.tv/download.php?id=(removed)
2023-02-21 19:55:18.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-21 19:55:18.3|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/download.php?id=(removed) 302.Redirect (0 bytes) (278 ms)
2023-02-21 19:55:18.3|Trace|IndexerHttpClient|Redirected to https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161
2023-02-21 19:55:18.3|Trace|RateLimitService|Rate Limit triggered, delaying 'kinozal.tv' for 1.721 sec
2023-02-21 19:55:20.0|Trace|IndexerHttpClient|Req: [GET] https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161
2023-02-21 19:55:20.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-21 19:55:20.3|Trace|IndexerHttpClient|Res: [GET] https://kinozal.tv/login.php?to=%2Fdownload.php%3Fid%3D1389161: 200.OK (3553 bytes) (300 ms)
2023-02-21 19:55:20.3|Debug|Cardigann|Downloaded for release finished (3553 bytes from https://kinozal.tv/download.php?id=(removed)
2023-02-21 19:55:20.3|Trace|Cardigann|Invalid torrent file contents: <!DOCTYPE HTML>
<html lang="ru">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<title>???? :: ???????.??</title>
<meta name="description" content="??????? ?????? ???????.?? - ?????? ? ???????, ???????????, ????? ? ??????, ??????? ????????? ? ???????">
<meta name="Keywords" content="250 ?????? ???????, 100 ?????? ???????, ?????? ???????, ?????? ?????? ??????, ?????? ?????, ?????? ?????? +???? ??????, kinozal, ???????, ???????-??????, ??????? ??????? ?????????">
<meta name="robots" content="index,follow">
<link rel="shortcut icon" href="/pic/favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="/pic/0_kinozal.tv.css?v=3.4" type="text/css">
<script type="text/javascript" src="/pic/jquery-3.6.3.min.js?v=1.1"></script>
<script type="text/javascript" src="/pic/use.js?v=3.4"></script>
</head>
<body>
<div id="body_wrapper">
<div id="header">
	<table style="width:100%;padding:0;margin:0;border:0;"><tr>
		<td style="width:43%;"><div class="logo_new"><a href="https://kinozal.tv" title="???????.??"><img src="/pic/logo3.gif" alt="???????.??"></a></div></td>
		<td style="width:57%;" align=center>
			<div class="rb_new" style="height:93px;overflow: hidden;">
				


			</div>
</td></tr></table>
<div class="clr"></div>
	<div class="menu">
	<ul>
		<li><a href="/" title="???????">???????</a></li>
		<li><a href="https://forum.kinozal.tv" title="?????">?????</a></li>
		<li><a href="/signup.php" title="??????????? ?? ???????">???????????</a></li>
		<li><a href="/browse.php" title="??????? ??????">???????</a></li>
		<li><a href="/top.php" title="??? ??????">??? ??????</a></li>
		<li><a href="/personsearch.php" title="???????">???????</a></li>
		<li><a href="/novinki.php" title="??????? ????">??????? ????</a></li>
		<li><a href="/groupexlist.php" title="??????? ?????">??????</a></li>
	</ul>
	<form action="/browse.php" method="get" id="srchform">
		<div><input type="text" class="inp" id="s" name="s" size="15" value=""><input class="s_submit" type="submit" title="????? ??????"></div>
	</form>
	<div class="clr"></div>
	</div>
	<span class="zan_l"></span>
	<span class="zan_r"></span>
</div>
<div class="clr"></div>
<div id="main">
<div style="width: 100%; text-align: center;"><div style="width: 700px; display: inline-block;text-align: left;">
<div class=pad0x0x5x0><ul class=lis><li class=mn><a href="/login.php">????</a></li><li><a href="/signup.php">??????????? ? ???????.??</a></li><li><a href="/recover.php">?????????????? ??????</a></li></ul></div>
<form method=post action="/takelogin.php" name=upt"><div class=bx1>????? ????????????? ??? ????????, ????? ????? ?? ????</div><input type=hidden name=to value="/download.php?id=(removed)"><div class="bx1_0"><input type=hidden value=takerecover name=wact><div class="pad10x10 floatleft"><table class="tables1"><tr><td class="w150 nw b">?????</td><td><input type=text size=35 id="username" name="username" value=""></td><tr><td class="w150 nw b">??????</td><td><input type=password size=35 id="password" name="password" value=""></td><tr><td colspan=2 class="right"><input class=buttonS type=submit value=" ????? "></td></table></div><div class=pad10x10 style="margin: 0 5px 0 380px;">???? ??? ?????????????? ? ???????.??<br>??? ????? ?? ???? ??????? ????? ? ??????<br>?? ???????????????? ? ???????.??? <a href="/signup.php" class=sba>??????????????</a><br></div></div></form></div></div><div class="clr"></div>
</div>
</div>
</div></body></html>

2023-02-21 19:55:20.3|Trace|Http|Res: 61 [GET] /3/download?apikey=(removed)&link=SzdPY2ZXVW80K1psMGluZ2dIb2d6NkZ4NHpmeFQzTHhVaGJrNzdPWkZqN2Y3eXo1UHlwVkc5QUhFRER0bmhySGNOUVhXL0xOVWxncndGczJDSHdaV3c9PQ&file=Avatar+(Extended+version)+2009+DUB%2C+Sub+BDRip: 500.InternalServerError (10363 ms)
```

**Comment by GoldGshok** [comment]
Update prowlarr to latest version 1.2.2.2699

Attach file with trace logs
[prowlarr_trace_log.txt](https://github.com/Prowlarr/Prowlarr/files/10802050/prowlarr_trace_log.txt)

**Comment by msergein** [comment]
new `kinozal.yml` works, thanks

**Comment by bakerboy448** [comment]
fixed by aforementioned referenced commits
