### ISSUE TITLE
YGGTorrent - Login failed: No form found on https://www6.yggtorrent.lol/ using form selector #user-login

### ISSUE THREAD

**Issue by Zegorax** [Prowlarr/Prowlarr#1392]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using a combination of Prowlarr and Flaresolverr (both at the latest version) and trying to add YGGTorrent with valid credentials (not using YGGCookie), Prowlarr will fail to add the indexer even though Flaresolverr solved the challenge successfully.

### Expected Behavior

Prowlarr should be able to parse the response and log into YGGTorrent

### Steps To Reproduce

1. Install Prowlarr and FlareSolverr in containers (same docker-compose, same network)
2. Configure the proxy in Prowlarr
3. Try to add YGGTorrent and set the flag to the same one as assigned in the configured proxy
4. Test will fail

### Environment

```markdown
- OS: Ubuntu Server 20.04
- Prowlarr: 1.0.1.2220
- Docker Install: Yes
- Using Reverse Proxy: Yes (Traefik)
- Browser: N/A
```

### What branch are you running?

Master

### Trace Logs?

```
prowlarr_1      | [Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
prowlarr_1      |  -- : Unable to connect to indexer, check the log for more details 
prowlarr_1      | [Info] Cardigann: Adding request: https://www6.yggtorrent.lol/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date 
prowlarr_1      | [Warn] Cardigann: Unable to connect to indexer 
prowlarr_1      | 
prowlarr_1      | [v1.0.1.2220] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannConfigException: Login failed: No form found on https://www6.yggtorrent.lol/ using form selector #user-login
prowlarr_1      |    at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 253
prowlarr_1      |    at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 165
prowlarr_1      |    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 374
prowlarr_1      |    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 285
prowlarr_1      |    at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 447
prowlarr_1      | 
prowlarr_1      | 
prowlarr_1      | [Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 
prowlarr_1      | 
prowlarr_1      | [v1.0.1.2220] FluentValidation.ValidationException: Validation failed: 
prowlarr_1      |  -- : Unable to connect to indexer, check the log for more details
prowlarr_1      |    at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
prowlarr_1      |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
prowlarr_1      |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
prowlarr_1      | --- End of stack trace from previous location ---
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
prowlarr_1      | --- End of stack trace from previous location ---
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
prowlarr_1      |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
prowlarr_1      |    at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
prowlarr_1      |    at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
prowlarr_1      |    at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
prowlarr_1      |    at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
prowlarr_1      |    at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
prowlarr_1      |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
prowlarr_1      |    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
prowlarr_1      |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
prowlarr_1      |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
prowlarr_1      |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
prowlarr_1      | 
prowlarr_1      | 
prowlarr_1      | [Warn] ProwlarrErrorPipeline: FluentValidation.ValidationException: Validation failed: 
prowlarr_1      |  -- : Unable to connect to indexer, check the log for more details 
prowlarr_1      | 
prowlarr_1      | [v1.0.1.2220] FluentValidation.ValidationException: Validation failed: 
prowlarr_1      |  -- : Unable to connect to indexer, check the log for more details
prowlarr_1      |    at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
prowlarr_1      |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
prowlarr_1      |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
prowlarr_1      | --- End of stack trace from previous location ---
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
prowlarr_1      | --- End of stack trace from previous location ---
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
prowlarr_1      |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
prowlarr_1      |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
prowlarr_1      |    at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
prowlarr_1      |    at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
prowlarr_1      |    at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
prowlarr_1      |    at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
prowlarr_1      |    at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
prowlarr_1      |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
prowlarr_1      |    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
prowlarr_1      |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
prowlarr_1      |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
prowlarr_1      |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
prowlarr_1      | 
prowlarr_1      | 
prowlarr_1      | [Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
prowlarr_1      |  -- : Unable to connect to indexer, check the log for more details 
```

[AB#4836](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4836)

**Comment by Zegorax** [comment]
Here are the trace logs. I think that either the FlareSolverr cookies are not used properly for the next requests, or that it is not using it at all.

https://gist.github.com/Zegorax/00da48aa61a1414c692864dcbc5f9e10

**Comment by bakerboy448** [comment]
Not Prowlarr issue; YGG has made breaking changes to their site because they hate automation apps, ban users for any discussion of Starrs, and actively make prowlarr as broken as often as possible.
