### ISSUE TITLE
ntfy integration fails to send notifications

### ISSUE THREAD

**Issue by thespad** [Prowlarr/Prowlarr#1398]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

ntfy integration fails to send test notification.

This is with a self-hosted ntfy instance, using authentication. Same configuration is working with Radarr.

### Expected Behavior

ntfy integration should send test notification when properly configured

### Steps To Reproduce

1. Add ntfy under Notifications
2. Configure with self-hosted URL and authentication, i.e.:

![image](https://user-images.githubusercontent.com/8425502/216819156-462e0c16-1b52-45aa-a0b1-7a66d65feb94.png)

4. Run Test or Save

### Environment

```markdown
- OS: Ubuntu 22.04
- Prowlarr: 1.2.0.2523
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: N/A
```

### What branch are you running?

Nightly

### Trace Logs?

2023-02-05 12:33:28.8|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v1.2.0.2523] System.NullReferenceException: Object reference not set to an instance of an object.
   at Prowlarr.Http.ClientSchema.SchemaBuilder.<>c.<GetValueConverter>b__8_7(Object fieldValue) in D:\a\1\s\src\Prowlarr.Http\ClientSchema\SchemaBuilder.cs:line 249
   at Prowlarr.Http.ClientSchema.SchemaBuilder.<>c__DisplayClass5_2.<GetFieldMapping>b__2(Object t, Object v) in D:\a\1\s\src\Prowlarr.Http\ClientSchema\SchemaBuilder.cs:line 135
   at Prowlarr.Http.ClientSchema.SchemaBuilder.ReadFromSchema(List`1 fields, Type targetType) in D:\a\1\s\src\Prowlarr.Http\ClientSchema\SchemaBuilder.cs:line 52
   at Prowlarr.Api.V1.ProviderResourceMapper`2.ToModel(TProviderResource resource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderResource.cs:line 68
   at Prowlarr.Api.V1.Notifications.NotificationResourceMapper.ToModel(NotificationResource resource) in D:\a\1\s\src\Prowlarr.Api.V1\Notifications\NotificationResource.cs:line 43
   at Prowlarr.Api.V1.ProviderControllerBase`3.GetDefinition(TProviderResource providerResource, Boolean validate, Boolean includeWarnings, Boolean forceValidate) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 97
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 65
   at lambda_method338(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2023-02-05 12:33:28.9|Warn|ProwlarrErrorPipeline|System.NullReferenceException: Object reference not set to an instance of an object.

[v1.2.0.2523] System.NullReferenceException: Object reference not set to an instance of an object.
   at Prowlarr.Http.ClientSchema.SchemaBuilder.<>c.<GetValueConverter>b__8_7(Object fieldValue) in D:\a\1\s\src\Prowlarr.Http\ClientSchema\SchemaBuilder.cs:line 249
   at Prowlarr.Http.ClientSchema.SchemaBuilder.<>c__DisplayClass5_2.<GetFieldMapping>b__2(Object t, Object v) in D:\a\1\s\src\Prowlarr.Http\ClientSchema\SchemaBuilder.cs:line 135
   at Prowlarr.Http.ClientSchema.SchemaBuilder.ReadFromSchema(List`1 fields, Type targetType) in D:\a\1\s\src\Prowlarr.Http\ClientSchema\SchemaBuilder.cs:line 52
   at Prowlarr.Api.V1.ProviderResourceMapper`2.ToModel(TProviderResource resource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderResource.cs:line 68
   at Prowlarr.Api.V1.Notifications.NotificationResourceMapper.ToModel(NotificationResource resource) in D:\a\1\s\src\Prowlarr.Api.V1\Notifications\NotificationResource.cs:line 43
   at Prowlarr.Api.V1.ProviderControllerBase`3.GetDefinition(TProviderResource providerResource, Boolean validate, Boolean includeWarnings, Boolean forceValidate) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 97
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 65
   at lambda_method338(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2023-02-05 12:33:29.0|Fatal|ProwlarrErrorPipeline|Request Failed. POST /api/v1/notification

[v1.2.0.2523] System.NullReferenceException: Object reference not set to an instance of an object.
   at Prowlarr.Http.ClientSchema.SchemaBuilder.<>c.<GetValueConverter>b__8_7(Object fieldValue) in D:\a\1\s\src\Prowlarr.Http\ClientSchema\SchemaBuilder.cs:line 249
   at Prowlarr.Http.ClientSchema.SchemaBuilder.<>c__DisplayClass5_2.<GetFieldMapping>b__2(Object t, Object v) in D:\a\1\s\src\Prowlarr.Http\ClientSchema\SchemaBuilder.cs:line 135
   at Prowlarr.Http.ClientSchema.SchemaBuilder.ReadFromSchema(List`1 fields, Type targetType) in D:\a\1\s\src\Prowlarr.Http\ClientSchema\SchemaBuilder.cs:line 52
   at Prowlarr.Api.V1.ProviderResourceMapper`2.ToModel(TProviderResource resource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderResource.cs:line 68
   at Prowlarr.Api.V1.Notifications.NotificationResourceMapper.ToModel(NotificationResource resource) in D:\a\1\s\src\Prowlarr.Api.V1\Notifications\NotificationResource.cs:line 43
   at Prowlarr.Api.V1.ProviderControllerBase`3.GetDefinition(TProviderResource providerResource, Boolean validate, Boolean includeWarnings, Boolean forceValidate) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 97
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 65
   at lambda_method338(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[AB#4862](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4862)

**Comment by Qstick** [comment]
Lets try next build with 011fd57f7d066ec3e10c06eaa4a97f0e263900ab
