### ISSUE TITLE
Anidex - Cannot Add to Prowlarr, "Validation Failed"

### ISSUE THREAD

**Issue by jeff15110168** [Prowlarr/Prowlarr#1409]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

hi - i'm having issues adding anidex to my prowlarr once i saw it was [added per the Hellonext update](https://prowlarr.hellonext.co/p/torrent-anidex). Below is the trace snippet of log when i try to hit test button with flaresolverr active in the tag field. Any idea what could be causing this or what fix is?

### Expected Behavior

Expect Anidex test to be successful.

### Steps To Reproduce

1. add indexer to prowlarr
2. select Anidex from list
3. add flaresolverr tag
4. click test button

### Environment

```markdown
- OS: Unraid 6.11.5
- Prowlarr: 1.1.3.2521
- Docker Install: 1.1.3.2521-ls89 by linuxserver.io
- Using Reverse Proxy: no, direct access via 192.168.0.xxx:9696
- Browser: Chrome 109.0.5414.120
```

### What branch are you running?

Master

### Trace Logs?
FULL LOG: https://gist.github.com/jeff15110168/97cb05cf46603241d984e678bc4a41ac

```
[v1.1.3.2521] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

[AB#4885](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4885)

**Comment by bakerboy448** [comment]
Please provide the trace logs required for bug reports. The bug report template links to the wiki explaining how to get trace logs.

An error saying an error occurred and to check the logs [above that message] is not valid for bug reports

**Comment by jeff15110168** [comment]
thank you - i turned on trace, reset my logs, and pasted the entire output here after replicating the steps:

https://gist.github.com/jeff15110168/97cb05cf46603241d984e678bc4a41ac

**Comment by bakerboy448** [comment]
```
2023-02-08 11:30:28.8|Debug|FlareSolverr|Cloudflare Detected, Applying FlareSolverr Proxy FlareSolverr to request https://anidex.info/?page=search&s=upload_timestamp&o=desc&group_id=0&q=
2023-02-08 11:30:28.8|Trace|HttpClient|Req: [POST] http://192.168.0.117:8191/v1
2023-02-08 11:30:28.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-02-08 11:30:28.8|Warn|Anidex|Unable to connect to indexer

[v1.1.3.2521] System.Net.Http.HttpRequestException: Connection refused (192.168.0.117:8191)
```

nothing is accessible at that IP:Port

**Comment by ilike2burnthing** [comment]
If you access `http://192.168.0.117:8191` in browser, what is returned?

If you use `curl -v http://192.168.0.117:8191` from within the Prowlarr container, what is returned?

**Comment by jeff15110168** [comment]
ah i got it to work! had to update my flaresolverr container that was acting up. thank you so much!
