### ISSUE TITLE
Polishsource Unable to connect to indexer

### ISSUE THREAD

**Issue by kodifan** [Prowlarr/Prowlarr#1433]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Polishsource tracker is not functional. It was working like few days ago.
In logs there is information :
[v1.2.0.2583] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://polishsource.cz/login.php]

Site itself is working fine i can login to it without any problems. 

### Expected Behavior

It should work again :)

### Steps To Reproduce

Test in Indexer  configuration. 

### Environment

```markdown
- OS: Synology 6.1
- Prowlarr: 1.2.0.2583
- Docker Install: yes
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

2023-02-15 17:05:09.4|Warn|IndexerHttpClient|HTTP Error - Res: [GET] https://polishsource.cz/login.php: 403.Forbidden (162 bytes)
2023-02-15 17:05:09.5|Warn|Cardigann|Unable to connect to indexer

[v1.2.0.2583] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://polishsource.cz/login.php]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 127
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.GetConfigurationForSetup(Boolean automaticlogin) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 606
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 247
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 180
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 385
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 319
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 463
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by bakerboy448** [comment]
Not a Prowlarr issue.

the tracker is blocking Prowlarr's useragent - you'll need to discuss with them why they are deciding to block prowlarr

**Comment by kodifan** [comment]
> Not a Prowlarr issue.
> 
> the tracker is blocking Prowlarr's useragent - you'll need to discuss with them why they are deciding to block prowlarr

i was suspecting this that something is maybe blocked at tracker side, but i thought it might be either reconfigured from Prowlarr side. I dont think they will change their minds, they are kind of stubborn people :)

**Comment by bakerboy448** [comment]
I mean if they don't want automation used on their site; that is their prerogative

**Comment by kodifan** [comment]
they also blocked some shell providers recently. what is more strange ive search over their site i cant see any info about not allowing indexers to search their tracker. maybe they will unblock it in future who knows :(

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/e59074ff1e5c4d5ae10f4a25cda61756bbd0f389
