### ISSUE TITLE
Issues with GreatPosterWall indexer

### ISSUE THREAD

**Issue by sunnyd24** [Prowlarr/Prowlarr#1445]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Constant indexer failures for GreatPosterWall.

"Unable to connect to indexer. Unexpected response status Redirect code from API request"

### Expected Behavior

Passes test and does not fail. Used to work fine a few weeks/month ago.

### Steps To Reproduce

Add indexer to list (provide username and password)
Add socks5 proxy (tested without proxy and still does not work, same error as below)
Press test.
Fails with error "Unable to connect to indexer. Unexpected response status Redirect code from API request"

### Environment

```markdown
- OS: Windows
- Prowlarr: 1.1.3.2521
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Edge 110.0.1587.41
```

### What branch are you running?

Master

### Trace Logs?

2023-02-19 02:11:09.3|Trace|Http|Req: 24652 [POST] /api/v1/indexer/action/getUrls (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41)
2023-02-19 02:11:09.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-19 02:11:09.3|Trace|Http|Res: 24652 [POST] /api/v1/indexer/action/getUrls: 200.OK (2 ms)
2023-02-19 02:11:09.3|Debug|Api|[POST] /api/v1/indexer/action/getUrls: 200.OK (2 ms)
2023-02-19 02:11:10.5|Trace|Http|Req: 24653 [POST] /api/v1/indexer/test (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41)
2023-02-19 02:11:10.5|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-19 02:11:10.5|Debug|GreatPosterWall|Downloading Feed https://greatposterwall.com/ajax.php?action=browse&order_by=time&order_way=desc
2023-02-19 02:11:10.5|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-02-19 02:11:10.5|Debug|Socks5|Applying Socks5 Proxy Socks5 to request https://greatposterwall.com/ajax.php?action=browse&order_by=time&order_way=desc
2023-02-19 02:11:10.5|Trace|IndexerHttpClient|Req: [GET] https://greatposterwall.com/ajax.php?action=browse&order_by=time&order_way=desc
2023-02-19 02:11:11.7|Trace|IndexerHttpClient|Res: [GET] https://greatposterwall.com/ajax.php?action=browse&order_by=time&order_way=desc: 302.Redirect (0 bytes) (1215 ms)
2023-02-19 02:11:11.7|Trace|GreatPosterWall|Attempting to re-auth based on indexer search response
2023-02-19 02:11:11.7|Debug|Socks5|Applying Socks5 Proxy Socks5 to request https://greatposterwall.com/login.php
2023-02-19 02:11:11.7|Trace|IndexerHttpClient|Req: [POST] https://greatposterwall.com/login.php: username=(removed)&password=(removed)&keeplogged=1
2023-02-19 02:11:12.0|Trace|IndexerHttpClient|Res: [POST] https://greatposterwall.com/login.php: 301.Moved (0 bytes) (296 ms)
2023-02-19 02:11:12.0|Trace|IndexerHttpClient|Response content (0 bytes): 
2023-02-19 02:11:12.0|Trace|EventAggregator|Publishing IndexerAuthEvent
2023-02-19 02:11:12.0|Trace|EventAggregator|IndexerAuthEvent -> HistoryService
2023-02-19 02:11:12.0|Trace|EventAggregator|IndexerAuthEvent <- HistoryService
2023-02-19 02:11:12.0|Debug|GreatPosterWall|Gazelle authentication succeeded.
2023-02-19 02:11:12.0|Debug|Socks5|Applying Socks5 Proxy Socks5 to request https://greatposterwall.com/ajax.php?action=browse&order_by=time&order_way=desc
2023-02-19 02:11:12.0|Trace|RateLimitService|Rate Limit triggered, delaying 'greatposterwall.com' for 0.475 sec
2023-02-19 02:11:12.5|Trace|IndexerHttpClient|Req: [GET] https://greatposterwall.com/ajax.php?action=browse&order_by=time&order_way=desc
2023-02-19 02:11:13.7|Trace|IndexerHttpClient|Res: [GET] https://greatposterwall.com/ajax.php?action=browse&order_by=time&order_way=desc: 302.Redirect (0 bytes) (1213 ms)
2023-02-19 02:11:13.7|Trace|GreatPosterWall|Unexpected Response content (0 bytes): 
2023-02-19 02:11:13.7|Warn|GreatPosterWall|Unable to connect to indexer

[v1.1.3.2521] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status Redirect code from API request
   at NzbDrone.Core.Indexers.Definitions.GreatPosterWallParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\GreatPosterWall.cs:line 124
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 308
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 508
RequestUri: https://greatposterwall.com/ajax.php?action=browse&order_by=time&order_way=desc;StatusCode: Redirect;ContentType: text/html; charset=utf-8;ContentLength: 0

2023-02-19 02:11:13.7|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v1.1.3.2521] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Redirect code from API request
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 146
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2023-02-19 02:11:13.8|Trace|ProwlarrErrorPipeline|Handling Exception
2023-02-19 02:11:13.8|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Redirect code from API request

[v1.1.3.2521] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Redirect code from API request
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 146
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2023-02-19 02:11:13.9|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Redirect code from API request
2023-02-19 02:11:13.9|Trace|Http|Res: 24653 [POST] /api/v1/indexer/test: 400.BadRequest (3413 ms)
2023-02-19 02:11:13.9|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (3413 ms)
2023-02-19 02:11:16.0|Trace|Scheduler|Pending Tasks: 0
2023-02-19 02:11:17.3|Trace|Http|Req: 24654 [GET] /api/v1/health (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41)
2023-02-19 02:11:17.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-19 02:11:17.3|Trace|Http|Res: 24654 [GET] /api/v1/health: 200.OK (1 ms)
2023-02-19 02:11:17.3|Debug|Api|[GET] /api/v1/health: 200.OK (1 ms)
2023-02-19 02:11:17.3|Trace|Http|Req: 24655 [GET] /api/v1/system/status (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41)
2023-02-19 02:11:17.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-19 02:11:17.3|Trace|Http|Res: 24655 [GET] /api/v1/system/status: 200.OK (4 ms)
2023-02-19 02:11:17.3|Debug|Api|[GET] /api/v1/system/status: 200.OK (4 ms)
2023-02-19 02:11:18.3|Trace|Http|Req: 24656 [GET] /api/v1/log/file (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41)
2023-02-19 02:11:18.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-19 02:11:18.3|Trace|Http|Res: 24656 [GET] /api/v1/log/file: 200.OK (2 ms)
2023-02-19 02:11:18.3|Debug|Api|[GET] /api/v1/log/file: 200.OK (2 ms)
2023-02-19 02:11:20.0|Trace|Http|Req: 24657 [GET] /logfile/prowlarr.trace.txt (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41)
2023-02-19 02:11:20.0|Info|Prowlarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.

**Comment by sunnyd24** [comment]
@Bogdan

Interesting, it seems the website is being redirected to kshare.club. Not
sure if this is a sister site of theirs or the website has been hijacked.

**Comment by sunnyd24** [comment]
@Bogdan
Installed the nightly, and tried out cookies but with no success.
I had username/password entered and tried out two cookie types, phpsessid
and session values (from logged in session in Chrome using Developer
Settings).
Neither worked for me, with error message:

"Unable to connect to indexer. We are being redirected to the login page.
Most likely your session expired or was killed. Recheck your cookie or
credentials and try testing the indexer."

**Comment by sunnyd24** [comment]
@Bogdan
It is working now using the format provided.

I was missing the "lang=chs; session=" before the cookie value string.

Thanks for fixing this issue. Now need to disable 2FA if I can!
