### ISSUE TITLE
HD-Space "Unknown error message, please report"

### ISSUE THREAD

**Issue by Kopernikus1979** [Prowlarr/Prowlarr#1552]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hi,

When I try to add HD-Space I get the error "Unknown error message, please report".
I also use Flaresolvr 3.04 and when I check the logs, it's solving the query receiving from HD-Space.

### Expected Behavior

Working indexer

### Steps To Reproduce

Adding HD-Space to the indexers

### Environment

```markdown
- OS: Unraid
- Prowlarr: nightly (linuxserver)
- Flaresolvr: latest (docker)
- Docker Install: Unraid template
- Using Reverse Proxy: No
```

### What branch are you running?

Nightly

### Trace Logs?

[Warn] ProwlarrErrorPipeline: FluentValidation.ValidationException: Validation failed: 
 -- : Unknown error message, please report. 

[v1.3.2.2964] FluentValidation.ValidationException: Validation failed: 
 -- : Unknown error message, please report.
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 69
   at lambda_method573(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\StartingUpMiddleware.cs:line 38
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- : Unknown error message, please report.

**Comment by bakerboy448** [comment]
Please provide the trace logs that are required and the bug report asks for.

the provided info logs and error saying there is an error are not valid for bug reports.

From the template 

> Trace Logs?
> Trace Logs (https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files)
> Generally speaking, all bug reports must have trace logs provided.

**Comment by Kopernikus1979** [comment]
Done

**Comment by bakerboy448** [comment]
Looks like those logs got mangled or html encoded?

**Comment by bakerboy448** [comment]
flaresolverr needs to be on the same machine/(public)IP as prowlarr - is that the case?

**Comment by Kopernikus1979** [comment]
Yes/No, my prowlarr is set to use privoxy (just like my other arr aps).
To test I disabled it, add I could add HD-Space.
Then enabled privoxy again and seems te be working...

Thx

**Comment by klepp0906** [comment]
having the same problem, unsure if i should open a separate issue or?  (both prowl and flare on running on same machine)

https://0bin.net/paste/nCoMkdgC#D+Q47y4iBh6u2o5lLBBfkXUDM62bUEL9J68+uLA3Szi
