### ISSUE TITLE
spotweb xml error

### ISSUE THREAD

**Issue by stevezau** [Prowlarr/Prowlarr#1563]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hi, I see Spotweb failing at times with the below error. Looks like it might not be handling the response correctly.

If I hit the URL manually I get a "the query is not allowed popup". 

I suspect it is related to https://github.com/spotweb/spotweb/issues/802

### Expected Behavior

I'd expect the query to work or the error to be handled so it does not disable the indexer 

### Environment

```markdown
- OS: Ubuntu 22.10 (Docker)
- Prowlarr: 1.2.2.2699
- Docker Install: 1.2.2.2699
```

### What branch are you running?

Master

### Trace Logs?

```[Error] Newznab: An error occurred while processing indexer feed. https://spotweb.nzbfinder.ws/api?t=search&extended=1&cat=2030,2040,2050,2060,2000&apikey=XXXX&q=Barbie+as+the+Island+Princess+2007&limit=100&offset=0

[v1.2.2.2699] System.Xml.XmlException: There are multiple root elements. Line 1, position 76.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 109
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Newznab\NewznabRssParser.cs:line 65
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 410
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 267
RequestUri: https://spotweb.nzbfinder.ws/api?t=search&extended=1&cat=2030,2040,2050,2060,2000&apikey=XXXX&q=Barbie+as+the+Island+Princess+2007&limit=100&offset=0;StatusCode: OK;ContentType: text/html; charset=utf-8;ContentLength: 179;ContentSample: <script language="javascript">alert("This query is not allowed!")</script><script language = "javascript">window.location.href = "/?search[tree]=&search[unfiltered]=true"</script>;FeedUrl: https://spotweb.nzbfinder.ws/api?t=search&extended=1&cat=2030,2040,2050,2060,2000&apikey=XXXX&q=Barbie+as+the+Island+Princess+2007&limit=100&offset=0```

**Comment by bakerboy448** [comment]
> Trace Logs (https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files)
> Generally speaking, all bug reports must have trace logs provided.

Please provide the required trace logs.  a single line error is not valid for bug reports

**Comment by stevezau** [comment]
@bakerboy448 I understand.. However. The bug report shows the URL which was hit, that URL is returned always returned an error. It seems the indexer code does not understand how to handle that error. I thought that would have been enough.

That URL is ```https://spotweb.nzbfinder.ws/api?t=search&extended=1&cat=2030,2040,2050,2060,2000&apikey=XXXX&q=Barbie+as+the+Island+Princess+2007&limit=100&offset=0```

I will try capture the next time the error occurs but it is random so it makes it difficult to get a full trace log without trace being on all the time.

**Comment by stevezau** [comment]
Attaching more detailed logs (i think)

```
023-04-02 10:33:49.8|Info|ReleaseSearchService|Searching indexer(s): [NZBFinder] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2010, 2030, 2040, 2045, 2050, 2060, 2070, 2080]
2023-04-02 10:33:49.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:33:49.8|Debug|Newznab|Downloading Feed https://nzbfinder.ws/api?t=search&extended=1&cat=2010,2030,2040,2045,2050,2060,2070,2080,2090,2999,2000&apikey=(removed)&limit=100&offset=0
2023-04-02 10:33:49.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:33:49.8|Info|ReleaseSearchService|Searching indexer(s): [SpotNZB] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2030, 2040, 2050, 2060]
2023-04-02 10:33:49.8|Info|ReleaseSearchService|Searching indexer(s): [TorrentLeech] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2030, 2070, 2050, 2040, 2045, 2010, 2080]
2023-04-02 10:33:49.8|Debug|Newznab|Downloading Feed https://spotweb.nzbfinder.ws/api?t=search&extended=1&cat=2030,2040,2050,2060,2000&apikey=(removed)&limit=100&offset=0
2023-04-02 10:33:49.8|Debug|Cardigann|Populating config vars
2023-04-02 10:33:49.8|Info|ReleaseSearchService|Searching indexer(s): [Nzb.su] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2010, 2040, 2020, 2030, 2045]
2023-04-02 10:33:49.8|Info|Cardigann|Adding request: https://www.torrentleech.org/torrents/browse/list/categories/1%2C8%2C9%2C11%2C12%2C13%2C14%2C15%2C47%2C36%2C37%2C43/exact/1/query//newfilter/2/orderby/added/order/desc
2023-04-02 10:33:49.8|Debug|Newznab|Downloading Feed https://api.nzb.su/api?t=search&extended=1&cat=2010,2040,2020,2030,2045,2000&apikey=(removed)&limit=100&offset=0
2023-04-02 10:33:49.8|Info|ReleaseSearchService|Searching indexer(s): [NzbPlanet] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2060, 2050, 2080, 2010, 2040, 2020, 2030, 2070]
2023-04-02 10:33:49.8|Info|ReleaseSearchService|Searching indexer(s): [NZBgeek] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060]
2023-04-02 10:33:49.8|Debug|Cardigann|Downloading Feed https://www.torrentleech.org/torrents/browse/list/categories/1%2C8%2C9%2C11%2C12%2C13%2C14%2C15%2C47%2C36%2C37%2C43/exact/1/query//newfilter/2/orderby/added/order/desc
2023-04-02 10:33:49.8|Debug|Newznab|Downloading Feed https://api.nzbplanet.org/api?t=search&extended=1&cat=2060,2050,2080,2010,2040,2020,2030,2070,2000&apikey=(removed)&limit=100&offset=0
2023-04-02 10:33:49.8|Debug|Newznab|Downloading Feed https://api.nzbgeek.info/api?t=search&extended=1&cat=2010,2020,2030,2040,2045,2050,2060,2000&apikey=(removed)&limit=100&offset=0
2023-04-02 10:33:49.8|Info|ReleaseSearchService|Searching indexer(s): [RevolutionTT] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2050, 2070, 2040, 2020, 2030]
2023-04-02 10:33:49.8|Debug|RevolutionTT|Downloading Feed https://revolutiontt.me/browse.php?incldead=1&titleonly=1&search=&c10=1&c20=1&c12=1&c44=1&c11=1&c19=1
2023-04-02 10:33:50.7|Debug|ReleaseSearchService|Total of 50 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [2000] from 1 indexer(s)
2023-04-02 10:33:50.8|Debug|ReleaseSearchService|Total of 100 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2030, 2040, 2050, 2060] from 1 indexer(s)
2023-04-02 10:33:50.8|Debug|ReleaseSearchService|Total of 100 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2010, 2030, 2040, 2045, 2050, 2060, 2070, 2080] from 1 indexer(s)
2023-04-02 10:33:50.9|Debug|ReleaseSearchService|Total of 67 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2010, 2040, 2020, 2030, 2045] from 1 indexer(s)
2023-04-02 10:33:51.1|Debug|Cardigann|Parsing
2023-04-02 10:33:51.7|Debug|Cardigann|Got 35 releases
2023-04-02 10:33:51.7|Debug|ReleaseSearchService|Total of 35 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2030, 2070, 2050, 2040, 2045, 2010, 2080] from 1 indexer(s)
2023-04-02 10:33:51.8|Debug|ReleaseSearchService|Total of 50 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2030, 2040, 2045, 2050] from 1 indexer(s)
2023-04-02 10:33:51.8|Debug|ReleaseSearchService|Total of 100 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2060, 2050, 2080, 2010, 2040, 2020, 2030, 2070] from 1 indexer(s)
2023-04-02 10:33:52.8|Debug|ReleaseSearchService|Total of 100 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060] from 1 indexer(s)
2023-04-02 10:33:53.1|Debug|ReleaseSearchService|Total of 200 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2050, 2070, 2040, 2020, 2030] from 1 indexer(s)
2023-04-02 10:34:27.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:27.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:27.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:27.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:27.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:27.9|Info|ReleaseSearchService|Searching indexer(s): [AlphaRatio] for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2030, 2040, 2045, 2050]
2023-04-02 10:34:27.9|Info|ReleaseSearchService|Searching indexer(s): [RevolutionTT] for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2050, 2070, 2040, 2020, 2030]
2023-04-02 10:34:27.9|Debug|AlphaRatio|Downloading Feed https://alpharatio.cc/ajax.php?action=browse&order_by=time&order_way=desc&searchstr=By+Deception+2022&filter_cat[8]=1&filter_cat[9]=1&filter_cat[10]=1&filter_cat[11]=1&filter_cat[12]=1&filter_cat[13]=1&filter_cat[15]=1
2023-04-02 10:34:27.9|Debug|RevolutionTT|Downloading Feed https://revolutiontt.me/browse.php?incldead=1&titleonly=0&search=tt2231058&c10=1&c20=1&c12=1&c44=1&c11=1&c19=1
2023-04-02 10:34:27.9|Info|ReleaseSearchService|Searching indexer(s): [NzbPlanet] for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2060, 2050, 2080, 2010, 2040, 2020, 2030, 2070]
2023-04-02 10:34:27.9|Info|ReleaseSearchService|Searching indexer(s): [NZBFinder] for Term: [] | ID(s): IMDbId:[2231058] TMDbId:[886970], Offset: 0, Limit: 100, Categories: [2000, 2010, 2030, 2040, 2045, 2050, 2060, 2070, 2080]
2023-04-02 10:34:27.9|Debug|Newznab|Downloading Feed https://api.nzbplanet.org/api?t=movie&extended=1&cat=2060,2050,2080,2010,2040,2020,2030,2070,2000&apikey=(removed)&imdbid=2231058&limit=100&offset=0
2023-04-02 10:34:27.9|Info|ReleaseSearchService|Searching indexer(s): [HDBits] for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000]
2023-04-02 10:34:27.9|Debug|Newznab|Downloading Feed https://nzbfinder.ws/api?t=movie&extended=1&cat=2010,2030,2040,2045,2050,2060,2070,2080,2090,2999,2000&apikey=(removed)&tmdbid=886970&imdbid=2231058&limit=100&offset=0
2023-04-02 10:34:27.9|Debug|HDBits|Downloading Feed https://hdbits.org/api/torrents
2023-04-02 10:34:28.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:28.0|Info|ReleaseSearchService|Searching indexer(s): [TorrentLeech] for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2030, 2070, 2050, 2040, 2045, 2010, 2080]
2023-04-02 10:34:28.0|Debug|Cardigann|Populating config vars
2023-04-02 10:34:28.0|Info|Cardigann|Adding request: https://www.torrentleech.org/torrents/browse/list/categories/1%2C8%2C9%2C11%2C12%2C13%2C14%2C15%2C47%2C36%2C37%2C43/imdbID/tt2231058/newfilter/2/orderby/added/order/desc
2023-04-02 10:34:28.0|Debug|Cardigann|Downloading Feed https://www.torrentleech.org/torrents/browse/list/categories/1%2C8%2C9%2C11%2C12%2C13%2C14%2C15%2C47%2C36%2C37%2C43/imdbID/tt2231058/newfilter/2/orderby/added/order/desc
2023-04-02 10:34:28.2|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [] | ID(s): IMDbId:[2231058] TMDbId:[886970], Offset: 0, Limit: 100, Categories: [2000, 2010, 2030, 2040, 2045, 2050, 2060, 2070, 2080] from 1 indexer(s)
2023-04-02 10:34:28.2|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:28.3|Info|ReleaseSearchService|Searching indexer(s): [NZBgeek] for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060]
2023-04-02 10:34:28.3|Debug|Newznab|Downloading Feed https://api.nzbgeek.info/api?t=movie&extended=1&cat=2010,2020,2030,2040,2045,2050,2060,2000&apikey=(removed)&imdbid=2231058&limit=100&offset=0
2023-04-02 10:34:28.6|Debug|Cardigann|Parsing
2023-04-02 10:34:28.6|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2030, 2070, 2050, 2040, 2045, 2010, 2080] from 1 indexer(s)
2023-04-02 10:34:28.6|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:28.6|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2030, 2040, 2045, 2050] from 1 indexer(s)
2023-04-02 10:34:28.6|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:28.6|Info|ReleaseSearchService|Searching indexer(s): [Nzb.su] for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2010, 2040, 2020, 2030, 2045]
2023-04-02 10:34:28.6|Debug|Newznab|Downloading Feed https://api.nzb.su/api?t=movie&extended=1&cat=2010,2040,2020,2030,2045,2000&apikey=(removed)&imdbid=2231058&limit=100&offset=0
2023-04-02 10:34:28.6|Info|ReleaseSearchService|Searching indexer(s): [SpotNZB] for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2030, 2040, 2050, 2060]
2023-04-02 10:34:28.6|Debug|Newznab|Downloading Feed https://spotweb.nzbfinder.ws/api?t=movie&extended=1&cat=2030,2040,2050,2060,2000&apikey=(removed)&imdbid=2231058&limit=100&offset=0
2023-04-02 10:34:28.8|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2060, 2050, 2080, 2010, 2040, 2020, 2030, 2070] from 1 indexer(s)
2023-04-02 10:34:28.9|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000] from 1 indexer(s)
2023-04-02 10:34:29.0|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2050, 2070, 2040, 2020, 2030] from 1 indexer(s)
2023-04-02 10:34:29.2|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060] from 1 indexer(s)
2023-04-02 10:34:29.3|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2010, 2040, 2020, 2030, 2045] from 1 indexer(s)
2023-04-02 10:34:29.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:29.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:29.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:29.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:29.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:29.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:29.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:29.9|Info|ReleaseSearchService|Searching indexer(s): [NzbPlanet] for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2060, 2050, 2080, 2010, 2040, 2020, 2030, 2070]
2023-04-02 10:34:29.9|Info|ReleaseSearchService|Searching indexer(s): [HDBits] for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000]
2023-04-02 10:34:29.9|Debug|HDBits|Downloading Feed https://hdbits.org/api/torrents
2023-04-02 10:34:29.9|Debug|Newznab|Downloading Feed https://api.nzbplanet.org/api?t=search&extended=1&cat=2060,2050,2080,2010,2040,2020,2030,2070,2000&apikey=(removed)&q=By+Deception+2022&limit=100&offset=0
2023-04-02 10:34:29.9|Info|ReleaseSearchService|Searching indexer(s): [NZBgeek] for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060]
2023-04-02 10:34:29.9|Debug|Newznab|Downloading Feed https://api.nzbgeek.info/api?t=search&extended=1&cat=2010,2020,2030,2040,2045,2050,2060,2000&apikey=(removed)&q=By+Deception+2022&limit=100&offset=0
2023-04-02 10:34:29.9|Info|ReleaseSearchService|Searching indexer(s): [RevolutionTT] for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2050, 2070, 2040, 2020, 2030]
2023-04-02 10:34:29.9|Info|ReleaseSearchService|Searching indexer(s): [TorrentLeech] for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2030, 2070, 2050, 2040, 2045, 2010, 2080]
2023-04-02 10:34:29.9|Debug|RevolutionTT|Downloading Feed https://revolutiontt.me/browse.php?incldead=1&titleonly=1&search=By+Deception+2022&c10=1&c20=1&c12=1&c44=1&c11=1&c19=1
2023-04-02 10:34:29.9|Info|ReleaseSearchService|Searching indexer(s): [NZBFinder] for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2010, 2030, 2040, 2045, 2050, 2060, 2070, 2080]
2023-04-02 10:34:29.9|Debug|Cardigann|Populating config vars
2023-04-02 10:34:29.9|Debug|Newznab|Downloading Feed https://nzbfinder.ws/api?t=search&extended=1&cat=2010,2030,2040,2045,2050,2060,2070,2080,2090,2999,2000&apikey=(removed)&q=By+Deception+2022&limit=100&offset=0
2023-04-02 10:34:29.9|Info|Cardigann|Adding request: https://www.torrentleech.org/torrents/browse/list/categories/1%2C8%2C9%2C11%2C12%2C13%2C14%2C15%2C47%2C36%2C37%2C43/exact/1/query/By%20Deception%202022/orderby/added/order/desc
2023-04-02 10:34:29.9|Debug|Cardigann|Downloading Feed https://www.torrentleech.org/torrents/browse/list/categories/1%2C8%2C9%2C11%2C12%2C13%2C14%2C15%2C47%2C36%2C37%2C43/exact/1/query/By%20Deception%202022/orderby/added/order/desc
2023-04-02 10:34:29.9|Info|ReleaseSearchService|Searching indexer(s): [Nzb.su] for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2010, 2040, 2020, 2030, 2045]
2023-04-02 10:34:29.9|Debug|Newznab|Downloading Feed https://api.nzb.su/api?t=search&extended=1&cat=2010,2040,2020,2030,2045,2000&apikey=(removed)&q=By+Deception+2022&limit=100&offset=0
2023-04-02 10:34:30.2|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2010, 2030, 2040, 2045, 2050, 2060, 2070, 2080] from 1 indexer(s)
2023-04-02 10:34:30.2|Debug|NewznabRssParser|Truncated response content (originally 179 characters): <script language="javascript">alert("This query is not allowed!")</script><script language = "javascript">window.location.href = "/?search[tree]=&search[unfiltered]=true"</script>
2023-04-02 10:34:30.2|Error|Newznab|An error occurred while processing indexer feed. https://spotweb.nzbfinder.ws/api?t=movie&extended=1&cat=2030,2040,2050,2060,2000&apikey=(removed)&imdbid=2231058&limit=100&offset=0

[v1.2.2.2699] System.Xml.XmlException: There are multiple root elements. Line 1, position 76.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 109
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Newznab\NewznabRssParser.cs:line 65
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 410
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 267
RequestUri: https://spotweb.nzbfinder.ws/api?t=movie&extended=1&cat=2030,2040,2050,2060,2000&apikey=(removed)&imdbid=2231058&limit=100&offset=0;StatusCode: OK;ContentType: text/html; charset=utf-8;ContentLength: 179;ContentSample: <script language="javascript">alert("This query is not allowed!")</script><script language = "javascript">window.location.href = "/?search[tree]=&search[unfiltered]=true"</script>;FeedUrl: https://spotweb.nzbfinder.ws/api?t=movie&extended=1&cat=2030,2040,2050,2060,2000&apikey=(removed)&imdbid=2231058&limit=100&offset=0

2023-04-02 10:34:30.2|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [] | ID(s): IMDbId:[2231058], Offset: 0, Limit: 100, Categories: [2000, 2030, 2040, 2050, 2060] from 1 indexer(s)
2023-04-02 10:34:30.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-02 10:34:30.3|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [By Deception 2022], Offset: 0, Limit: 100, Categories: [2000, 2050, 2070, 2040, 2020, 2030] from 1 indexer(s)
```

**Comment by bakerboy448** [comment]
Those are debug not trace

not a prowlarr issue; spot web is not quite newznab and thus not fully supported. Prowlarr only supports newznab and that response is non-supported
