### ISSUE TITLE
Identify issues in config.xml instead of just throwing blank error

### ISSUE THREAD

**Issue by rootwyrm** [Prowlarr/Prowlarr#1648]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The message on config.xml problems is entirely useless, and in fact, extremely counterproductive for PostgreSQL installs. This error should at minimum specify which line is causing the error, or preferably, the element causing the error.

```
2023-05-07 13:25:27.7|Info|Bootstrap|Starting Prowlarr - /opt/Prowlarr/Prowlarr - Version 1.4.1.3258
2023-05-07 13:25:27.8|Info|AppFolderInfo|Data directory is being overridden to [/talecaster/config]
2023-05-07 13:25:27.8|Fatal|ConsoleApp|EPIC FAIL!

[v1.4.1.3258] NzbDrone.Common.Exceptions.ProwlarrStartupException: Prowlarr failed to start: /talecaster/config/config.xml is corrupt or invalid. Please delete the config file and Prowlarr will recreate it.
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in ./Prowlarr.Host/Bootstrap.cs:line 112
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in ./Prowlarr.Console/ConsoleApp.cs:line 43
```

### Describe the solution you'd like

Error message should be updated to provide either the line or the element causing the parsing error.

### Describe alternatives you've considered

None available.

### Anything else?

 If a PostgreSQL user follows these instructions, they will blow up their installation. That's definitely ungood.

**Comment by bakerboy448** [comment]
Bug not a feature request.  Please edit your post to follow the bug report template & provide the corrupt config file sans apikey

**Comment by rootwyrm** [comment]
This is for the error message itself, NOT a config parse bug. (That would be a separate issue.) The error message not containing any further information is intended behavior. 

https://github.com/Prowlarr/Prowlarr/blob/92e7a38bd0a2b832d82163c5ac527ab1e23fe026/src/NzbDrone.Host/Bootstrap.cs#L241
