### ISSUE TITLE
Updater does not work

### ISSUE THREAD

**Issue by Xionax** [Prowlarr/Prowlarr#1694]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When clicking on `install latest` it looks like the update proces is running but just after prowlarr is restarted the same version is still running.

### Expected Behavior

Updating to the latest version

### Steps To Reproduce

1. Click on install latest
2. Wait until prowlarr is restarted
3. Check which version is running

### Environment

```markdown
- OS: Debian Bullseye
- Prowlarr: 1.4.1.3258
- Docker Install: n/a
- Using Reverse Proxy: n/a
- Browser: Any
```

### What branch are you running?

Master

### Trace Logs?

```
I got the same problem as the submitter of this ticket

```
2023-05-26 13:37:12.7|Debug|UpdateApp|NzbDrone process ID: 1109
2023-05-26 13:37:12.7|Debug|UpdateApp|Arguments:
2023-05-26 13:37:12.7|Debug|UpdateApp|  1109
2023-05-26 13:37:12.7|Debug|UpdateApp|  /tmp/prowlarr_update
2023-05-26 13:37:12.7|Debug|UpdateApp|  /opt/Prowlarr/Prowlarr
2023-05-26 13:37:12.7|Debug|UpdateApp|  /data=/var/lib/prowlarr
2023-05-26 13:37:12.7|Debug|UpdateApp|  /nobrowser
2023-05-26 13:37:12.7|Debug|UpdateApp|Using executing application: /opt/Prowlarr/Prowlarr
2023-05-26 13:37:12.7|Debug|UpdateApp|Executable location: /opt/Prowlarr/Prowlarr
2023-05-26 13:37:12.7|Info|InstallUpdateService|Installation Folder: /opt/Prowlarr
2023-05-26 13:37:12.7|Info|InstallUpdateService|Updating Prowlarr from version 1.4.1.3258 to version 1.5.0.3390
2023-05-26 13:37:12.7|Info|InstallUpdateService|Verifying requirements before update...
2023-05-26 13:37:12.7|Debug|ProcessProvider|Finding process with Id:1109
2023-05-26 13:37:12.8|Fatal|UpdateApp|An error has occurred while applying update package.

[v1.5.0.3390] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in ./Prowlarr.Common/Processes/ProcessProvider.cs:line 333
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in ./Prowlarr.Common/Processes/ProcessProvider.cs:line 316
   at NzbDrone.Common.Processes.ProcessProvider.GetProcessById(Int32 id) in ./Prowlarr.Common/Processes/ProcessProvider.cs:line 74
   at NzbDrone.Common.Processes.ProcessProvider.Exists(Int32 processId) in ./Prowlarr.Common/Processes/ProcessProvider.cs:line 57
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Verify(String targetFolder, Int32 processId) in ./Prowlarr.Update/UpdateEngine/InstallUpdateService.cs:line 74
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in ./Prowlarr.Update/UpdateEngine/InstallUpdateService.cs:line 91
   at NzbDrone.Update.UpdateApp.Start(String[] args) in ./Prowlarr.Update/UpdateApp.cs:line 59
   at NzbDrone.Update.UpdateApp.Main(String[] args) in ./Prowlarr.Update/UpdateApp.cs:line 44
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by Xionax** [comment]
Logs can be found in the `tar.gz` file attached to this ticket.
[debug.tar.gz](https://github.com/Prowlarr/Prowlarr/files/11575902/debug.tar.gz)

**Comment by Xionax** [comment]
> @Qstick I just pushed [b8793d8](https://github.com/Prowlarr/Prowlarr/commit/b8793d8783664b94dde7a985364d1e7778d0ebc4)
> 
> But looking at https://github.com/Prowlarr/Prowlarr/blob/v1.5.0.3390/src/NzbDrone.Common/Processes/ProcessProvider.cs#L333 looks like `process.MainModule.FileName` can be hit by NullReferenceException.

Thank you. Just for my information; I've installed prowlarr using [http://prowlarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64](url) which means I should wait until the master release has this fix in it. Once again update it by "reinstalling" the master file and from that moment on I can update via the webinterface. right?

Or are there ways to quickly patch this issue without waiting for new master release?

**Comment by Qstick** [comment]
> @Qstick I just pushed [b8793d8](https://github.com/Prowlarr/Prowlarr/commit/b8793d8783664b94dde7a985364d1e7778d0ebc4)
> 
> But looking at https://github.com/Prowlarr/Prowlarr/blob/v1.5.0.3390/src/NzbDrone.Common/Processes/ProcessProvider.cs#L333 looks like `process.MainModule.FileName` can be hit by NullReferenceException.

Any idea what cases would cause this? Functionality shouldn't change either way from that commit given we dropped mono long ago, but would be interesting to know if we ever actually see what's driving a NullRef there.
