### ISSUE TITLE
Unable to connect to indexer, blocked by CloudFlare Protection despite FlareSolverr solving challenge

### ISSUE THREAD

**Issue by DanTm99** [Prowlarr/Prowlarr#1733]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Attempting to add EZTV indexer results in `blocked by CloudFlare Protection.` even though the challenge was solved by FlareSolverr.

### Expected Behavior

The indexer should be able to be added without issue

### Steps To Reproduce

1. Attempt to add EZTV indexer
2. Add the tag used for the FlareSolverr proxy
3. Hit `Test` or `Save`

### Environment

```markdown
- OS: Ubuntu Server 22.02.2 LTS
- Prowlarr: 1.4.1.3258
- Docker Install: Yes
- Using Reverse Proxy: No
- FlareSolverr: 3.2.1
```

### What branch are you running?

Master

### Trace Logs?

FlareSolverr Logs:
```
2023-06-15 19:45:08 INFO     Incoming request => POST /v1 body: {'maxTimeout': 120000, 'cmd': 'request.get', 'url': 'https://eztv.unblockit.mov/', 'proxy': {}}
2023-06-15 19:45:08 INFO     Challenge detected. Title found: Just a moment...
2023-06-15 19:45:12 INFO     Challenge solved!
2023-06-15 19:45:12 INFO     Response in 4.53 s
2023-06-15 19:45:12 INFO     172.18.0.1 POST http://localhost:8191/v1 200 OK
```

Prowlarr Logs (No logs between this and the previous attempt to test EZTV):
```
2023-06-15 19:45:12.6|Warn|Cardigann|HTTP Error - Res: [GET] https://eztv.unblockit.mov/: 403.Forbidden (7439 bytes)
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=7d7cf801fd18d178')"></div>
        <form id="challenge-form" action="/?__cf_chl_f_tk=W8baSv6oJyzVL3Osu.n0Zcb6e35j42PKpbEFz2d2GPY-1686854712-0-gaNycGzNCuU" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="dOVk6MwyfvmfAg1N0ssd7uXKue3WATWLFsgRd6NXmV4-1686854712-0-AcaaNciWVJ1pJ-Ff4K0gR8Xo1ZdlPWPHHO_UwEjR7rI-xtGWaH_4C6KiMY27WcBPqpIDNU3kkjsJYgfMtBMocw00EWd5n1KAuW-teYs1-wvMABl-hVjB9wNhJy1gca6ewoQA573wGd60T53qR-CMRs4q8sR5xQqGb41WkPwPnNoHJ4KUYKNdwPPUGP7HZLYBCp2vdtSN5fiiix_dKRDpeJJi2G612uZyF5c0sBrWZFQBAlzjBgZnjqTS_BttvK-Zfnft-pP04fL7fubKJeZSrCVZyIkF2qeddLKfl2bYTmBGAm68I7CvVwgS7YtfZ0M3nYR53waR2QRB4euOGbkLY_3tFrx1rkPaIfiWoJYJ06rN6MC_B-GZwa8awUt8XLC0Wm0bwFX7QP97R4BRO63vNEe40J-UP75cgNcgeH9obQ95q39u4Ws40j-YxBWDU03OBkGBpduH4EGpITwhan-Vz_M-6GzzjbLMTiPCsfBVnopxfzDBhZypjkwlACftxROWvGENB51G4ReQTVKBCvglODPQ4MTjx4NSIvmRqgxArvWcRfaf_rXleJvn3MESBSHLJolJ9SfvuInmKvBjFdJq9G-ccRIsswNKVAawWTl9LIO327mJ-rs9arD6UZYETPRh4lmp_GS0CxUdnTVCI7-Br6Y5idHcC6E4LiC9Bcr0fbGfyX6sKResQrpGwtd91xkzDCx6NQw6fkMvvaNuhSFy29EvPRQnXQiDM7l3WRj2PYM8Dnw7WjuTiFpku6C9VLW1_NCXUpKuqhfKsql32f6iG3pE6I78FT4IH90nTcAU5E2OsOXb7Eosuh5xB9fPBJShOkw0bpWav-3CD56Br0BkjHHnq036AdBzjGbWR3iCZJMYEL_X5giGT3FwCfvgLPYn8nKR40lo8IWN_7WZfUiMQmnXWIF_SVDow-mSqkW83zB-hgW3MtLjJvi74BA_Lakh2V6mFiYw9szUtNu8s7Qg-qw75PaNwLTO4EsI7PChgFML-BFUN9s5gq_kJz8Bx1xc0ejT-PZ0P5NZfTwxTry2oCj36tFlQSp8ym2Zx0MfaCjzckmYS27ZYmq9309uu4IAETSem1T12oSQedt1YzE2y-xNTTB9uRlR8CWHMUcLKIx0rkDMYyHtEQ0jtLVEiO6YEzYTIpb7Ke3NB9R78J4-CiXxFSLKHcm8S6_ZhaKB8-TVatiflOwyPc7jcVxX6cRWSMdmuri83bU3vk2Ov14Gsf3PIK9cd2m_kf1doIGCDGnyyAhM0zcRkM3YYBLIH9KKodv5nEcjJs7WY8M_-m2lpRy2ROy5sAl6R2kYgmAz-aae8sxWoqR1ET8teHFqcDjzgvpriyZ5UEb7GzK4bejbjJf7VcIVbbLaOCYPMZR8D87blJ0YhSqwKy-F5J4lEEmiwuv_QtwXjlTmeSVsp2MrxYMY6kmD2BMpDs3gC6k9OBtYKqFMavKi5kIPF8lw9_TsgP60XwPF5bWwSi6IWIC0eXVj-mceCD0Lf8EdfjhXu_tFYPA65-pnncZwhjCzeK_QUOmE1O5Nfb1N3jLtDBsfg39Gx7cjNbNcEe8inJHk1Ba9qjqx3UO1sodVFTb9tysaZP5OEZq7t4WmUtKBz9-eO7V8f44MU3OcsKAPnvu9_OPI3CfMXm-y2za3JXMmaYrF20BFqY1VCrnqVlM7yrNMkBFDNkVHDvQbiJeKHgsRDSlWG-fjRLgzsYk4SDmXw06Wew91x_mBF1iYK1zS1kP4BcpXmkwqbiv61A3tne0_5OCOz7DshjCMfhYmDnqj6oO5eftindLufcNNkyYJ7LOPKizoU056CPECBnp0XfqYPQhuARWPW5ZiXMsgM56v2zHEcfJbmZtTMmw5RRPqW-jvnW31hw7JHhgfUWRLHyhOrRBYNGeCYN9I7lwn1HffbRWDT70y_g4vPkiIln7Y6NjLTDYoPKYydIPRtCk6EwfQ9EtB_jauCiuUVXMXbGcEtqbpUjZ3Btn3Bbrotvf5YivRq1P30HOwSg8F9VphoUX-caLZaxR8KhIyFMWgKnTNUSzczCl0Uzd3t3ggOe8tnIRCe3AXtSZFbxE05wn0YcjMw2Hu0gsRfUJkBJCAUTC9QV9HiFaUs9GwP-kCycx8A2Lya9kGNm22VYKsrmM_D8stsz_CFAUfZJCilOcoMCCeg4xHXyDPwjDJRsjvS6L8V1CrMDANdLO_jk7OfkA2wd3-R_EW0VuOWDlKKy1DZkgXMcSPSBGL6vjtmlhpAJbNz1wXa6IlYzybElAEEYRASRMQC9X-4q9WqYkBItNGk0nSKuCHrYz0YpK40CUlqw2q3cvWYQIB_z_uUjYBUbwfEZm1LPWnPOWrSM3xsJ3LIJ9l_9tEfus9VNjBAMv75Of654NwYYtfLZ_bukkhattk0B4MdR__1rmAwOGVsINznFdFqy8P2OOD7rx3fQcbxFeaD6lHx3Fc_ZSTTK8sKlImSy-1bQrl2HOCQdtXVRspzM4K3IpnQzP9z3rmk360BUmQhxRikvLTPeu12_X7fYONCvI4OF2ZmtXp0yBLoFOURSsSPgN8CT5tiVkGH7qF6x5hLSEa7bZ8ECN-QPReKMtwsGKlthxir5FlmGJyVnizhc3xx_97H_EICHDHdzmeuRDMeQpaAY-Bzye5jhI0QtOol7ml-vea5glB5VGXTslzDfUaldhG-TGuOvNA7YIehbZmwlDio78w6GkzZtIG3LZd7xhxLe7O">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'eztv.unblockit.mov',
            cType: 'non-interactive',
            cNounce: '93335',
            cRay: '7d7cf801fd18d178',
            cHash: '6487d6e06fe30d6',
            cUPMDTk: "\/?__cf_chl_tk=W8baSv6oJyzVL3Osu.n0Zcb6e35j42PKpbEFz2d2GPY-1686854712-0-gaNycGzNCuU",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cMTimeMs: '60000',
            cTplV: 5,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly9lenR2LnVuYmxvY2tpdC5tb3Yv',
                ra: 'TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTE0LjAuMC4wIFNhZmFyaS81MzcuMzY=',
                rm: 'R0VU',
                d: 'sd3mRKtf8o0OTOwfrzEMthxFmZTbOVXAcsRklWoMRIxN0I26zssVkQ4HdabsGTQpme1BGc/YySvay5hP1lfJajEJg4CMhsD1IYG1wLOutOAXaj/9vApVAxjhTq+F7yNx/JDjS1SUVh0xelMLgiwb81gi53I6rE0Nt0PEx3sEz03d9IO+gfJn+8sM4RJuCSUhZEq5XIro9yTtmff8lYgaGt+Az1yIQoFYajmCJrU0K24GjKvfPAh1f2pOmiCmHvBWZukSzOoK6Om6UQLx5CDKhBOmvYgoWWPP5m1ksNDu3rhoGzFBvj5bxeXFtonH3+z7L/y3Zvx6TpNJsGhtrPKherHLfdytm8VwQHlOwnrnBNz1XmNVs5pruBxAxLW7qKQzmOal8Nt+A4fCxDXWLVdcnFikJuYhvcK7kbhhMEbcjiInTwJUfpb2SR/EPs4c1uzyZKoN74r42zQDg/mvc8YT66bi+/QKixmoVbl5bK3Hi5EO/g8KuXTuwz/+enByMRjsxbqaVR8xHMQgv+nxLoyiuZMw9zrW52nNZMA7Li/+EVZHjuAT9/NKf2dyaX+yexJK/6e1mjSPSE9aTjH0T+PVEgUmMOCw9ZlRepy7/gsElUA=',
                t: 'MTY4Njg1NDcxMi42NTUwMDA=',
                cT: Math.floor(Date.now() / 1000),
                m: 'XkB6XKyjyVYA/BTNg3RT61ukkt28VwoLVsbdSBE7iQU=',
                i1: 'idbbaz+S2G/xA5qLaGYC/A==',
                i2: '809qao6SeIOZu5CvsGcwpA==',
                zh: 'YPSBbxnl93j02Qhk+Sbh+amenX8p0B8X03yzAm5uZXE=',
                uh: 'e7loE3vDKk6iaYD2COC8KZq7+0SgkY1qaKWhiZXS1F0=',
                hh: 'UTNOneV56aj02YK9LpH/9GlP7v9y8MqDgH5P4Iw+yEk=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=7d7cf801fd18d178');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=7d7cf801fd18d178';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/?__cf_chl_rt_tk=W8baSv6oJyzVL3Osu.n0Zcb6e35j42PKpbEFz2d2GPY-1686854712-0-gaNycGzNCuU" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>


</body>
</html>

2023-06-15 19:45:12.6|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v1.4.1.3258] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to access eztv.unblockit.mov, blocked by CloudFlare Protection.
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2023-06-15 19:45:12.7|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to access eztv.unblockit.mov, blocked by CloudFlare Protection.

[v1.4.1.3258] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to access eztv.unblockit.mov, blocked by CloudFlare Protection.
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2023-06-15 19:45:12.7|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to access eztv.unblockit.mov, blocked by CloudFlare Protection.
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by DanTm99** [comment]
Updated logs to use trace logs instead of info

**Comment by DanTm99** [comment]
@mynameisbogdan For all the other EZTV base URLs, I get a `The SSL connection could not be established` error, but I can't open them in my browser either, so I think they're just blocked for me.

The base URL I tried for this is the only one that works in my browser.
