### ISSUE TITLE
ipv6 support for downloaders

### ISSUE THREAD

**Issue by covert8** [Prowlarr/Prowlarr#1792]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Transmission: Failed to test                                                                           ││                                                                                                                ││ [v1.7.3.3747] System.Net.Http.HttpRequestException: No data available (transmission.default:9091)

### Expected Behavior

A working connection to transmission

### Steps To Reproduce

In a kubernetes (k3s) cluster with ipv6 only (yes i hate myself) when trying to connect from prowlarr to transmission there is an error.

### Environment

```markdown
- OS: nixos/k3s
- Prowlarr: nightly
- Docker Install: containerd
- Using Reverse Proxy: none
- Browser: firefox developer edition
```

### What branch are you running?

Master

### Trace Logs?

[Error] Transmission: Failed to test

[v1.7.3.3747] System.Net.Http.HttpRequestException: No data available (transmission.logic-p-podman:9091)
 ---> System.Net.Sockets.SocketException (61): No data available
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.attemptConnection(AddressFamily addressFamily, SocketsHttpConnectionContext context, CancellationToken cancellationToken) in ./Prowlarr.Common/Http/Dispatchers/ManagedHtt
pDispatcher.cs:line 331
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.onConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 307
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool
pool, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationTo
ken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 110
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, TransmissionSettings settings, Boolean reauthenticate) in ./Prowlarr.Core/Download/Clients/Transmission/Trans
missionProxy.cs:line 222
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.ProcessRequest(String action, Object arguments, TransmissionSettings settings) in ./Prowlarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 259
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetSessionVariables(TransmissionSettings settings) in ./Prowlarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 145
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetConfig(TransmissionSettings settings) in ./Prowlarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 120
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetClientVersion(TransmissionSettings settings) in ./Prowlarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 112
   at NzbDrone.Core.Download.Clients.Transmission.Transmission.ValidateVersion() in ./Prowlarr.Core/Download/Clients/Transmission/Transmission.cs:line 25
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.TestConnection() in ./Prowlarr.Core/Download/Clients/Transmission/TransmissionBase.cs:line 98

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by covert8** [comment]
Similar errors of "No data available" were solved by upgrades to c# if i read the issues of other rr's correctly. 

Im just looking for a pointer and I'll write the patch myself

**Comment by covert8** [comment]
Closing as this was an issue with DB corruption for some unexplainable reason.
