### ISSUE TITLE
Unable to connect to indexer yggtorrent.wtf

### ISSUE THREAD

**Issue by FrackerZ** [Prowlarr/Prowlarr#1804]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Unable to reach YGGTorrent.wtf with or without FlareSolverr since 2,3 days
When I visit the site, I get the impression that the confirmation challenge has changed. 

### Expected Behavior

We should be able to access the tracker, I'm having the same problem since Jackett....

### Environment

```markdown
- OS: Windows Server 2022 
- Prowlarr: 1.7.4.3769
- Using flaresolverr if necessary
```

### What branch are you running?

Master

### Trace Logs?

[v1.7.4.3769] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://www3.yggtorrent.wtf/]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.GetConfigurationForSetup(Boolean automaticLogin) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 654
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.DoLogin() in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 266
   at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.DoLogin() in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 191
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 510
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 444
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 687
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript><form id="challenge-form" action="/?__cf_chl_f_tk=YsZRCMge3Wwj0l0FwH1qAZyN3J0.UB1FZ0KPOzSbcYs-1690789082-0-gaNycGzNCVA" method="POST" enctype="application/x-www-form-urlencoded"><input type="hidden" name="md" value="pw8enGmosi1.zqyvVj9NCA1g6AqymaNBVsKT3yBuTXk-1690789082-0-Acau4Mm08o2W6LQlYH_mYTC_kxZWmaXxGP2ypGVurEsTinNXG-0ASrROgZPhxRPiTP9Dv0i5Oja4RV01Ms45_ob5O246uTeJTWWklfED8wQN_7vJO5OJb3_80nfMdUrvv6EuLfWsTCWIxTP7HPDBSBchB0ZXcobpV0w8yFUUsYY-igdQ_Bxq40_kyjvWN39Ifu4NipGBQJ34ODxUgh1vmEtLnnbS_BbdWI5qkdesgCG5QAyE9ELWDO9ntVrg9R8AmtAYO1TNeoFm4dv6jSkAhkX7CO8tYkehM9jWeho3nEtHknN6w7ZXa2wGtfc_M8Pt1JdpMyZlhHUxMdxZ0CKHazho0h1tA6i5J0oa0Qx_cgst-YOpUVvS5oROggYfB1dOX_Q0gGYb9suEv4QIeKUbFhfxFxI6CxWIlEuRKoJs_YXY33bX8ddojVLcQLfkc9v6ZSUeFbnGthHXAm3aD9M65DyB7w2OL41qoJ43qbXUIKWlSyvepaZsG4vSCXz9wD76xn2tff8mNpMWx2PXge0di8H5Ml8pwIW2W6bn8B4LrKlwMWHZP3qVgQs4rvlqYI-yT9rAI9BjQZGVGyTRpGeD7Maz85SikBRPv2PvOK33Bs15MWDOc5lJJqv4LUpLbGLiQwF8bYugrm3HM5RLhzMVYFiq3DVC1yMGqiQvFCjeFr9v00G4U1Z4EO1mjGHZ3R-zmAm_xkdSoTX5KGhfYIo2Qphn2Q_0z9Ta0JdXr-30bZ7XSIo5rgUNgXLk2b7fqLZLdEg4mMd8hwrTk9JA2lrmcy89gfmz9LDnOdurjdlDPDC5PMm8Ok5uu3F_6waqNlwNY4fcBKXHXaPhtInwl7ZjL7wsLE8zOPYRFLnrcORxcGG1KlkwpXisnntniRVB0KtWJJf7Voh716FDX5yGd6dURlaovYrHkOlBIsOm2BvgcEZD7oMk7tnZQRCt9ZfLLrLZRA93ikgsXCMhdrbYrn9caSW_dLvNq9jUdm2lZ5cZCrPPn1pzBDh0RUsjCE4LXR4VevkA8ikQsj4WjDGjmOwpVFw-Ccqz0tW_Ks8e2iSsOTdFXr__2HCX9PnsktwtYEpzPrDAy946JnBKUz1WrSsa-0k0nLj_4cw_N_v5uQuPjPXHjjsxcmvD3XNyLU9TeBDhGACZoxHUpS18bL2TPjy4BPIsYzSI2lovvCCbn06LE1bGZM3-1UCo-7uWSb18M7XqNirpEVcmWxvWUeQEuWW4ehlaRAySHEnO25NsS__mX0SR732oywG8qak4gQ6sUSu268fKUQXCGS6Kyz_BffCRdH-W2LxQdOz5GzH57VglIN9HYfQp7w1fwf_UQY9I5tmbQB7Bqqt54BEWOGKrYspG2k2nKACJsCpz4dUldHwu17G_rvwIEHFDzKRvsQhH-R7BJwWp-0Hc9BsRj_-GyaS-8GyfO6CKIpN3nDL0964wUqtNWGKTDcNrmN-R59jQwCk6cMzriL1HeOmD3bv-nuVN1cyQgNRRCu0YGNZfCX62SxmazeMojhkTcFakAlIWZsMT-0i9F74hSzOhDxyViXlETczcdfKdmpRrqgBanuHAv4JWt3UuS0fFL6olxRzxtMHOWKAfsMmjzo4EAojsxxZ21M0E1wxIFuCcZfGa_fd_ynA8YKfQCfQ9LpaSe32tHstJxtszk6mUfiAH5FuLpmG9ofPGxG25PHeIlXosHYL3aOnJ9O0BWrWgbMszPiSAR7yF4CaH2ri6Ox_sktQ4Cvkg_ks84hVLJm0lM3hXssfhDrL-LIjpRG3dM2aodbYNObHJp7vzLu-ur5X2aIFYUAm-5-uxZcAvMHrfhzkOaovEB3yHF5hdq8piAvKyDuTAL6DqBli7IGWUlbMgnOblglVdWX-KD6j-tmRXwpqmkVUlhJ3v5MXs5UgBoIRZUl6rckGHfKJz6Vb4xPrF1_DFbrh3K_1JWMLJ8N4R9kGh6wN0hgQKrBY6bTeu8YB9KPWkggnk9RohJJZI7Fpf31aSDMLeCZ3xPr5uVfF1f4jLAfmXUwmita0TAgP8jZ_yR65ltT-i7YwGIhEIzbCTi1u43hPaGcm1r3uk9SLKM3Hm149ZTbRc6q90mXeKoyZgyS1yACV_e10auWlAVdlOVeUZM9jZA3gBhAwLzyVX2TJtq9OPmCzLgsanA4VqZtrjLD7Pjufn8py8etHeqBYBRQPWX_qLUvzmPRvSj5_0m0K3cF69nI269Dislm_SzShtBcOfT_BQ9myQc9zPTSoOMLKuJaHFN0Y4ZQqpFAR0lmB3UUmlzFvY3uPag-JqpBbvx8rKsSgA7kMgOh15xgjDA5SGXlAFpGI"></form></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: 'www3.yggtorrent.wtf',cType: 'managed',cNounce: '32048',cRay: '7ef42df3be45f96d',cHash: 'fb5573ca2c9c13a',cUPMDTk: "\/?__cf_chl_tk=YsZRCMge3Wwj0l0FwH1qAZyN3J0.UB1FZ0KPOzSbcYs-1690789082-0-gaNycGzNCVA",cFPWv: 'b',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "",cRq: {ru: 'aHR0cHM6Ly93d3czLnlnZ3RvcnJlbnQud3RmLw==',ra: 'UHJvd2xhcnIvMS43LjQuMzc2OSAod2luZG93cyBzZXJ2ZXIgMTAuMC4yMDM0OC4wKQ==',rm: 'R0VU',d: 'D/ksdrav63tayUYGPMk/fO7h79xb6Zhulsv+wIlPw+grkWLGlTEpTlNDllOeQWidTyegci4jWRqNwx8jxzWOnN2keyvDt3RF1MLB0OTP30ykTySTVLOeqc1fv/zBhy/oGIIgPJfQWgMc5caFRrJP1rsdq6+GfLxtqva1blyW/GKS4GuJ72vdN95QLJeAHN1Tr3qLJlNRbzUrcS2L0iDrV/XTx2vQLPcfhqgvH+Wx4rIPQvixOruwLM8nXbOhSun4TTyDycj3V3pzpcJzHnfwVgl+j2wKlGNnITvotbqjtkczEtyOlnv3BSVaYKPOwhbdYuiGWucTicvcVKI6dBXvc9H6JnBEHc9CUHocwdIljgCoTm7mUuwcCY+latiWxBSNHAqmFIOS6rYfmpqEBPWQjGY2shzXyUjXEcumv1uTEqJeAf0xWQ4LG/h4K1fmn8YOLQba7MiyxbEINkTdC3Mgz6FleqZTZWEo8RIA/0N0SnqSrsXkLJhHg7irR5AzYKdajy9ObP3IEMMIkkYo87DnZdBM3PrWrBeqhTNdt8hB4w0=',t: 'MTY5MDc4OTA4Mi4xOTgwMDA=',cT: Math.floor(Date.now() / 1000),m: 'NPHeWGsOm22enCtzt7gzW/Lg83Eb6TPZ40At+5CjFCk=',i1: '4hiXi9MfFi+428SlSmzN0Q==',i2: 'GNJ71e6sZ9+qo7tUYVq/Ag==',zh: 'gYAnmlFOeGhiJJ8vfum0ixS0eUbFqDEoFaOwzC+fTQE=',uh: 'ZTZ5RJFlR/zkV347Y9+xoRWcLOghkqEijrK/rf7xH0c=',hh: 'bbRYPhEJvQfExDpefg3OBVEuUQ9vxoecGT6N8gTJD40=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=7ef42df3be45f96d';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/?__cf_chl_rt_tk=YsZRCMge3Wwj0l0FwH1qAZyN3J0.UB1FZ0KPOzSbcYs-1690789082-0-gaNycGzNCVA" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);};}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>

2023-07-31 09:38:02.2|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. HTTP request failed: [403:Forbidden] [GET] at [https://www3.yggtorrent.wtf/]

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by FrackerZ** [comment]
actually I just looked on their forum and it comes from their under attack mode, sorry I didn't know this kind of inconvenience when this mode was activated... Sorry for the inconvenience here.
