### ISSUE TITLE
Manually adding file to download client fails if the file already exists

### ISSUE THREAD

**Issue by seth100** [Prowlarr/Prowlarr#1805]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After making a manual search in Prowlarr I get:

```sh
[Fatal] ProwlarrErrorPipeline: Request Failed. POST /api/v1/search 
 
[v1.7.4.3769] NzbDrone.Core.Download.Clients.DownloadClientException: Download client failed to add torrent by url
    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AddTorrentFromUrl(String torrentUrl, TorrentSeedConfiguration seedConfiguration, QBittorrentSettings settings, String category) in ./Prowlarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 163
    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromMagnetLink(TorrentInfo release, String hash, String magnetLink) in ./Prowlarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 57
    at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(TorrentInfo release, String magnetUrl) in ./Prowlarr.Core/Download/TorrentClientBase.cs:line 181
    at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(TorrentInfo release, IIndexer indexer, String torrentUrl) in ./Prowlarr.Core/Download/TorrentClientBase.cs:line 145
    at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in ./Prowlarr.Core/Download/TorrentClientBase.cs:line 121
    at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect, IDownloadClient downloadClient) in ./Prowlarr.Core/Download/DownloadService.cs:line 83
    at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect, Nullable`1 downloadClientId) in ./Prowlarr.Core/Download/DownloadService.cs:line 57
    at Prowlarr.Api.V1.Search.SearchController.GrabRelease(ReleaseResource release) in ./Prowlarr.Api.V1/Search/SearchController.cs:line 76
    at lambda_method399(Closure , Object , Object[] )
    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
 --- End of stack trace from previous location ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
 --- End of stack trace from previous location ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
 --- End of stack trace from previous location ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/BufferingMiddleware.cs:line 28
    at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
    at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
    at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/StartingUpMiddleware.cs:line 38
    at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
    at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/VersionMiddleware.cs:line 29
    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Expected Behavior

Some days ago (probably before a Docker image upgrade of Prowlarr or qBittorrent) the torrents / magnet links I was used to click in Prowlarr were correctly added to the download client (qBittorrent) and, if existing, the trackers were merged!
That's the behavior I expect and would like!

### Steps To Reproduce

1. Manual search something in Prowlarr
2. Choose a file and click the "Add release to download client" button 
3. The icon gets red and the error is thrown in logs

### Environment

```markdown
- OS: Ubuntu 22.04
- Prowlarr: 1.7.4.3769 - 25 Jul 2023
- Docker Install: Yes (lscr.io/linuxserver/prowlarr:latest)
- Using Reverse Proxy: no
- Browser: Firefox v115
```

### What branch are you running?

Master

### Trace Logs?

```sh
2023-07-31 18:05:30.0|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] ....: 200.OK (28499 bytes) (271 ms)
2023-07-31 18:05:30.0|Debug|Cardigann|CardigannIndexer (...): Download selector NzbDrone.Core.Indexers.Definitions.Cardigann.SelectorField matched:
<a class="kaGiantButton " data-nop="" title="Magnet link" href="magnet:...">
	<i class="ka ka-magnet"></i>
</a>
2023-07-31 18:05:30.0|Trace|HttpClient|Req: [GET] http://localhost:8223/api/v2/app/preferences
2023-07-31 18:05:30.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-07-31 18:05:30.0|Trace|HttpClient|Res: HTTP/1.1 [GET] http://localhost:8223/api/v2/app/preferences: 200.OK (11014 bytes) (1 ms)
2023-07-31 18:05:30.0|Trace|HttpClient|Response content (11014 bytes): {"add_trackers":"udp://tracker.opentrackr.org:1337/announce\n\n..."}
2023-07-31 18:05:30.0|Trace|HttpClient|Req: [POST] http://localhost:8223/api/v2/torrents/add: urls=magnet...
2023-07-31 18:05:30.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-07-31 18:05:30.0|Trace|HttpClient|Res: HTTP/1.1 [POST] http://localhost:8223/api/v2/torrents/add: 200.OK (6 bytes) (0 ms)
2023-07-31 18:05:30.0|Trace|HttpClient|Response content (6 bytes): Fails.
2023-07-31 18:05:30.0|Trace|ProwlarrErrorPipeline|Handling Exception
2023-07-31 18:05:30.0|Fatal|ProwlarrErrorPipeline|Request Failed. POST /api/v1/search

[v1.7.4.3769] NzbDrone.Core.Download.Clients.DownloadClientException: Download client failed to add torrent by url
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AddTorrentFromUrl(String torrentUrl, TorrentSeedConfiguration seedConfiguration, QBittorrentSettings settings, String category) in ./Prowlarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 163
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromMagnetLink(TorrentInfo release, String hash, String magnetLink) in ./Prowlarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 57
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(TorrentInfo release, String magnetUrl) in ./Prowlarr.Core/Download/TorrentClientBase.cs:line 181
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(TorrentInfo release, IIndexer indexer, String torrentUrl) in ./Prowlarr.Core/Download/TorrentClientBase.cs:line 145
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in ./Prowlarr.Core/Download/TorrentClientBase.cs:line 121
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect, IDownloadClient downloadClient) in ./Prowlarr.Core/Download/DownloadService.cs:line 83
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect, Nullable`1 downloadClientId) in ./Prowlarr.Core/Download/DownloadService.cs:line 57
   at Prowlarr.Api.V1.Search.SearchController.GrabRelease(ReleaseResource release) in ./Prowlarr.Api.V1/Search/SearchController.cs:line 76
   at lambda_method399(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2023-07-31 18:05:30.1|Trace|Http|Res: 991 [POST] /api/v1/search: 500.InternalServerError (430 ms)
2023-07-31 18:05:30.1|Debug|Api|[POST] /api/v1/search: 500.InternalServerError (430 ms)
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Can't do anything until qbit returns a valid response for dupes https://github.com/qbittorrent/qBittorrent/issues/18361

**Comment by seth100** [comment]
> Also [qbittorrent/qBittorrent@4ef9a64](https://github.com/qbittorrent/qBittorrent/commit/4ef9a6444ae9067bb40fd2f5442564416e047689)

so there is a commit about that! Do you know when is it going to be added to the latest docker image?
