### ISSUE TITLE
AlphaRatio - MonoTorrent.TorrentException: Invalid torrent file specified - FL Token Issue?

### ISSUE THREAD

**Issue by dylancmds** [Prowlarr/Prowlarr#1811]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Searches are working as expected. Grabs are failing directly in Prowlarr, as well as Sonarr and Radarr for any AlphaRatio torrents.  From the trace log, it looks like its attempting to use a FL token on a torrent that is not FL token eligible? 

```
2023-08-04 09:39:39.4|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://alpharatio.cc/torrents.php?action=download&id=(removed)&usetoken=1: 200.OK (21630 bytes) (494 ms)
2023-08-04 09:39:39.4|Debug|AlphaRatio|Downloaded for release finished (21630 bytes from https://alpharatio.cc/torrents.php?action=download&id=(removed)&usetoken=1)
2023-08-04 09:39:39.4|Trace|AlphaRatio|Invalid torrent file contents: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Error :: AlphaRatio</title>
<meta http-equiv="X-UA-Compatible" content="chrome=1;IE=edge" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />


<TRUNCATED>



		<div class="box pad">
			<p>This torrent is too large. Please use the regular DL link.</p>
		</div>
	</div>
</div>
<div id="footer">


<TRUNCATED>

</body>
</html>

2023-08-04 09:39:39.5|Trace|ProwlarrErrorPipeline|Handling Exception
2023-08-04 09:39:39.5|Fatal|ProwlarrErrorPipeline|Request Failed. POST /api/v1/search

[v1.8.0.3805] MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
```
  
Prowlarr Event:  
```
Details
Message
MonoTorrent.TorrentException: Invalid torrent file specified: Invalid torrent file specified
Exception
MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Indexers.TorrentIndexerBase`1.ValidateDownloadData(Byte[] fileData) in ./Prowlarr.Core/Indexers/TorrentIndexerBase.cs:line 23
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 190
   at NzbDrone.Core.Indexers.Definitions.Gazelle.GazelleBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/Definitions/Gazelle/GazelleBase.cs:line 87
   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in ./Prowlarr.Core/Download/DownloadService.cs:line 160
   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in ./Prowlarr.Api.V1/Indexers/NewznabController.cs:line 255
Close
```  
  
Sonarr Events:  
```
Details
Message
Downloading torrent failed: Downloading torrent failed
Exception
NzbDrone.Core.Exceptions.ReleaseDownloadException: Downloading torrent failed ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [http://10.0.0.10:9696/58/download?apikey=APIKEYREPLACED&link=LINKREPLACED&file=The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00154] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:105 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:281 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x0004c] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:135 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x001b5] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:179 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00148] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:117 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00271] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\DownloadService.cs:99 
  at Sonarr.Api.V3.Indexers.ReleaseModule.DownloadRelease (Sonarr.Api.V3.Indexers.ReleaseResource release) [0x001a7] in C:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:129 


Details
Message
Downloading torrent file for episode 'The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC' failed (http://10.0.0.10:9696/58/download?apikey=(removed)&link=LINKREPLACED&file=The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC): HTTP request failed: [500:InternalServerError] [GET] at [http://10.0.0.10:9696/58/download?apikey=APIKEYREPLACED&link=LINKREPLACED&file=The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC]
Exception
NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [http://10.0.0.10:9696/58/download?apikey=APIKEYREPLACED&link=LINKREPLACED&file=The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00154] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:105 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:281 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x0004c] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:135 
<?xml version="1.0" encoding="UTF-8"?>
<error code="500" description="Invalid torrent file specified" />


Details
Message
Downloading torrent file for episode 'The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC' failed (http://10.0.0.10:9696/58/download?apikey=(removed)&link=LINKREPLACED&file=The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC): HTTP request failed: [500:InternalServerError] [GET] at [http://10.0.0.10:9696/58/download?apikey=APIKEYREPLACED&link=LINKREPLACED&file=The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC]
Exception
NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [http://10.0.0.10:9696/58/download?apikey=APIKEYREPLACED&link=LINKREPLACED&file=The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00154] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:105 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:281 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x0004c] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:135 
<?xml version="1.0" encoding="UTF-8"?>
<error code="500" description="Invalid torrent file specified" />


Details
Message
HTTP Error - Res: [GET] http://10.0.0.10:9696/58/download?apikey=(removed)&link=LINKREPLACED&file=The.Witcher.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DoVi.HDR.HEVC-SiC: 500.InternalServerError (104 bytes)
<?xml version="1.0" encoding="UTF-8"?>
<error code="500" description="Invalid torrent file specified" />
```

### Expected Behavior

The torrent is successfully grabbed without error and added to the download client. Manually browsing to the tracker and downloading the .torrent file presents no issue. No other tracker presents this issue. 

### Steps To Reproduce

1. Execute a search with the AlphaRatio indexer  
2. Click 'Add release to download client' for any result
3. Red Cloud Icon in UI: Invalid torrent file specified

### Environment

```markdown
- OS: TrueNAS Scale 22.12.3.3 (Debian)
- Prowlarr: 1.8.0.3805
- Docker Install: Yes, Kubernetes Helm Chart
- Using Reverse Proxy: No
- Browser: Any
```

### What branch are you running?

Master

### Trace Logs?

2023-08-04 09:39:39.4|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://alpharatio.cc/torrents.php?action=download&id=(removed)&usetoken=1: 200.OK (21630 bytes) (494 ms)
2023-08-04 09:39:39.4|Debug|AlphaRatio|Downloaded for release finished (21630 bytes from https://alpharatio.cc/torrents.php?action=download&id=(removed)&usetoken=1)
2023-08-04 09:39:39.4|Trace|AlphaRatio|Invalid torrent file contents: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Error :: AlphaRatio</title>
<meta http-equiv="X-UA-Compatible" content="chrome=1;IE=edge" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<TRUNCATED>

		<div class="box pad">
			<p>This torrent is too large. Please use the regular DL link.</p>
		</div>
	</div>
</div>
<div id="footer">

<TRUNCATED>

</body>
</html>

2023-08-04 09:39:39.5|Trace|ProwlarrErrorPipeline|Handling Exception
2023-08-04 09:39:39.5|Fatal|ProwlarrErrorPipeline|Request Failed. POST /api/v1/search

[v1.8.0.3805] MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
looks easy enough to handle like was done for the various other trackers that need a retry if it's too large :)

**Comment by dylancmds** [comment]
No problem. Thanks for the speedy reply.

**Comment by dylancmds** [comment]
Thank you everyone! I'll test as soon as it hits the TrueCharts repo.
