### ISSUE TITLE
Indexer test failure, however works without issue in Sonarr

### ISSUE THREAD

**Issue by chrisfoster1971** [Prowlarr/Prowlarr#1826]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I noticed my configuration was a bit light on indexers and noticed that one of my all-time favourites was no longer working
I removed the indexer and attempted to re-add it using the preconfigured indexers, however, the validation test fails each time. 
UI reports
"Unable to connect to indexer, check the log above the ValidationFailure for more details. Root element is missing."
As mentioned earlier the manually configured settings work within Sonarr etc without issue, so assuming its a bug within the otherwise excellent Prowlarr?

### Expected Behavior

Validation test to succeed and save indexer

### Steps To Reproduce

1. UNRAID  6.12.3 2023-07-14
2. Version 1.8.1.3837 / Package Version testing-780e5d3 by [hotio](https://github.com/hotio)
3. Select "Indexers" left pane menu
4. [click] add indexer
5. In search indexers text field type gingadaddy
6. Once indexer is listed below, select and proceed to enter API copied from Gingadaddy profile, including VIP expiration
7. [click] save
8. Noticed Red ! mark over "Save" button and red text box appears the top of the indexer configuration page. Reading. 
"Unable to connect to indexer, check the log above the ValidationFailure for more details. Root element is missing."

### Environment

```markdown
- OS: UNRAID  6.12.3 2023-07-14
- Prowlarr: 1.8.1.3837 / Package Version testing-780e5d3
- Docker Install: https://github.com/hotio
- Using Reverse Proxy: No
- Browser: Edge(Windows11)/Brave(Android 14.B5)Chrome
```

### What branch are you running?

Develop

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/12325604/prowlarr.trace.txt)
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/12325607/prowlarr.debug.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by chrisfoster1971** [comment]
Thanks for your response. Below is text scrape and screenshot for reference.

This page contains the following errors:
error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.
![Screenshot 2023-08-12 001653](https://github.com/Prowlarr/Prowlarr/assets/26031582/0c8c5d0f-84ae-4e8e-80a8-acff93e8e069)

**Comment by chrisfoster1971** [comment]
View Source within "MS Edge" outputs <?xml version="1.0" encoding="UTF-8"?>
which I guess isn;t what you're after.
Ill take another look tomorrow. T

**Comment by chrisfoster1971** [comment]
See return on curl.

curl `https://www.gingadaddy.com/api?t=search&extended=1&apikey=myapikey`
[1] 435
[2] 436
-bash: https://www.gingadaddy.com/api?t=search: No such file or directory
curl: try 'curl --help' or 'curl --manual' for more information
curl: (3) URL using bad/illegal format or missing URL
[1]-  Exit 3                  curl 'https://www.gingadaddy.com/api?t=search&extended=1&apikey=myapikey
curl https://www.gingadaddy.com/api?t=search&extended=1&apikey=myapikey
curl 'https://www.gingadaddy.com/api?t=search
[2]+  Done                    extended=1

Oddly Sonarr is working without issue, only Prowlarr appears to be having this issue. So I'm not convinced it an indexer issue

**Comment by stu1811** [comment]
I'm having the same issue where prowlarr's test fails. The curl succeeds.
Ubuntu 22.04.3 LTS
Firefox 116.0.3 (64-bit)

![image](https://github.com/Prowlarr/Prowlarr/assets/12236842/dea3abb6-ed2f-4562-b68a-b2f13dae7568)


```
curl -v 'https://www.gingadaddy.com/api?t=search&extended=1&apikey=XXXXXXXXXXXXXXXX'
*   Trying 198.101.15.234:443...
* Connected to www.gingadaddy.com (198.101.15.234) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=www.gingadaddy.com
*  start date: Jun 14 11:47:06 2023 GMT
*  expire date: Sep 12 11:47:05 2023 GMT
*  subjectAltName: host "www.gingadaddy.com" matched cert's "www.gingadaddy.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /api?t=search&extended=1&apikey=XXXXXXXXX HTTP/1.1
> Host: www.gingadaddy.com
> User-Agent: curl/7.81.0
> Accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.13.8
< Date: Thu, 17 Aug 2023 01:36:36 GMT
< Content-Type: text/xml;charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/5.6.33
< Accept: *
< Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host www.gingadaddy.com left intact

```

Logs 
```
[Warn] Newznab: Unable to connect to indexer 

[v1.8.2.3856] System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(XmlReader reader)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/RssParser.cs:line 104
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Newznab/NewznabRssParser.cs:line 67
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 483
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 659
RequestUri: https://www.gingadaddy.com/api?t=search&extended=1&apikey=XXXXXXXXXX;StatusCode: OK;ContentType: text/xml; charset=UTF-8;ContentLength: 39;ContentSample: <?xml version="1.0" encoding="UTF-8"?>


[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. Root element is missing. 
```

**Comment by chrisfoster1971** [comment]
Could you please explain that rationale, especially given that sonarr for example interacts with GD without issue, so it's not unsurmountable and would appear to be a programatic issue. I'm no developer but logically this appears to be isolated to prowlarr
