### ISSUE TITLE
System.NotSupportedException: Memory stream is not expandable

### ISSUE THREAD

**Issue by lutzky** [Prowlarr/Prowlarr#1836]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

See stack trace:

```
System.NotSupportedException: Memory stream is not expandable.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MonoTorrent.BEncoding.RawReader.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeString(RawReader reader, Int32 length)
   at MonoTorrent.BEncoding.BEncodeDecoder.Decode(RawReader reader, Int32 read)
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeDictionary(RawReader reader, Boolean strictDecoding)
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Indexers.TorrentIndexerBase`1.ValidateDownloadData(Byte[] fileData) in ./Prowlarr.Core/Indexers/TorrentIndexerBase.cs:line 23
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 248
   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in ./Prowlarr.Core/Download/DownloadService.cs:line 162
   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in ./Prowlarr.Api.V1/Indexers/NewznabController.cs:line 255
```

### Expected Behavior

At the very least, a clearer error message. Not sure what's actually causing the error though.

### Steps To Reproduce

Attempt to add, via Radarr, [this particular file](https://1337x.to/torrent/5768359/Elemental-2023-1080p-WEB-DL-DDP5-1-Atmos-H-264-XEBEC-TGx/). Other files (with the same provider) seem to work fine.

### Environment

```markdown
- OS: Ubuntu 22.04
- Prowlarr: 1.8.2.3860-ls118 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/12380032/prowlarr.trace.txt)

Error as seen in Radarr:

```
HTTP Error - Res: HTTP/1.1 [GET] http://prowlarr:9696/6/download?apikey=(removed)&link=a2dzdXNaSWhvOVJHejJtTjdsTVUyMUh2Mmd4WXhkS0hpM0pIMkhRVndVNzNaYmJqenRzRWdTUVYyNTVQaDc1TWI4ajladXdkOWZTMlFiWUthb1dJRzNtQmlGbStTblR2K2N4ZUNacWJzVVJQTDFxaTQyNjFCSHJVMUozVXhiazFIU0dDaE40RzV4VDdPUHAzSjhpY2JnPT0&file=Elemental.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-XEBEC%5BTGx%5D: 500.InternalServerError (106 bytes)
<?xml version="1.0" encoding="UTF-8"?>
<error code="500" description="Memory stream is not expandable." />
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by lutzky** [comment]
Downloading the torrent directly works fine (e.g. via magnet link), and I indeed managed to get the file I needed. I'm not sure why Prowlarr is having trouble with it though, and it took a bit of debugging to realize what the issue was to begin with (radarr just decided that prowlarr "has errors", and it was only clear after looking at both event logs) - so I think it may be worth improving the error messaging here, or avoiding the issue altogether.
