### ISSUE TITLE
Prowlarr is not connecting to flaresolverr even though the flaresolverr test is completing normally.

### ISSUE THREAD

**Issue by Sectimus** [Prowlarr/Prowlarr#1848]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Using docker and I can connect to the flaresolverr instance via the flaresolverr domain, the test completes (this is also the same setup I have for sonarr and radarr that work just fine).

Though I have nothing in my flaresolverr logs outside of the test done on flaresolverr itself, indicating that the request from prowlarr is probably malformed.

```
2023-09-01 20:34:05 INFO     Challenge not detected!
2023-09-01 20:34:06 INFO     Response in 1.079 s
2023-09-01 20:34:06 INFO     172.30.0.8 POST http://flaresolverr:8191/v1 200 OK
2023-09-01 20:37:38 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
```

Any ideas appreciated!

### Expected Behavior

Prowlarr can comunicate with Flaresolverr correctly.

### Steps To Reproduce

1. Prowlarr>Settings>Indexers>+>FlareSolverr
2. Name: "flaresolverr - container", Tags: "cloudflare", Host: "http://flaresolverr:8191"
3. Click "Test" - observe ✅ success.
![5](https://github.com/Prowlarr/Prowlarr/assets/33827951/05ca31db-d87f-405b-970d-ce5a56b20049)
4. Prowlarr>Indexers>Add Indexer
5. Search for "ExtraTorrent.st" and click
6. Click "Test"
7. Observe cloudflare error
![7](https://github.com/Prowlarr/Prowlarr/assets/33827951/19b07164-d231-4644-a202-19812281ce53)
8. Add the tag "cloudflare"
9. Click "Test"
10. Observe the new error and error in logs
![3](https://github.com/Prowlarr/Prowlarr/assets/33827951/601c85e4-e22a-4b37-9cdb-af1f8e62e4aa)

### Environment

```markdown
- OS: Ubuntu 20.04 LTS
- Prowlarr: latest docker image
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
```

### What branch are you running?

Master

### Trace Logs?

```
[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- : Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. The SSL connection could not be established, see inner exception. 
[Warn] Cardigann: Unable to connect to indexer 

[v1.7.4.3769] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 110
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 503
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 444
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 687
   ```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/prowlarr/faq#can-i-use-flaresolverr-indexers

**Comment by Sectimus** [comment]
@bakerboy448, yes I have followed that guide. As you can see in my replication steps the tags are matching and the test completes, but not when it is tested against a tracker. Afaics everything is setup correctly, but prowlarr is not formatting the request correctly to flaresolverr. Is there anywhere I can view the proxy request in a prowlarr logfile to verify this?

**Comment by bakerboy448** [comment]
Based on your screenshots you did not follow the guide and you have not told prowlarr to use Flaresolverr for that indexer

**Comment by bakerboy448** [comment]
SSL issues are not a bug and are a support issue

Most likely your ISP or DNS provider causing issues

**Comment by Sectimus** [comment]
There is no log entry for these requests in the log for flaresolverr. Though there is a log entry for the test that successfully completed. This is not going over the network at all as this is just two docker containers communicating with one another on a shared virtual network so no ISP or DNS is involved at this point.

**Comment by Sectimus** [comment]
Is it possible that prowlarr requires an SSL connection to flaresolverr?

**Comment by bakerboy448** [comment]
GitHub is not for support. Please use discord for support.
