### ISSUE TITLE
The "YGGtorrent" indexer has not been working for 24 hours

### ISSUE THREAD

**Issue by Love-Ukraine** [Prowlarr/Prowlarr#1902]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I use the YGGtorrent indexer which is the largest French tracker, but it no longer works on Prowlarr after website maintenance!

 How to resolve the problem?

### Expected Behavior

The indexer should work

### Steps To Reproduce

1. Add the YGGtorrent indexer from the Prowlarr indexers list
 2. Try to make it work

### Environment

```markdown
- OS: Debian 11
- Prowlarr: 1.9.1.3981
- Docker Install:
- Using Reverse Proxy: 
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

[trace.txt](https://github.com/Prowlarr/Prowlarr/files/13060367/trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Love-Ukraine** [comment]
How could I solve this problem then?
 Because it’s the only indexer I use!

**Comment by grimlokason** [comment]
Hello,

It seems to be ok on Flaresolverr : 
When i run a test from prowlarr with flaresolverr on debug level, i'm able to get the content of the homepage of yggtorrent.
but the result showed on prowlarr is "Unable to connect to indexer, check the log above the ValidationFailure for more details. Login failed: No form found on https://www3.yggtorrent.wtf/ using form selector #user-login"

Complete logs from prowlarr after a test : 
```[v1.9.4.4039] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannConfigException: Login failed: No form found on https://www3.yggtorrent.wtf/ using form selector #user-login
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.DoLogin() in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 277
   at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.DoLogin() in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 192
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 580
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 514
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 757


2023-10-21 22:41:47.4|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. Login failed: No form found on https://www3.yggtorrent.wtf/ using form selector #user-login
```

Best regards.

**Comment by Love-Ukraine** [comment]
@mynameisbogdan As @grimlokason explained, the problem comes from prowlarr, please reopen this issue
