### ISSUE TITLE
Indexers added using Terraform failed to sync App Indexers to other *arr: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by tinhtruong** [Prowlarr/Prowlarr#1903]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The indexers are not synced to other *arr applications (Sonarr, Lidarr, Readarr) after being added using Terraform with https://registry.terraform.io/providers/devopsarr/prowlarr/latest/docs/resources/indexer.
When I manually added the same indexer using Prowlarr web UI, everything works as expected

### Expected Behavior

Indexers should be copied/synced to there *arr applications when added using Terraform

### Steps To Reproduce

1. Create a Terraform configuration wit the following files:
  * main.tf
  ```
  resource "prowlarr_indexer" "usenet_indexers" {
  for_each = {
    for indexer in var.usenet_indexers:
      indexer.name => indexer
  }
  enable          = each.value.enable
  name            = "${each.value.name}"
  implementation  = "Newznab"
  config_contract = "NewznabSettings"
  protocol        = "usenet"

  fields = [
    {
      name       = "baseUrl"
      text_value = "${each.value.baseUrl}"
    },
    {
      name       = "apiPath"
      text_value = "${each.value.apiPath}"
    },
    {
      name       = "apiKey"
      text_value = "${each.value.apiKey}"
    },
    {
      name       = "vipExpiration"
      text_value = ""
    },
    {
      name       = "baseSettings.limitsUnit"
      number_value = "0"
    }
  ]
}
```
* versions.tf
```
terraform {
  required_version = ">= 1.5.0"

  required_providers {
    prowlarr = {
      source  = "devopsarr/prowlarr"
      version = ">=2.0.0"
    }
  }
}

```
* variables.tf  
```
variable "prowlarr_url" {
  type = string
}

variable "prowlarr_api_key" {
  type      = string
  sensitive = true
}

variable "usenet_indexers" {
  type = list(object({
    name    = string
    baseUrl = string
    apiPath = string
    apiKey  = string
    enable  = bool
  }))
}
```

### Environment

```markdown
- OS: ArchLinux
- Prowlarr: 1.9.4.4039
- Docker Install: N/A
- Using Reverse Proxy: Caddy
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

2023-10-21 23:14:10.2|Info|HousekeepingService|Running housecleaning tasks
2023-10-21 23:14:10.3|Info|Database|Vacuuming Log database
2023-10-21 23:14:10.3|Info|Database|Log database compressed
2023-10-21 23:14:10.3|Info|Database|Vacuuming Main database
2023-10-21 23:14:10.3|Info|Database|Main database compressed
2023-10-21 23:14:10.4|Info|HistoryService|Removing items older than 30 days from history
2023-10-22 04:39:41.2|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Sonarr.Sonarr.BuildSonarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Sonarr/Sonarr.cs:line 240
   at NzbDrone.Core.Applications.Sonarr.Sonarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Sonarr/Sonarr.cs:line 135
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 04:39:41.2|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Sonarr.Sonarr.BuildSonarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Sonarr/Sonarr.cs:line 240
   at NzbDrone.Core.Applications.Sonarr.Sonarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Sonarr/Sonarr.cs:line 135
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 04:39:41.2|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Lidarr.Lidarr.BuildLidarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Lidarr/Lidarr.cs:line 234
   at NzbDrone.Core.Applications.Lidarr.Lidarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Lidarr/Lidarr.cs:line 130
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 04:39:41.2|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Lidarr.Lidarr.BuildLidarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Lidarr/Lidarr.cs:line 234
   at NzbDrone.Core.Applications.Lidarr.Lidarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Lidarr/Lidarr.cs:line 130
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 04:39:41.2|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Readarr.Readarr.BuildReadarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 228
   at NzbDrone.Core.Applications.Readarr.Readarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 130
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 04:39:41.2|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Readarr.Readarr.BuildReadarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 228
   at NzbDrone.Core.Applications.Readarr.Readarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 130
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 10:39:42.5|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Sonarr.Sonarr.BuildSonarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Sonarr/Sonarr.cs:line 240
   at NzbDrone.Core.Applications.Sonarr.Sonarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Sonarr/Sonarr.cs:line 135
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 10:39:42.5|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Sonarr.Sonarr.BuildSonarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Sonarr/Sonarr.cs:line 240
   at NzbDrone.Core.Applications.Sonarr.Sonarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Sonarr/Sonarr.cs:line 135
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 10:39:42.5|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Lidarr.Lidarr.BuildLidarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Lidarr/Lidarr.cs:line 234
   at NzbDrone.Core.Applications.Lidarr.Lidarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Lidarr/Lidarr.cs:line 130
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 10:39:42.5|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Lidarr.Lidarr.BuildLidarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Lidarr/Lidarr.cs:line 234
   at NzbDrone.Core.Applications.Lidarr.Lidarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Lidarr/Lidarr.cs:line 130
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 10:39:42.6|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Readarr.Readarr.BuildReadarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 228
   at NzbDrone.Core.Applications.Readarr.Readarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 130
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

2023-10-22 10:39:42.6|Error|ApplicationService|An error occurred while talking to remote application.

[v1.9.4.4039] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.Readarr.Readarr.BuildReadarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 228
   at NzbDrone.Core.Applications.Readarr.Readarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 130
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Roxedus** [comment]
This sounds like a problem with the provider, not the application.

**Comment by tinhtruong** [comment]
@mynameisbogdan missing field(s) in the problem. By adding the `app_profile_id` field, things started working properly.
Here is my final Terraform code:
```terraform
resource "prowlarr_indexer" "usenet_indexers" {
  for_each = {
    for indexer in var.usenet_indexers :
    indexer.name => indexer
  }
  enable          = each.value.enable
  name            = each.value.name
  implementation  = "Newznab"
  config_contract = "NewznabSettings"
  protocol        = "usenet"
  tags            = []
  priority        = each.value.priority
  app_profile_id  = 1

  fields = [
    {
      name       = "baseUrl"
      text_value = "${each.value.baseUrl}"
    },
    {
      name       = "apiPath"
      text_value = "${each.value.apiPath}"
    },
    {
      name       = "apiKey"
      text_value = "${each.value.apiKey}"
    },
    {
      name       = "vipExpiration"
      text_value = ""
    },
    {
      name         = "baseSettings.limitsUnit"
      number_value = "0"
    }
  ]
}
```
>NOTE: The `priority` and `tags` don't make any differences

**Comment by tinhtruong** [comment]
@mynameisbogdan My updated code includes the `app_profile_id`, `priority` and the `tags` fields/properties.
After adding the `app_profile_id`, my code work. I just want to leave a note for others having the same problem.
