### ISSUE TITLE
YGGTORRENT don't find the login form

### ISSUE THREAD

**Issue by imranedrissi** [Prowlarr/Prowlarr#1919]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Unable to connect to indexer, check the log above the ValidationFailure for more details. Login failed: No form found on https://www3.yggtorrent.wtf/ using form selector #user-login

### Expected Behavior

login on YGGTORRENT

### Environment

```markdown
- OS: Windows 11
- Prowlarr:1.10.2.4064
- Docker Install:
- Using Reverse Proxy: 
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

don't find it

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by TheEcho** [comment]
I think this is a real bug, I have the same issue on my prowlarr hosted in docker
Here is the log from Prowlarr :  

2023-11-20 18:52:33.5|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. Login failed: No form found on https://www3.yggtorrent.wtf/ using form selector #user-login
2023-11-20 22:59:29.4|Warn|Cardigann|Unable to connect to indexer

[v1.9.4.4039] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannConfigException: Login failed: No form found on https://www3.yggtorrent.wtf/ using form selector #user-login
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.DoLogin() in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 277
   at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.DoLogin() in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 191
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 580
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 491
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 671

**Comment by imranedrissi** [comment]
YGGCOOKIE is working, not YGGTORRENT. Of course I’m using Flaresolverr !
