### ISSUE TITLE
scenetime.com issues with cookie/login

### ISSUE THREAD

**Issue by goffy59** [Prowlarr/Prowlarr#1959]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

500 error when trying to attach cookie to the scenetime tracker

### Expected Behavior

used to work fine

### Steps To Reproduce

add a cookie

"PHPSESSID=rqv7ftblablablablabla8o2u; acopendivids=login,donateok; acgroupswithpersist=nada; uid=46666666684; pass=c588a169fblablablablablab90c2a"

### Environment

```markdown
- OS: docker on dietpios (armbian)
- Prowlarr: 1.11.1.4146
- Docker Install: yes
- Using Reverse Proxy: yes (flaresolvarr)
- Browser: firefox
```

### What branch are you running?

Master

### Trace Logs?

2023-12-15 11:54:24.6|Debug|FlareSolverr|CF Protection not detected, returning original response
2023-12-15 11:54:24.7|Debug|ReleaseSearchService|Total of 100 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [3000] from 1 indexer(s)
2023-12-15 11:54:24.7|Debug|ReleaseSearchService|Total of 100 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [3000] from 1 indexer(s)
2023-12-15 11:54:24.8|Debug|ReleaseSearchService|Total of 35 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [3000] from 1 indexer(s)
2023-12-15 11:54:24.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-12-15 11:54:24.9|Info|ReleaseSearchService|Searching indexer(s): [TorrentSeeds (API)] for Term: [], Offset: 100, Limit: 100, Categories: [3000]
2023-12-15 11:54:24.9|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [], Offset: 100, Limit: 100, Categories: [3000] from 1 indexer(s)
2023-12-15 11:54:32.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-12-15 11:54:32.1|Debug|SceneTime|Downloading Feed https://www.scenetime.com/browse.php?cata=yes
2023-12-15 11:54:32.3|Debug|FlareSolverr|Cloudflare Detected, Applying FlareSolverr Proxy FlareSolverr to request https://www.scenetime.com/browse.php?cata=yes
2023-12-15 11:54:44.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-12-15 11:54:44.4|Debug|SceneTime|Downloading Feed https://www.scenetime.com/browse.php?cata=yes
2023-12-15 11:54:44.4|Debug|FlareSolverr|Cloudflare Detected, Applying FlareSolverr Proxy FlareSolverr to request https://www.scenetime.com/browse.php?cata=yes
2023-12-15 11:54:48.4|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-12-15 11:54:48.4|Debug|Api|[GET] /api/v1/health: 200.OK (12 ms)
2023-12-15 11:54:48.4|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-12-15 11:54:48.4|Debug|Api|[GET] /api/v1/system/status: 200.OK (46 ms)
2023-12-15 11:54:51.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-12-15 11:54:51.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-12-15 11:54:51.9|Debug|Api|[GET] /api/v1/config/host: 200.OK (22 ms)
2023-12-15 11:54:52.4|Debug|Api|[GET] /api/v1/update: 200.OK (594 ms)
2023-12-15 11:55:27.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-12-15 11:55:27.9|Debug|Api|[GET] /api/v1/command: 200.OK (22 ms)
2023-12-15 11:55:34.6|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [POST] http://torpi:8191/v1: 500.InternalServerError (182 bytes)
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 60.0 seconds.", "startTimestamp": 1702666472365, "endTimestamp": 1702666534619, "version": "3.3.11"}
2023-12-15 11:55:34.6|Warn|SceneTime|Unable to connect to indexer

[v1.11.1.4146] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://torpi:8191/v1]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 51
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 573
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 514
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 671
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 60.0 seconds.", "startTimestamp": 1702666472365, "endTimestamp": 1702666534619, "version": "3.3.11"}

2023-12-15 11:55:34.7|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, indexer's server is unavailable. Try again later. HTTP request failed: [500:InternalServerError] [POST] at [http://torpi:8191/v1]
2023-12-15 11:55:34.7|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (62719 ms)
2023-12-15 11:55:34.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-12-15 11:55:35.0|Debug|Api|[GET] /api/v1/log/file: 200.OK (35 ms)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Flaresolverr failed to solve the challenge as the warning indicates. Not a Prowlarr issue.

**Comment by goffy59** [comment]
they were limiting scraping due to bandwidth limitations.... better to use RSS feed on this tracker, but if not, just be sure to limit your scrapes.
