### ISSUE TITLE
Rate Limit for several Indexers

### ISSUE THREAD

**Issue by CaveMedia** [Prowlarr/Prowlarr#1972]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Searching for content causes indexer issues (multiple indexers). While searching for new content, prowlarr causes some kind wrong requests that causes error 401, 500 & 502 and even API bans. Even tho the indexer don't have any ratelimits nor see any issue on their side, I see several rate limit delays. I don't search manually, these are all automatic searches.

### Expected Behavior

I think it could be enough to raise the rate-limit. Not only the hourly/daily, but also one for every second. 

### Steps To Reproduce

1. Let the automatic search task search for new content
2. Wait
3. ...
4. Indexer timeouts

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Prowlarr: 1.11.4.4173
- Docker Install: Yes
- Using Reverse Proxy: Yes, but not related
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

2024-01-04 21:38:16.0|Trace|RateLimitService|Rate Limit triggered, delaying 'immortuos.life' for 1.859 sec
2024-01-04 21:38:17.0|Trace|Http|Req: 2725 [GET] /api/v1/health (from 185.*.*.41 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
2024-01-04 21:38:17.0|Trace|Http|Req: 2726 [GET] /api/v1/system/status (from 185.*.*.41 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
2024-01-04 21:38:17.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-01-04 21:38:17.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-01-04 21:38:17.0|Trace|Http|Res: 2725 [GET] /api/v1/health: 200.OK (1 ms)
2024-01-04 21:38:17.0|Debug|Api|[GET] /api/v1/health: 200.OK (1 ms)
2024-01-04 21:38:17.0|Trace|Http|Res: 2726 [GET] /api/v1/system/status: 200.OK (1 ms)
2024-01-04 21:38:17.0|Debug|Api|[GET] /api/v1/system/status: 200.OK (1 ms)
2024-01-04 21:38:17.9|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-01-04 21:38:17.9|Trace|Cardigann|Populating config vars
2024-01-04 21:38:17.9|Trace|RateLimitService|Rate Limit triggered, delaying 'immortuos.life' for 1.998 sec
2024-01-04 21:38:19.9|Trace|IndexerHttpClient|Req: [GET] https://immortuos.life/download/the-winter-king-s01e07-german-dl-1080p-web-x264-wvf.169678
2024-01-04 21:38:19.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-04 21:38:20.0|Trace|Http|Req: 2727 [POST] /api/v1/indexer/testall (from 185.*.*.41 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
2024-01-04 21:38:20.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-01-04 21:38:20.0|Trace|Cardigann|Getting Basic search
2024-01-04 21:38:20.0|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-01-04 21:38:20.0|Trace|Cardigann|Populating config vars
2024-01-04 21:38:20.0|Debug|Cardigann|Adding request: https://immortuos.life/filterTorrents?sorting=created_at&direction=desc&qty=100&page=0&view=list
2024-01-04 21:38:20.0|Debug|Cardigann|Downloading Feed https://immortuos.life/filterTorrents?sorting=created_at&direction=desc&qty=100&page=0&view=list
2024-01-04 21:38:20.0|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-01-04 21:38:20.0|Trace|RateLimitService|Rate Limit triggered, delaying 'immortuos.life' for 1.913 sec
2024-01-04 21:38:20.1|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://immortuos.life/download/the-winter-king-s01e07-german-dl-1080p-web-x264-wvf.169678: 200.OK (34787 bytes) (151 ms)
2024-01-04 21:38:20.1|Debug|Cardigann|Downloaded for release finished (34787 bytes from https://immortuos.life/download/the-winter-king-s01e07-german-dl-1080p-web-x264-wvf.169678)
2024-01-04 21:38:20.1|Trace|DownloadService|Downloaded 34787 bytes from https://immortuos.life/download/the-winter-king-s01e07-german-dl-1080p-web-x264-wvf.169678
2024-01-04 21:38:20.1|Trace|EventAggregator|Publishing IndexerDownloadEvent
2024-01-04 21:38:20.1|Trace|EventAggregator|IndexerDownloadEvent -> NotificationService
2024-01-04 21:38:20.1|Trace|EventAggregator|IndexerDownloadEvent <- NotificationService
2024-01-04 21:38:20.1|Trace|EventAggregator|IndexerDownloadEvent -> HistoryService
2024-01-04 21:38:20.1|Trace|EventAggregator|IndexerDownloadEvent <- HistoryService
2024-01-04 21:38:20.1|Trace|Http|Res: 2724 [GET] /2/download?apikey=(removed)&link=RTdtb1FWNFhRV3A3MWh1TDZpSWlFcmphcG82aytVVk1JZlNudFFkUjc4bks2L2YvZWFzUkVEMTRqc3J6SjJjdmYvWGx3WUZlYTVvb0toODlQc1p2d2x6MzgxblFSbW5YTkt6UDhOck1uZW02ZVBUMG9sWjFMSFJHaEwyMTlCOXdyM1NnYXpBZEM2S1I1bG84MEtjRml3PT0&file=The+Winter+King+S01E07+German+DL+1080p+WEB+x264-WvF: 200.OK (4021 ms)
2024-01-04 21:38:20.1|Trace|Http|Req: 2728 [GET] /2/download?apikey=(removed)&link=bndVTHdDYmJPazd6NSswWDVPR21nSXZSbzFhRURzUzFybU5NQnZJNndVS0JNTUF1REV0UjhUd21aK3oyMFdDYnEwdUc3WFdLV2JaN3BIY0JhZXlZaGcwaW5TSWViNUNvZHpmaFVBbk9aOFc3L1JLNEsvT1NlQTdIUXRPRnJJNm5ZeklmYTdsU0d0c1ZOQ21LMitZMCt3PT0&file=The+Winter+King+S01E07+German+DL+1080p+WEB+x264-WvF (from 172.17.0.1 Sonarr/4.0.0.747 (alpine 3.19.0))
2024-01-04 21:38:20.1|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-01-04 21:38:20.1|Trace|DownloadService|Attempting download of https://immortuos.life/download/the-winter-king-s01e07-german-dl-1080p-web-x264-wvf.169678
2024-01-04 21:38:20.1|Trace|RateLimitService|Rate Limit triggered, delaying 'immortuos.life' for 3.834 sec
2024-01-04 21:38:20.4|Trace|HealthCheckService|Check health -> UpdateCheck
2024-01-04 21:38:20.4|Trace|HealthCheckService|Check health <- UpdateCheck
2024-01-04 21:38:20.4|Trace|HealthCheckService|Check health -> ApiKeyValidationCheck
2024-01-04 21:38:20.4|Trace|HealthCheckService|Check health <- ApiKeyValidationCheck
2024-01-04 21:38:20.4|Trace|HealthCheckService|Check health -> ProxyCheck
2024-01-04 21:38:20.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-04 21:38:20.4|Trace|HealthCheckService|Check health <- ProxyCheck
2024-01-04 21:38:20.4|Trace|HealthCheckService|Check health -> ReleaseBranchCheck
2024-01-04 21:38:20.4|Trace|HealthCheckService|Check health <- ReleaseBranchCheck
2024-01-04 21:38:20.4|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2024-01-04 21:38:20.4|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2024-01-04 21:38:20.4|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2024-01-04 21:38:20.4|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2024-01-04 21:38:20.4|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2024-01-04 21:38:20.4|Trace|Http|Req: 2729 [GET] /api/v1/health (from 185.*.*.41 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
2024-01-04 21:38:20.4|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-01-04 21:38:20.4|Trace|Http|Res: 2729 [GET] /api/v1/health: 200.OK (0 ms)
2024-01-04 21:38:20.4|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2024-01-04 21:38:21.9|Trace|IndexerHttpClient|Req: [GET] https://immortuos.life/filterTorrents?sorting=created_at&direction=desc&qty=100&page=0&view=list
2024-01-04 21:38:21.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-04 21:38:22.0|Trace|Http|Req: 2731 [GET] /api/v1/command (from 185.*.*.41 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
2024-01-04 21:38:22.0|Trace|Http|Req: 2730 [GET] /api/v1/system/task (from 185.*.*.41 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
2024-01-04 21:38:22.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-01-04 21:38:22.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-01-04 21:38:22.0|Trace|CommandQueueManager|Getting all commands
2024-01-04 21:38:22.0|Trace|Http|Res: 2731 [GET] /api/v1/command: 200.OK (1 ms)
2024-01-04 21:38:22.0|Debug|Api|[GET] /api/v1/command: 200.OK (1 ms)
2024-01-04 21:38:22.0|Trace|Http|Res: 2730 [GET] /api/v1/system/task: 200.OK (1 ms)
2024-01-04 21:38:22.0|Debug|Api|[GET] /api/v1/system/task: 200.OK (1 ms)
2024-01-04 21:38:23.6|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://immortuos.life/filterTorrents?sorting=created_at&direction=desc&qty=100&page=0&view=list: 200.OK (685014 bytes) (1682 ms)
2024-01-04 21:38:23.6|Trace|Cardigann|Cardigann (immortuos): Parsing response
2024-01-04 21:38:23.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-01-04 21:38:23.6|Trace|Cardigann|Cardigann (immortuos): Got 100 releases
2024-01-04 21:38:23.6|Trace|Cardigann|Getting Basic search
2024-01-04 21:38:23.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-01-04 21:38:23.6|Trace|Cardigann|Populating config vars
2024-01-04 21:38:23.6|Debug|Cardigann|Adding request: https://animeworld.cx/api/torrents/filter?sortField=created_at&sortDirection=desc&perPage=100
2024-01-04 21:38:23.6|Debug|Cardigann|Downloading Feed https://animeworld.cx/api/torrents/filter?sortField=created_at&sortDirection=desc&perPage=100
2024-01-04 21:38:23.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-01-04 21:38:23.6|Trace|IndexerHttpClient|Req: [GET] https://animeworld.cx/api/torrents/filter?sortField=created_at&sortDirection=desc&perPage=100
2024-01-04 21:38:23.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-04 21:38:23.9|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-01-04 21:38:23.9|Trace|Cardigann|Populating config vars
2024-01-04 21:38:23.9|Trace|RateLimitService|Rate Limit triggered, delaying 'immortuos.life' for 1.997 sec
2024-01-04 21:38:25.9|Trace|IndexerHttpClient|Req: [GET] https://immortuos.life/download/the-winter-king-s01e07-german-dl-1080p-web-x264-wvf.169678
2024-01-04 21:38:25.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-04 21:38:26.0|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://immortuos.life/download/the-winter-king-s01e07-german-dl-1080p-web-x264-wvf.169678: 200.OK (34787 bytes) (109 ms)
2024-01-04 21:38:26.0|Debug|Cardigann|Downloaded for release finished (34787 bytes from https://immortuos.life/download/the-winter-king-s01e07-german-dl-1080p-web-x264-wvf.169678)
2024-01-04 21:38:26.0|Trace|DownloadService|Downloaded 34787 bytes from https://immortuos.life/download/the-winter-king-s01e07-german-dl-1080p-web-x264-wvf.169678
2024-01-04 21:38:26.0|Trace|EventAggregator|Publishing IndexerDownloadEvent
2024-01-04 21:38:26.0|Trace|EventAggregator|IndexerDownloadEvent -> NotificationService
2024-01-04 21:38:26.0|Trace|EventAggregator|IndexerDownloadEvent <- NotificationService
2024-01-04 21:38:26.0|Trace|EventAggregator|IndexerDownloadEvent -> HistoryService
2024-01-04 21:38:26.0|Trace|EventAggregator|IndexerDownloadEvent <- HistoryService
2024-01-04 21:38:26.0|Trace|Http|Res: 2728 [GET] /2/download?apikey=(removed)&link=bndVTHdDYmJPazd6NSswWDVPR21nSXZSbzFhRURzUzFybU5NQnZJNndVS0JNTUF1REV0UjhUd21aK3oyMFdDYnEwdUc3WFdLV2JaN3BIY0JhZXlZaGcwaW5TSWViNUNvZHpmaFVBbk9aOFc3L1JLNEsvT1NlQTdIUXRPRnJJNm5ZeklmYTdsU0d0c1ZOQ21LMitZMCt3PT0&file=The+Winter+King+S01E07+German+DL+1080p+WEB+x264-WvF: 200.OK (5960 ms)
2024-01-04 21:38:26.0|Trace|Http|Req: 2732 [GET] /2/download?apikey=(removed)&link=S0NhMFdteEpueXFjV0JwN292T0cxdkF4TzFDVWhTekoxaVBkakhHZmJ2ZkRGRUJzTjJLWUtuRWVra3FIZHdhZnVaRnZyUk01eTN3NkgwRFcvTjFmNVJEYlJKU1pqN002d2IxeXZNTTQ4R0xubGl6T0tsdVpueG9JMUJRUTZjNmFZVEVIUGtzWmY2dG1nZ04wdGtDMUFnPT0&file=The+Winter+King+S01E08+German+DL+1080p+WEB+x264-WvF (from 172.17.0.1 Sonarr/4.0.0.747 (alpine 3.19.0))
2024-01-04 21:38:26.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-01-04 21:38:26.0|Trace|DownloadService|Attempting download of https://immortuos.life/download/the-winter-king-s01e08-german-dl-1080p-web-x264-wvf.169679
2024-01-04 21:38:26.0|Trace|RateLimitService|Rate Limit triggered, delaying 'immortuos.life' for 1.868 sec
2024-01-04 21:38:26.6|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://animeworld.cx/api/torrents/filter?sortField=created_at&sortDirection=desc&perPage=100: 200.OK (710908 bytes) (2945 ms)
2024-01-04 21:38:26.6|Trace|Cardigann|Cardigann (animeworld-api): Parsing response
2024-01-04 21:38:26.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-01-04 21:38:26.6|Trace|Cardigann|Cardigann (animeworld-api): Got 100 releases
2024-01-04 21:38:26.6|Debug|TorrentSyndikat|Downloading Feed https://torrent-syndikat.org/api_9djWe8Tb2NE3p6opyqnh/v1/browse.php?apikey=(removed)&limit=50&ponly=false
2024-01-04 21:38:26.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-01-04 21:38:26.6|Trace|IndexerHttpClient|Req: [GET] https://torrent-syndikat.org/api_9djWe8Tb2NE3p6opyqnh/v1/browse.php?apikey=(removed)&limit=50&ponly=false
2024-01-04 21:38:26.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-04 21:38:26.7|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://torrent-syndikat.org/api_9djWe8Tb2NE3p6opyqnh/v1/browse.php?apikey=(removed)&limit=50&ponly=false: 500.InternalServerError (0 bytes)
 (96 ms)
2024-01-04 21:38:26.7|Warn|TorrentSyndikat|HTTP Error - Res: HTTP/2.0 [GET] https://torrent-syndikat.org/api_9djWe8Tb2NE3p6opyqnh/v1/browse.php?apikey=(removed)&limit=50&ponly=false: 500.InternalServerError (0 bytes)

2024-01-04 21:38:26.7|Warn|TorrentSyndikat|Unable to connect to indexer

[v1.11.4.4173] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://torrent-syndikat.org/api_9djWe8Tb2NE3p6opyqnh/v1/browse.php?apikey=(removed)&limit=50&ponly=false]
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 608
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 514
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 671

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by CaveMedia** [comment]
Well obviously its not high enough for several indexers. Is there a way to raise this?
