### ISSUE TITLE
Cant add AnimeTorrents as an indexer

### ISSUE THREAD

**Issue by maxwdjoh** [Prowlarr/Prowlarr#2009]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to add AnimeTorrents into Prowlarr, the system errors out with a 403 error code. I suspect this is related to the CloudFlare protection the website uses. I noticed the IPTorrents indexer has the ability to store the website cookie and works great. 

### Expected Behavior

Connection to the website and the indexer to be added to the list. 

### Steps To Reproduce

1. Open Prowlarr
2. Go to the indexer section
3. Add new indexer
4. Search for AnimeTorrents
5. Fill out corresponding information
6. Click test
7. Get error 403

### Environment

```markdown
- OS: Synology NAS DSM 7.2.1 
- Prowlarr: 1.12.2.4211
- Docker Install: Portainer
- Using Reverse Proxy: Yes
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs?

[v1.12.2.4211] NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://animetorrents.me/login.php]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.ExecuteAuth(HttpRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 631
   at NzbDrone.Core.Indexers.Definitions.AnimeTorrents.DoLogin() in ./Prowlarr.Core/Indexers/Definitions/AnimeTorrents.cs:line 53
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 580
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 514
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 671
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@keyframes lds-ring{0%{transform:rotate(0deg)}to{transform:rotate(360deg)}}*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{text-decoration:underline;color:#ee730a}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .big-button,body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4)}}body{display:flex;flex-direction:column;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.no-js .challenge-running{display:none}body.dark{background-color:#222;color:#d9d9d9}body.dark a{color:#fff}a:hover,body.dark a:hover,body.light a:hover{text-decoration:underline;color:#ee730a}body.dark .lds-ring div{border-color:#999 transparent transparent}body.dark .font-red{color:#b20f03}body.dark .big-button,body.dark .pow-button{background-color:#4693ff;color:#1d1d1d}body.dark #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4)}body.light{color:#313131}a,body.light a{color:#0051c3}body.light .lds-ring div{border-color:#595959 transparent transparent}body.light .font-red{color:#fc574a}body.light .big-button,body.light .pow-button{border-color:#003681;background-color:#003681;color:#fff}body.light #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}a,body.light{background-color:transparent}a{transition:color 150ms ease;text-decoration:none}.main-content{margin:8rem auto;width:100%;max-width:60rem}.heading-favicon{margin-right:.5rem;width:2rem;height:2rem}.footer,.main-content{padding-right:1.5rem;padding-left:1.5rem}.main-wrapper{display:flex;flex:1;flex-direction:column;align-items:center}.font-red{color:#b20f03}.spacer{margin:2rem 0}.h1{line-height:3.75rem;font-size:2.5rem;font-weight:500}.core-msg,.h2{line-height:2.25rem;font-size:1.5rem}.h2{font-weight:500}.body-text,.core-msg{font-weight:400}.body-text{line-height:1.25rem;font-size:1rem}#challenge-error-text,#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);background-repeat:no-repeat;background-size:contain;padding-left:34px}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);padding-left:42px}.text-center{text-align:center}.big-button{transition-duration:200ms;transition-property:background-color,border-color,color;transition-timing-function:ease;border:.063rem solid #0051c3;border-radius:.313rem;padding:.375rem 1rem;line-height:1.313rem;font-size:.875rem}.big-button:hover{cursor:pointer}.captcha-prompt:not(.hidden){display:flex}.pow-button{margin:2rem 0;background-color:#0051c3;color:#fff}.pow-button:hover{border-color:#003681;background-color:#003681;color:#fff}.footer{margin:0 auto;width:100%;max-width:60rem;line-height:1.125rem;font-size:.75rem}.footer-inner{border-top:1px solid #d9d9d9;padding-top:1rem;padding-bottom:1rem}.clearfix::after{display:table;clear:both;content:""}.clearfix .column{float:left;padding-right:1.5rem;width:50%}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center}.footer .ray-id code{font-family:monaco,courier,monospace}.core-msg,.zone-name-title{overflow-wrap:break-word}.loading-spinner{height:76.391px}.lds-ring,.lds-ring div{display:inline-block;position:relative;width:1.875rem;height:1.875rem}.lds-ring div{box-sizing:border-box;display:block;position:absolute;border:.3rem solid #595959;border-radius:50%;border-color:#313131 transparent transparent;animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite}.lds-ring div:nth-child(1){animation-delay:-.45s}.lds-ring div:nth-child(2){animation-delay:-.3s}.lds-ring div:nth-child(3){animation-delay:-.15s}@media screen and (-ms-high-contrast:active),screen and (-ms-high-contrast:none){.main-wrapper,body{display:block}}</style><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "animetorrents.me",cType: 'managed',cNounce: '7714',cRay: '84d610726f346748',cHash: 'e759c76b9bf21a9',cUPMDTk: "\/login.php?__cf_chl_tk=.gIWS0bF8RT8B2rSMyc9xAPpTWdtMoogNgEMShPCdZI-1706579428-0-gaNycGzNCjs",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '375000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/login.php?__cf_chl_f_tk=.gIWS0bF8RT8B2rSMyc9xAPpTWdtMoogNgEMShPCdZI-1706579428-0-gaNycGzNCjs",md: "PGKP14NfvMTOK_Yxm6m3oAL71fxcQBuArt49mIpEiRE-1706579428-1-AfaUEViCrn76MKO0J0rohKLlRiUVWYvXZyhpUgrxLeb1Hb6O1hgUbR1LD7Zd3CtzVvHUSCmZ7OTReu46huaav9Q1KGkuCDcaoNpoKe1N0FYj32Zjy2-yBd5pTzTdba9FCSUbhk1US55tjC2SEviVMeQ0QY8CdpK4iGRJ5inFFPezPWXx41C4dj2R3_UPAW1UHQRrDT1NhIxuXZbl56ZCGTnZi3_1Vl7dAdkof9pwzskPy470UDOC5nmQDsbJAsMOY4gbYm2GCpPovac8qXFWmNmS_fCeSR59nBUEDs16GWItsUs1PIRZr8UnvjiSp5fxKp4GibOcu7NBZ0F79oW0a_yWMT2o6_IzEmYJkQJx0dIESOPo03CjmNVKQq-LkTM-P_xj50aMvDKllIPR3KaRqi0ixJkXO1Hc6kuNFczslHE4eyh2u5KurLIj5L5xkiPYSQdUnROzgElAD4lQYOoqf0rgI2N9VSYk80H7hsfEeH4eGVLjL2t5w9QOmUGyE1zWT5-rdK5bmtkPDSsFwhfDnecFa-Q4dXU4vRjSH9MPEUD0L0MeLJTi0icRhThlI1uor1aJ7Fijnbnr91jfa7GNfeWZqrHs0F81e5zwGMJfT_d_MSdmHVP4c9ipAdw1x6W4M_kQXCILk5o727H1ExM_J_FSkzVByzM1o4OriLDxjo330urp9M9jKJtrydzw4fDz2FpWnBg11P0BLSHwntFxdaEszIla_LdHdUmdKY0cd1oAOBZ1nX1zs3LX2CGm3EsC67fUzgRkNUEOnxDc6OV6dU1aR_pIJFXEFP9J8_F1Q755pN_ejs6HqtGAP3v93WddTDFC9WTaG9FLsGnEnZ7c6K6fS8a45B_WaSJfZXEK6eZFp39CVJV9w74BiE3YFldxCDy_uUY8i6z_jfHOAsVLtuTOA9arv4WrZOiTeGnfecCP-Qb6tH1Cf5aK556FvprQ2as8xu18UxEEH8F21jjxWdkbpmzU8ufU9jQ2E7Ttt-Lc0Lui77TZPdmHcat4ypXLqSprUnmryAeifm16NTrC7zkSL3zJMig9mKhVk1BcP1BAIpoBLz4kGyywjg-Q-scmmhNAm8hILyC5uKRk4clw76_NZAEZeglwCo9r9YPEy1bCRR6LchQSGsAp2tPWTaXoJ4QtOhdCKDH4CBn0Fl_tdgyi4SJxohcdGuWTN4yKnZi3QjheQC7Ydu0NttFEF78Scndbi9lP15ysaIaMKqcUzoc1fl4Zifw4tkTmwopbBtJ__5KiCl_mVmew0l98VqUdTR54Aq5KPw5pJwBBzUwxIL2obAT8NStH3SWkKUmnsXSfgU1MZQaVL0mDXt_cboHrLrYcxCl2nvdQwBzzvdvNnGEV4MyRQhsCvhMjhaseOYJ9xmIHIRkcISAGlxk2IavPPv93r-B0tLgHBPqv1m48owI6ZWrjkCsRXBi0hOW4nRpU3Jgl8JFMQUj5QajVLLSxUu8yDmWgFHqeG76-tRzwU4R8noLKFsVAQoAEl_nkwJSAEcvqp21MP237xCM6DfaluMSX_TWpgzPTo7k0Jobk4JSjoqLo3iXF9itASPfRERRSqYBMoG1Ngxdda9KtSttFVA80RplxzI9Xb8Xj2zFTwHvNhyqdrTvJld5NuDQOU_rGg-5JeWC_gpaN5ir2x_oRqNZsMBLfbI-FdmR5hWHJ4wg8YCuynf0BzNtJgQ1tcbSq8ekJHYz5t6uVeyhz019MzRjxk7ao4Q048js0fuuVbGMjOBOP2pBm8XvsGaSug5sZGtZZMUPz24FYDMUxUZ7gtrW4Vb4RXYTlZbAkRDRWXV3uTfp2awJQhaCTc3gWD1UOxN87XvfbTBWu4If9rU_yd69U1g8HBASbNLdSbw4I-E4RAwHtfZY2lJMf7voS1FQk7wC4RgcxUS1xfzmw4iAOlUkGJOgef6DnVx41VsLaet8f7ExSdEjyKKRlRGJ8v4222KoLGsTXeZec3T9HL_uyrtxjtLezHaHJ88GAw-QQ_Gjeka3NDbUi407Kq74OqKzM8X-lopq9Ra6xxHYPXEVMF-jlC0gkEC8_GpU0BTdjqjshEbD9swxRBxe2GbywbtMwNN3Z7Hv77enq-ZQ5jUWBniTVK7ZW0A1h27oAcRyftCqqeXU4JFdKldctARQp7Jk3HpQLyzNREtWsKzfPktfZpGqMyggfydIFLBrCOeMVoGL7QZXUWSfbHIVyCKcEM0ZBDok6yrn2DrZHdVCsLJSRwWAZdelWMOb8DQOElxOgUtWx2kXGVh_f4Vq_cl8MCYpdQiy4QgSmK1FZvkyl31yxGAffRNEunv1CyoMPwvggRl48TCpl2cfeWmOWv8OVZlBgzmeh4ULyfXB75kTAY0rUNa4gkGyKq6AGjLsJey0D1hQPb0xTo8MgcRZjduRSum1IZUc63umo9KI1XyO6_g4T60yTR5NV-5OVEPzpDRIuk6HX9tkoqklvjcIz8kioLIPNRQ-L2ppRZdEjtc8febF0gght1zv4KYvlcYGzDFytxfmlVstY8E0ebflRpw-_1h-Vf98eRlzWoeU2K1LJlQWqQQ",cRq: {ru: 'aHR0cHM6Ly9hbmltZXRvcnJlbnRzLm1lL2xvZ2luLnBocA==',ra: 'UHJvd2xhcnIvMS4xMi4yLjQyMTEgKGFscGluZSAzLjE4LjUp',rm: 'R0VU',d: 'w2f7aBTXp42wXwbEQcuNsiIAQ01bbH/hj+Qj4KGvtW4NiYkqI7hivGoookwOnlTJEBoTRqExTZxDzR8+2ov2r6v7GwZ0IMgDz3wQDdjPkvhG8fA+e9PGbIWWe19X6qtG5ecJfjh9E46lv7Jmj3aLy3OHciiUlouNO1RXuTd72nx3kl5MJb78e2lf4j/FvE+EOLtiyyVNU0zo2GrPN8TcNgQTteNyZqL+tzm7XYU0F6Jp44Ka0Dc2zSdb+O+Mu3+W6VSgQXlRXpFHqHACB8cHFnSLxFDmwaVW8lWXCpE1mWNRttiCug56lW/xfXA7hBa3QPbuGGkbJOGvPKHUm9ORY+ljuZT7MfEmH9177COYBxuUw67hNF/7Z+uqjR/j6SLfcPpm+CLSIcXAXKxz45m6Pwxc2lVu1OeFEcfrhiVkByI9gpiMkeJO/C5O051WbdM/JZK83UbrrrYp9Sz0ePMpibnZP9peSosc9KCyE7MQn8w1DU3g3NJj8RwFmyyRgzmVnkMXJSta3N0YTPJ++S4sMQ3K4Lqa3sieORfETMENcSSV8T645ZhXhrBRtQspmouN45AxUrZ2MIU4xqGXHmCUWg==',t: 'MTcwNjU3OTQyOC4yMjEwMDA=',cT: Math.floor(Date.now() / 1000),m: 'irCc68wWyS5GZwEFBgHGY/52V+XCJfwLB4GRRQroowE=',i1: '+0G6EGTyXIl01hv4iFIinQ==',i2: '9Pd9uovabRcQzhTSwTJAoA==',zh: '/df7TkXR3cDyPgu58N+6jOlupWGDdHXDKF9Quq6YLD0=',uh: 'EDLjy340GM9+4VJDWXcq9BRxreoRaU3oBDCuBSvIJnE=',hh: '25M/X8v2MAd+u//yYWWlW/qfBew4XaGj/1AMcCVpmJc=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=84d610726f346748';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/login.php?__cf_chl_rt_tk=.gIWS0bF8RT8B2rSMyc9xAPpTWdtMoogNgEMShPCdZI-1706579428-0-gaNycGzNCjs" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>

2024-01-30 01:50:28.4|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. HTTP request failed: [403:Forbidden] [GET] at [https://animetorrents.me/login.php]

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by douglasparker** [comment]
I'm experiencing this issue too!

**Comment by ilike2burnthing** [comment]
Have you configured FlareSolverr correctly (itself and for the indexer)?
https://trash-guides.info/Prowlarr/prowlarr-setup-flaresolverr/

If you have further issues - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

**Comment by douglasparker** [comment]
Hey @ilike2burnthing,

Thank you so much for the information on FlareSolverr! I wasn't aware this was a thing.
