### ISSUE TITLE
Flaresolverr not used if there isn't a global proxy set

### ISSUE THREAD

**Issue by chripede** [Prowlarr/Prowlarr#2014]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using Flaresolverr without setting a global proxy, it is not used when checking the indexers.

I am tailing the flaresolverr logs, and I can see the PING/PONG test go through, but when testing 1337x nothing shows up in the log (and the test fails). If I set a global proxy it will however show up in the flaresolverr logs and actually work.

### Expected Behavior

I would expect Flaresolverr to be used both with and without a global proxy. Maybe even also work if a local proxy (tag) is set for the indexer.

### Environment

```markdown
- Prowlarr: 1.13.2.4251
- Docker Install: Yes
```

### What branch are you running?

Master

### Trace Logs?

```
2024-02-05 09:20:29.8|Trace|DiskProviderBase|Deleting file: /config/logs/prowlarr.debug.txt
2024-02-05 09:20:29.8|Trace|CommandQueueManager|Updating command status
2024-02-05 09:20:29.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
2024-02-05 09:20:29.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2024-02-05 09:20:29.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2024-02-05 09:20:29.8|Trace|EventAggregator|Publishing CommandExecutedEvent
2024-02-05 09:20:29.8|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2024-02-05 09:20:29.8|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2024-02-05 09:20:29.8|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2024-02-05 09:20:29.8|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2024-02-05 09:20:29.8|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0751865]
2024-02-05 09:20:29.8|Trace|Http|Req: 179 [GET] /api/v1/command (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:20:29.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:20:29.8|Trace|CommandQueueManager|Getting all commands
2024-02-05 09:20:29.9|Trace|Http|Res: 179 [GET] /api/v1/command: 200.OK (19 ms)
2024-02-05 09:20:29.9|Debug|Api|[GET] /api/v1/command: 200.OK (19 ms)
2024-02-05 09:20:29.9|Trace|Http|Req: 180 [GET] /api/v1/log/file (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:20:29.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:20:29.9|Trace|Http|Res: 180 [GET] /api/v1/log/file: 200.OK (11 ms)
2024-02-05 09:20:29.9|Debug|Api|[GET] /api/v1/log/file: 200.OK (11 ms)
2024-02-05 09:20:33.8|Trace|Http|Req: 181 [GET] /api/v1/log/file (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:20:33.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:20:33.8|Trace|Http|Res: 181 [GET] /api/v1/log/file: 200.OK (12 ms)
2024-02-05 09:20:33.8|Debug|Api|[GET] /api/v1/log/file: 200.OK (12 ms)
2024-02-05 09:20:38.8|Trace|Http|Req: 182 [GET] /api/v1/indexerProxy (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:20:38.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:20:38.8|Trace|Http|Res: 182 [GET] /api/v1/indexerProxy: 200.OK (13 ms)
2024-02-05 09:20:38.8|Debug|Api|[GET] /api/v1/indexerProxy: 200.OK (13 ms)
2024-02-05 09:20:41.7|Trace|Http|Req: 183 [POST] /api/v1/indexerProxy/test (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:20:41.7|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:20:41.7|Debug|FlareSolverr|Cloudflare Detected, Applying FlareSolverr Proxy FlareSolverr to request https://prowlarr.servarr.com/v1/ping
2024-02-05 09:20:41.7|Trace|HttpClient|Req: [POST] http://192.168.0.2:8191/v1
2024-02-05 09:20:43.5|Trace|HttpClient|Res: HTTP/1.1 [POST] http://192.168.0.2:8191/v1: 200.OK (540 bytes) (1805 ms)
2024-02-05 09:20:43.5|Trace|HttpClient|Response content (540 bytes): {"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://prowlarr.servarr.com/v1/ping", "status": 200, "cookies": [], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "headers": {}, "response": "<html><head><meta name=\"color-scheme\" content=\"light dark\"></head><body><pre style=\"word-wrap: break-word; white-space: pre-wrap;\">Pong</pre></body></html>"}, "startTimestamp": 1707121241740, "endTimestamp": 1707121243541, "version": "3.3.13"}
2024-02-05 09:20:43.5|Trace|Http|Res: 183 [POST] /api/v1/indexerProxy/test: 200.OK (1837 ms)
2024-02-05 09:20:43.5|Debug|Api|[POST] /api/v1/indexerProxy/test: 200.OK (1837 ms)
2024-02-05 09:20:46.7|Trace|Scheduler|Pending Tasks: 0
2024-02-05 09:20:50.3|Trace|Http|Req: 184 [POST] /api/v1/indexer/action/getUrls (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:20:50.3|Trace|Http|Req: 185 [GET] /api/v1/downloadclient (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:20:50.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:20:50.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:20:50.3|Trace|Http|Res: 184 [POST] /api/v1/indexer/action/getUrls: 200.OK (17 ms)
2024-02-05 09:20:50.3|Debug|Api|[POST] /api/v1/indexer/action/getUrls: 200.OK (17 ms)
2024-02-05 09:20:50.3|Trace|Http|Res: 185 [GET] /api/v1/downloadclient: 200.OK (22 ms)
2024-02-05 09:20:50.3|Debug|Api|[GET] /api/v1/downloadclient: 200.OK (22 ms)
2024-02-05 09:20:54.3|Trace|Http|Req: 186 [POST] /api/v1/indexer/test (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:20:54.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:20:54.4|Trace|Cardigann|Getting Basic search
2024-02-05 09:20:54.4|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-05 09:20:54.4|Trace|Cardigann|Populating config vars
2024-02-05 09:20:54.4|Debug|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2024-02-05 09:20:54.4|Debug|Cardigann|Downloading Feed https://1337x.to/cat/Movies/time/desc/1/
2024-02-05 09:20:54.4|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-05 09:20:54.4|Trace|IndexerHttpClient|Req: [GET] https://1337x.to/cat/Movies/time/desc/1/
2024-02-05 09:21:16.7|Trace|Scheduler|Pending Tasks: 0
2024-02-05 09:21:46.7|Trace|Scheduler|Pending Tasks: 0
2024-02-05 09:22:16.7|Trace|Scheduler|Pending Tasks: 0
2024-02-05 09:22:34.4|Warn|Cardigann|Unable to connect to indexer.

[v1.13.2.4251] System.Net.WebException: Http request timed out
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 162
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 573
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 514
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 671


2024-02-05 09:22:34.5|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IIndexer>
2024-02-05 09:22:34.5|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> -> IndexerStatusController
2024-02-05 09:22:34.5|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> <- IndexerStatusController
2024-02-05 09:22:34.5|Trace|ProwlarrErrorPipeline|Handling Exception
2024-02-05 09:22:34.5|Trace|Http|Req: 187 [GET] /api/v1/indexerStatus (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:22:34.5|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, indexer's server is unavailable. Try again later. Http request timed out
2024-02-05 09:22:34.5|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:22:34.5|Trace|Http|Res: 186 [POST] /api/v1/indexer/test: 400.BadRequest (100158 ms)
2024-02-05 09:22:34.5|Trace|Http|Res: 187 [GET] /api/v1/indexerStatus: 200.OK (10 ms)
2024-02-05 09:22:34.5|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (100158 ms)
2024-02-05 09:22:34.5|Debug|Api|[GET] /api/v1/indexerStatus: 200.OK (10 ms)
2024-02-05 09:22:39.5|Trace|HealthCheckService|Check health -> IndexerCheck
2024-02-05 09:22:39.5|Trace|HealthCheckService|Check health <- IndexerCheck
2024-02-05 09:22:39.5|Trace|HealthCheckService|Check health -> IndexerLongTermStatusCheck
2024-02-05 09:22:39.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.5|Trace|HealthCheckService|Check health <- IndexerLongTermStatusCheck
2024-02-05 09:22:39.5|Trace|HealthCheckService|Check health -> IndexerStatusCheck
2024-02-05 09:22:39.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-05 09:22:39.6|Trace|HealthCheckService|Check health <- IndexerStatusCheck
2024-02-05 09:22:39.6|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2024-02-05 09:22:39.6|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2024-02-05 09:22:39.6|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2024-02-05 09:22:39.6|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2024-02-05 09:22:39.6|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2024-02-05 09:22:39.6|Trace|Http|Req: 188 [GET] /api/v1/health (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:22:39.6|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:22:39.7|Trace|Http|Res: 188 [GET] /api/v1/health: 200.OK (13 ms)
2024-02-05 09:22:39.7|Debug|Api|[GET] /api/v1/health: 200.OK (13 ms)
2024-02-05 09:22:46.7|Trace|Scheduler|Pending Tasks: 0
2024-02-05 09:23:14.0|Trace|Http|Req: 189 [GET] /api/v1/health (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:23:14.0|Trace|Http|Req: 190 [GET] /api/v1/system/status (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:23:14.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:23:14.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:23:14.0|Trace|Http|Res: 189 [GET] /api/v1/health: 200.OK (8 ms)
2024-02-05 09:23:14.0|Trace|Http|Res: 190 [GET] /api/v1/system/status: 200.OK (11 ms)
2024-02-05 09:23:14.0|Debug|Api|[GET] /api/v1/health: 200.OK (8 ms)
2024-02-05 09:23:14.0|Debug|Api|[GET] /api/v1/system/status: 200.OK (11 ms)
2024-02-05 09:23:14.8|Trace|Http|Req: 191 [GET] /api/v1/log/file (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-05 09:23:14.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-05 09:23:14.8|Trace|Http|Res: 191 [GET] /api/v1/log/file: 200.OK (16 ms)
2024-02-05 09:23:14.8|Debug|Api|[GET] /api/v1/log/file: 200.OK (16 ms)
2024-02-05 09:23:16.7|Trace|Scheduler|Pending Tasks: 0
2024-02-05 09:23:17.0|Trace|Http|Req: 192 [GET] /logfile/prowlarr.trace.txt (from 192.168.0.201 Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0)

```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by chripede** [comment]
@mynameisbogdan The problem is that a query to 1337x will not use the flaresolverr proxy UNLESS there is a global proxy set.

As you can see in my trace log, there is no mention of flaresolverr in the error, even though it is enabled for the indexer.

**Comment by chripede** [comment]
So you're saying that it will first request the site without using flaresolverr and then only use flaresolverr if there is a cloudflare captcha?

I am not blocked from using 1337x, it loads fine in my browser.
