### ISSUE TITLE
Download Client Doesn't Sync To Apps

### ISSUE THREAD

**Issue by halorrr** [Prowlarr/Prowlarr#2022]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The download client set for an indexing in Prowlarr does not get synced to the app

### Expected Behavior

If the download client is set in prowlarr that it would sync to the app.

### Steps To Reproduce

1. Edit an indexer in Prowlarr
2. Show advanced options
3. Set the download client to a specific client
4. Sync App Indexers
5. Check Indexers app like Sonarr
6. Show advanced options
7. Sonarr will have the donwload client set to `(Any)`

### Environment

```markdown
- OS: Unraid 6.12.6
- Prowlarr: 1.13.3.4273
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome Version 121.0.6167.160
```

### What branch are you running?

Master

### Trace Logs?

![image](https://github.com/Prowlarr/Prowlarr/assets/1358708/f80ab11d-2157-49dd-b849-c9e6380d4952)

![image](https://github.com/Prowlarr/Prowlarr/assets/1358708/70c5eee6-b47d-4eef-b6b2-074341eff579)

```
2024-02-11 14:12:36.1|Info|ReleaseSearchService|Searching indexer(s): [EZTV] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000]
2024-02-11 14:12:36.1|Info|ReleaseSearchService|Searching indexer(s): [kickasstorrents.to] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5070]
2024-02-11 14:12:36.1|Info|ReleaseSearchService|Searching indexer(s): [The Pirate Bay] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5050, 5040, 5045]
2024-02-11 14:12:36.1|Info|ReleaseSearchService|Searching indexer(s): [Nyaa.si] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5070]
2024-02-11 14:12:39.3|Info|ReleaseSearchService|Searching indexer(s): [LimeTorrents] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2024-02-11 14:12:39.4|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [POST] http://192.168.50.88:7878/api/v3/indexer: 400.BadRequest (274 bytes)
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2024-02-11 14:12:39.4|Warn|RadarrV3Proxy|No Results in configured categories. See FAQ Entry: Prowlarr will not sync X Indexer to App

[v1.13.3.4273] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://192.168.50.88:7878/api/v3/indexer]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.Applications.Radarr.RadarrV3Proxy.ExecuteIndexerRequest(HttpRequest request) in ./Prowlarr.Core/Applications/Radarr/RadarrV3Proxy.cs:line 202
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]


2024-02-11 14:12:41.3|Info|ReleaseSearchService|Searching indexer(s): [LimeTorrents] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2024-02-11 14:12:41.4|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [POST] http://192.168.50.88:7878/api/v3/indexer?forceSave=true: 400.BadRequest (274 bytes)
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2024-02-11 14:12:41.4|Warn|RadarrV3Proxy|No Results in configured categories. See FAQ Entry: Prowlarr will not sync X Indexer to App

[v1.13.3.4273] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://192.168.50.88:7878/api/v3/indexer?forceSave=true]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.Applications.Radarr.RadarrV3Proxy.ExecuteIndexerRequest(HttpRequest request) in ./Prowlarr.Core/Applications/Radarr/RadarrV3Proxy.cs:line 202
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]


2024-02-11 14:12:41.4|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.50.88:7878/api/v3/indexer?forceSave=true]

[v1.13.3.4273] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://192.168.50.88:7878/api/v3/indexer?forceSave=true]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.Applications.Radarr.RadarrV3Proxy.ExecuteIndexerRequest(HttpRequest request) in ./Prowlarr.Core/Applications/Radarr/RadarrV3Proxy.cs:line 202
   at NzbDrone.Core.Applications.Radarr.RadarrV3Proxy.AddIndexer(RadarrIndexer indexer, RadarrSettings settings) in ./Prowlarr.Core/Applications/Radarr/RadarrV3Proxy.cs:line 100
   at NzbDrone.Core.Applications.Radarr.Radarr.AddIndexer(IndexerDefinition indexer) in ./Prowlarr.Core/Applications/Radarr/Radarr.cs:line 132
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction(Action`1 applicationAction, IApplication application) in ./Prowlarr.Core/Applications/ApplicationService.cs:line 279
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Roxedus** [comment]
Prowlarr has never claimed to sync download clients. it is not a feature of prowlarr, neither is it meant to be a feature.

**Comment by halorrr** [comment]
Why have the setting in Prowlarr if it isn't going to be synced then?

**Comment by Roxedus** [comment]
Its used for prowlarrs integrated search.

**Comment by halorrr** [comment]
Alright, can we treat this as a feature request then?

**Comment by bakerboy448** [comment]
> Specify which download client is **used for grabs made within Prowlarr from this indexer**

Not a bug; the UI notes its only relevant to grabs in prowlarr

no plans to nor is there a need to sync download clients given it's a 1x configuration that rarely changes for users

**Comment by snickers2k** [comment]
> > Specify which download client is **used for grabs made within Prowlarr from this indexer**
> 
> Not a bug; the UI notes its only relevant to grabs in prowlarr
> 
> no plans to nor is there a need to sync download clients given it's a 1x configuration that rarely changes for users

hey, i just have encountered the same problem, since i moved to a new machine and had to set up all the 'arrs download clients (sab and nzb) by hand.
also if all it needs is a simple port change of sab or so and it needs a lot of work by hand.

+1

**Comment by appiekap653** [comment]
> > Specify which download client is **used for grabs made within Prowlarr from this indexer**
> 
> Not a bug; the UI notes its only relevant to grabs in prowlarr
> 
> no plans to nor is there a need to sync download clients given it's a 1x configuration that rarely changes for users

So when I want to use Prowlarr as a 'single central place to manage all indexers for all other apps', I can setup all indexers once in Prowlarr and have it set to auto sync to all apps.
Then I need to open every *arr app, go through every indexer, and setup the right download client.
Then after the auto sync from Prowlarr, I wouldn't need to go through every indexer in every *arr app again to re-setup the right download client?

I was under the impression that those settings would be set back to 'any' after the sync...

**Comment by bakerboy448** [comment]
Please use [Discord](https://prowlarr.com/discord) for support/questions.

**Comment by appiekap653** [comment]
why would I reply to a message that you replied here somewhere else?
I'm just going further continuing onto this conversation that is right here...

**Comment by bakerboy448** [comment]
GITHUB IS NOT FOR SUPPORT
