### ISSUE TITLE
ValidationFailure Error while adding AvistaZ indexer

### ISSUE THREAD

**Issue by th3curious** [Prowlarr/Prowlarr#2030]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When ever i try to adde "AvistaZ" indexer it shows ValidationFailure Error

Other relevant information:
I am vip user of it, not newbie, if ur newbie from what i know is that you can't use avistaz with indexer softwares, one of the points mentioned when adding AvistaZ in jackett. Additionally, i was able to add AvistaZ in jackett only after my member status changed from newbie.

### Expected Behavior

When clicking save, it save the index instead get the error

### Steps To Reproduce

* Add a indexer named AvistaZ
* Fill the necessary information - URL, username, password and pid.
* Click "Test", and shows correct tick
* When clicking "Save" it shows ValidationFailure error

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS x86_64
- Prowlarr: v1.13.3.4273
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Brave Version 1.62.165 Chromium: 121.0.6167.184 (Official Build)  (64-bit)
- CPU: AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16) @ 5.263GHz
- RAM: 32 GB
```

### What branch are you running?

Master

### Trace Logs?

Here are the log - [prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/14308609/prowlarr.txt)

Here is the screenshot:
![Screenshot 2024-02-16 124119](https://github.com/Prowlarr/Prowlarr/assets/106827312/e5abb687-9e66-479c-9b77-12e6b534c3e5)

Here is portion of trace from the log:
```
[v1.13.3.4273] System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at NzbDrone.Common.Serializer.STJson.Deserialize[T](String json) in ./Prowlarr.Common/Serializer/System.Text.Json/STJson.cs:line 45
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazBase.GetToken() in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazBase.cs:line 137
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazBase.TestConnection() in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazBase.cs:line 93


2024-02-16 12:41:05.4|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details
2024-02-16 12:41:21.8|Warn|AvistaZ|Unable to connect to indexer

[v1.13.3.4273] System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at NzbDrone.Common.Serializer.STJson.Deserialize[T](String json) in ./Prowlarr.Common/Serializer/System.Text.Json/STJson.cs:line 45
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazBase.GetToken() in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazBase.cs:line 137
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazBase.TestConnection() in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazBase.cs:line 93


2024-02-16 12:41:21.8|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by th3curious** [comment]
Here is the shared log file with trace enabled.
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/14336838/prowlarr.trace.txt)

**Comment by th3curious** [comment]
@mynameisbogdan, sorry for late reply, Here is the shared log file with trace enabled.
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/14336838/prowlarr.trace.txt)

**Comment by R8s6** [comment]
i just wanna confirm i'm having the same errors.

Trace logs: https://privatebin.net/?6b7ac59487bdb116#D5HiYPCJ2mvRG5NbZy6J82yeQtCL2vwfwd8Z7j6Scpqf

At first glance it appears to be a rate limiting issue, which explains why *sometimes* the "Test" function works (but not always), also explains why even after "Test" did occasionally work, a followed "Save" would fail.
