### ISSUE TITLE
Tracker 3changtrai's captcha not loading

### ISSUE THREAD

**Issue by HydeonTZ** [Prowlarr/Prowlarr#2043]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

In the add indexer page, if I try to add 3changtrai, the captcha field doesn't show any image to solve. Clicking the refresh button does not do anything. Consequently, I cannot add 3changtrai to prowlarr at all.

I removed the HTML output in the trace log so as not to make it too long.

### Expected Behavior

A captcha should show up similar to TorrentGalaxy.

### Environment

```markdown
- OS: Debian GNU/Linux 10
- Prowlarr: 1.13.3
- Docker Install:No
- Using Reverse Proxy: Not sure
- Browser: Chrome and Firefox
```

### What branch are you running?

Master

### Trace Logs?

2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2024-02-22 23:51:34.7|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'applicationurl' defaultValue:''
2024-02-22 23:51:34.7|Trace|EventAggregator|Publishing ConfigSavedEvent
2024-02-22 23:51:34.7|Trace|EventAggregator|ConfigSavedEvent -> UiAuthorizationHandler
2024-02-22 23:51:34.7|Trace|EventAggregator|ConfigSavedEvent <- UiAuthorizationHandler
2024-02-22 23:51:34.7|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2024-02-22 23:51:34.7|Trace|EventAggregator|ConfigSavedEvent ~> TaskManager
2024-02-22 23:51:34.7|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2024-02-22 23:51:34.7|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'applicationurl' defaultValue:''
2024-02-22 23:51:34.8|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'30'
2024-02-22 23:51:34.8|Trace|Http|Res: 5944 [PUT] /prowlarr/api/v1/config/host: 202.Accepted (170 ms)
2024-02-22 23:51:34.8|Trace|EventAggregator|ConfigSavedEvent <~ TaskManager
2024-02-22 23:51:37.0|Trace|ProwlarrErrorPipeline|Handling Exception
2024-02-22 23:51:37.0|Fatal|ProwlarrErrorPipeline|Request Failed. POST /api/v1/indexer/action/checkCaptcha

[v1.13.3.4273] System.Net.WebException: Http request timed out
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 162
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 51
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.GetConfigurationForSetup(Boolean automaticLogin) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 679
   at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.RequestAction(String action, IDictionary`2 query) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 237
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.RequestAction(TProviderDefinition definition, String action, IDictionary`2 query) in ./Prowlarr.Core/ThingiProvider/ProviderFactory.cs:line 86
   at Prowlarr.Api.V1.ProviderControllerBase`4.RequestAction(String name, TProviderResource resource) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 237
   at lambda_method346(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2024-02-22 23:51:37.2|Trace|Http|Res: 5931 [POST] /prowlarr/api/v1/indexer/action/checkCaptcha: 500.InternalServerError (65260 ms)
2024-02-22 23:51:39.3|Trace|Http|Req: 5945 [GET] /prowlarr/api/v1/indexerProxy (from 169.*.*.243 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-22 23:51:39.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-22 23:51:39.3|Trace|Http|Res: 5945 [GET] /prowlarr/api/v1/indexerProxy: 200.OK (3 ms)
2024-02-22 23:51:39.7|Trace|HealthCheckService|Check health -> UpdateCheck
2024-02-22 23:51:39.7|Trace|HealthCheckService|Check health <- UpdateCheck
2024-02-22 23:51:39.7|Trace|HealthCheckService|Check health -> ApiKeyValidationCheck
2024-02-22 23:51:39.7|Trace|HealthCheckService|Check health <- ApiKeyValidationCheck
2024-02-22 23:51:39.7|Trace|HealthCheckService|Check health -> ProxyCheck
2024-02-22 23:51:39.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:51:39.7|Trace|HealthCheckService|Check health <- ProxyCheck
2024-02-22 23:51:39.7|Trace|HealthCheckService|Check health -> ReleaseBranchCheck
2024-02-22 23:51:39.7|Trace|HealthCheckService|Check health <- ReleaseBranchCheck
2024-02-22 23:51:39.7|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2024-02-22 23:51:39.7|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2024-02-22 23:51:39.7|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2024-02-22 23:51:39.7|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2024-02-22 23:51:39.7|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2024-02-22 23:51:39.7|Trace|Http|Req: 5946 [GET] /prowlarr/api/v1/health (from 169.*.*.243 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-22 23:51:39.7|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-22 23:51:39.7|Trace|Http|Res: 5946 [GET] /prowlarr/api/v1/health: 200.OK (1 ms)
2024-02-22 23:51:40.3|Trace|ProwlarrErrorPipeline|Handling Exception
2024-02-22 23:51:40.3|Fatal|ProwlarrErrorPipeline|Request Failed. POST /api/v1/indexer/action/checkCaptcha

[v1.13.3.4273] System.Net.WebException: Http request timed out
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>g__ReadAheadWithZeroByteReadAsync|45_0()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 162
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 51
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.GetConfigurationForSetup(Boolean automaticLogin) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 679
   at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.RequestAction(String action, IDictionary`2 query) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 237
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.RequestAction(TProviderDefinition definition, String action, IDictionary`2 query) in ./Prowlarr.Core/ThingiProvider/ProviderFactory.cs:line 86
   at Prowlarr.Api.V1.ProviderControllerBase`4.RequestAction(String name, TProviderResource resource) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 237
   at lambda_method346(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2024-02-22 23:51:40.5|Trace|Http|Res: 5932 [POST] /prowlarr/api/v1/indexer/action/checkCaptcha: 500.InternalServerError (65275 ms)
2024-02-22 23:51:45.8|Trace|Http|Req: 5947 [GET] /prowlarr/api/v1/indexer/schema (from 169.*.*.243 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-22 23:51:45.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-22 23:51:45.9|Trace|HttpClient|Req: [GET] https://indexers.prowlarr.com/master/9
2024-02-22 23:51:45.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:51:45.9|Trace|HttpClient|Res: HTTP/2.0 [GET] https://indexers.prowlarr.com/master/9: 200.OK (1283333 bytes) (48 ms)
2024-02-22 23:51:46.2|Trace|Http|Res: 5947 [GET] /prowlarr/api/v1/indexer/schema: 200.OK (337 ms)
2024-02-22 23:51:50.3|Trace|Http|Req: 5948 [POST] /prowlarr/api/v1/indexer/action/getUrls (from 169.*.*.243 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-22 23:51:50.3|Trace|Http|Req: 5949 [POST] /prowlarr/api/v1/indexer/action/checkCaptcha (from 169.*.*.243 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-22 23:51:50.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-22 23:51:50.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-22 23:51:50.3|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-22 23:51:50.3|Trace|Cardigann|Populating config vars
2024-02-22 23:51:50.3|Trace|Http|Res: 5948 [POST] /prowlarr/api/v1/indexer/action/getUrls: 200.OK (3 ms)
2024-02-22 23:51:50.3|Trace|IndexerHttpClient|Req: [GET] https://3changtrai.com/login.php
2024-02-22 23:51:50.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:51:50.3|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://3changtrai.com/login.php: 403.Forbidden (17036 bytes)
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"> .....
</body></html> (24 ms)
2024-02-22 23:51:50.3|Trace|Http|Req: 5950 [GET] /prowlarr/api/v1/downloadclient (from 169.*.*.243 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-22 23:51:50.3|Trace|IndexerHttpClient|Response content (17036 bytes): <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge">......
</body></html>
2024-02-22 23:51:50.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-22 23:51:50.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:51:50.4|Debug|FlareSolverr|Cloudflare Detected, Applying FlareSolverr Proxy FlareSolverr to request https://3changtrai.com/login.php
2024-02-22 23:51:50.4|Trace|HttpClient|Req: [POST] http://*.*.*.*:port/v1
2024-02-22 23:51:50.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:51:50.4|Trace|Http|Res: 5950 [GET] /prowlarr/api/v1/downloadclient: 200.OK (91 ms)
2024-02-22 23:51:58.6|Trace|Scheduler|Pending Tasks: 0
2024-02-22 23:52:02.4|Trace|Http|Req: 5951 [POST] /prowlarr/api/v1/indexer/test (from 169.*.*.243 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-22 23:52:02.4|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-22 23:52:02.4|Trace|Cardigann|Getting Basic search
2024-02-22 23:52:02.4|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-22 23:52:02.4|Trace|Cardigann|Populating config vars
2024-02-22 23:52:02.4|Debug|Cardigann|Adding request: https://3changtrai.com/torrents.php?incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1
2024-02-22 23:52:02.4|Debug|Cardigann|Downloading Feed https://3changtrai.com/torrents.php?incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1
2024-02-22 23:52:02.4|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-22 23:52:02.4|Trace|IndexerHttpClient|Req: [GET] https://3changtrai.com/torrents.php?incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1
2024-02-22 23:52:02.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:52:03.6|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://3changtrai.com/torrents.php?incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1: 302.Redirect (0 bytes) (1190 ms)
2024-02-22 23:52:03.6|Debug|FlareSolverr|CF Protection not detected, returning original response
2024-02-22 23:52:03.6|Trace|Cardigann|Attempting to re-auth based on indexer search response
2024-02-22 23:52:03.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-22 23:52:03.6|Trace|Cardigann|Populating config vars
2024-02-22 23:52:03.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-22 23:52:03.6|Trace|Cardigann|Populating config vars
2024-02-22 23:52:03.6|Trace|RateLimitService|Rate Limit triggered, delaying '3changtrai.com' for 0.806 sec
2024-02-22 23:52:04.4|Trace|IndexerHttpClient|Req: [GET] https://3changtrai.com/login.php
2024-02-22 23:52:04.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:52:04.5|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://3changtrai.com/login.php: 403.Forbidden (17036 bytes)
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"></script>
</body></html> (8 ms)
2024-02-22 23:52:04.5|Trace|IndexerHttpClient|Response content (17036 bytes): <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1">.....
</body></html>
2024-02-22 23:52:04.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:52:04.5|Debug|FlareSolverr|Cloudflare Detected, Applying FlareSolverr Proxy FlareSolverr to request https://3changtrai.com/login.php
2024-02-22 23:52:04.5|Trace|HttpClient|Req: [POST] http://*.*.*.*:port/v1
2024-02-22 23:52:04.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:52:08.3|Trace|Http|Req: 5952 [POST] /prowlarr/api/v1/indexer/action/checkCaptcha (from 169.*.*.243 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-22 23:52:08.3|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-22 23:52:08.3|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-22 23:52:08.3|Trace|Cardigann|Populating config vars
2024-02-22 23:52:08.3|Trace|IndexerHttpClient|Req: [GET] https://3changtrai.com/login.php
2024-02-22 23:52:08.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-22 23:52:08.3|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://3changtrai.com/login.php: 403.Forbidden (17015 bytes)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by ilike2burnthing** [comment]
Working ok on Windows for me, but had mixed results on Docker. Try increasing the timeout to 120s, see if that makes a difference. If not, share the debug FlareSolverr logs as well - https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by HydeonTZ** [comment]
I tried to increase timeout to 120s, still the same problem. On the FlareSolverr front, I just have this error:
```
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 120.0 seconds.", "startTimestamp": 1708732113569, "endTimestamp": 1708732234955, "version": "3.3.15"}
```

**Comment by ilike2burnthing** [comment]
> If not, share the debug FlareSolverr logs as well - https://github.com/FlareSolverr/FlareSolverr#environment-variables
