### ISSUE TITLE
In Page Apps, add application (radarr) ,then test fail

### ISSUE THREAD

**Issue by ultramandada** [Prowlarr/Prowlarr#2044]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

1.input prowlarr server
2.input radarr server
3.input apikey
4.click "test"button
5.test fail
![prowlarrbug](https://github.com/Prowlarr/Prowlarr/assets/125641972/693149cf-e01d-47bd-a6c7-324b1129a8aa)

### Expected Behavior

add successfully

### Steps To Reproduce

1.input prowlarr server
2.input radarr server
3.input apikey
4.click "test"button

### Environment

```markdown
- OS: win10
- Prowlarr:1.13.3.4273
- Docker Install: yes
- Using Reverse Proxy:
- Browser: chrome  107.0.5304.122
```

### What branch are you running?

Master

### Trace Logs?

docker -prowlarr log:

[Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [GET] http://172.27.207.69/:7878/api/v1/indexer/schema: 404.NotFound (3212 bytes)
[Warn] Readarr: Unable to complete application test

[v1.13.3.4273] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://172.27.207.69/:7878/api/v1/indexer/schema]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.Applications.Readarr.ReadarrV1Proxy.Execute[TResource](HttpRequest request) in ./Prowlarr.Core/Applications/Readarr/ReadarrV1Proxy.cs:line 201
   at NzbDrone.Core.Applications.Readarr.ReadarrV1Proxy.GetIndexerSchema(ReadarrSettings settings) in ./Prowlarr.Core/Applications/Readarr/ReadarrV1Proxy.cs:line 76
   at NzbDrone.Core.Applications.Readarr.Readarr.<>c__DisplayClass11_0.<BuildReadarrIndexer>b__0() in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 220
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Prowlarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Applications.Readarr.Readarr.BuildReadarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 220
   at NzbDrone.Core.Applications.Readarr.Readarr.Test() in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 52
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>.center{font-family:Verdana,Arial,sans-serif}.center:lang(zh-TW){font-family:Verdana,Arial,Microsoft JhengHei,sans-serif}.center:lang(zh-CN){font-family:Verdana,Arial,Microsoft YaHei,sans-serif}.center:lang(ja){font-family:Verdana,Arial,Meiryo,sans-serif}.circle_text{font-weight:700}html{height:100%}body{margin:0 auto;min-height:600px;min-width:800px;height:100%}.top{height:100px;height:calc(40% - 140px)}.bottom{height:150px;height:calc(60% - 210px)}.center{height:350px;text-align:center;vertical-align:middle}.circle{margin:auto;width:260px;height:260px;border-radius:50%;background:#c0c6cc}.circle_text{line-height:260px;font-size:100px;color:#fff}.text{line-height:40px;font-size:26px;color:#414b55}
</style>
</head>
<body>
<div class="top"></div>
<div class="center">
<div class="circle">
<div class="circle_text">404</div>
</div>
<div>
<p class="text" id="a"></p>
</div>
<script>
/* Copyright (c) 2023 Synology Inc. All rights reserved. */

(function(){var a=new XMLHttpRequest();a.open("get","/missing",true);a.send();a.onreadystatechange=function(){if(a.readyState==4&&(a.status==200||a.status==304)){var c=String(a.responseText);var e=document.open("text/html","replace");e.write(c);e.close()}else{var d={en:"The page you are looking for cannot be found.",zh:"\u60a8\u8981\u627e\u7684\u9875\u9762\u672a\u627e\u5230\u3002",it:"Impossibile trovare la pagina ricercata.","zh-HK":"\u60a8\u6240\u6307\u5b9a\u7684\u9801\u9762\u4e0d\u5b58\u5728\u3002",cs:"Hledan\u00e1 str\u00e1nka nebyla nalezena.",es:"Lo sentimos, no se encuentra la p\u00e1gina que est\u00e1 buscando.",ru:"\u041d\u0435 \u0443\u0434\u0430\u0435\u0442\u0441\u044f \u043d\u0430\u0439\u0442\u0438 \u0438\u0441\u043a\u043e\u043c\u0443\u044e \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443.",nl:"Kan de gezochte pagina niet vinden.",pt:"A p\u00e1gina que procura n\u00e3o foi encontrada.",no:"Finner ikke siden du leter etter.",nb:"Finner ikke siden du leter etter.",tr:"Arad\u0131\u011f\u0131n\u0131z sayfa bulunam\u0131yor.",pl:"Nie znaleziono strony, kt\u00f3rej szukasz.",fr:"La page que vous recherchez est introuvable.",de:"Die Seite, nach der Sie suchen, kann nicht gefunden werden.",hu:"A keresett oldal nem tal\u00e1lhat\u00f3.","pt-BR":"N\u00e3o foi poss\u00edvel encontrar a p\u00e1gina que voc\u00ea est\u00e1 buscando.","zh-MO":"\u60a8\u6240\u6307\u5b9a\u7684\u9801\u9762\u4e0d\u5b58\u5728\u3002",da:"Den side, du leder efter, kunne ikke findes.",ja:"\u304a\u63a2\u3057\u306e\u30da\u30fc\u30b8\u304c\u3001\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002",nn:"Finner ikke siden du leter etter.","zh-TW":"\u60a8\u6240\u6307\u5b9a\u7684\u9801\u9762\u4e0d\u5b58\u5728\u3002",ko:"\ucc3e\uace0 \uacc4\uc2e0 \ud398\uc774\uc9c0\ub97c \ubc1c\uacac\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.",sv:"Sidan du s\u00f6ker kunde inte hittas."};var b=["zh-TW","zh-HK","zh-MO","pt-BR"];var f;if(window.navigator.languages!==undefined){f=window.navigator.languages[0]}else{f=window.navigator.language||window.navigator.browserLanguage}if(b.indexOf(f)<0){f=f.split("-")[0]}document.getElementById("a").innerHTML=d[f]||d.enu}}})();
</script>
</div>
<div class="bottom"></div>
</body>
</html>

[Warn] ProwlarrErrorPipeline: Invalid request Validation failed:
 -- BaseUrl: Unable to complete application test, cannot connect to Readarr. HTTP request failed: [404:NotFound] [GET] at [http://172.27.207.69/:7878/api/v1/indexer/schema]
[Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [GET] http://172.27.207.69:7878/api/v1/indexer/schema: 404.NotFound (0 bytes)
[Warn] Readarr: Unable to complete application test

[v1.13.3.4273] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://172.27.207.69:7878/api/v1/indexer/schema]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.Applications.Readarr.ReadarrV1Proxy.Execute[TResource](HttpRequest request) in ./Prowlarr.Core/Applications/Readarr/ReadarrV1Proxy.cs:line 201
   at NzbDrone.Core.Applications.Readarr.ReadarrV1Proxy.GetIndexerSchema(ReadarrSettings settings) in ./Prowlarr.Core/Applications/Readarr/ReadarrV1Proxy.cs:line 76
   at NzbDrone.Core.Applications.Readarr.Readarr.<>c__DisplayClass11_0.<BuildReadarrIndexer>b__0() in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 220
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Prowlarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Applications.Readarr.Readarr.BuildReadarrIndexer(IndexerDefinition indexer, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 220
   at NzbDrone.Core.Applications.Readarr.Readarr.Test() in ./Prowlarr.Core/Applications/Readarr/Readarr.cs:line 52

[Warn] ProwlarrErrorPipeline: Invalid request Validation failed:
 -- BaseUrl: Unable to complete application test, cannot connect to Readarr. HTTP request failed: [404:NotFound] [GET] at [http://172.27.207.69:7878/api/v1/indexer/schema]

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- for future reference: Trace logs not provided; please don't check the box claiming you read the wiki and provided trace logs when that's not the case
- an error is not a bug
