### ISSUE TITLE
TurkTorrent.us not working

### ISSUE THREAD

**Issue by GinoBadouri** [Prowlarr/Prowlarr#2048]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm trying to add the TurkTorrent.us private tracker but it fails.
I've followed the instructions and torrent listing is set to "classic" and the language to "english".
I've copied the full cookie request header btw.
```tsue_guest_language=1; shoutboxChannelID=1; tsue_member=xxx```

The logfile returns:
```
2024-02-28 20:27:58.5|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
```

### Expected Behavior

Working TurkTorrent.us indexer

### Environment

```markdown
- OS: Fedora 39 using Podman
- Prowlarr: 1.13.3.4273-ls54 by linuxserver.io
- Docker Install: yes, using podman
- Using Reverse Proxy: no
- Browser: Firefox 123.0
```

### What branch are you running?

Master

### Trace Logs?
```
2024-02-28 21:07:24.9|Warn|Cardigann|Unable to connect to indexer

[v1.13.3.4273] System.FormatException: The format of value '' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.AddRequestHeaders(HttpRequestMessage webRequest, HttpHeader headers) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 210
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 573
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 514
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 757


2024-02-28 21:07:25.0|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. The format of value '' is invalid.
2024-02-28 21:12:31.0|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
```
### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
> I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain trace - that are relevant and show this issue.

please don't check the box simply because it is required when the action was not executed

**Comment by MastaG** [comment]
Hi @bakerboy448 I set the loglevel to trace and copied the message from the logfile.
I already had a feeling it wasn't sufficient.
Perhaps I need to restart the application first after changing the level to trace.

**Comment by GinoBadouri** [comment]
This should be the trace:

```
2024-02-28 21:12:28.9|Trace|Http|Req: 221 [POST] /api/v1/indexer/test (from 10.88.0.43 Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0)
2024-02-28 21:12:28.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-02-28 21:12:28.9|Trace|Cardigann|Getting Basic search
2024-02-28 21:12:28.9|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-28 21:12:28.9|Trace|Cardigann|Populating config vars
2024-02-28 21:12:28.9|Debug|Cardigann|Adding request: https://turktorrent.us/?p=torrents&pid=(removed)&search_type=name&sortOptions[sortBy]=added&sortOptions[sortOrder]=desc
2024-02-28 21:12:28.9|Debug|Cardigann|Downloading Feed https://turktorrent.us/?p=torrents&pid=(removed)&search_type=name&sortOptions[sortBy]=added&sortOptions[sortOrder]=desc
2024-02-28 21:12:28.9|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-28 21:12:28.9|Trace|IndexerHttpClient|Req: [GET] https://turktorrent.us/?p=torrents&pid=(removed)&search_type=name&sortOptions[sortBy]=added&sortOptions[sortOrder]=desc
2024-02-28 21:12:28.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-28 21:12:29.1|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://turktorrent.us/?p=torrents&pid=(removed)&search_type=name&sortOptions[sortBy]=added&sortOptions[sortOrder]=desc: 200.OK (8493 bytes) (265 ms)
2024-02-28 21:12:29.1|Debug|FlareSolverr|CF Protection not detected, returning original response
2024-02-28 21:12:29.1|Trace|Cardigann|Attempting to re-auth based on indexer search response
2024-02-28 21:12:29.1|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-28 21:12:29.1|Trace|Cardigann|Populating config vars
2024-02-28 21:12:29.1|Trace|RateLimitService|Rate Limit triggered, delaying 'turktorrent.us' for 1.727 sec
2024-02-28 21:12:30.9|Trace|IndexerHttpClient|Req: [GET] https://turktorrent.us/?p=torrents&pid=(removed)&search_type=name&sortOptions[sortBy]=added&sortOptions[sortOrder]=desc
2024-02-28 21:12:30.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-02-28 21:12:30.9|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://turktorrent.us/?p=torrents&pid=(removed)&search_type=name&sortOptions[sortBy]=added&sortOptions[sortOrder]=desc: 200.OK (8493 bytes) (47 ms)
2024-02-28 21:12:30.9|Debug|FlareSolverr|CF Protection not detected, returning original response
2024-02-28 21:12:30.9|Trace|Cardigann|Cardigann (turktorrent): Parsing response
2024-02-28 21:12:30.9|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-02-28 21:12:30.9|Trace|Cardigann|Cardigann (turktorrent): Got 0 releases
2024-02-28 21:12:30.9|Trace|Cardigann|No releases found. Response: <!DOCTYPE html>
<html id="TSUE" lang="en-us">
<head>
<noscript><meta http-equiv=refresh content="0; URL=https://turktorrent.us/?noscript=1" /></noscript>
<base href="https://turktorrent.us/" />
<title>TurkTorrent.us</title>
<meta charset="utf-8" />
<meta name="description" content="TurkTorrent" />
<link rel="stylesheet" href="https://turktorrent.us/style.php?lv=2.2&l=style,fancybox,jqueryTools,forums,fileuploader,tinymce_ui,thread_prefixes,comments,downloads,image_gallery,extra,menu,ajax,shoutbox,staffDropDownMenu,upcomingReleases,staffOnlineNow,subtitles,oneStepUpload,mixed,topDonors,fls,memberCard,plugin_torrent_categories,members,donations,livechat" type="text/css" media="screen" />
<link rel="Shortcut Icon" href="https://turktorrent.us/favicon.ico?lv=2.2" type="image/x-icon" />
</head>
<body>

<div id="wrap">

<div id="header">
<div class="content"><img src="https://turktorrent.us/data/languageFlags/1.png" alt="default" rel="selectLanguage" class="clickable" />
</div>
</div>

<ul id="menu">
<li class="nodrop">
<a href="https://turktorrent.us/?p=home&amp;pid=(removed)" class="link ">Home</a>
</li><li class="nodrop">
<a href="https://turktorrent.us/?p=signup&amp;pid=(removed)" class="link ">Sign-up</a>
</li>
</ul>
<div class="clear"></div>

<div id="inner">
<div class="breadBoxTop">
<nav>
<fieldset class="breadcrumb">
<span class="crumbs">
<span class="crust" itemscope="itemscope" itemtype="http://data-vocabulary.org/Breadcrumb">
<a href="https://turktorrent.us/?p=home&amp;pid=(removed)" class="crumb" rel="up" itemprop="url"><span itemprop="title">Home</span></a>
<span class="arrow"><span></span></span>
</span>
<span class="crust" itemscope="itemscope" itemtype="http://data-vocabulary.org/Breadcrumb">
<a href="https://turktorrent.us/?p=torrents&amp;pid=(removed)" class="crumb" rel="up" itemprop="url"><span itemprop="title">Torrents</span></a>
<span class="arrow"><span></span></span>
</span>
</span>
</fieldset>
</nav>
</div>

<div id="plugins">
<div id="content" class="mainContent fullwidth"> <div class="error" id="show_error">
<b>An error has occured!</b><br/>You do not have permission to view this page or perform this action.
</div><div class="widget">
<h4>Log in</h4>
<div id="loginbox">
<form id="loginbox_form" action>
<p>
<label for="loginbox_membername">Membername</label><br/>
<input type="text" name="loginbox_membername" id="loginbox_membername" class="s" accesskey="m" value />
</p>
<p>
<label for="loginbox_password">Password</label><br/>
<input type="password" name="loginbox_password" id="loginbox_password" class="s" accesskey="p" value />
</p>
<center></br><SCRIPT type="text/javascript">
  function onHuman(response) {
    document.getElementById('captcha').value = response;
  }
</SCRIPT>
<script src="https://hcaptcha.com/1/api.js?hl=tr" async defer></script>
<div class="h-captcha" data-callback="onHuman" data-sitekey="18b46fe7-6021-408e-b14c-f318dbae672a" data-size="compact" data-theme="dark" id="1"></div>
<INPUT type="hidden" id="captcha" name="captcha" value></center>
<p>
<input type="checkbox" name="loginbox_remember" id="loginbox_remember" accesskey="r" value="1" />
<label for="loginbox_remember">Stay logged in</label>
</p>
<p id="loginbox-buttons">
<input type="submit" value="Log in" class="submit" />
<input type="reset" value="Clear" class="submit" />
</p>
<p>
<a href="https://turktorrent.us/?p=signup&pid=(removed)" id="signup">Sign up</a>
<br/>
<a href="#" rel="forgot-password">Forgot your password?</a>
</p>
</form>
</div>
</div></div>
<div class="clear"></div>
</div>

</div>


<div id="footer">
<div class="wrap">

<p>Powered by TurkTorrent.us &copy; 2006-2024</p>

</div>
</div>

</div>

<script type="text/javascript">
		//<![CDATA[
			var TSUEPhrases = 
{
	months: "January,February,March,April,May,June,July,August,September,October,November,December",
	shortMonths: "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
	days: "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
	shortDays: "Sun,Mon,Tue,Wed,Thu,Fri,Sat",

	relative_a_moment_ago: "A moment ago",
	relative_one_minute_ago: "One minute ago",
	relative_x_minutes_ago: "{1} minutes ago",
	relative_one_hour_ago: "One hour ago",
	relative_x_hours_ago: "{1} hours ago",
	relative_one_day_ago: "One day ago",
	relative_x_days_ago: "{1} days ago",

	button_save: "Save",
	button_update: "Update",
	button_cancel: "Cancel",
	button_okay: "Okay",
	button_preview: "Preview",

	message_saved: "Your changes have been saved.",
	message_posted: "Your message have been posted.",
	message_deleted: "Your message have been deleted.",
	message_required_fields_error: "Please complete all required fields.",

	website_active_admin_alert: "Alert! Website is currently closed!",
	ajax_error: "Ajax Error! Please try again later.",
	confirmation_required: "Confirmation Required",
	confirm_delete_message: "Are you sure that you want to delete this message(s)?",
	confirm_delete_message_global: "Are you sure that you want to delete this content?",
	login_required: "You must be logged-in to do that.",
	an_error_hash_occurded: "An error has occured!",
	loading: "Please wait, loading...",

	shoutbox_inacitivityWarning: "We have stopped running the Shoutbox due to your inactivity. If you are back again, please click <span id=(removed)"imback\">here</span>.",
	you_have_new_alerts: "You have new alerts.",

	javascript_resized: "Resized from %1px * %2px to %3px * %4px. Click the image to view the full image.",
	javascript_current: "Showing image {current} of {total}"
	,turn_on_suggestions: "turn on suggestions",turn_off_suggestions: "turn off suggestions",turn_on_suggestions_alt: "Auto-suggest helps you quickly narrow down your search results by suggesting possible matches as you type.",searching: "Searching...",enter_a_search_word: "enter a search word",forums_search_results: "Search Results",message_nothing_found: "Nothing found.",show_more_torrents: "Show More Torrents"
};

var TSUESettings = 
{
	charset: "utf-8",
	memberid: "0",
	membername: "Guest",
	memberTimezone: 1,
	memberDST: 0,
	stKey: "0-1709151150-b7112adce44fb19a73fe792d3237514604d984b3",
	website_title: "TurkTorrent.us",
	website_url: "https://turktorrent.us",
	theme_dir: "https://turktorrent.us/styles/default/",
	website_active: "1",
	website_resize_images_max_width: "665",
	website_resize_images_max_height: "665",
	ajaxHolderID: 'ajaxloader',
	ajaxLoaderImage: '<img src="https://turktorrent.us/styles/default/ajax/fb_ajax-loader.gif" class="ajaxLoaderImage">',
	security_enable_captcha: "1",

	shoutbox_enabled: 1,
	irtm_enabled: 0,
	alerts_enabled: 0,

	pageid: 32,
	pagefile: 'torrents'
};
		//]]>
		</script>
<script type="text/javascript" src="https://turktorrent.us/js.php?lv=2.2&s=jquery,tsue,comments,torrents,login,signup,forgot_password,passwordstrength"></script>
<script type="text/javascript" src="https://turktorrent.us/js/tiny_mce/tiny_mce_gzip.js?lv=2.2"></script>
<script type="text/javascript">tinyMCE_GZ.init({plugins : '-inlinepopups,-smilies,-quote,-tsuecode,-autoresize,-autolink',themes:'tsue',languages:'',disk_cache:true,debug:false});</script>
<script type="text/javascript">
		//<![CDATA[
			tinyMCE.addI18n('en.tsue',
{
	apply: "Apply",
	insert: "Insert",
	update: "Update",
	cancel: "Cancel",
	close: "Close",
	font_size: "Font Size",
	fontdefault: "Font Family",
	bold_desc: "Bold (CTRL+B)",
	italic_desc: "Italic (CTRL+I)",
	underline_desc: "Underline (CTRL+U)",
	striketrough_desc: "Strikethrough",
	justifyleft_desc: "Align left",
	justifycenter_desc: "Align center",
	justifyright_desc: "Align right",
	bullist_desc: "Unordered List",
	numlist_desc: "Ordered List",
	undo_desc: "Undo (CTRL+Z)",
	redo_desc: "Redo (CTRL+Y)",
	link_desc: "Insert/Edit Link",
	unlink_desc: "Unlink",
	image_desc: "Insert/Edit Image",
	removeformat_desc: "Remove formatting",
	cleanup_desc: "Cleanup messy code",
	forecolor_desc: "Select text color",
	quote: "Quote",
	code_desc: "Insert formatted code",
	smilies_desc: "Smilies"
});

tinyMCE.init({ mode:'none', theme:'tsue', language:'', plugins:'-inlinepopups,-smilies,-quote,-tsuecode,-autoresize,-autolink' });
		//]]>
		</script>
<img src="https://turktorrent.us/cron.php?rq=1709151150&amp;lv=2.2" alt width="1" height="1" />
<script src="https://hostixz.com/js/anonymize.js" type="text/javascript"></script>
<script type="text/javascript">
protected_links = "turktorrent.us, plux.me";
auto_anonymize();
</script>
</body>
</html>
2024-02-28 21:12:31.0|Trace|ProwlarrErrorPipeline|Handling Exception
2024-02-28 21:12:31.0|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
2024-02-28 21:12:31.0|Trace|Http|Res: 221 [POST] /api/v1/indexer/test: 400.BadRequest (2106 ms)
2024-02-28 21:12:31.0|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (2106 ms)
```

**Comment by GinoBadouri** [comment]
Nevermind I got it to work :)
It seems I had to properly decode the ```%3D%3D``` part of the to ```==```  of the ```tsue_member``` value.
Furthermore I need to leave out the other two values ```tsue_guest_language=1``` and ```shoutboxChannelID=1```.
