### ISSUE TITLE
NZBStars fails when searching for movie from Radarr

### ISSUE THREAD

**Issue by Warbs816** [Prowlarr/Prowlarr#2057]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When searching for a movie through Radarr, NZBStars returns a failure.

From the logs, it looks as if Radarr/Prowlarr is attempting to perform some sort of IMDB search that NZBStars doesn't recognise.

Searching for, and grabbing the movie directly from Prowlarr works as expected.

Sonarr is not affected, this works as expected.

### Expected Behavior

I expected Prowlarr to use the API to correctly search for the movie requested by Radarr.

### Steps To Reproduce

1. Have NZBStars added as an indexer in Prowlarr
2. Open a movie page in Radarr
3. Perform either an automatic or interactive search
4. NZBStars will then report an error and will not display any results.

### Environment

```markdown
- OS: Raspberry Pi OS Bookworm
- Prowlarr: 1.13.3.4273
- Docker Install: Yes
- Using Reverse Proxy: Yes - Nginx
```

### What branch are you running?

Master

### Trace Logs?

2024-03-06 14:59:20.6|Trace|EventAggregator|IndexerQueryEvent -> HistoryService
2024-03-06 14:59:20.6|Trace|EventAggregator|IndexerQueryEvent <- HistoryService
2024-03-06 14:59:20.6|Debug|ReleaseSearchService|Total of 1 reports were found for Term: [Amsterdam 2022], Offset: 0, Limit: 100, Categories: [2000, 2010, 2030] from 1 indexer(s)
2024-03-06 14:59:20.6|Trace|Http|Res: 664 [GET] /15/api?t=search&cat=2000,2010,2030&extended=1&apikey=(removed)&offset=0&limit=100&q=Amsterdam%202022: 200.OK (1047 ms)
2024-03-06 14:59:21.1|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://nzbstars.com/api?t=movie&extended=1&cat=2030,2040,2050,2060,2000&apikey=(removed)&imdbid=10304142&limit=100&offset=0: 200.OK (110 bytes) (1541 ms)
2024-03-06 14:59:21.1|Trace|Newznab|Unexpected Response content (110 bytes): <?xml version="1.0" encoding="utf-8"?>
<error code="301" description="IMDB information returned is invalid"/>

2024-03-06 14:59:21.1|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IIndexer>
2024-03-06 14:59:21.1|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> -> IndexerStatusController
2024-03-06 14:59:21.1|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> <- IndexerStatusController
2024-03-06 14:59:21.1|Warn|Newznab|https://nzbstars.com/api?t=movie&extended=1&cat=2030,2040,2050,2060,2000&apikey=(removed)&imdbid=10304142&limit=100&offset=0

[v1.13.3.4273] NzbDrone.Core.Indexers.Newznab.NewznabException: IMDB information returned is invalid
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.CheckError(XDocument xdoc, IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Newznab/NewznabRssParser.cs:line 48
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Newznab/NewznabRssParser.cs:line 71
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 514
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, SearchCriteriaBase searchCriteria, Boolean isRecent) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 352
RequestUri: https://nzbstars.com/api?t=movie&extended=1&cat=2030,2040,2050,2060,2000&apikey=(removed)&imdbid=10304142&limit=100&offset=0;StatusCode: OK;ContentType: text/xml; charset=utf-8;ContentLength: 110;ContentSample: <?xml version="1.0" encoding="utf-8"?>
<error code="301" description="IMDB information returned is invalid"/>

2024-03-06 14:59:21.1|Trace|EventAggregator|Publishing IndexerQueryEvent

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [x] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
This is something you'll need to take up with nzbstars for not being newznab compliant
