### ISSUE TITLE
Can't login into SkTorrents?

### ISSUE THREAD

**Issue by SonGokussj4** [Prowlarr/Prowlarr#2059]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Indexer fails on login
```
prowlarr  |  -- : Unable to connect to indexer, indexer's server is unavailable. Try again later. HTTP request failed:
[500:InternalServerError] [GET] at [https://sktorrent.eu/torrent/login.php]
```

### Expected Behavior

Test should be OK

Is this a problem with Prowlarr or in my setup? It worked until a few weeks ago. Not sure when it stopped.

### Steps To Reproduce

1. In the prowlarr, add SkTorrent as indexer
2. Add auth (user, pass)
3. Select base URL (https://sktorrent.eu/)
4. Click on Test

### Environment

```markdown
- OS: Docker (Synology NAS) through Docker Compose
- Prowlarr: 1.13.3.4273 — Feb 11 2024
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: All
```

### What branch are you running?

Master

### Trace Logs?

```
prowlarr  | [Warn] IndexerHttpClient: HTTP Error - Res: HTTP/1.0 [GET] https://sktorrent.eu/torrent/login.php: 500.InternalServerError (13165 bytes)
prowlarr  | <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
prowlarr  | <!-- Mikrodaten-Markup hinzugefügt von Google Strukturierte Daten: Markup-Hilfe -->
prowlarr  | <html lang="sk"><head prefix="og: https://ogp.me/ns#">
prowlarr  | <meta name="viewport" content="width=device-width">
prowlarr  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
prowlarr  | <META NAME="Copyright" CONTENT="sktorrent.eu" />
prowlarr  | <META NAME="Revisit" CONTENT="After 1 days" />
prowlarr  | <META NAME="Description" CONTENT="Najnovsie HD Filmy online s CZ/SK dabing, serial, hry, knihy a casopisy. Komunita pre ludi ktory odosielaju a stahuju online filmy s hodnotenim CSFD" />
prowlarr  | <META NAME="Abstract" CONTENT="Volny torrent tracker na zdielanie filmov, serialov, hier a knih" />
prowlarr  | <META NAME="audience" CONTENT="Alle" />
prowlarr  | <META NAME="Robots" CONTENT="ALL,FOLLOW" />
prowlarr  | <META NAME="Language" CONTENT="sk" />
prowlarr  | <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
prowlarr  | <meta name="B-verify" content="c873ae4a3f393e53b436d07a5cfaf696ae700431" />
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |   <!--script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async='async'></script-->
prowlarr  |   <script>
prowlarr  |     var OneSignal = window.OneSignal || [];
prowlarr  |     OneSignal.push(["init", {
prowlarr  |       appId: "40c5b400-a8fd-454c-b394-d1b5a9de0649",
prowlarr  |       allowLocalhostAsSecureOrigin: true,
prowlarr  |       autoRegister: true, /* Set to true to automatically prompt visitors */
prowlarr  |       httpPermissionRequest: {
prowlarr  |         enable: true
prowlarr  |       },
prowlarr  |       notifyButton: {
prowlarr  |           enable: false /* Set to false to hide */
prowlarr  |       }
prowlarr  |     OneSignal.push(["sendTags", {id: 1, level: 1}]);
prowlarr  |   </script>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <!-- Google tag (gtag.js) -->
prowlarr  | <script async src="https://www.googletagmanager.com/gtag/js?id=G-GQP9ZGYTXS"></script>
prowlarr  | <script>
prowlarr  |   window.dataLayer = window.dataLayer || [];
prowlarr  |   gtag('js', new Date());
prowlarr  |
prowlarr  |   gtag('config', 'G-GQP9ZGYTXS');
prowlarr  | </script>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <link rel="icon" href="https://announce.sktorrent.eu/torrent/favicon.ico" type="image/ico" />
prowlarr  | <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/minified/jquery-ui.min.css" type="text/css" />
prowlarr  | <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
prowlarr  | <script src="//code.jquery.com/jquery-latest.js"></script>
prowlarr  | <link rel="stylesheet" type="text/css" href="ddajaxsidepanel.css" />
prowlarr  | <link rel="stylesheet" type="text/css" href="interstitial.css">
prowlarr  | <link rel="stylesheet" href="css/site.css">
prowlarr  |
prowlarr  |
prowlarr  |             <script src="//raw.githubusercontent.com/aFarkas/html5shiv/master/dist/html5shiv.min.js"></script>
prowlarr  |     <![endif]-->
prowlarr  |         <div id="container">
prowlarr  |           <header>
prowlarr  |             <div id="mini-notification">
prowlarr  |                 <p>Tvoj ú&#269;et nieje VIP.<br>Preto sú tvoje funkcie a mo&#382;nosti zna&#269;ne obmedzené.<br><a href=forum.php?action=viewtopic&topicid=20#top>Pre aktiváciu VIP klikni sem.</a></p>
prowlarr  |             </div>
prowlarr  |         </div>
prowlarr  |     <!-- end of #container -->
prowlarr  |
prowlarr  |
prowlarr  | <title>Sk-CzTorrent | stiahni si HD Filmy online - Login</title>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <link rel="stylesheet" href=./style/base/torrent.css type="text/css" /><script language="JavaScript" src="overlib.js" type="text/javascript"></script>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | </head>
prowlarr  |
prowlarr  | <button onclick="topFunction()" id="myBtn" title="Go to top">&#8593; Top &#8593;</button>
prowlarr  |
prowlarr  | <script>
prowlarr  | //Get the button
prowlarr  | var mybutton = document.getElementById("myBtn");
prowlarr  |
prowlarr  | // When the user scrolls down 20px from the top of the document, show the button
prowlarr  | window.onscroll = function() {scrollFunction()};
prowlarr  |
prowlarr  | function scrollFunction() {
prowlarr  |   if (document.body.scrollTop > 200 || document.documentElement.scrollTop > 200) {
prowlarr  |     mybutton.style.display = "block";
prowlarr  |   } else {
prowlarr  |     mybutton.style.display = "none";
prowlarr  |   }
prowlarr  | }
prowlarr  |
prowlarr  | // When the user clicks on the button, scroll to the top of the document
prowlarr  | function topFunction() {
prowlarr  |   document.body.scrollTop = 0;
prowlarr  |   document.documentElement.scrollTop = 0;
prowlarr  | }
prowlarr  | </script>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <center>
prowlarr  | <table width="950" height="100%"  border="0" bgcolor="#BEDBEB">
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <h1>Cz-SkTorrent open Tracker, na volné zdieľanie súborov. Pridajte sa k našej komunite a získajte prístup k tisícom torrentov.</h1>
prowlarr  | <h2>
prowlarr  | <li>vysoká rýchlosť
prowlarr  | <li>úplne zdarma
prowlarr  | <li>prevažne Slovenská a Česká scéna
prowlarr  | <li>ste tu s nami už 10 rokov - Ďakujeme
prowlarr  | </h2>
prowlarr  |
prowlarr  | </td>
prowlarr  | </tr>
prowlarr  | <tr><td height="100" colspan="2">
prowlarr  |
prowlarr  |
prowlarr  | <script type="text/javascript" language="JavaScript">
prowlarr  | function ShowHide(id,id1) {
prowlarr  |     obj = document.getElementsByTagName("div");
prowlarr  |     if (obj[id].style.display == 'block'){
prowlarr  |      obj[id].style.display = 'none';
prowlarr  |      obj[id1].style.display = 'block';
prowlarr  |     }
prowlarr  |     else {
prowlarr  |      obj[id].style.display = 'block';
prowlarr  |      obj[id1].style.display = 'none';
prowlarr  |     }
prowlarr  | }
prowlarr  |
prowlarr  | </script>
prowlarr  |
prowlarr  |
prowlarr  |     <table class=lista width=100%>
prowlarr  |     <tr>
prowlarr  | <td class=header align=center>Vitaj Guest
prowlarr  | <a href=login.php>(Login)</a></td>
prowlarr  | <td class=header align=center>
prowlarr  |        <a href=/torrent/forum.php?action=viewtopic&topicid=21 title="Ako stahovat torrenty">Ako stahovat<br>torrenty?</a>
prowlarr  |        </td>
prowlarr  |
prowlarr  |        <td class=header>
prowlarr  |        <a href=torrents_v2.php?active=0>Torrenty</a>:
prowlarr  |        <br><a href=torrents.php?active=0><font color=brown size=1>v1 textová</font></a>
prowlarr  |        <br><a href=torrents_v2.php?active=0><font color=brown size=1>v2 obrázková</font></a>
prowlarr  |        </td>
prowlarr  | <td class=header align=center><a href=forum.php>Forum</a>
prowlarr  |          <br><a href=forum.php?action=viewforum&forumid=3><font size=1>Pravidlá</font></a><br>
prowlarr  |              <a href=https://social.sktorrent.eu target="_blank">SkTSocial</a></td>
prowlarr  | <td class=header align=center><a href="forum.php?action=viewtopic&topicid=27&page=1#117">BitTorrent<br>klient</a></td>
prowlarr  | <td class=header align=center><a href="forum.php?action=viewtopic&topicid=20#prispevok"><img src="images/paypal.gif"></a></td>
prowlarr  |    </tr>
prowlarr  | <div style="position:absolute; left:50%; top:150px; margin-left:480px">
prowlarr  | <img src=//sktorrent.eu/torrent/images/bannery/120x600.jpg>
prowlarr  | <!--a href=https://stake.bet/?c=c6363a8f><img src=//sktorrent.eu/torrent/images/Stake_Casino_160x600.gif></a-->
prowlarr  | </div>
prowlarr  |
prowlarr  |
prowlarr  |             </td>
prowlarr  |     </tr>
prowlarr  | </table></td>
prowlarr  | </tr>
prowlarr  | </table>
prowlarr  |
prowlarr  | <p align=center><table width=800><tr><td width=800 align=center><font size=1>
prowlarr  |     Na serveru se nenalézají zádne soubory.
prowlarr  |     Za odkazy jsou výhradně zodpovědní uzivatelé a návstěvníci tohoto trackeru.
prowlarr  |     Administrátor není zodpovědný za pridaný obsah ani za skody zpusobené uzivateli.
prowlarr  |     Nesmíte pouzívat tuto webovou stránku pro distribuovaní nebo download zádného materiálu pokud nemáte povolení od príslusného vlastníka práv.
prowlarr  |     Uzivatelé jsou zodpovědní za dodrzování těchto pravidel a podmínek. Owner má právo kdykoliv změnit pravidla tohoto trackeru.
prowlarr  |     </font><br><br></td></tr></table>[ Script trval: 0.007 sec. ] - [ GZIP: enabled ]<br />Je zhruba 15:53<br></p><a href="//www.toplist.cz/internet" target="_top"><img src="//toplist.cz/count.asp?id=1599472&logo=mc" border="0" alt="TOPlist" width="88" height="60"/></a>
prowlarr  | [Warn] Cardigann: Unable to connect to indexer
prowlarr  |
prowlarr  | [v1.13.3.4273] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://sktorrent.eu/torrent/login.php]
prowlarr  |    at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 41
prowlarr  |    at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.GetConfigurationForSetup(Boolean automaticLogin) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 659
prowlarr  |    at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.DoLogin() in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 266
prowlarr  |    at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.DoLogin() in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 191
prowlarr  |    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 580
prowlarr  |    at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 671
prowlarr  | <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
prowlarr  | <!-- Mikrodaten-Markup hinzugefügt von Google Strukturierte Daten: Markup-Hilfe -->
prowlarr  | <html lang="sk"><head prefix="og: https://ogp.me/ns#">
prowlarr  | <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
prowlarr  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
prowlarr  | <meta name="viewport" content="width=device-width">
prowlarr  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
prowlarr  | <meta name="msvalidate.01" content="8279D9FD1AA9EFCBEEFEC9193790DDD7" />
prowlarr  | <META NAME="Title" CONTENT="Sk-CzTorrent | stiahni si HD Filmy online" />
prowlarr  | <META NAME="Author" CONTENT="Martin Zich" />
prowlarr  | <META NAME="Publisher" CONTENT="sktorrent.eu" />
prowlarr  | <META NAME="Copyright" CONTENT="sktorrent.eu" />
prowlarr  | <META NAME="Revisit" CONTENT="After 1 days" />
prowlarr  | <META NAME="Description" CONTENT="Najnovsie HD Filmy online s CZ/SK dabing, serial, hry, knihy a casopisy. Komunita pre ludi ktory odosielaju a stahuju online filmy s hodnotenim CSFD" />
prowlarr  | <META NAME="Abstract" CONTENT="Volny torrent tracker na zdielanie filmov, serialov, hier a knih" />
prowlarr  | <META NAME="audience" CONTENT="Alle" />
prowlarr  | <META NAME="Robots" CONTENT="ALL,FOLLOW" />
prowlarr  | <META NAME="Language" CONTENT="sk" />
prowlarr  | <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
prowlarr  | <meta name="B-verify" content="c873ae4a3f393e53b436d07a5cfaf696ae700431" />
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |   <!--script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async='async'></script-->
prowlarr  |   <script>
prowlarr  |     var OneSignal = window.OneSignal || [];
prowlarr  |     OneSignal.push(["init", {
prowlarr  |       appId: "40c5b400-a8fd-454c-b394-d1b5a9de0649",
prowlarr  |       allowLocalhostAsSecureOrigin: true,
prowlarr  |       autoRegister: true, /* Set to true to automatically prompt visitors */
prowlarr  |       httpPermissionRequest: {
prowlarr  |         enable: true
prowlarr  |       },
prowlarr  |       notifyButton: {
prowlarr  |           enable: false /* Set to false to hide */
prowlarr  |       }
prowlarr  |     }]);
prowlarr  |     OneSignal.push(["sendTags", {id: 1, level: 1}]);
prowlarr  |   </script>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <!-- Google tag (gtag.js) -->
prowlarr  | <script async src="https://www.googletagmanager.com/gtag/js?id=G-GQP9ZGYTXS"></script>
prowlarr  | <script>
prowlarr  |   window.dataLayer = window.dataLayer || [];
prowlarr  |   function gtag(){dataLayer.push(arguments);}
prowlarr  |   gtag('js', new Date());
prowlarr  |
prowlarr  |   gtag('config', 'G-GQP9ZGYTXS');
prowlarr  | </script>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <link rel="icon" href="https://announce.sktorrent.eu/torrent/favicon.ico" type="image/ico" />
prowlarr  | <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/minified/jquery-ui.min.css" type="text/css" />
prowlarr  | <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
prowlarr  | <script src="//code.jquery.com/jquery-latest.js"></script>
prowlarr  | <link rel="stylesheet" type="text/css" href="ddajaxsidepanel.css" />
prowlarr  | <link rel="stylesheet" type="text/css" href="interstitial.css">
prowlarr  | <link rel="stylesheet" href="css/site.css">
prowlarr  | <script src="ddajaxsidepanel.js"></script>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |     <!-- Popcontainer navrchu -->
prowlarr  |     <!--[if IE]>
prowlarr  |             <script src="//raw.githubusercontent.com/aFarkas/html5shiv/master/dist/html5shiv.min.js"></script>
prowlarr  |     <![endif]-->
prowlarr  |         <div id="container">
prowlarr  |           <header>
prowlarr  |             <div id="mini-notification">
prowlarr  |                 <p>Tvoj ú&#269;et nieje VIP.<br>Preto sú tvoje funkcie a mo&#382;nosti zna&#269;ne obmedzené.<br><a href=forum.php?action=viewtopic&topicid=20#top>Pre aktiváciu VIP klikni sem.</a></p>
prowlarr  |             </div>
prowlarr  |         </div>
prowlarr  |     <!-- end of #container -->
prowlarr  |
prowlarr  |
prowlarr  | <title>Sk-CzTorrent | stiahni si HD Filmy online - Login</title>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <link rel="stylesheet" href=./style/base/torrent.css type="text/css" /><script language="JavaScript" src="overlib.js" type="text/javascript"></script>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | </head>
prowlarr  |
prowlarr  | <button onclick="topFunction()" id="myBtn" title="Go to top">&#8593; Top &#8593;</button>
prowlarr  |
prowlarr  | <script>
prowlarr  | //Get the button
prowlarr  | var mybutton = document.getElementById("myBtn");
prowlarr  |
prowlarr  | // When the user scrolls down 20px from the top of the document, show the button
prowlarr  | window.onscroll = function() {scrollFunction()};
prowlarr  |
prowlarr  | function scrollFunction() {
prowlarr  |   if (document.body.scrollTop > 200 || document.documentElement.scrollTop > 200) {
prowlarr  |     mybutton.style.display = "block";
prowlarr  |   } else {
prowlarr  |     mybutton.style.display = "none";
prowlarr  |   }
prowlarr  | }
prowlarr  |
prowlarr  | // When the user clicks on the button, scroll to the top of the document
prowlarr  | function topFunction() {
prowlarr  |   document.body.scrollTop = 0;
prowlarr  |   document.documentElement.scrollTop = 0;
prowlarr  | }
prowlarr  | </script>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <center>
prowlarr  | <table width="950" height="100%"  border="0" bgcolor="#BEDBEB">
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <h1>Cz-SkTorrent open Tracker, na volné zdieľanie súborov. Pridajte sa k našej komunite a získajte prístup k tisícom torrentov.</h1>
prowlarr  | <h2>
prowlarr  | <li>vysoká rýchlosť
prowlarr  | <li>úplne zdarma
prowlarr  | <li>prevažne Slovenská a Česká scéna
prowlarr  | <li>ste tu s nami už 10 rokov - Ďakujeme
prowlarr  | </h2>
prowlarr  |
prowlarr  | </td>
prowlarr  | </tr>
prowlarr  | <tr><td height="100" colspan="2">
prowlarr  |
prowlarr  |
prowlarr  | <script type="text/javascript" language="JavaScript">
prowlarr  | function ShowHide(id,id1) {
prowlarr  |     obj = document.getElementsByTagName("div");
prowlarr  |     if (obj[id].style.display == 'block'){
prowlarr  |      obj[id].style.display = 'none';
prowlarr  |      obj[id1].style.display = 'block';
prowlarr  |     }
prowlarr  |     else {
prowlarr  |      obj[id].style.display = 'block';
prowlarr  |      obj[id1].style.display = 'none';
prowlarr  |     }
prowlarr  | }
prowlarr  |
prowlarr  | </script>
prowlarr  |
prowlarr  |
prowlarr  |     <table class=lista width=100%>
prowlarr  |     <tr>
prowlarr  | <td class=header align=center>Vitaj Guest
prowlarr  | <a href=login.php>(Login)</a></td>
prowlarr  |        <a href=/torrent/forum.php?action=viewtopic&topicid=21 title="Ako stahovat torrenty">Ako stahovat<br>torrenty?</a>
prowlarr  |        </td>
prowlarr  |
prowlarr  |        <td class=header>
prowlarr  |        <a href=torrents_v2.php?active=0>Torrenty</a>:
prowlarr  |        <br><a href=torrents.php?active=0><font color=brown size=1>v1 textová</font></a>
prowlarr  |        <br><a href=torrents_v2.php?active=0><font color=brown size=1>v2 obrázková</font></a>
prowlarr  |        </td>
prowlarr  | <td class=header align=center><a href=forum.php?action=viewtopic&topicid=19><font size=1>Ako sa stat<br>Uploaderom</font></a></td>
prowlarr  | <td class=header align=center><a href=//online.sktorrent.eu>Online<br>Filmy</a></td>
prowlarr  | <td class=header align=center><a href=forum.php>Forum</a>
prowlarr  |          <br><a href=forum.php?action=viewforum&forumid=3><font size=1>Pravidlá</font></a><br>
prowlarr  |              <a href=https://social.sktorrent.eu target="_blank">SkTSocial</a></td>
prowlarr  | <td class=header align=center><a href="forum.php?action=viewtopic&topicid=27&page=1#117">BitTorrent<br>klient</a></td>
prowlarr  | <td class=header align=center><a href="forum.php?action=viewtopic&topicid=20#prispevok"><img src="images/paypal.gif"></a></td>
prowlarr  |    </tr>
prowlarr  |    </table>
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  |
prowlarr  | <div style="position:absolute; left:50%; top:770px; margin-left:480px">
prowlarr  |
prowlarr  |
prowlarr  | <!-- i-Reklama - Ad Display Code name=160 -->
prowlarr  | <div id="adm-container-12"></div><script data-cfasync="false" type="text/javascript" async src="//i-reklama.sk/display/items.php?12&0&160&600&4&0&0"></script>
prowlarr  | <!-- i-Reklama - Ad Display Code  -->
prowlarr  |
prowlarr  | [Warn] ProwlarrErrorPipeline: Invalid request Validation failed:
prowlarr  |  -- : Unable to connect to indexer, indexer's server is unavailable. Try again later. HTTP request failed: [500:InternalServerError] [GET] at [https://sktorrent.eu/torrent/login.php]
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Invalid report; console output are not the required trace logs. Additionally, lying and saying the wiki was followed for providing trace logs when it is clear the wiki was never read is an extremely poor practice.
