### ISSUE TITLE
prowlarr not trusting self signed certificate

### ISSUE THREAD

**Issue by dudomatik** [Prowlarr/Prowlarr#2125]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I created a self signed certificate for sonarr/radarr and prowlarr doesn't connect to the app. When i try to add app sonarr/radarr to prowlarr using https an error occurs: Unable to complete application test, cannot connect to Sonarr. The SSL connection could not be established, see inner exception.

It works using http.

### Expected Behavior

connection established

### Steps To Reproduce

1. Environment:
- docker on debian, linuxserver images of prowlarr/sonarr/radarr
2.  container ports for http and https mapped in docker compose files, accessible with browser
created self signed cert using `openssl req \
       -newkey rsa:2048 -nodes -keyout sonarr.key \
       -x509 -days 3650 -out sonarr.crt` and `openssl pkcs12 -export -in sonarr.crt -inkey sonarr.key -out sonarr.pfx`
3. added cert and pw to sonarr/radarr instances
4. try to connect to sonarr/radarr server using https adress and port

### Environment

```markdown
- OS: debian
- Prowlarr:     1.16.2.4435
- Docker Install: 26.1.1,
- Using Reverse Proxy: no
- Browser: Mozilla Firefox 125.0.3
```

### What branch are you running?

Master

### Trace Logs?

[Error] X509CertificateValidationService: Certificate validation for 192.168.0.121 failed. RemoteCertificateNameMismatch, RemoteCertificateChainErrors 
[Warn] Radarr: Unable to complete application test 

[v1.16.2.4435] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 120
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.Applications.Radarr.RadarrV3Proxy.Execute[TResource](HttpRequest request) in ./Prowlarr.Core/Applications/Radarr/RadarrV3Proxy.cs:line 227
   at NzbDrone.Core.Applications.Radarr.RadarrV3Proxy.GetIndexerSchema(RadarrSettings settings) in ./Prowlarr.Core/Applications/Radarr/RadarrV3Proxy.cs:line 80
   at NzbDrone.Core.Applications.Radarr.Radarr.<>c__DisplayClass12_0.<BuildRadarrIndexer>b__0() in ./Prowlarr.Core/Applications/Radarr/Radarr.cs:line 223
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Prowlarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Applications.Radarr.Radarr.BuildRadarrIndexer(IndexerDefinition indexer, IndexerCapabilities indexerCapabilities, DownloadProtocol protocol, Int32 id) in ./Prowlarr.Core/Applications/Radarr/Radarr.cs:line 223
   at NzbDrone.Core.Applications.Radarr.Radarr.Test() in ./Prowlarr.Core/Applications/Radarr/Radarr.cs:line 54

[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- BaseUrl: Unable to complete application test, cannot connect to Radarr. The SSL connection could not be established, see inner exception. 

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- you cannot use an HTTPS certificate for an ip address
- there's just about no reason to do HTTPS between the applications. Anyone with a reasonable reason to do so would then mean they believe their entire local network is compromised and have MITM attacks
