### ISSUE TITLE
Avistaz validation error

### ISSUE THREAD

**Issue by DominicMCN** [Prowlarr/Prowlarr#2129]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Avistaz cannot be added as an indexer. Log:

```
[Warn] AvistaZ: Unable to connect to indexer 
[v1.16.2.4435] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status Unauthorized code from indexer request
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazParserBase.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazParserBase.cs:line 38
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 549
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 727
RequestUri: https://avistaz.to/api/v1/jackett/torrents?in=1&type=0&limit=50&search=;StatusCode: Unauthorized;ContentType: text/html; charset=utf-8;ContentLength: 630;ContentSample: <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>                body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
                .container { margin: 30px; max-width: 600px; }
                h1 { color: #dc3545; font-size: 24px; }</style>
    </head>
    <body>
                        <div class="container">
                    <h1>Whoops, looks like something went wrong.</h1>
                </div>
    </body>
</html>
[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Unauthorized code from indexer request 
[Warn] AvistaZ: Unable to connect to indexer 
[v1.16.2.4435] System.Exception: Invalid response from AvistaZ, the response is not valid JSON
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazBase.GetToken() in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazBase.cs:line 139
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazBase.TestConnection() in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazBase.cs:line 93
[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details 
[Warn] AvistaZ: HTTP Error - Res: HTTP/2.0 [GET] https://avistaz.to/api/v1/jackett/torrents?in=1&type=0&limit=50&search=: 401.Unauthorized (630 bytes)
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>                body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
                .container { margin: 30px; max-width: 600px; }
                h1 { color: #dc3545; font-size: 24px; }</style>
    </head>
    <body>
                        <div class="container">
                    <h1>Whoops, looks like something went wrong.</h1>
                </div>
    </body>
</html> 
```

### Expected Behavior

Adding Avistaz successfully

### Steps To Reproduce

Adding avistaz with correct username, password and PID

### Environment

```markdown
- OS: hotio image
- Prowlarr: 1.16.2.4435
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

Enabled trace but doesn't seem like anything was logged at trace level

```
[Warn] AvistaZ: Unable to connect to indexer 
[v1.16.2.4435] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status Unauthorized code from indexer request
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazParserBase.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazParserBase.cs:line 38
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 549
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 727
RequestUri: https://avistaz.to/api/v1/jackett/torrents?in=1&type=0&limit=50&search=;StatusCode: Unauthorized;ContentType: text/html; charset=utf-8;ContentLength: 630;ContentSample: <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>                body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
                .container { margin: 30px; max-width: 600px; }
                h1 { color: #dc3545; font-size: 24px; }</style>
    </head>
    <body>
                        <div class="container">
                    <h1>Whoops, looks like something went wrong.</h1>
                </div>
    </body>
</html>
[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Unauthorized code from indexer request 
[Warn] AvistaZ: Unable to connect to indexer 
[v1.16.2.4435] System.Exception: Invalid response from AvistaZ, the response is not valid JSON
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazBase.GetToken() in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazBase.cs:line 139
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazBase.TestConnection() in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazBase.cs:line 93
[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details 
[Warn] AvistaZ: HTTP Error - Res: HTTP/2.0 [GET] https://avistaz.to/api/v1/jackett/torrents?in=1&type=0&limit=50&search=: 401.Unauthorized (630 bytes)
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>                body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
                .container { margin: 30px; max-width: 600px; }
                h1 { color: #dc3545; font-size: 24px; }</style>
    </head>
    <body>
                        <div class="container">
                    <h1>Whoops, looks like something went wrong.</h1>
                </div>
    </body>
</html> 
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by DominicMCN** [comment]
I can't join discord, it says invitation link expired
