### ISSUE TITLE
DesiTorrents (API) - Changed

### ISSUE THREAD

**Issue by chiragkrishna** [Prowlarr/Prowlarr#2154]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Indexer is not working as the api has changed

### Expected Behavior

indexer should work

### Environment

```markdown
{"message":"The API has moved. Please use the new API ROUTE PREFIX: \/api\/v1\/"}
```

### What branch are you running?

Master

### Trace Logs?

[v1.18.0.4543] NzbDrone.Core.Indexers.Exceptions.IndexerException: Error Parsing Rows Selector
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannParser.cs:line 121
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 604
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 855
RequestUri: https://torrent.desi/api/torrents/filter?sortField=created_at&sortDirection=desc&perPage=100;StatusCode: OK;ContentType: application/json;ContentLength: 81;ContentSample: {"message":"The API has moved. Please use the new API ROUTE PREFIX: \/api\/v1\/"}

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by ilike2burnthing** [comment]
https://github.com/Prowlarr/Indexers/commit/4806f61c19906c5a02a80f3747a9227a18ac568a

Manually run `Indexer Definition Update` task.
