### ISSUE TITLE
NZBindex (API updated)

### ISSUE THREAD

**Issue by YESIHACK** [Prowlarr/Prowlarr#2177]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

API for Usenet NZBindex has been updated. prowlarr/sonar/radarr/etc.. needs to be updated to support the V3 API 

Type {Torrent|Usenet}: Usenet
Tracker {Name}: NZBindex
URL {URL}:https://nzbindex.com/api/v3

Additional Information: Please update the NZBindex API to v3. I am unable to connect via prowler, sonar, radar, etc.

### Describe the solution you'd like

Updating API to use V3 api

### Describe alternatives you've considered

None

### Anything else?

https://nzbindex.com/api/v3

**Comment by bakerboy448** [comment]
We already use v3. Invalid request
https://github.com/Prowlarr/Prowlarr/blob/d1084039b3d9629cfc8a93f2470ddd950ede66e3/src/NzbDrone.Core/Indexers/Definitions/NzbIndex.cs#L1097

**Comment by YESIHACK** [comment]
`: Unable to connect to indexer, invalid credentials. HTTP request failed: [403:Forbidden] [GET] at [https://api.nzbindex.com/api?t=caps&apikey=(removed)
2024-07-14 22:25:27.4|Warn|Newznab|Unable to connect to indexer

[v4.0.6.1805] System.Xml.XmlException: 'defer' is an unexpected token. The expected token is '='. Line 8, position 719.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in ./Sonarr.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs:line 96
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in ./Sonarr.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs:line 91
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Sonarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in ./Sonarr.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs:line 37
   at NzbDrone.Core.Indexers.Newznab.NewznabRequestGenerator.GetRecentRequests() in ./Sonarr.Core/Indexers/Newznab/NewznabRequestGenerator.cs:line 197
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 376
`

**Comment by YESIHACK** [comment]
This is the error I'm getting

**Comment by YESIHACK** [comment]
Currently on prowlarr Version 1.20.1.4603
