### ISSUE TITLE
Error on startup - rantop.org

### ISSUE THREAD

**Issue by shomilsaini** [Prowlarr/Prowlarr#2223]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

on boot - logs show error

### Expected Behavior

should be a clean boot

### Steps To Reproduce

run the container

### Environment

```markdown
- OS: Unraid
- Using Reverse Proxy: NO
- Browser: Chrome
- Version 1.23.1.4708
- Package Version 1.23.1.4708-1 by prowlarr
- .NET Yes (6.0.32)
- Docker Yes
- Database Sqlite 3.46.0
```

### What branch are you running?

Master

### Trace Logs?
```
[Info] AppFolderInfo: Data directory is being overridden to [/config/prowlarr] 

2024-09-13 21:45:07,822 DEBG 'start-script' stdout output:
[Info] MigrationController: *** Migrating data source=/config/prowlarr/prowlarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 

2024-09-13 21:45:08,070 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrating 

2024-09-13 21:45:08,088 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: PerformDBOperation  

2024-09-13 21:45:08,089 DEBG 'start-script' stdout output:
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Performing DB Operation 

2024-09-13 21:45:08,221 DEBG 'start-script' stdout output:
[Info] DatabaseEngineVersionCheck: SQLite 3.46.0 

2024-09-13 21:45:08,225 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: => 0.133399s 

2024-09-13 21:45:08,226 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrated 

2024-09-13 21:45:08,226 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: => 0.1373849s 

2024-09-13 21:45:08,296 DEBG 'start-script' stdout output:
[Info] MigrationController: *** Migrating data source=/config/prowlarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 

2024-09-13 21:45:08,300 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrating 

2024-09-13 21:45:08,301 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: PerformDBOperation  

2024-09-13 21:45:08,301 DEBG 'start-script' stdout output:
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Performing DB Operation 

2024-09-13 21:45:08,305 DEBG 'start-script' stdout output:
[Info] DatabaseEngineVersionCheck: SQLite 3.46.0 

2024-09-13 21:45:08,306 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0046779s 

2024-09-13 21:45:08,306 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrated 

2024-09-13 21:45:08,306 DEBG 'start-script' stdout output:
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0049132s 

2024-09-13 21:45:08,905 DEBG 'start-script' stdout output:
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:9696 

2024-09-13 21:45:09,187 DEBG 'start-script' stdout output:
[Info] CommandExecutor: Starting 3 threads for tasks. 

2024-09-13 21:45:09,415 DEBG 'start-script' stdout output:
[Info] ManagedHttpDispatcher: IPv4 is available: True, IPv6 will be disabled 

2024-09-13 21:45:09,973 DEBG 'start-script' stdout output:
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 

2024-09-13 21:45:09,974 DEBG 'start-script' stdout output:
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: / 

2024-09-13 21:48:11,586 DEBG 'start-script' stdout output:
[Warn] Cardigann: Redirected to https://www.rantop.org/ from indexer request 

2024-09-13 21:48:11,644 DEBG 'start-script' stdout output:
[Warn] Cardigann: Unable to connect to indexer 

[v1.23.1.4708] NzbDrone.Core.Indexers.Exceptions.IndexerException: Redirected to https://www.rantop.org/ from indexer request
2024-09-13 21:48:11,644 DEBG 'start-script' stdout output:

   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 606
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 852
RequestUri: https://www.zetorrents.in/;StatusCode: Moved;ContentType: text/html; charset=iso-8859-1;ContentLength: 297;ContentSample: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.rantop.org">here</a>.</p>
<hr>
<address>Apache Server at www.zetorrents.in Port 80</address>
</body></html>
```
### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by shomilsaini** [comment]
This is not a support request, your application is throwing error because of hard-coded website which has moved domains.
Thanks

**Comment by bakerboy448** [comment]
- support issue, not a bug
- Container logs are not prowlarr logs - invalid report
- The wiki was not read nor followed - please don't check a box simply because it is required and you didn't act on it
- indexer errors are generally not bugs - invalid report
- Prowlarr is running just fine. Report is invalid as the issue reported does not exist

**Comment by bakerboy448** [comment]
- zetorrents url updated, restart prowlarr https://github.com/Prowlarr/Indexers/commit/e0a33a4fc52fd7879dd53a4c0aaa8b87c8e18716
- for rantop open an issue on Prowlarr/Indexers or Jackett/Jackett; alternatively simply PR the new URL and move the current invalid url to legacylinks

**Comment by shomilsaini** [comment]
ok
