### ISSUE TITLE
unable to connect ygg

### ISSUE THREAD

**Issue by behead974** [Prowlarr/Prowlarr#2233]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hello,
it was still working 3 days ago, YGG no longer uses Cloudflare, so there's no need for FlareSolverr anymore, yet it's impossible to connect.

error:
Unable to connect to indexer, check the log above the ValidationFailure for more details. HTTP request failed: [403:Forbidden] [GET] at [https://www.ygg.re/auth/login]

### Expected Behavior

How to fix the problem?

### Environment

```markdown
- OS: ubuntu 20.04
- Prowlarr: 1.24.3.4754
- Docker Install: yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. HTTP request failed: [403:Forbidden] [GET] at [https://www.ygg.re/auth/login]

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by behead974** [comment]
The problem affects all Ygg users

**Comment by behead974** [comment]
Sorry, I didn't see that they had reactivated the Cloudflare protection. Thank you.

**Comment by ocervell** [comment]
@behead974 can you please reopen ?

Here are the trace logs you asked for:
```

nas-prowlarr-1  | [Info] Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler: AuthenticationScheme: API was challenged.
nas-prowlarr-1  | [Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [POST] http://192.168.1.18:8191/v1: 500.InternalServerError (182 bytes)
nas-prowlarr-1  | {"status": "error", "message": "Error: Error solving the challenge. Timeout after 70.0 seconds.", "startTimestamp": 1731237727109, "endTimestamp": 1731237798158, "version": "3.3.10"}
nas-prowlarr-1  | [Warn] Cardigann: Request for YGGtorrent failed with exception 'HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.1.18:8191/v1]'. Retrying in 2.5236401s.
nas-prowlarr-1  |
nas-prowlarr-1  | [v1.23.1.4708] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.1.18:8191/v1]
nas-prowlarr-1  |    at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
nas-prowlarr-1  |    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
nas-prowlarr-1  |    at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 57
nas-prowlarr-1  |    at NzbDrone.Core.Indexers.IndexerHttpClient.<>c.<PostResponse>b__6_0(HttpResponse current, IIndexerProxy selectedProxy) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
nas-prowlarr-1  |    at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
nas-prowlarr-1  |    at NzbDrone.Core.Indexers.IndexerHttpClient.PostResponse(HttpResponse response, IList`1 selectedProxies) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
nas-prowlarr-1  |    at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 43
nas-prowlarr-1  |    at NzbDrone.Core.Indexers.HttpIndexerBase`1.<>c.<<FetchIndexerResponse>b__57_0>d.MoveNext() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 661
nas-prowlarr-1  | --- End of stack trace from previous location ---
nas-prowlarr-1  |    at Polly.ResiliencePipeline.<>c__9`2.<<ExecuteAsync>b__9_0>d.MoveNext()
```
