### ISSUE TITLE
exitorrent.org downloading issue

### ISSUE THREAD

**Issue by lisekxd1234** [Prowlarr/Prowlarr#2241]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to download torrent from https://exitorrent.org/ i'm getting error 404 not found.

### Expected Behavior

make it work

### Environment

```markdown
- OS: Ubuntu 18.04
- Prowlarr: 1.24.3.4754
- Docker Install: Yes
- Using Reverse Proxy: no
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

2024-10-07 08:41:15.7|Warn|IndexerHttpClient|HTTP Error - Res: HTTP/1.1 [GET] https://exitorrent.org/return%20downloadTorrent('223678',%20'Hold.Your.Breath.2024.MULTi.2160p.DSNP.WEB-DL.DV.HDR.HEVC-CiNEMAET.mkv.torrent',%20'FL');: 404.NotFound (277 bytes)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.56 (Debian) Server at exitorrent.org Port 443</address>
</body></html>

2024-10-07 08:41:15.7|Error|Cardigann|Downloading file for release failed since it no longer exists (https://exitorrent.org/return%20downloadTorrent('223678',%20'Hold.Your.Breath.2024.MULTi.2160p.DSNP.WEB-DL.DV.HDR.HEVC-CiNEMAET.mkv.torrent',%20'FL');)

[v1.24.3.4754] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://exitorrent.org/return%20downloadTorrent('223678',%20'Hold.Your.Breath.2024.MULTi.2160p.DSNP.WEB-DL.DV.HDR.HEVC-CiNEMAET.mkv.torrent',%20'FL');]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 44
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 251
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.56 (Debian) Server at exitorrent.org Port 443</address>
</body></html>

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by lisekxd1234** [comment]
[log.txt](https://github.com/user-attachments/files/17274032/log.txt)
