### ISSUE TITLE
Sharewood (API) don't work

### ISSUE THREAD

**Issue by plivdev** [Prowlarr/Prowlarr#2245]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Value cannot be null. (Parameter 'fileKey') error when I try to add Sharewood (API) because Sharewood one doesn't exist anymore

### Expected Behavior

Add new indexer (Sharewood (API))

### Steps To Reproduce

1. be on version 1.24.3.4754
2. try to add Sharewood (API) indexer

### Environment

```markdown
- OS: 
- Prowlarr: Prowlarr 1.24.3.4754
- Docker Install: Linuxserver Prowlarr (Latest)
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

2024-10-07 22:20:50.7|Fatal|ProwlarrErrorPipeline|Request Failed. POST /api/v1/indexer

[v1.24.3.4754] System.ArgumentNullException: Value cannot be null. (Parameter 'fileKey')
   at NzbDrone.Core.IndexerVersions.IndexerDefinitionUpdateService.GetUncachedDefinition(String fileKey) in ./Prowlarr.Core/IndexerVersions/IndexerDefinitionUpdateService.cs:line 219
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Prowlarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.IndexerVersions.IndexerDefinitionUpdateService.GetCachedDefinition(String fileKey) in ./Prowlarr.Core/IndexerVersions/IndexerDefinitionUpdateService.cs:line 121
   at Prowlarr.Api.V1.Indexers.IndexerResourceMapper.ToModel(IndexerResource resource, IndexerDefinition existingDefinition) in ./Prowlarr.Api.V1/Indexers/IndexerResource.cs:line 122
   at Prowlarr.Api.V1.ProviderControllerBase`4.GetDefinition(TProviderResource providerResource, Boolean validate, Boolean includeWarnings, Boolean forceValidate) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 154
   at Prowlarr.Api.V1.ProviderControllerBase`4.CreateProvider(TProviderResource providerResource, Boolean forceSave) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 73
   at lambda_method415(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by plivdev** [comment]
I just restart it and it worked, I will see in future if it appear again, thank's :)
