### ISSUE TITLE
An error occurred while processing indexer feed. An item with the same key has already been added.

### ISSUE THREAD

**Issue by Klemek** [Prowlarr/Prowlarr#2275]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

[TorrentRssIndexerRequestGenerator.cs](https://github.com/Prowlarr/Prowlarr/blob/8e69415d64b14b1af2e45f347bfa4db35f8d2ba4/src/NzbDrone.Core/Indexers/Definitions/TorrentRss/TorrentRssIndexerRequestGenerator.cs#L50)
Adds cookies with
```cs
            if (Settings.Cookie.IsNotNullOrWhiteSpace())
            {
                foreach (var cookie in HttpHeader.ParseCookies(Settings.Cookie))
                {
                    request.HttpRequest.Cookies[cookie.Key] = cookie.Value;
                }
            }
```
Then [HttpIndexerBase.cs](https://github.com/Prowlarr/Prowlarr/blob/8e69415d64b14b1af2e45f347bfa4db35f8d2ba4/src/NzbDrone.Core/Indexers/HttpIndexerBase.cs#L647)
Adds previous requests cookies with
```cs
            Cookies = GetCookies();

            if (Cookies != null)
            {
                foreach (var cookie in Cookies)
                {
                    request.HttpRequest.Cookies.Add(cookie.Key, cookie.Value);
                }
            }
```
Where it fails
```
System.ArgumentException: An item with the same key has already been added. Key: account_created
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 655
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 603
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, SearchCriteriaBase searchCriteria, Boolean isRecent) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 421
```

### Expected Behavior

Working Torrent RSS Indexer

### Steps To Reproduce

Add a Torrent RSS Indexer with a cookie, test and save.
Edit the same indexer and retry

### Environment

```markdown
- OS: Ubuntu 22.04
- Prowlarr: latest 1.25.4.4818
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: non related
```

### What branch are you running?

Master

### Trace Logs?

```
System.ArgumentException: An item with the same key has already been added. Key: account_created
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 655
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 603
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, SearchCriteriaBase searchCriteria, Boolean isRecent) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 421
   ```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Klemek** [comment]
![image](https://github.com/user-attachments/assets/2c93545f-2790-4e49-9345-303e2c43a017)
![image](https://github.com/user-attachments/assets/09618d4e-881e-4005-af85-11bdc809b101)
![image](https://github.com/user-attachments/assets/d3090ae2-6bc5-4873-81d9-6776a8f38c35)

**Comment by Klemek** [comment]
> Can you check if you have a cookie parameter more than once in your cookies input?

Already checked, I can split it if you want:
```
account_created=true; cf_clearance=<redacted>; v51_promo_details=<redacted>; hide_side_menu=true; ygg_=<redacted>; yggxf_session=<redacted>; yggxf_csrf=<redacted>
```

**Comment by Klemek** [comment]
I tried with another open (no cookie required) RSS feed with a cookie set in the field, it's working.
The one I'm trying to reach have a `Set-Cookie` header, maybe that's why

**Comment by Klemek** [comment]
FYI it's working on [Sonaar](https://github.com/Sonarr/Sonarr/blob/4e9ef57e3d8c923f765b3337279a0cf4e93d6068/src/NzbDrone.Core/Indexers/HttpIndexerBase.cs#L349) and [Radarr](https://github.com/Radarr/Radarr/blob/9ab3e6bab73fa6a21e4d9afb851438c266883e68/src/NzbDrone.Core/Indexers/HttpIndexerBase.cs#L319)
They seem to not change cookies before request

**Comment by Klemek** [comment]
Thank you !
