### ISSUE TITLE
 Invalid torrent file specified

### ISSUE THREAD

**Issue by lluisd** [Prowlarr/Prowlarr#2282]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I get often errors of indexers not available from sonarr and radarr. I use all in http and it was working fine during some years ago.

### Expected Behavior

working fine

### Environment

```markdown
- OS: docker
- Prowlarr:  1.25.4.4818
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

MonoTorrent.TorrentException: Invalid torrent file specified: Invalid torrent file specified

MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Indexers.TorrentIndexerBase`1.ValidateDownloadData(Byte[] fileData) in ./Prowlarr.Core/Indexers/TorrentIndexerBase.cs:line 28
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 323
   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in ./Prowlarr.Core/Download/DownloadService.cs:line 182
   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in ./Prowlarr.Api.V1/Indexers/NewznabController.cs:line 315

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Invalid bug report; Incomplete and information indicated provided not provided / template not folllowed
