### ISSUE TITLE
[abtorrents] Login Failed, we are being redirected to the login page.

### ISSUE THREAD

**Issue by Nammurg** [Prowlarr/Prowlarr#2318]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Can't connect to ABTorrents with the following error:
We are being redirected to the login page. Most likely your session expired or was killed. Recheck your cookie or credentials and try testing the indexer. 

### Expected Behavior

Expected to be able to login using the cookies.
I have followed all the steps and been able to go to URL: _https://abtorrents.me/browse.php?searchin=title&incldead=1;_ within my browser successfully.

### Environment

```markdown
- OS: Unraid 6.12.14
- Prowlarr: 1.28.2.4885 
- Docker Install: 
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Master

### Trace Logs?

[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- : Unable to connect to indexer. We are being redirected to the login page. Most likely your session expired or was killed. Recheck your cookie or credentials and try testing the indexer. 
[Warn] Cardigann: Redirected to https://abtorrents.me/login.php from indexer request 
[Warn] Cardigann: Unable to connect to indexer 

[v1.28.2.4885] NzbDrone.Core.Indexers.Exceptions.IndexerException: We are being redirected to the login page. Most likely your session expired or was killed. Recheck your cookie or credentials and try testing the indexer.
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannParser.cs:line 50
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 606
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 852
RequestUri: https://abtorrents.me/browse.php?searchin=title&incldead=1;StatusCode: Redirect;ContentType: text/html; charset=utf-8;ContentLength: 0

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Nammurg** [comment]
I have also tried to play around with the cookies and I have exported them from the working session and imported them in an Incognito session on the same machine/public IP and they do not seem to be working, I get redirected to the login page....
