### ISSUE TITLE
Anthelion Issues

### ISSUE THREAD

**Issue by Junkbite** [Prowlarr/Prowlarr#252]
**Describe the bug**
my password is showing up as plain text on the ui. probaly need to set password input to password type. Also, setup is failing:

**To Reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/62021344/122791066-e1c27400-d286-11eb-8f99-fa9e7075461b.png)
**Platform Information (please complete the following information):**
```

Version
0.1.0.497
Package Version
nightly-5b974ec by hotio
.NET
Yes (5.0.6)
Docker
Yes
DB Migration
7
```

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

```
2021-06-21 11:46:22.4|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2021-06-21 11:46:22.4|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'60'
2021-06-21 11:46:22.4|Trace|Http|Req: 76 [GET] /api/v1/health (from 192.168.1.214)
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'availabilitydelay' defaultValue:'0'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'importlistsyncinterval' defaultValue:'240'
2021-06-21 11:46:22.4|Trace|Http|Res: 76 [GET] /api/v1/health: 200.OK (1 ms)
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'listsynclevel' defaultValue:'disabled'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'importexclusions' defaultValue:''
2021-06-21 11:46:22.4|Debug|Api|[GET] /api/v1/health: 200.OK (1 ms)
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'preferindexerflags' defaultValue:'False'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'allowhardcodedsubs' defaultValue:'False'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'whitelistedhardcodedsubs' defaultValue:''
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'autoredownloadfailed' defaultValue:'True'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'removefaileddownloads' defaultValue:'True'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'30'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'firstdayofweek' defaultValue:'0'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'calendarweekcolumnheader' defaultValue:'ddd M/D'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'shortdateformat' defaultValue:'MMM D YYYY'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'longdateformat' defaultValue:'dddd, MMMM D YYYY'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'timeformat' defaultValue:'h(:mm)a'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'cleanupmetadataimages' defaultValue:'True'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2021-06-21 11:46:22.4|Trace|Http|Req: 77 [GET] /api/v1/health (from 192.168.1.214)
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2021-06-21 11:46:22.4|Trace|Http|Res: 77 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-21 11:46:22.4|Trace|EventAggregator|Publishing ConfigSavedEvent
2021-06-21 11:46:22.4|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-21 11:46:22.4|Trace|Http|Req: 78 [GET] /api/v1/health (from 192.168.1.214)
2021-06-21 11:46:22.4|Trace|Http|Res: 78 [GET] /api/v1/health: 200.OK (1 ms)
2021-06-21 11:46:22.4|Debug|Api|[GET] /api/v1/health: 200.OK (1 ms)
2021-06-21 11:46:22.4|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-21 11:46:22.4|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2021-06-21 11:46:22.4|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-06-21 11:46:22.4|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2021-06-21 11:46:22.4|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2021-06-21 11:46:22.4|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2021-06-21 11:46:22.4|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2021-06-21 11:46:22.4|Trace|Http|Req: 79 [GET] /api/v1/health (from 192.168.1.214)
2021-06-21 11:46:22.4|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-06-21 11:46:22.4|Trace|Http|Res: 79 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-21 11:46:22.4|Trace|Http|Res: 75 [PUT] /api/v1/config/host: 202.Accepted (67 ms)
2021-06-21 11:46:22.4|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-21 11:46:22.4|Debug|Api|[PUT] /api/v1/config/host: 202.Accepted (67 ms)
2021-06-21 11:46:22.4|Trace|Http|Req: 80 [GET] /api/v1/health (from 192.168.1.214)
2021-06-21 11:46:22.4|Trace|Http|Res: 80 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-21 11:46:22.4|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-21 11:46:22.4|Trace|Http|Req: 81 [GET] /api/v1/health (from 192.168.1.214)
2021-06-21 11:46:22.4|Trace|Http|Res: 81 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-21 11:46:22.4|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-21 11:46:24.1|Trace|Http|Req: 82 [POST] /api/v1/indexer (from 192.168.1.214)
2021-06-21 11:46:24.1|Debug|Anthelion|Downloading Feed https://anthelion.me/torrents.php?order_by=time&order_way=desc&action=basic&searchsubmit=1&searchstr=
2021-06-21 11:46:24.1|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-06-21 11:46:24.1|Trace|HttpClient|Req: [GET] https://anthelion.me/torrents.php?order_by=time&order_way=desc&action=basic&searchsubmit=1&searchstr=
2021-06-21 11:46:24.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-21 11:46:24.6|Trace|HttpClient|Res: [GET] https://anthelion.me/torrents.php?order_by=time&order_way=desc&action=basic&searchsubmit=1&searchstr=: 302.Redirect (516 ms)
2021-06-21 11:46:24.6|Trace|Anthelion|Attempting to re-auth based on indexer search response
2021-06-21 11:46:24.6|Trace|HttpClient|Req: [POST] https://anthelion.me/login.php: username=(removed)&password=(removed)&keeplogged=1&login=Log%2BIn%21
2021-06-21 11:46:24.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-21 11:46:25.2|Trace|HttpClient|Res: [POST] https://anthelion.me/login.php: 302.Redirect (580 ms)
2021-06-21 11:46:25.2|Trace|HttpClient|Response content (0 bytes): 
2021-06-21 11:46:25.2|Trace|EventAggregator|Publishing IndexerAuthEvent
2021-06-21 11:46:25.2|Trace|EventAggregator|IndexerAuthEvent -> HistoryService
2021-06-21 11:46:25.2|Trace|EventAggregator|IndexerAuthEvent <- HistoryService
2021-06-21 11:46:25.2|Warn|Anthelion|Indexer returned result for RSS URL, Credentials appears to be invalid: Anthelion Auth Failed
2021-06-21 11:46:25.2|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.0.497] FluentValidation.ValidationException: Validation failed: 
 -- ApiKey: Invalid API Key
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method175(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-06-21 11:46:25.3|Trace|ProwlarrErrorPipeline|Handling Exception
2021-06-21 11:46:25.3|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- ApiKey: Invalid API Key
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method175(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[v0.1.0.497] FluentValidation.ValidationException: Validation failed: 
 -- ApiKey: Invalid API Key
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method175(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-06-21 11:46:25.4|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- ApiKey: Invalid API Key
2021-06-21 11:46:25.4|Trace|Http|Res: 82 [POST] /api/v1/indexer: 400.BadRequest (1353 ms)
2021-06-21 11:46:25.4|Debug|Api|[POST] /api/v1/indexer: 400.BadRequest (1353 ms)
2021-06-21 11:46:36.8|Trace|Scheduler|Pending Tasks: 0
2021-06-21 11:47:06.8|Trace|Scheduler|Pending Tasks: 0
```

**Comment by bakerboy448** [comment]
Password in plaintext should be fixed with https://github.com/Prowlarr/Prowlarr/commit/538db52d16c4eed5cc7e38b2aed27dd4fa773f24

**Comment by ljmerza** [comment]
The other issue was fixed too?

**Comment by Qstick** [comment]
Missed that we had a 2 for 1 here
