### ISSUE TITLE
HD-Space setup fails

### ISSUE THREAD

**Issue by Junkbite** [Prowlarr/Prowlarr#294]
**Describe the bug**

cant setup hd-space

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**
```
Version
0.1.0.556
Package Version
nightly-1976752 by hotio
.NET
Yes (5.0.6)
Docker
Yes
DB Migration
7
```

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

```
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
2021-06-28 12:27:41.6|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'60'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'availabilitydelay' defaultValue:'0'
2021-06-28 12:27:41.6|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'importlistsyncinterval' defaultValue:'240'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'listsynclevel' defaultValue:'disabled'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'importexclusions' defaultValue:''
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'maximumsize' defaultValue:'0'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'preferindexerflags' defaultValue:'False'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'allowhardcodedsubs' defaultValue:'False'
2021-06-28 12:27:41.6|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'whitelistedhardcodedsubs' defaultValue:''
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'autoredownloadfailed' defaultValue:'True'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'removefaileddownloads' defaultValue:'True'
2021-06-28 12:27:41.6|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2021-06-28 12:27:41.6|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'30'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'firstdayofweek' defaultValue:'0'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'calendarweekcolumnheader' defaultValue:'ddd M/D'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'shortdateformat' defaultValue:'MMM D YYYY'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'longdateformat' defaultValue:'dddd, MMMM D YYYY'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'timeformat' defaultValue:'h(:mm)a'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2021-06-28 12:27:41.6|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'cleanupmetadataimages' defaultValue:'True'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2021-06-28 12:27:41.6|Trace|EventAggregator|Publishing ConfigSavedEvent
2021-06-28 12:27:41.6|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2021-06-28 12:27:41.6|Trace|Http|Req: 109 [GET] /api/v1/health (from 192.168.1.214)
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-28 12:27:41.6|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2021-06-28 12:27:41.6|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-06-28 12:27:41.6|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2021-06-28 12:27:41.6|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2021-06-28 12:27:41.6|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2021-06-28 12:27:41.6|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-06-28 12:27:41.6|Trace|Http|Req: 110 [GET] /api/v1/health (from 192.168.1.214)
2021-06-28 12:27:41.6|Trace|Http|Res: 109 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Trace|Http|Res: 110 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-06-28 12:27:41.6|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Trace|Http|Res: 108 [PUT] /api/v1/config/host: 202.Accepted (36 ms)
2021-06-28 12:27:41.6|Debug|Api|[PUT] /api/v1/config/host: 202.Accepted (36 ms)
2021-06-28 12:27:41.6|Trace|Http|Req: 111 [GET] /api/v1/health (from 192.168.1.214)
2021-06-28 12:27:41.6|Trace|Http|Res: 111 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Trace|Http|Req: 112 [GET] /api/v1/health (from 192.168.1.214)
2021-06-28 12:27:41.6|Trace|Http|Res: 112 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Trace|Http|Req: 113 [GET] /api/v1/health (from 192.168.1.214)
2021-06-28 12:27:41.6|Trace|Http|Res: 113 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Trace|Http|Req: 114 [GET] /api/v1/health (from 192.168.1.214)
2021-06-28 12:27:41.6|Trace|Http|Res: 114 [GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:41.6|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-06-28 12:27:43.3|Trace|Http|Req: 115 [POST] /api/v1/indexer (from 192.168.1.214)
2021-06-28 12:27:43.3|Debug|HDSpace|Downloading Feed https://hd-space.org/index.php?page=torrents&
2021-06-28 12:27:43.3|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-06-28 12:27:43.3|Trace|HttpClient|Req: [GET] https://hd-space.org/index.php?page=torrents&
2021-06-28 12:27:43.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-28 12:27:44.0|Trace|HttpClient|Res: [GET] https://hd-space.org/index.php?page=torrents&: 200.OK (709 ms)
2021-06-28 12:27:44.0|Trace|HDSpace|Attempting to re-auth based on indexer search response
2021-06-28 12:27:44.0|Trace|HttpClient|Req: [GET] https://hd-space.org/index.php?page=login
2021-06-28 12:27:44.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-28 12:27:45.1|Trace|HttpClient|Res: [GET] https://hd-space.org/index.php?page=login: 200.OK (1110 ms)
2021-06-28 12:27:45.1|Trace|HttpClient|Req: [POST] https://hd-space.org/index.php?page=login: uid=(removed)&pwd=
2021-06-28 12:27:45.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-06-28 12:27:45.8|Trace|HttpClient|Res: [POST] https://hd-space.org/index.php?page=login: 302.Redirect (743 ms)
2021-06-28 12:27:45.8|Trace|HttpClient|Response content (0 bytes): 
2021-06-28 12:27:45.8|Trace|EventAggregator|Publishing IndexerAuthEvent
2021-06-28 12:27:45.8|Trace|EventAggregator|IndexerAuthEvent -> HistoryService
2021-06-28 12:27:45.9|Trace|EventAggregator|IndexerAuthEvent <- HistoryService
2021-06-28 12:27:45.9|Warn|HDSpace|Indexer returned result for RSS URL, Credentials appears to be invalid: Login Failed: You have  remaining login attempts
2021-06-28 12:27:45.9|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.0.556] FluentValidation.ValidationException: Validation failed: 
 -- : Login Failed: You have  remaining login attempts
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method159(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-06-28 12:27:45.9|Trace|ProwlarrErrorPipeline|Handling Exception
2021-06-28 12:27:45.9|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Login Failed: You have  remaining login attempts
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method159(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[v0.1.0.556] FluentValidation.ValidationException: Validation failed: 
 -- : Login Failed: You have  remaining login attempts
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method159(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-06-28 12:27:46.2|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Login Failed: You have  remaining login attempts
2021-06-28 12:27:46.2|Trace|Http|Res: 115 [POST] /api/v1/indexer: 400.BadRequest (2946 ms)
2021-06-28 12:27:46.2|Debug|Api|[POST] /api/v1/indexer: 400.BadRequest (2946 ms)
2021-06-28 12:27:51.2|Trace|Http|Req: 116 [GET] /api/v1/log/file (from 192.168.1.214)
2021-06-28 12:27:51.2|Trace|Http|Res: 116 [GET] /api/v1/log/file: 200.OK (1 ms)
2021-06-28 12:27:51.2|Debug|Api|[GET] /api/v1/log/file: 200.OK (1 ms)

```

[AB#110](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/110)

**Comment by bakerboy448** [comment]
Likely related to the fact they are a Flaresolverr indexer which don't have plans to support.

**Comment by Junkbite** [comment]
Jackett hd-space has always worked just fine though

**Comment by Qstick** [comment]
Yea, could be something I missed on the pull over

**Comment by bakerboy448** [comment]
Partial fix (or maybe full fix?) https://github.com/Prowlarr/Prowlarr/commit/fe8247df8aea027f98673b7a5f0e9452b0f2cb85
