### ISSUE TITLE
NZBNDX failing to add (API not working)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Prowlarr/Prowlarr#302]
**Describe the bug**

as first discussed in discord, I tried to add NZBNDX & it required a key in prowlarr even though it doesn't need one
the indexer works fine in nzbhydra 2 & gets results however in prowlarr it fails to add.

also the call prowlarr is using https://www.nzbndx.com/api?t=search&extended=1&apikey=(removed)&
spits out `<error code="100" description="Incorrect user credentials"/>` when tested in the browser

with https://www.nzbndx.com/api?t=search&extended=1
`<error code="200" description="Missing parameter"/>`

I suspect nzbhydra2 queries the site it self without API.

**To Reproduce**
just try to add it as an indexer

**Expected behavior**
to work, like nzbhydra makes it work with no issues

**Screenshots**
![Screen_Shot_2021-07-01_at_4 03 32_pm](https://user-images.githubusercontent.com/2242880/124081670-2e7c2b00-da8f-11eb-93c8-72efa72778a1.jpg)
![Screen_Shot_2021-07-01_at_4 20 22_pm](https://user-images.githubusercontent.com/2242880/124081689-32a84880-da8f-11eb-9525-4b4553e1d95b.jpg)

**Platform Information (please complete the following information):**
 - OS: macOS 11.4
 - Docker: NO | running it from application container using `launchd` to run it as a service
 - .NET Version Yes (5.0.6)
 - Browser and Version Chrome: Version 91.0.4472.114 (Official Build) (x86_64)
 - Prowlarr Version: 0.1.0.545
 - Prowlarr Branch: develop

**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[All Logs.zip](https://github.com/Prowlarr/Prowlarr/files/6746096/All.Logs.zip) - has all the .txt log files including trace

Snippet:
```
2021-07-01 17:06:37.7|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- ApiKey: Invalid API Key
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67
   at lambda_method337(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

[AB#1155](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1155)

**Comment by XxUnkn0wnxX** [comment]
NM got confused with `NZBIndex` with `NZBNDX`
