### ISSUE TITLE
Unable to validate Limetorrents index

### ISSUE THREAD

**Issue by groenator** [Prowlarr/Prowlarr#316]
When I add the LimeTorrents index and click on test, prowlarr is not able to validate the index because is redirecting to a new domain as showed below:

```bash
prowlarr    | [Warn] Cardigann: Unable to connect to indexer
prowlarr    |
prowlarr    | [v0.1.0.545] System.Exception: Got redirected to another domain. Try changing the indexer URL to https://www.limetorrents.pro/.
prowlarr    |    at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.CheckIfLoginIsNeeded(HttpResponse response) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 789
prowlarr    |    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 436
prowlarr    |    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 374
prowlarr    |    at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 562
prowlarr    |
prowlarr    |
prowlarr    | [Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
prowlarr    |
prowlarr    | [v0.1.0.545] FluentValidation.ValidationException: Validation failed:
prowlarr    |  -- : Unable to connect to indexer, check the log for more details
prowlarr    |    at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
prowlarr    |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
prowlarr    |    at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 139
prowlarr    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
prowlarr    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
prowlarr    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
prowlarr    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

[AB#1214](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1214)

**Comment by Qstick** [comment]
Def has been updated, once you pull a new definition this should work.

**Comment by groenator** [comment]
I am using docker and I pulled the latest image. Under which version was this fixed?

**Comment by bakerboy448** [comment]
System-> Tasks -> Definition update

**Comment by groenator** [comment]
Hey There,

I update the Index definition but I still get the same error.

```

> [v0.1.0.545] System.Exception: Got redirected to another domain. Try
> changing the indexer URL to https://www.limetorrents.pro/.
> prowlarr    |    at
> NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.CheckIfLoginIsNeeded(HttpResponse
> response) in
> D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line
> 789
> prowlarr    |    at
> NzbDrone.Core.Indexers.Cardigann.Cardigann.CheckIfLoginNeeded(HttpResponse
> httpResponse) in
> D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line
> 147
> prowlarr    |    at
> NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest
> request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 436
> prowlarr    |    at
> NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request,
> IParseIndexerResponse parser) in
> D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 350
> prowlarr    |    at
> NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in
> D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 499
> prowlarr    |
> prowlarr    |
> prowlarr    | [Error]
> Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled
> exception has occurred while executing the request.
> prowlarr    |
>
```

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

read the error message.

**Comment by groenator** [comment]
Thanks for that, I am trying to change the URL but I am not able to do so.
Hence, why I created an issue here. If you can guide me on how to change
the URL from the UI that would be great.

Thank you! Regards

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

**Comment by groenator** [comment]
Sure! Thanks
