### ISSUE TITLE
[BUG]: unsupported encoding name for Deildu

### ISSUE THREAD

**Issue by water1309** [Prowlarr/Prowlarr#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

unable to add Deildu as indexer. Error is:

`"[v0.1.0.608] System.ArgumentException: 'latin1_swedish_ci' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')"`

### Expected Behavior

Deildu would be added as indexer without error (because on the wiki it says deildu is supported)

### Steps To Reproduce

- prowlarr docker on synology NAS 
- docker compose copied from Linuxserver
- adding deildu.net

### Environment

```markdown
- OS: DSM 6.3
- Prowlarr: Package Version 0.1.0.608-ls9 by linuxserver.io
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: chrome 92
```

### What branch are you running?

Develop

### Anything else?

```
2021-07-28 10:57:54.6|Info|HistoryService|Removing items older than 365 days from history
2021-07-28 10:57:59.8|Info|HousekeepingService|Running housecleaning tasks
2021-07-28 10:58:11.9|Info|Database|Vacuuming Log database
2021-07-28 10:58:14.3|Info|Database|Log database compressed
2021-07-28 10:58:14.7|Info|Database|Vacuuming Main database
2021-07-28 10:58:17.7|Info|Database|Main database compressed
2021-07-28 12:22:28.7|Error|IndexerDefinitionUpdateService|Failed to Connect to Indexer Definition Server for Indexer listing
2021-07-28 12:32:12.0|Info|Cardigann|Adding request: https://ptfiles.net/browse.php?search=&incldead=0&title=0&free=&sort=4&type=desc
2021-07-28 12:32:28.6|Info|Cardigann|Adding request: https://ptfiles.net/browse.php?search=&incldead=0&title=0&free=&sort=4&type=desc
2021-07-28 12:38:57.0|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2021-07-28 12:39:00.5|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/time/desc/1/
2021-07-28 12:40:21.2|Info|Cardigann|Adding request: https://deildu.net/browse.php?search=&incldead=1&Lysing=&sort=added&type=desc
2021-07-28 12:40:21.5|Warn|Cardigann|Unable to connect to indexer

[v0.1.0.608] System.ArgumentException: 'latin1_swedish_ci' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at NzbDrone.Common.Http.HttpHeader.GetEncodingFromContentType(String contentType) in D:\a\1\s\src\NzbDrone.Common\Http\HttpHeader.cs:line 150
   at NzbDrone.Common.Http.HttpHeader.GetEncodingFromContentType() in D:\a\1\s\src\NzbDrone.Common\Http\HttpHeader.cs:line 134
   at NzbDrone.Common.Http.HttpResponse.get_Content() in D:\a\1\s\src\NzbDrone.Common\Http\HttpResponse.cs:line 53
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 159
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 68
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 195
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 158
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 437
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 347
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 496
```

**Comment by chryzsh** [comment]
Had similar issues with rutracker. This should be taken care of with a merge of this PR, which adds support for encodings specified in definition https://github.com/Prowlarr/Prowlarr/pull/371/files

**Comment by Qstick** [comment]
> Had similar issues with rutracker. This should be taken care of with a merge of this PR, which adds support for encodings specified in definition https://github.com/Prowlarr/Prowlarr/pull/371/files

I think we need to add some logic to use the encoding all the time in HttpIndexerBase, as we just used it one specifically in RuTracker def.
