### ISSUE TITLE
[BUG]: If custom Torznab indexer returns empty magnet URLs, prowlarr won't return any results

### ISSUE THREAD

**Issue by Mouton99** [Prowlarr/Prowlarr#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not getting any results, because an exception is thrown:

```
[Info] NzbSearchService: Searching indexers: [Test] for {Term: Vivo, Offset: 0, Limit: 0, Categories: []} 
[Error] SearchController: Search failed: Invalid URI: The URI is empty. 

[v0.1.0.767] System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Prowlarr.Api.V1.Search.SearchController.MapDecisions(IEnumerable`1 releases, String serverUrl) in D:\a\1\s\src\Prowlarr.Api.V1\Search\SearchController.cs:line 129
   at Prowlarr.Api.V1.Search.SearchController.GetSearchReleases(String query, List`1 indexerIds, List`1 categories) in D:\a\1\s\src\Prowlarr.Api.V1\Search\SearchController.cs:line 119
```

### Expected Behavior

Getting results, and no crash.

```
[Info] NzbSearchService: Searching indexers: [Test] for {Term: Vivo, Offset: 0, Limit: 0, Categories: []} 
```

### Steps To Reproduce

1. Add a custom Torznab indexer that returns empty magnet URLs
2. Search for anything on that indexer

### Environment

```markdown
- Prowlarr: develop branch (d937e0324fc09a2a67341402a5e56188cd2860d9)

(Was having this problem in Docker, so I cloned the Git repo, and was able to reproduce the issue on the above branch & commit)
```

### What branch are you running?

Develop

### Anything else?

I can easily submit a PR to fix this, if this makes sense:

`SearchController.cs`
```diff
+                 if (!string.IsNullOrEmpty(release.MagnetUrl))
+                 {
                      release.MagnetUrl = release.MagnetUrl != null ? _downloadMappingService.ConvertToProxyLink(new Uri(release.MagnetUrl), serverUrl, release.IndexerId, release.Title).ToString() : null;
+                 }
```

My `release.MagnetUrl` was an empty string; not sure if it can be null, but better safe than sorry.

[AB#1414](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1414)

**Comment by Mouton99** [comment]
Just noticed a very different Exception stack, when the search is made from a remote app (using the API):

```
[Info] NzbSearchService: Searching indexers: [Test] for {Term: Vivo, Offset: 0, Limit: 100, Categories: [5000]} 
[Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 

[v0.1.0.767] System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at NzbDrone.Api.V1.Indexers.NewznabController.GetNewznabResponse(Int32 id, NewznabRequest request) in D:\a\1\s\src\Prowlarr.Api.V1\Indexers\NewznabController.cs:line 136
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
