### ISSUE TITLE
[BUG]: ProwlarrUrl: Prowlarr url is invalid, Sonarr cannot connect to Prowlarr

### ISSUE THREAD

**Issue by kingrob79** [Prowlarr/Prowlarr#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you config sonarr in APP it gives the following error 
ProwlarrUrl: Prowlarr url is invalid, Sonarr cannot connect to Prowlarr

### Expected Behavior

it should add sonarr 

### Steps To Reproduce

1. Install Prowlarr
2. Click APP add sonarr
3. Fill out details 
4. under prowlarr url you get the error

### Environment

```markdown
- OS: Ubuntu 18.04
- Prowlarr:0.1.0.816
- Docker Install: no
- Using Reverse Proxy:Yes
- Browser: chome
```

### What branch are you running?

Nightly

### Anything else?

There is no error with Versions 0.1.0.758  or 0.1.0.791 
I have been on discord and other users have confirmed the same bug

2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'whitelistedhardcodedsubs' defaultValue:''
2021-08-16 10:02:59.2|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'autoredownloadfailed' defaultValue:'True'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'removefaileddownloads' defaultValue:'True'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'30'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'firstdayofweek' defaultValue:'0'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'calendarweekcolumnheader' defaultValue:'ddd M/D'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'shortdateformat' defaultValue:'MMM D YYYY'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'longdateformat' defaultValue:'dddd, MMMM D YYYY'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'timeformat' defaultValue:'h(:mm)a'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'cleanupmetadataimages' defaultValue:'True'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2021-08-16 10:02:59.2|Trace|EventAggregator|Publishing ConfigSavedEvent
2021-08-16 10:02:59.2|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-08-16 10:02:59.2|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2021-08-16 10:02:59.2|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2021-08-16 10:02:59.2|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2021-08-16 10:02:59.2|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2021-08-16 10:02:59.2|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2021-08-16 10:02:59.2|Trace|ConfigService|Using default config value for 'historycleanupdays' defaultValue:'365'
2021-08-16 10:02:59.3|Trace|Http|Res: 427 [PUT] /prowlarr/api/v1/config/host: 202.Accepted (115 ms)
2021-08-16 10:02:59.3|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-08-16 10:02:59.3|Trace|Http|Req: 428 [GET] /prowlarr/api/v1/health (from 95.*.*.31)
2021-08-16 10:02:59.3|Trace|Http|Res: 428 [GET] /prowlarr/api/v1/health: 200.OK (0 ms)
2021-08-16 10:02:59.4|Trace|Http|Req: 429 [GET] /prowlarr/api/v1/health (from 95.*.*.31)
2021-08-16 10:02:59.4|Trace|Http|Res: 429 [GET] /prowlarr/api/v1/health: 200.OK (0 ms)
2021-08-16 10:02:59.4|Trace|Http|Req: 430 [GET] /prowlarr/api/v1/health (from 95.*.*.31)
2021-08-16 10:02:59.4|Trace|Http|Res: 430 [GET] /prowlarr/api/v1/health: 200.OK (0 ms)
2021-08-16 10:02:59.5|Trace|Http|Req: 431 [GET] /prowlarr/api/v1/health (from 95.*.*.31)
2021-08-16 10:02:59.5|Trace|Http|Res: 431 [GET] /prowlarr/api/v1/health: 200.OK (0 ms)
2021-08-16 10:03:05.7|Trace|Http|Req: 432 [GET] /prowlarr/api/v1/applications (from 95.*.*.31)
2021-08-16 10:03:05.7|Trace|Http|Res: 432 [GET] /prowlarr/api/v1/applications: 200.OK (2 ms)
2021-08-16 10:03:05.8|Trace|Http|Req: 433 [GET] /prowlarr/api/v1/appprofile (from 95.*.*.31)
2021-08-16 10:03:05.8|Trace|Http|Res: 433 [GET] /prowlarr/api/v1/appprofile: 200.OK (0 ms)
2021-08-16 10:03:07.0|Trace|Http|Req: 434 [GET] /prowlarr/api/v1/applications/schema (from 95.*.*.31)
2021-08-16 10:03:07.0|Trace|Http|Res: 434 [GET] /prowlarr/api/v1/applications/schema: 200.OK (0 ms)
2021-08-16 10:03:10.9|Trace|Scheduler|Pending Tasks: 1
2021-08-16 10:03:10.9|Trace|CommandQueueManager|Publishing MessagingCleanup
2021-08-16 10:03:10.9|Trace|CommandQueueManager|Checking if command is queued or started: MessagingCleanup
2021-08-16 10:03:10.9|Trace|CommandQueueManager|Inserting new command: MessagingCleanup
2021-08-16 10:03:10.9|Trace|CommandExecutor|MessagingCleanupCommand -> CleanupCommandMessagingService
2021-08-16 10:03:10.9|Trace|CommandQueueManager|Marking command as started: MessagingCleanup
2021-08-16 10:03:10.9|Trace|CommandQueueManager|Cleaning up old commands
2021-08-16 10:03:10.9|Trace|CommandQueueManager|Updating command status
2021-08-16 10:03:10.9|Trace|EventAggregator|Publishing CommandExecutedEvent
2021-08-16 10:03:10.9|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2021-08-16 10:03:10.9|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Messaging.Commands.MessagingCleanupCommand
2021-08-16 10:03:10.9|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2021-08-16 10:03:10.9|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2021-08-16 10:03:10.9|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2021-08-16 10:03:10.9|Trace|CommandExecutor|MessagingCleanupCommand <- CleanupCommandMessagingService [00:00:00.0017884]
2021-08-16 10:03:11.0|Trace|Http|Req: 435 [GET] /prowlarr/api/v1/command (from 95.*.*.31)
2021-08-16 10:03:11.0|Trace|CommandQueueManager|Getting all commands
2021-08-16 10:03:11.0|Trace|Http|Res: 435 [GET] /prowlarr/api/v1/command: 200.OK (0 ms)
2021-08-16 10:03:11.0|Trace|Http|Req: 436 [GET] /prowlarr/api/v1/command (from 95.*.*.31)
2021-08-16 10:03:11.0|Trace|CommandQueueManager|Getting all commands
2021-08-16 10:03:11.0|Trace|Http|Res: 436 [GET] /prowlarr/api/v1/command: 200.OK (0 ms)
2021-08-16 10:03:14.6|Trace|Http|Req: 437 [POST] /prowlarr/signalr/messages?access_token=(removed)&id=hoIQf78PLqKZajj95u5oXA (from 95.*.*.31)
2021-08-16 10:03:14.6|Trace|Http|Res: 437 [POST] /prowlarr/signalr/messages?access_token=(removed)&id=hoIQf78PLqKZajj95u5oXA: 200.OK (1 ms)
2021-08-16 10:03:27.2|Trace|Http|Req: 438 [POST] /prowlarr/api/v1/applications/test (from 95.*.*.31)
2021-08-16 10:03:27.2|Trace|HttpClient|Req: [POST] http://localhost:8989/sonarr/api/v3/indexer/test
2021-08-16 10:03:27.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-08-16 10:03:27.2|Trace|HttpClient|Res: [POST] http://localhost:8989/sonarr/api/v3/indexer/test: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "No rss feed query available. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
] (8 ms)
2021-08-16 10:03:27.2|Warn|HttpClient|HTTP Error - Res: [POST] http://localhost:8989/sonarr/api/v3/indexer/test: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "No rss feed query available. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2021-08-16 10:03:27.3|Error|SonarrV3Proxy|Prowlarr URL is invalid
 
[v0.1.0.816] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://localhost:8989/sonarr/api/v3/indexer/test]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 114
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 123
   at NzbDrone.Core.Applications.Sonarr.SonarrV3Proxy.Execute[TResource](HttpRequest request) in D:\a\1\s\src\NzbDrone.Core\Applications\Sonarr\SonarrV3Proxy.cs:line 149
   at NzbDrone.Core.Applications.Sonarr.SonarrV3Proxy.TestConnection(SonarrIndexer indexer, SonarrSettings settings) in D:\a\1\s\src\NzbDrone.Core\Applications\Sonarr\SonarrV3Proxy.cs:line 102
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "No rss feed query available. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
 
 
2021-08-16 10:03:27.3|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
 
[v0.1.0.816] FluentValidation.ValidationException: Validation failed: 
 -- ProwlarrUrl: Prowlarr url is invalid, Sonarr cannot connect to Prowlarr
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 139
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
 
 
2021-08-16 10:03:27.4|Trace|ProwlarrErrorPipeline|Handling Exception
2021-08-16 10:03:27.4|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- ProwlarrUrl: Prowlarr url is invalid, Sonarr cannot connect to Prowlarr
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 139
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
 
[v0.1.0.816] FluentValidation.ValidationException: Validation failed: 
 -- ProwlarrUrl: Prowlarr url is invalid, Sonarr cannot connect to Prowlarr
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 139
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
 
 
2021-08-16 10:03:27.9|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- ProwlarrUrl: Prowlarr url is invalid, Sonarr cannot connect to Prowlarr
2021-08-16 10:03:27.9|Trace|Http|Res: 438 [POST] /prowlarr/api/v1/applications/test: 400.BadRequest (649 ms)
2021-08-16 10:03:29.6|Trace|Http|Req: 439 [POST] /prowlarr/signalr/messages?access_token=(removed)&id=hoIQf78PLqKZajj95u5oXA (from 95.*.*.31)
2021-08-16 10:03:29.6|Trace|Http|Res: 439 [POST] /prowlarr/signalr/messages?access_token=(removed)&id=hoIQf78PLqKZajj95u5oXA: 200.OK (0 ms)
2021-08-16 10:03:32.1|Trace|Http|Req: 440 [GET] /prowlarr/api/v1/health (from 95.*.*.31)
2021-08-16 10:03:32.1|Trace|Http|Res: 440 [GET] /prowlarr/api/v1/health: 200.OK (2 ms)
2021-08-16 10:03:32.2|Trace|Http|Req: 441 [GET] /prowlarr/api/v1/system/status (from 95.*.*.31)
2021-08-16 10:03:32.2|Trace|Http|Res: 441 [GET] /prowlarr/api/v1/system/status: 200.OK (1 ms)
2021-08-16 10:03:33.0|Trace|Http|Req: 442 [GET] /prowlarr/api/v1/log/file (from 95.*.*.31)
2021-08-16 10:03:33.0|Trace|Http|Res: 442 [GET] /prowlarr/api/v1/log/file: 200.OK (0 ms)
2021-08-16 10:03:35.3|Trace|Http|Req: 443 [GET] /prowlarr/logfile/prowlarr.trace.txt (from 95.*.*.31)

[AB#1454](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1454)

**Comment by buddha88** [comment]
Same issue. Radarr, Lidarr, and Readarr connected just fine though.

**Comment by bakerboy448** [comment]
Fixed in Build 0.1.0.820

**Comment by kesurof** [comment]
i opened another issue for the same reason, but deleted for duplicate. however the bug this product still under version .826

**Comment by bakerboy448** [comment]
> Fixed
> Build 0.1.0.820
> Those experiencing issue will likely need to restart Sonarr after they update Prowlarr to kill Sonarr's caps cache or wait 7 days

**Comment by kesurof** [comment]
my apologies, i didn't think about restarting sonarr, i confirm that it works well now
