### ISSUE TITLE
[BUG]: Invalid torrent file specified

### ISSUE THREAD

**Issue by broven** [Prowlarr/Prowlarr#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trigger a download action in prowlarr with this magnet will cause some error
```
magnet:?xt=urn:btih:3c080b7aad0245ab7bdd2230ab03c81674c7a16d&amp;dn=%5B%E7%94%B5%E5%BD%B1%E5%A4%A9%E5%A0%82www.dytt89.com%5D%E6%B2%90%E6%B5%B4%E4%B9%8B%E7%8E%8B-2020_HD%E5%9B%BD%E8%AF%AD%E4%B8%AD%E5%AD%97.mp4
```
I picked the error trace log below

### Expected Behavior

success download via prowlarr

I test this magnet via manual add to the same qbittorrent, it's valid

### Steps To Reproduce

Feed this magnet to Prowlarr download action

### Environment

```markdown
- Prowlarr: 0.1.1.842
- Docker Install: Yes
- Using Reverse Proxy: No
```

### What branch are you running?

Nightly

### Anything else?

```
[v0.1.0.834] MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Download.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(ReleaseInfo release, IIndexer indexer, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 144
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 116
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 77
```

[AB#1488](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1488)

**Comment by bakerboy448** [comment]
A single error line is not a trace log nor sufficient information

**Comment by Qstick** [comment]
Right, please let us know what indexer, etc. So we can track this down
