### ISSUE TITLE
[BUG]: Unable to add SpeedTorrent Reloaded / ST-Tracker - Login failed: No form found

### ISSUE THREAD

**Issue by Schwarzarbeit** [Prowlarr/Prowlarr#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to add  SpeedTorrent Reloaded / ST-Tracker will not work when verifying/testing before its added, it fails with `Login failed: No form found on https://st-tracker.eu/sessioncheck.php?session=1 using form selector form`

### Expected Behavior

Successfully adds the indexer. The login with the same credentials on the website work.

### Steps To Reproduce

1. Go to Add Indexer
2. Add SpeedTorrent Reloaded
3. Enter credentials
4. Test the indexer
5. Check the Logs for the error

### Environment

```markdown
- OS: Ubuntu 20.04 LTS
- Prowlarr: 0.1.1.875
- Docker Install: Yes (Package Version 0.1.1.875-ls19 by linuxserver.io )
- Using Reverse Proxy: No
- Browser: Firefox 92.0.1
```

### What branch are you running?

Develop

### Anything else?

Please see for the tracelog:
https://hastebin.com/raw/jisisewihe

**Comment by bakerboy448** [comment]
X-Ref https://github.com/Jackett/Jackett/issues/10026

Seems to be a known issue with no resolution at this point

**Comment by bakerboy448** [comment]
- Are you running Prowlarr behind a reverse proxy?
- Are you using a VPN or proxy for the indexer?
- Are all other indexers (particularly semi-private/private) working?
- Can you access the site and login in browser from the same device and IP?
- Was the indexer working previously in Prowlarr? If so, when?
- Has/does the indexer work in jackett?

**Comment by Schwarzarbeit** [comment]
Are you running Prowlarr behind a reverse proxy?
No

Are you using a VPN or proxy for the indexer?
No

Are all other indexers (particularly semi-private/private) working?
Yes

Can you access the site and login in browser from the same device and IP?
I'm running this on a ubuntu server, but doing ``curl -v https://st-tracker.eu/sessioncheck.php?session=1`` gives me the sites html:
![curl](https://user-images.githubusercontent.com/44566093/135769174-d074bdfa-705a-45b3-9007-2d4b37c21da2.png)

Was the indexer working previously in Prowlarr? If so, when?
No, I have never got it running.

Has/does the indexer work in jackett?
I don't know, I don't have jackett setup.

**Comment by daerup** [comment]
I am having the same Issue. I do use a reverse proxy for prowlarr AND Jackett though. SpeedTorrent Reloaded does work in Jackett.

Has there bin any progress regarding this issue?

**Comment by linus-ha** [comment]
Same issue here. I am running prowlarr as a docker container.

**Comment by linus-ha** [comment]
So... The current version of Jackett works flawless. I am now using Jacket to integrate this indexer to Prowlarr. Just changing the login path in a custom yaml did not do it for me in Prowlarr.

**Comment by Serph91P** [comment]
Have the same error, Jacket working fine and am able to access the site from the same IP. So back to using 3 indexer manger.

**Comment by Qstick** [comment]
Feel free to try 0.4.3.1884 or later

**Comment by Sulphuratum** [comment]
I experience the same error on version 0.4.3.1897

**Comment by wiesel24** [comment]
same on Version 0.4.3.1921

**Comment by seth100** [comment]
Same on `v0.4.6.1969`

**Comment by herodev1337** [comment]
Having this problem too

Version 0.4.10.2111
Package Version testing-fea37fa by [hotio](https://github.com/hotio)

**Comment by Qstick** [comment]
I'll need an account or invite to fix this.

**Comment by Serph91P** [comment]
> I'll need an account or invite to fix this.

As far as I know there are no invites. How would you go about sharing the account.

**Comment by Qstick** [comment]
Ask an admin

**Comment by Serph91P** [comment]
> Ask an admin

I asked, will get back to you as soon as I get answer.

**Comment by Serph91P** [comment]
> Ask an admin

Invites are not posiible. And as far as I understand this topic with this site beeing fixed has been asked before. Will See what is beeing answered to my question.

**Comment by Serph91P** [comment]
> Ask an admin

just got message back, you should contact them via https://st-tracker.eu/kontact.php#tocontact

**Comment by Serph91P** [comment]
> > Ask an admin
> 
> @Qstick just got message back, you should contact them via https://st-tracker.eu/kontact.php#tocontact Then you will recieve an account.

@Qstick FYI

**Comment by Serph91P** [comment]
> Just curious since I don't have an account there, but changing the login from `form` to `cookie` doesn't help bypass the sessioncheck.php weird redirect?

Do you mean in the code? Because on prowlarr there is no such option.

**Comment by Serph91P** [comment]
> I know. But using the guide [here](https://wiki.servarr.com/prowlarr/indexers#adding-a-custom-yml-definition) download this file [speedtorrentreloaded-cookie.yml](https://gist.githubusercontent.com/mynameisbogdan/84bf23e8e357fa4cdec7e4a647250a97/raw/912e0bb2a26291fb88fea7974805ed8b9ceaa135/speedtorrentreloaded-cookie.yml), restart Prowlarr and try to add `SpeedTorrent Reloaded (Cookie)`.
> 
> I'm curios if it works or would still redirect to that sessioncheck.php

Ok will try later.

**Comment by Serph91P** [comment]
> > Ask an admin
> 
> @Qstick just got message back, you should contact them via https://st-tracker.eu/kontact.php#tocontact Then you will recieve an account.

@Qstick FYI

> I know. But using this guide [here](https://wiki.servarr.com/prowlarr/indexers#adding-a-custom-yml-definition), download this file [speedtorrentreloaded-cookie.yml](https://gist.githubusercontent.com/mynameisbogdan/84bf23e8e357fa4cdec7e4a647250a97/raw/912e0bb2a26291fb88fea7974805ed8b9ceaa135/speedtorrentreloaded-cookie.yml), restart Prowlarr and try to add `SpeedTorrent Reloaded (Cookie)`.
> 
> I'm curios if it works or would still redirect to that sessioncheck.php

Still the Same I Guess:

```
`[v1.0.0.2171] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 69
   at lambda_method170(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`
```

**Comment by Serph91P** [comment]
> That's a bummer. Thanks for trying.

@Qstick will need to get back to us to fix it.

**Comment by Serph91P** [comment]
Why is this labeld as Exteral Bug. BTW When are we going zo hear back from you @Qstick ?
