### ISSUE TITLE
[BUG]: Issue first starting on Centos7

### ISSUE THREAD

**Issue by NunoHiggs** [Prowlarr/Prowlarr#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

When i first start Prowlarr (the very first time), and having all the correct depedencies, i get an error when starting the process.
I've narrowed it down to this point:

While Processing:
"UPDATE History SET Successful = (json_extract(History.Data,'$.successful') == 'True' );" 

[v0.1.1.978] System.Exception: SQL logic error or missing database
**no such function: json_extract**
While Processing:
"UPDATE History SET Successful = (json_extract(History.Data,'$.successful') == 'True' );"
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error or missing database
no such function: json_extract
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass70_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)

The database does exist and is accessible by the user running the app:

[prowlarr@lxcVpar33 Prowlarr]$ ll /home/prowlarr/.config/Prowlarr/prowlarr.db
-rw-r--r-- 1 prowlarr Prowlarr 43008 Oct  8 15:03 /home/prowlarr/.config/Prowlarr/prowlarr.db
[prowlarr@lxcVpar33 Prowlarr]$

This is an Centos7.9, fully updated with SQLite3 3.36.0.

What am i missing?

Kindly!

### Expected Behavior

For it to execute the first full startup sequence.

### Steps To Reproduce

1. Start the app in foreground.
2. It's stops / crash.

### Environment

```markdown
- OS: Centos7 
- Prowlarr: Latest available as defined by your wiki - 'http://prowlarr.servarr.com/v1/update/develop/updatefile?os=linux&runtime=netcore&arch=x64'
- Docker Install: No
- Using Reverse Proxy: No
- Browser: No
```

### What branch are you running?

Master

### Anything else?

[prowlarr@lxcVpar33 Prowlarr]$ ./Prowlarr
[Info] Bootstrap: Starting Prowlarr - /opt/Prowlarr/Prowlarr - Version 0.1.1.978 
[Debug] Bootstrap: Console selected 
[Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting 
[Info] MigrationController: *** Migrating data source=/home/prowlarr/.config/Prowlarr/prowlarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] FluentMigrator.Runner.MigrationRunner: 7: history_failed migrating 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction 
[Info] history_failed: Starting migration to 7 
[Info] FluentMigrator.Runner.MigrationRunner: AlterTable History 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.000833s 
[Info] FluentMigrator.Runner.MigrationRunner: CreateColumn History Successful Boolean 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: ALTER TABLE "History" ADD COLUMN "Successful" INTEGER NOT NULL DEFAULT 1 
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0449118s 
[Info] FluentMigrator.Runner.MigrationRunner: ExecuteSqlStatement UPDATE History SET Successful = (json_extract(History.Data,'$.successful') == 'True' ); 
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: UPDATE History SET Successful = (json_extract(History.Data,'$.successful') == 'True' ); 
[Error] FluentMigrator.Runner.MigrationRunner: SQL logic error or missing database
no such function: json_extract
While Processing:
"UPDATE History SET Successful = (json_extract(History.Data,'$.successful') == 'True' );" 

[v0.1.1.978] System.Exception: SQL logic error or missing database
no such function: json_extract
While Processing:
"UPDATE History SET Successful = (json_extract(History.Data,'$.successful') == 'True' );"
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error or missing database
no such function: json_extract
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass70_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)

[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Rolling back transaction 
[Fatal] Microsoft.AspNetCore.Hosting.Diagnostics: Application startup exception 

[v0.1.1.978] NzbDrone.Common.Exceptions.ProwlarrStartupException: Prowlarr failed to start: Error creating main database
 ---> System.Exception: SQL logic error or missing database
no such function: json_extract
While Processing:
"UPDATE History SET Successful = (json_extract(History.Data,'$.successful') == 'True' );"
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error or missing database
no such function: json_extract
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass70_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\Migration\Framework\MigrationController.cs:line 65
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 103
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 118
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 67
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 55
   at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\CompositionExtensions.cs:line 10
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2870
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 10342
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10244
   at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 505
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 433
   at DryIoc.Interpreter.InterpretResolveMethod(IResolverContext resolver, IList`1 callArgs, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3634
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3512
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3025
   at DryIoc.Interpreter.TryInterpretNestedLambdaBodyAndUnwrapException(IResolverContext r, Expression bodyExpr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec) in /_/src/DryIoc/Container.cs:line 3329
   at DryIoc.Interpreter.<>c__DisplayClass3_0.<TryInterpretNestedLambda>b__0() in /_/src/DryIoc/Container.cs:line 3218
   at DryIoc.Interpreter.<>c__DisplayClass5_0`1.<ConvertFunc>b__0() in /_/src/DryIoc/Container.cs:line 3339
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, ProwlarrErrorPipeline errorHandler) in D:\a\1\s\src\NzbDrone.Host\Startup.cs:line 139
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

[Fatal] ConsoleApp: EPIC FAIL! 

[v0.1.1.978] NzbDrone.Common.Exceptions.ProwlarrStartupException: Prowlarr failed to start: Error creating main database
 ---> System.Exception: SQL logic error or missing database
no such function: json_extract
While Processing:
"UPDATE History SET Successful = (json_extract(History.Data,'$.successful') == 'True' );"
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error or missing database
no such function: json_extract
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   --- End of inner exception stack trace ---
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.ExecuteNonQuery(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(String sql)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Execute(String template, Object[] args)
   at FluentMigrator.Runner.Processors.ProcessorBase.Execute(String sql)
   at FluentMigrator.Expressions.ExecuteSqlStatementExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass70_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\Migration\Framework\MigrationController.cs:line 65
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 103
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 118
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 67
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in D:\a\1\s\src\NzbDrone.Core\Datastore\DbFactory.cs:line 55
   at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\CompositionExtensions.cs:line 10
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2870
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 10342
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10244
   at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 505
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 433
   at DryIoc.Interpreter.InterpretResolveMethod(IResolverContext resolver, IList`1 callArgs, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3634
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3512
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3025
   at DryIoc.Interpreter.TryInterpretNestedLambdaBodyAndUnwrapException(IResolverContext r, Expression bodyExpr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec) in /_/src/DryIoc/Container.cs:line 3329
   at DryIoc.Interpreter.<>c__DisplayClass3_0.<TryInterpretNestedLambda>b__0() in /_/src/DryIoc/Container.cs:line 3218
   at DryIoc.Interpreter.<>c__DisplayClass5_0`1.<ConvertFunc>b__0() in /_/src/DryIoc/Container.cs:line 3339
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, ProwlarrErrorPipeline errorHandler) in D:\a\1\s\src\NzbDrone.Host\Startup.cs:line 139
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 74
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Console\ConsoleApp.cs:line 43

Press enter to exit...
Non-recoverable failure, waiting for user intervention...

**Comment by bakerboy448** [comment]
Gonna  need at least version 3.9.0.
Note that Prowlarr uses libSQLite3.so which may or may not be contained in a SQLite3 upgrade package.
