### ISSUE TITLE
Milkie API substitution not working after switch to YAML

### ISSUE THREAD

**Issue by HalianElf** [Prowlarr/Prowlarr#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sending `{{ .Config.apikey }}` in place of API key

### Expected Behavior

Should be sending API key

### Steps To Reproduce

1. Attempt to add Milkie
2. Get Not authorized during test

### Environment

```markdown
- OS: Unraid
- Prowlarr: 0.1.3.1081
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Not UI related
```

### What branch are you running?

Nightly

### Anything else?

```
2021-11-15 12:08:29.6|Trace|HttpClient|Req: [GET] https://indexers.prowlarr.com/master/3
2021-11-15 12:08:29.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-11-15 12:08:29.7|Trace|HttpClient|Res: [GET] https://indexers.prowlarr.com/master/3: 200.OK (109 ms)
2021-11-15 12:08:30.0|Trace|Http|Res: 23 [GET] /prowlarr/api/v1/indexer/schema: 200.OK (505 ms)
2021-11-15 12:08:45.2|Trace|Scheduler|Pending Tasks: 0
2021-11-15 12:08:57.7|Trace|Http|Req: 24 [POST] /prowlarr/api/v1/indexer/action/getUrls (from 192.168.125.223)
2021-11-15 12:08:57.8|Trace|IndexerDefinitionUpdateService|Loading Cardigann definition /config/Definitions/milkie.yml
2021-11-15 12:08:57.9|Trace|Http|Res: 24 [POST] /prowlarr/api/v1/indexer/action/getUrls: 200.OK (218 ms)
2021-11-15 12:09:02.9|Trace|Http|Req: 25 [POST] /prowlarr/api/v1/indexer/test (from 192.168.125.223)
2021-11-15 12:09:02.9|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-11-15 12:09:02.9|Debug|Cardigann|Populating config vars
2021-11-15 12:09:03.0|Info|Cardigann|Adding request: https://milkie.cc/api/v1/torrents?ps=100&query=&categories=
2021-11-15 12:09:03.0|Trace|Cardigann|Adding Header Key [x-milkie-auth] with Value [{{ .Config.apikey }}]
2021-11-15 12:09:03.0|Debug|Cardigann|Downloading Feed https://milkie.cc/api/v1/torrents?ps=100&query=&categories=
2021-11-15 12:09:03.0|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-11-15 12:09:03.0|Trace|IndexerHttpClient|Req: [GET] https://milkie.cc/api/v1/torrents?ps=100&query=&categories=
2021-11-15 12:09:03.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-11-15 12:09:03.3|Trace|IndexerHttpClient|Res: [GET] https://milkie.cc/api/v1/torrents?ps=100&query=&categories=: 401.Unauthorized (288 ms)
2021-11-15 12:09:03.3|Warn|Cardigann|HTTP Error - Res: [GET] https://milkie.cc/api/v1/torrents?ps=100&query=&categories=: 401.Unauthorized
2021-11-15 12:09:03.3|Debug|Cardigann|Parsing
2021-11-15 12:09:03.3|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-11-15 12:09:03.3|Trace|Cardigann|Unexpected Response content (0 bytes): 
2021-11-15 12:09:03.3|Warn|Cardigann|Unable to connect to indexer

[v0.1.3.1081] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status Unauthorized code from API request
   at NzbDrone.Core.Indexers.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannParser.cs:line 49
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 301
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 457
RequestUri: https://milkie.cc/api/v1/torrents?ps=100&query=&categories=;StatusCode: Unauthorized;ContentLength: 0

2021-11-15 12:09:03.4|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.3.1081] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Unauthorized code from API request
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 199
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 139
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-11-15 12:09:03.7|Trace|ProwlarrErrorPipeline|Handling Exception
2021-11-15 12:09:03.7|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Unauthorized code from API request
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 199
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 139
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[v0.1.3.1081] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Unauthorized code from API request
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 199
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 190
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 139
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2021-11-15 12:09:04.6|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer. Unexpected response status Unauthorized code from API request
2021-11-15 12:09:04.6|Trace|Http|Res: 25 [POST] /prowlarr/api/v1/indexer/test: 400.BadRequest (1756 ms)```

[AB#1911](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1911)

**Comment by bakerboy448** [comment]
Notes:
- Per Elf works in Jackett
- Per my initial debugging when we set the header value in the CardigannDefinition it is not substituting the value and is using the placeholder still
https://github.com/Prowlarr/Prowlarr/blob/1aa914986600e0a494f7752d2850cdc098887aa9/src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannDefinition.cs#L140

**Comment by bakerboy448** [comment]
seems we just don't have support for apikeys in Prowlarr Cardigann when perusing jackett commits
https://github.com/Jackett/Jackett/search?p=4&q=apikey&type=code

**Comment by HalianElf** [comment]
Confirming the fixes baker did last night did fix it.
