### ISSUE TITLE
http request failed [404:NotFound] when opening Prowlarr

### ISSUE THREAD

**Issue by Manfred73** [Prowlarr/Prowlarr#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have Prowlarr (Apache80) package installed on QNAP (version: v0.1.0.136), but when trying to open it, I get an error message:

HTTP request failed: [404:NotFound] [GET] at [https://indexers.prowlarr.com/master/1/montorrent]
Version 0.1.0.771 

### Expected Behavior

Expected get into Prowlarr. 

### Environment

```markdown
- OS: QNAP h5.0.0.1772
- Prowlarr: v0.1.0.136
- Docker Install:
- Using Reverse Proxy:
- Browser: Chrome
```

### What branch are you running?

Develop

### Anything else?

2021-11-14 14:00:40.1|Error|CommandExecutor|Error occurred while executing task CheckHealth

[v0.1.0.771] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://indexers.prowlarr.com/master/1/tntfork]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 114
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 272
   at NzbDrone.Core.IndexerVersions.IndexerDefinitionUpdateService.GetHttpDefinition(String id) in D:\a\1\s\src\NzbDrone.Core\IndexerVersions\IndexerDefinitionUpdateService.cs:line 138
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.IndexerVersions.IndexerDefinitionUpdateService.GetDefinition(String file) in D:\a\1\s\src\NzbDrone.Core\IndexerVersions\IndexerDefinitionUpdateService.cs:line 120
   at NzbDrone.Core.Indexers.IndexerFactory.MapCardigannDefinition(IndexerDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 79
   at NzbDrone.Core.Indexers.IndexerFactory.All() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 53
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Active() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 153
   at NzbDrone.Core.Indexers.IndexerFactory.Active() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 74
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.GetAvailableProviders() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 91
   at NzbDrone.Core.Indexers.IndexerFactory.Enabled(Boolean filterBlockedIndexers) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 188
   at NzbDrone.Core.HealthCheck.Checks.IndexerCheck.Check() in D:\a\1\s\src\NzbDrone.Core\HealthCheck\Checks\IndexerCheck.cs:line 31
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at NzbDrone.Core.HealthCheck.HealthCheckService.PerformHealthCheck(IProvideHealthCheck[] healthChecks) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 72
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 118
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

2021-10-19 11:30:40.5|Warn|ProwlarrErrorPipeline|NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://indexers.prowlarr.com/master/1/tntfork]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 114
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 272
   at NzbDrone.Core.IndexerVersions.IndexerDefinitionUpdateService.GetHttpDefinition(String id) in D:\a\1\s\src\NzbDrone.Core\IndexerVersions\IndexerDefinitionUpdateService.cs:line 138
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
   at NzbDrone.Core.IndexerVersions.IndexerDefinitionUpdateService.GetDefinition(String file) in D:\a\1\s\src\NzbDrone.Core\IndexerVersions\IndexerDefinitionUpdateService.cs:line 120
   at NzbDrone.Core.Indexers.IndexerFactory.MapCardigannDefinition(IndexerDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 79
   at NzbDrone.Core.Indexers.IndexerFactory.All() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 53
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Active() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 153
   at NzbDrone.Core.Indexers.IndexerFactory.Active() in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerFactory.cs:line 74
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.GetAvailableProviders() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 91
   at NzbDrone.Core.IndexerSearch.NzbSearchService.Dispatch(Func`2 searchAction, SearchCriteriaBase criteriaBase) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 140
   at NzbDrone.Core.IndexerSearch.NzbSearchService.MusicSearch(NewznabRequest request, List`1 indexerIds, Boolean interactiveSearch) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 74
   at NzbDrone.Api.V1.Indexers.NewznabController.GetNewznabResponse(Int32 id, NewznabRequest request) in D:\a\1\s\src\Prowlarr.Api.V1\Indexers\NewznabController.cs:line 128
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[AB#1934](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1934)

**Comment by Manfred73** [comment]
Update: I uninstalled the package and reïnstalled the original package. Then did an update to  latest version 0.1.4.1120. I can now get into Prowlarr again. Unfortunately, need to reconfigure everything again. Not sure why I was getting the errors mentioned before.

**Comment by ta264** [comment]
Upgrade prowlarr, you're 800 builds out of date. Then come to discord for support if issues persist.

**Comment by ta264** [comment]
Sorry, missed your follow up. The original build is so old who knows what's going on
