### ISSUE TITLE
Cardigann DoLogin not using defined encoding 

### ISSUE THREAD

**Issue by Qstick** [Prowlarr/Prowlarr#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Auth fails on some indexers due to encoding.

### Expected Behavior

Login should use Encoding defined in yml for login requests and not just search queries 

### Steps To Reproduce

Use https://deildu.net/

### Environment

```markdown
- OS: 
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Anything else?

```
2021-11-26 12:37:57.9|Warn|Cardigann|Unable to connect to indexer

[v0.1.3.1113] System.ArgumentException: 'latin1_swedish_ci' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at NzbDrone.Common.Http.HttpHeader.GetEncodingFromContentType(String contentType) in D:\a\1\s\src\NzbDrone.Common\Http\HttpHeader.cs:line 150
   at NzbDrone.Common.Http.HttpHeader.GetEncodingFromContentType() in D:\a\1\s\src\NzbDrone.Common\Http\HttpHeader.cs:line 134
   at NzbDrone.Common.Http.HttpResponse.get_Content() in D:\a\1\s\src\NzbDrone.Common\Http\HttpResponse.cs:line 60
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 159
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 68
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 198
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 159
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 389
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 321
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 457
```

[AB#1983](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1983)

**Comment by Qstick** [comment]
10aa3e43a2d68f9c07b5d8802d030c7f50a10911
