### ISSUE TITLE
"Input string was not in a correct format" error when going to the indexers > stats tab

### ISSUE THREAD

**Issue by df-a** [Prowlarr/Prowlarr#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On nightly "0.1.6.1184", whenever I go to the 'http://localhost:9696/indexers/stats' tab I get a Input string was not in a correct format error. The stats won't load, only that error.

### Expected Behavior

I expect to see the per indexer stats.

### Steps To Reproduce

1. Updated to nightly "0.1.6.1184" from within the app
2. Update successful, reloaded prowlarr
3. Went to the "Indexer > Stats" page (http://localhost:9696/indexers/stats) and am only greeted by the error

### Environment

```markdown
- OS: macOs Catalina 10.15/7
- Prowlarr: 0.1.6.1184
- Docker Install: N/A, installed by DMG
- Using Reverse Proxy: none
- Browser: Brave
```

### What branch are you running?

Nightly

### Trace Logs?

[prowlarr-trace.txt](https://github.com/Prowlarr/Prowlarr/files/7646029/prowlarr-trace.txt)

![Screen Shot 2021-12-02 at 20 58 27](https://user-images.githubusercontent.com/1872835/144526703-d6bce43a-57ce-4244-bc29-24d9107d2703.jpg)

[AB#2028](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2028)

**Comment by df-a** [comment]
Message
```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at NzbDrone.Core.IndexerStats.IndexerStatisticsService.<>c.<IndexerStatistics>b__3_7(History h) in D:\a\1\s\src\NzbDrone.Core\IndexerStats\IndexerStatisticsService.cs:line 58
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at NzbDrone.Core.IndexerStats.IndexerStatisticsService.IndexerStatistics(DateTime start, DateTime end) in D:\a\1\s\src\NzbDrone.Core\IndexerStats\IndexerStatisticsService.cs:line 58
   at Prowlarr.Api.V1.Indexers.IndexerStatsController.GetAll(Nullable`1 startDate, Nullable`1 endDate) in D:\a\1\s\src\Prowlarr.Api.V1\Indexers\IndexerStatsController.cs:line 24
   at lambda_method265(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task): Input string was not in a correct format.
```

Exception
```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at NzbDrone.Core.IndexerStats.IndexerStatisticsService.<>c.<IndexerStatistics>b__3_7(History h) in D:\a\1\s\src\NzbDrone.Core\IndexerStats\IndexerStatisticsService.cs:line 58
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at NzbDrone.Core.IndexerStats.IndexerStatisticsService.IndexerStatistics(DateTime start, DateTime end) in D:\a\1\s\src\NzbDrone.Core\IndexerStats\IndexerStatisticsService.cs:line 58
```

**Comment by df-a** [comment]
Awesome, thanks for the fix!
