### ISSUE TITLE
[Bittorrentfiles] not working

### ISSUE THREAD

**Issue by kingofdunghill** [Prowlarr/Prowlarr#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to add Bittorrentfiles as an indexer. login credentials are correct as other configuration (base url bittorrentfiles.me, standard profile) is. Test and save fail. Other tracker are all addable properly.

BTW: Very nice and helpful tool, great job!

### Expected Behavior

Tracker should be connectable and addable.

### Steps To Reproduce

1. just try to add the indexer bittforrentfiles with correct login credentials
2. will fail right now (pretty sure its a common issue, i think they have made changes recently)

### Environment

```markdown
- OS: Ubuntu 18.04
- Prowlarr: 0.1.6.1184
- Docker Install: ghcr.io/linuxserver/prowlarr:develop
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Develop

### Trace Logs?

2021-12-03 14:48:16.4|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2021-12-03 14:48:16.5|Trace|ServerSideNotificationService|Getting server side health notifications
2021-12-03 14:48:16.5|Trace|ServerSideNotificationService|Getting server side health notifications
2021-12-03 14:48:16.5|Trace|HttpClient|Req: [GET] https://prowlarr.servarr.com/v1/notification?version=0.1.6.1184&os=linux&arch=X64&runtime=netcore&branch=develop
2021-12-03 14:48:16.5|Trace|HttpClient|Req: [GET] https://prowlarr.servarr.com/v1/notification?version=0.1.6.1184&os=linux&arch=X64&runtime=netcore&branch=develop
2021-12-03 14:48:16.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-03 14:48:16.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-03 14:48:16.5|Trace|Http|Res: 885 [PUT] /api/v1/config/host: 202.Accepted (1945 ms)
2021-12-03 14:48:16.5|Debug|Api|[PUT] /api/v1/config/host: 202.Accepted (1945 ms)
2021-12-03 14:48:16.6|Trace|HttpClient|Res: [GET] https://prowlarr.servarr.com/v1/notification?version=0.1.6.1184&os=linux&arch=X64&runtime=netcore&branch=develop: 200.OK (123 ms)
2021-12-03 14:48:16.6|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-12-03 14:48:16.6|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2021-12-03 14:48:16.6|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2021-12-03 14:48:16.6|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-12-03 14:48:16.6|Trace|HttpClient|Res: [GET] https://prowlarr.servarr.com/v1/notification?version=0.1.6.1184&os=linux&arch=X64&runtime=netcore&branch=develop: 200.OK (138 ms)
2021-12-03 14:48:16.6|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-12-03 14:48:16.6|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2021-12-03 14:48:16.6|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2021-12-03 14:48:16.6|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-12-03 14:48:16.7|Trace|Http|Req: 886 [GET] /api/v1/health (from 212.*.*.246)
2021-12-03 14:48:16.7|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-12-03 14:48:16.7|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-12-03 14:48:17.2|Trace|Http|Res: 886 [GET] /api/v1/health: 200.OK (520 ms)
2021-12-03 14:48:17.2|Debug|Api|[GET] /api/v1/health: 200.OK (520 ms)
2021-12-03 14:48:17.2|Trace|Http|Req: 887 [GET] /api/v1/health (from 212.*.*.246)
2021-12-03 14:48:17.2|Trace|Http|Res: 887 [GET] /api/v1/health: 200.OK (0 ms)
2021-12-03 14:48:17.2|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-12-03 14:48:21.6|Trace|Http|Req: 888 [GET] /api/v1/indexer/schema (from 212.*.*.246)
2021-12-03 14:48:21.8|Trace|HttpClient|Req: [GET] https://indexers.prowlarr.com/master/3
2021-12-03 14:48:21.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-03 14:48:22.1|Trace|HttpClient|Res: [GET] https://indexers.prowlarr.com/master/3: 200.OK (290 ms)
2021-12-03 14:48:22.7|Trace|Http|Res: 888 [GET] /api/v1/indexer/schema: 200.OK (1013 ms)
2021-12-03 14:48:22.7|Debug|Api|[GET] /api/v1/indexer/schema: 200.OK (1013 ms)
2021-12-03 14:48:26.4|Trace|Http|Req: 889 [POST] /api/v1/indexer/action/getUrls (from 212.*.*.246)
2021-12-03 14:48:26.9|Trace|Http|Res: 889 [POST] /api/v1/indexer/action/getUrls: 200.OK (496 ms)
2021-12-03 14:48:26.9|Debug|Api|[POST] /api/v1/indexer/action/getUrls: 200.OK (496 ms)
2021-12-03 14:48:27.8|Trace|Scheduler|Pending Tasks: 0
2021-12-03 14:48:51.6|Trace|Http|Req: 890 [POST] /api/v1/indexer/test (from 212.*.*.246)
2021-12-03 14:48:51.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-12-03 14:48:51.6|Debug|Cardigann|Populating config vars
2021-12-03 14:48:51.6|Info|Cardigann|Adding request: https://bittorrentfiles.me/browse.php?search=&search_where=0&status=1&orderby=added&sort=desc
2021-12-03 14:48:51.6|Debug|Cardigann|Downloading Feed https://bittorrentfiles.me/browse.php?search=&search_where=0&status=1&orderby=added&sort=desc
2021-12-03 14:48:51.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-12-03 14:48:51.6|Trace|IndexerHttpClient|Req: [GET] https://bittorrentfiles.me/browse.php?search=&search_where=0&status=1&orderby=added&sort=desc
2021-12-03 14:48:51.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-03 14:48:53.6|Trace|IndexerHttpClient|Res: [GET] https://bittorrentfiles.me/browse.php?search=&search_where=0&status=1&orderby=added&sort=desc: 302.Redirect (2026 ms)
2021-12-03 14:48:53.6|Trace|Cardigann|Attempting to re-auth based on indexer search response
2021-12-03 14:48:53.6|Trace|IndexerHttpClient|Req: [GET] https://bittorrentfiles.me/signin.php
2021-12-03 14:48:53.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-03 14:48:53.9|Trace|IndexerHttpClient|Res: [GET] https://bittorrentfiles.me/signin.php: 200.OK (262 ms)
2021-12-03 14:48:54.3|Trace|IndexerHttpClient|Response content (2636 bytes):     
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml"> 
        <head>
            <title>bittorrentfiles</title>
            
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
            <meta http-equiv="Content-Style-Type" content="text/css" />
            <meta http-equiv="Content-Script-Type" content="text/javascript" />
            <meta http-equiv="Expires" content="300" />
            <meta http-equiv="Cache-Control" content="Private" />
            <meta http-equiv="Connection" content="Keep-Alive" />
            <meta http-equiv="Connection-Timeout" content="300" />
            <meta name="robots" content="noindex, nofollow, noarchive" />
            <meta name="MSSmartTagsPreventParsing" content="true" />
                      
            <link rel="stylesheet" href="/site/style/style.css" type="text/css" />
        </head>
        
        <body>
            <div id=(removed)            	<div id=(removed)                    <div id=(removed)                        <ul id=(removed)            
                            <li ><a href="index.php">Home</a></li>
                            <li ><a href="news_ticker.php">Ticker</a></li>
                            <li ><a href="linux.php">Linux</a></li>
                            <li ><a href="protocol.php">BT-Protocol</a></li>
                            <li ><a href="client.php">Clients</a></li>
                            <li ><a href="torrent_lister.php">Lister</a></li>
                                                        <li ><a href="irc.php">IRC</a></li>
                        </ul>
            		</div>
            	</div>
            
            	<div id=(removed)            		<div class="sidebar">                    	
                            <h1><br /></h1>
                            <h4><br /></h4>
                            <h5><br /></h5>
                            <p><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /></p>                        
						            		</div>
            		<div id=(removed)<h1>Dev-Team</h1>

<p class='error'>Die maximalen Anmeldungsversuche wurden &uuml;berschritten.<br />Weiterhin wurde die genutzte IP <strong>***.***.***.***</strong> f&uuml;r 1 Stunde gesperrt!</p>    
    				</div>
            	</div>
    			<div id=(removed)      				<p><a href="/contact.php">Contact</a><a href="/disclaimer.php">Disclaimer</a>&copy; bittorrentfiles 2021</p>
    			</div>
  			</div>
		</body>
	</html>
    
    
2021-12-03 14:48:54.4|Warn|Cardigann|Unable to connect to indexer

[v0.1.6.1184] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannConfigException: Login failed: No form found on https://bittorrentfiles.me/signin.php using form selector form
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 230
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 159
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 388
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 519

2021-12-03 14:48:57.8|Trace|Scheduler|Pending Tasks: 0
2021-12-03 14:48:54.7|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.6.1184] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 205
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2021-12-03 14:49:02.4|Trace|ProwlarrErrorPipeline|Handling Exception
2021-12-03 14:49:02.4|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 205
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[v0.1.6.1184] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 205
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2021-12-03 14:49:02.9|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
2021-12-03 14:49:02.9|Trace|Http|Res: 890 [POST] /api/v1/indexer/test: 400.BadRequest (11306 ms)
2021-12-03 14:49:02.9|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (11306 ms)
2021-12-03 14:49:05.2|Trace|Http|Req: 891 [GET] /api/v1/health (from 212.*.*.246)
2021-12-03 14:49:05.2|Trace|Http|Res: 891 [GET] /api/v1/health: 200.OK (0 ms)
2021-12-03 14:49:05.2|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2021-12-03 14:49:05.2|Trace|Http|Req: 892 [GET] /api/v1/system/status (from 212.*.*.246)
2021-12-03 14:49:05.2|Trace|Http|Res: 892 [GET] /api/v1/system/status: 200.OK (1 ms)
2021-12-03 14:49:05.2|Debug|Api|[GET] /api/v1/system/status: 200.OK (1 ms)
2021-12-03 14:49:07.1|Trace|Http|Req: 893 [GET] /api/v1/log/file (from 212.*.*.246)
2021-12-03 14:49:07.1|Trace|Http|Res: 893 [GET] /api/v1/log/file: 200.OK (1 ms)
2021-12-03 14:49:07.1|Debug|Api|[GET] /api/v1/log/file: 200.OK (1 ms)
2021-12-03 14:49:11.4|Trace|Http|Req: 894 [GET] /logfile/prowlarr.trace.txt (from 212.*.*.246)

**Comment by bakerboy448** [comment]
Those are not trace logs and just the errror saying it failed validation doesn't tell anything.

Also please do not share the logs directly in the issue as they are extremely difficult to read and make reading the issue difficult as well.

see the wiki which was linked in the template for how to get and provide logs 
https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files

**Comment by kingofdunghill** [comment]
Ok, looks like they have temporarly banned my account due wrong password (didnt spell it wrong for sure) for a hour. Will try it again later.

**Comment by kingofdunghill** [comment]
Can be deleted. Not a prowlarr issue.

(Probably an interference with a parallel established connection to the tracker with the j*** tool and a resulting suspect pattern at btf.

**Comment by kingofdunghill** [comment]
Hm. Unluckily it still consists. The IP lock was removed by tracker and i can connect with same login credentials to bittorrentfiles over jackett flawlessly. So it must be a issue at prowlarr side. New trace logs added above.
