### ISSUE TITLE
Cardigann does not support UserAgents in Headers

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#670]
[v10.0.0.36096] System.NotSupportedException: User-Agent other than Prowlarr not allowed.
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.AddRequestHeaders(HttpWebRequest webRequest, HttpHeader headers) in C:\Development\Code\Prowlarr\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 257
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in C:\Development\Code\Prowlarr\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 66

[AB#2071](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2071)

**Comment by Qstick** [comment]
Intentional

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/0f52258d53258081f26887e60fa61bd48f40d2bc
