### ISSUE TITLE
Indexer AudiobookBay failing to add

### ISSUE THREAD

**Issue by aaronldunlap** [Prowlarr/Prowlarr#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding the indexer AudiobookBay consistently fails for multiple days now, using any of the provided base domains. Nothing is visible to the user, but the logs reveal the request simply timed out.

### Expected Behavior

Audiobookbay should add as an indexer s

### Steps To Reproduce

Add indexer
Select Audiobookbay
Select any base URL except for the last one (unblockit.bz)

### Environment

```markdown
- OS: Linux hyperion 5.10.0-0.bpo.8-amd64 #1 SMP Debian 5.10.46-4~bpo10+1 (2021-08-07) x86_64
- Prowlarr: 0.1.6.1184
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: safari ios
```

### What branch are you running?

Develop

### Trace Logs?

```
[v0.1.6.1184] System.Net.WebException: The operation has timed out.: 'http://audiobookbay.nl/'
 ---> System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 154
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 154
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 144
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 68
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 381
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 456
```

[AB#2075](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2075)

**Comment by bakerboy448** [comment]
Indexers Timing out is not a Prowlarr issue.  The issue lies with issues with your local networking, ISP, or routing to the site.
