### ISSUE TITLE
[GazelleGames] Does not pass validation or search

### ISSUE THREAD

**Issue by delize** [Prowlarr/Prowlarr#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

GazelleGames returns errors when validating indexer or searching for content.

When reaching out on Discord: https://discord.com/channels/767843854736949299/767843854824374281/925106015886782474

There was an attempted fix: https://discord.com/channels/767843854736949299/767843855335817251/925108525414363146
Was requested to file a Github Issue: https://discord.com/channels/767843854736949299/767843854824374281/925112359217942628

### Expected Behavior

Gazelle Games should return a successful test when on the indexer page
Gazelle Games should return a successful search result

### Steps To Reproduce

1. Add GazelleGames to Prowlarr
2. Test Indexer - This should result in "Success, bu failure" message
3. Test search for "Mario" or "Mario Party" and return error result

### Environment

```markdown
- OS: Ubuntu 20.04.3
- Prowlarr: 0.1.9.1276
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome 96.0.4664.110 (Official Build) (x86_64)

LinuxServer Docker container for reference
```

### What branch are you running?

Nightly

### Trace Logs?

[v0.1.9.1276] FluentValidation.ValidationException: Validation failed:  -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 205   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 191   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 67   at lambda_method303(Closure , Object , Object[] )   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()--- End of stack trace from previous location ---   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()--- End of stack trace from previous location ---   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-12-27 12:18:54.3|Warn|ProwlarrErrorPipeline|Invalid request Validation failed:  -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
2021-12-27 12:28:54.5|Info|ReleaseSearchService|Searching indexer(s): [GazelleGames] for Term: [mario party], Offset: 0, Limit: 0, Categories: []
2021-12-27 12:28:55.9|Error|GazelleGames|An error occurred while processing indexer feed. https://gazellegames.net/torrents.php?searchstr=mario+party&order_by=time&order_way=desc&action=basic&searchsubmit=1[v0.1.9.1276] System.OverflowException: Value was either too large or too small for an Int32.   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)   at NzbDrone.Core.Parser.ParseUtil.CoerceInt(String str) in D:\a\1\s\src\NzbDrone.Core\Parser\ParseUtil.cs:line 42   at NzbDrone.Core.Indexers.Definitions.GazelleGamesParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\GazelleGames.cs:line 361   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174RequestUri: https://gazellegames.net/torrents.php?searchstr=mario+party&order_by=time&order_way=desc&action=basic&searchsubmit=1;StatusCode: OK;ContentType: text/html; charset=utf-8;ContentLength: 720687;ContentSample: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head>    <title>Browse Torrents :: GazelleGames.net</title>    <meta http-equiv="X-UA-Compatible" content="chrome=1;IE=edge"/>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>    <meta name="msapplication-config" content="none"/>    <meta name="viewport" content="width=device-width,initial-scale=1.0">    <link rel="shortcut icon" href="favicon.ico"/>    <link rel="search" type="application/opensearchdescription+xml" title="GazelleGames" href="static/opensearch.xml">    <link rel="alternate" type="application/rss+xml"          href="/feeds.php?feed=feed_news&amp;user=(removed)&amp;auth=(removed)&amp;passkey=(removed)&amp;authkey=(removed)          title="GazelleGames.net - News"/>    <link rel="alternate" type="application/rss+xml"          href="/feeds.php?feed=feed_blog&amp;user=(removed)&amp;auth=(removed)&amp;passkey=(removed)&amp;authkey=(removed)          title="GazelleGames.net - Blog"/>    <link rel="alternate" type="application/rss+xml"          href="/feeds.php?feed=torrents_notify_cd0lzb79kn81af45m023zhx264b4ezk6&amp;user=(removed)&amp;auth=(removed)&amp;passkey=(removed)&amp;authkey=(removed)          title="GazelleGames.net - P.T.N."/>	                <link rel="alternate" type="application/rss+xml"                      href="/feeds.php?feed=torrents_notify_10415_cd0lzb79kn81af45m023zhx264b4ezk6&amp;user=(removed)&amp;auth=(removed)&amp;passkey=(removed)&amp;authkey=(removed)&amp;name=Tony+Hawk%26%2339%3Bs+Pro+Skater+1+++2"                      title="GazelleGames.net - Tony Hawk&#39;s Pro Skater 1   2"/>				    <link rel="alternate" type="application/rss+xml"          href="/feeds.php?feed=torrents_all&amp;user=(removed)&amp;auth=(removed)&amp;passkey=(removed)&amp;authkey=(removed)          title="GazelleGames.net - All Torrents"/>    <link rel="alternate" type="application/rss+xml"          href="/feeds.php?feed=torrents_music&amp;user=(removed)&amp;auth=(removed)&amp;passkey=(removed)&amp;authkey=(removed)          title="GazelleGames.net - Game Torrents"/>    <link rel="alternate" type="application/rss+xml"          href="/feeds.php?feed=torrents_apps&amp;user=(removed)&amp;auth=(removed)&amp;passkey=(removed)&amp;authkey=(removed)          title="GazelleGames.net - Application Torrents"/>    <link rel="alternate" type="application/rss+xml"          href="/feeds.php?feed=torrents_ebooks&amp;user=(removed)&amp;auth=(removed)&amp;passkey=(removed)&amp;authkey=(removed)          title="GazelleGames.net - E-Book Torrents"/>    <link rel="stylesheet" type="text/css"          href="static/styles/global.css?v=1617933543"/>

[AB#2276](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2276)

**Comment by Qstick** [comment]
Can you go to `https://gazellegames.net/torrents.php?searchstr=mario+party&order_by=time&order_way=desc&action=basic&searchsubmit=1` in a browser where you are signed into the site. Paste the response here please.

**Comment by delize** [comment]
Here is a screenshot taken from my phone. 
I launched the URL you posted above. I'm not sure what other response you were looking for.
![Screenshot_20220103-021330](https://user-images.githubusercontent.com/4028612/147910482-b4a263db-711e-4285-8927-5b3223d60c18.png)

**Comment by pairofcrocs** [comment]
I'm also having this exact same issue.

**Comment by Qstick** [comment]
Please Test on 0.4.3.1884 or above

**Comment by delize** [comment]
Hey @Qstick 

Still seeing similar issues with GGN.

```text
Version
0.4.3.1893
Package Version
0.4.3.1893-ls380 by [linuxserver.io](https://www.linuxserver.io/)
.NET
Yes (6.0.6)
Docker
Yes
DB Migration
20
Database
Sqlite 3.36.0
AppData directory
/config
Startup directory
/app/prowlarr/bin
Mode
Console
Uptime
00:03:28
```

`Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.`

```text

2022-07-06 21:50:33.3|Trace|IndexerHttpClient|Res: [GET] https://gazellegames.net/torrents.php?searchstr=&order_by=time&order_way=desc&action=basic&searchsubmit=1: 302.Redirect (0 bytes) (191 ms)
2022-07-06 21:50:33.3|Trace|GazelleGames|
2022-07-06 21:50:33.3|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.4.3.1893] FluentValidation.ValidationException: Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-07-06 21:50:33.4|Trace|ProwlarrErrorPipeline|Handling Exception
2022-07-06 21:50:33.4|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.

[v0.4.3.1893] FluentValidation.ValidationException: Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 204
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-07-06 21:50:33.5|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
2022-07-06 21:50:33.5|Trace|Http|Res: 39 [POST] /prowlarr/api/v1/indexer/test: 400.BadRequest (2423 ms)
```

**Comment by Qstick** [comment]
Going to need access to do anything with this, or PRs are welcome
