### ISSUE TITLE
RuTor indexer failed

### ISSUE THREAD

**Issue by dm3ch** [Prowlarr/Prowlarr#760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Indexer marked as failed

### Expected Behavior

Idexer works

### Environment

```markdown
- OS: 
- Prowlarr: 0.1.9.1313
- Docker Install: Yes - 0.1.9.1313-ls35 by linuxserver.io
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Nightly

### Trace Logs?

Unable to connect to indexer: Unable to cast object of type 'System.String' to type 'System.Boolean'.

System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Boolean'.
   at NzbDrone.Core.Indexers.Cardigann.CardigannBase.GetBaseTemplateVariables() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannBase.cs:line 306
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.GetQueryVariableDefaults(SearchCriteriaBase searchCriteria) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 163
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.GetSearchRequests(BasicSearchCriteria searchCriteria) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 117
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 449

[AB#2306](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2306)

**Comment by bakerboy448** [comment]
> Unable to connect to indexer: Unable to cast object of type 'System.String' to type 'System.Boolean'.

these are not trace logs and are just the error spew.

> # Trace Logs?
> **Trace Logs (https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files)**
> Generally speaking, all bug reports must have trace logs provided.
> Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
> Additionally, any additional info? Screenshots? References? Anything that will give us more context about the issue you are encountering!

**Comment by dm3ch** [comment]
@bakerboy448 I have searched throw my trace logs and it seems it's the only part that refer to problem:
```
2022-01-04 00:02:00.3|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2022-01-04 00:02:00.3|Debug|Cardigann|Populating config vars
2022-01-04 00:02:00.3|Warn|Cardigann|Unable to connect to indexer

[v0.1.9.1313] System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Boolean'.
   at NzbDrone.Core.Indexers.Cardigann.CardigannBase.GetBaseTemplateVariables() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannBase.cs:line 306
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.GetQueryVariableDefaults(SearchCriteriaBase searchCriteria) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 163
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.GetSearchRequests(BasicSearchCriteria searchCriteria) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 117
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 519
   ```
   If you want - I can share whole trace log

**Comment by Qstick** [comment]
Can you share what your setting are for the indexer and what was searched right before the error to get that result? (the call to rutor)

I was able to add and search fine, but it could be an edge case

![image](https://user-images.githubusercontent.com/376117/147993520-5060ce8b-04e0-446c-93d3-e5b316fc7e1f.png)

**Comment by dm3ch** [comment]
@Qstick Here's my configuration. Actually, I haven't performed a search manually, I just clicked the retest button from the problem view (where RuTor indexer was marked as not working).

<img width="777" alt="Screenshot 2022-01-04 at 03 15 45" src="https://user-images.githubusercontent.com/5025313/147993846-9d27b5d3-938e-4504-93bb-54e20ca9d533.png">
<img width="777" alt="Screenshot 2022-01-04 at 03 15 51" src="https://user-images.githubusercontent.com/5025313/147993847-28f6d00a-9e03-4ab5-9c1e-bb2e0887f81b.png">

I tried to recreate the indexer after taking screenshots and now it works.

**Comment by Qstick** [comment]
Maybe a settings migration on the yml

**Comment by dm3ch** [comment]
Isn't indexer setting update automatically when a definition is updated, is it?

**Comment by Qstick** [comment]
There's an issue that occurs due to how we store the old settings. So if settings are modified or type changed I think this will happen
