### ISSUE TITLE
Disable SSL checks for indexers

### ISSUE THREAD

**Issue by gotson** [Prowlarr/Prowlarr#846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

tasmanit.es has issues with their domain, they basically lost access to it. To circumvent that, setting the host files or custom DNS to resolve the hostname to the IP works. However, the SSL certificate is expired, and gives warning in browser, and Prowlarr won't connect to it because of that.

### Describe the solution you'd like

I would like a way to disable SSL certificate checks when connecting to a particular indexer.

This could be done either via the UI (probably overkill), some config (don't know where), or maybe directly on the indexer definition itself, given this is for a single indexer, until they can fix their domain issues (if ever).

### Describe alternatives you've considered

None, i don't know what else to do.

### Anything else?

Nope.

[AB#2583](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2583)

**Comment by bakerboy448** [comment]
This can be done on a per indexer basis - simply by updating the definition  like was done with Jackett here

https://github.com/Jackett/Jackett/commit/be4acdebf7bc79b7018bb17b6e5eea017930af63

Easiest way is report the issue to Jackett, provide the cert hash, and we'll pull their defintion updates down - you'd be able to use their updated def file in the interim 

https://github.com/Prowlarr/Indexers

https://wiki.servarr.com/prowlarr/indexers#adding-a-custom-yml-definition

**Comment by gotson** [comment]
> provide the cert hash

how does one find the cert hash?

**Comment by gotson** [comment]
> > provide the cert hash
> 
> how does one find the cert hash?

Managed to find it!

**Comment by gotson** [comment]
Hi @bakerboy448 , sorry for commenting on that closed issue.

My [Jacket PR](https://github.com/Jackett/Jackett/pull/12955) has been merged, and pulled in Prowlarr. After the update of my Prowlarr instance, this still doesn't work. It works on Jackett though.

```
[Error] X509CertificateValidationService: Certificate validation for https://tasmanit.es/browse.php failed. RemoteCertificateChainErrors 
[Warn] Cardigann: Unable to connect to indexer 

[v0.2.0.1534] System.Net.WebException: The SSL connection could not be established, see inner exception.: 'https://tasmanit.es/browse.php'
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 129
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 129
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 145
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 69
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 381
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 456
```

**Comment by bakerboy448** [comment]
Did you run the indexer definition refresh task?

**Comment by gotson** [comment]
It did by itself yes, and I just ran it again manually, but still getting errors.

**Comment by bakerboy448** [comment]
...what the hell then 

works fine here - so you and this poor <https://www.reddit.com/r/prowlarr/comments/somvpe/query_successful_but_no_results_were_returned/hx81o80/> sap have the same issue with the SSL certs - yet the certs are clearly fine

I also can't reproduce either - both `tasmanit` and `torrenting` have no issues and don't throw any SSL issues.

**Comment by SteffanCline** [comment]
Curious. @gotson, who is your ISP?

**Comment by gotson** [comment]
Keep in mind that you need to update your host file or use a custom DNS, so that the website is pointing to the correct ip, as described here: https://www.reddit.com/r/trackers/comments/r5pzs3/tasmanites_any_news/?utm_medium=android_app&utm_source=share

**Comment by gotson** [comment]
The indexer is still not available with the updated definition, while it works in Jackett. Should i open a new issue somewhere?

**Comment by bakerboy448** [comment]
> The indexer is still not available with the updated definition, while it works in Jackett. Should i open a new issue somewhere?

https://github.com/Prowlarr/Indexers/blob/f929290959526b58658297a97faa9f2018716c8f/definitions/v2/tasmanit.yml

The indexer was updated 3 weeks ago.


Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

Bring trace logs of the definition refresh task not updating anything.

**Comment by gotson** [comment]
@bakerboy448 maybe I wasn't clear, sorry.

I have the updated definition (already mentioned it [here](https://github.com/Prowlarr/Prowlarr/issues/846#issuecomment-1041560853)). However, the task still fails with the message i [posted above](https://github.com/Prowlarr/Prowlarr/issues/846#issuecomment-1041265023).

Jacket, with the same updated definition, works. Prowlarr doesn't.
