### ISSUE TITLE
Generic torznab - indexer from Jackett is failed when downloading torrent file

### ISSUE THREAD

**Issue by SuberSeb** [Prowlarr/Prowlarr#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error when downloading torrent file.

### Expected Behavior

Torrent file will be downloaded.

### Steps To Reproduce

Try to add indexer Kinozal from Jackett into Prowlarr as generic torznab. Then try to search something and try to add download. Prowlarr can't download torrent file while Jackett is working. Seems that this is bug.

### Environment

```markdown
- OS: Unraid 6.9.2
- Prowlarr: 0.2.0.1448
- Docker Install: 0.2.0.1448-ls43 by linuxserver.io
- Using Reverse Proxy: no
- Browser: Firefox latest
```

### What branch are you running?

Develop

### Trace Logs?

2022-03-14 23:43:08.2|Error|Torznab|An error occurred while processing indexer feed. http://192.168.1.45:9117/api/v2.0/indexers/kinozal/results/torznab/api?t=search&extended=1&cat=3000,3030&apikey=(removed)&limit=100&offset=0

[v0.2.0.1581] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (kinozal): Resource temporarily unavailable
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable (kinozal.tv:80)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 607
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1383
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 771
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 434
   at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Torznab\TorznabRssParser.cs:line 42
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174
RequestUri: http://192.168.1.45:9117/api/v2.0/indexers/kinozal/results/torznab/api?t=search&extended=1&cat=3000,3030&apikey=(removed)&limit=100&offset=0;StatusCode: OK;ContentType: application/xml; charset=utf-8;ContentLength: 4308;ContentSample: <?xml version="1.0" encoding="UTF-8"?>
<error code="900" description="Jackett.Common.IndexerException: Exception (kinozal): Resource temporarily unavailable&#xA; ---&gt; System.Net.Http.HttpRequestException: Resource temporarily unavailable (kinozal.tv:80)&#xA; ---&gt; System.Net.Sockets.SocketException (11): Resource temporarily unavailable&#xA;   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)&#xA;   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)&#xA;   at System.Net.Sockets.Socket.&lt;ConnectAsync&gt;g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)&#xA;   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)&#xA;   --- End of inner exception stack trace ---&#xA;   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)&#xA;   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xA;   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xA;   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)&#xA;   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)&#xA;   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xA;   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)&#xA;   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xA;   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)&#xA;   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)&#xA;   at System.Net.Http.HttpClient.&lt;SendAsync&gt;g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)&#xA;   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178&#xA;   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 607&#xA;   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1383&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415&#xA;   --- End of inner exception stack trace ---&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 771&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 434" />;FeedUrl: http://192.168.1.45:9117/api/v2.0/indexers/kinozal/results/torznab/api?t=search&extended=1&cat=3000,3030&apikey=(removed)&limit=100&offset=0

**Comment by SuberSeb** [comment]
`"System.NotSupportedException: The URI prefix is not recognized.\n   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)\n   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in D:\\a\\1\\s\\src\\NzbDrone.Common\\Http\\Dispatchers\\ManagedHttpDispatcher.cs:line 129\n   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in D:\\a\\1\\s\\src\\NzbDrone.Common\\Http\\HttpClient.cs:line 145\n   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\\a\\1\\s\\src\\NzbDrone.Common\\Http\\HttpClient.cs:line 95\n   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Indexers\\IndexerHttpClient.cs:line 42\n   at NzbDrone.Core.Indexers.TorrentIndexerBase`1.Download(Uri link) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Indexers\\TorrentIndexerBase.cs:line 46\n   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Download\\DownloadService.cs:line 131\n   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in D:\\a\\1\\s\\src\\Prowlarr.Api.V1\\Indexers\\NewznabController.cs:line 202\n   at lambda_method219(Closure , Object )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\BufferingMiddleware.cs:line 28\n   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\IfModifiedMiddleware.cs:line 41\n   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\CacheHeaderMiddleware.cs:line 33\n   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\UrlBaseMiddleware.cs:line 27\n   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Prowlarr.Http\\Middleware\\VersionMiddleware.cs:line 28\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"`

**Comment by bakerboy448** [comment]
That's just the error and stacktrace and not the trace logs that bug reports require. What was unclear on the bug report template  about requiring trace logs and the wiki link for how to get and gather trace logs?

Not a bug - Jackett reported the indexer is not available 

```
Jackett.Common.IndexerException: Exception (kinozal): Resource temporarily unavailable
---> System.Net.Http.HttpRequestException: Resource temporarily unavailable (kinozal.tv:80)
```


Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

**Comment by SuberSeb** [comment]
No, indexer was available at the moment of request, because Jackett indexer grabbed torrent successfully. Prowlarr indexer marked as failed after the unsuccessful try to grab the torrent.

Just try it yourself. I put all needed steps. It's reproduses every time.

**Comment by bakerboy448** [comment]
It's not a Prowlarr error.

Look at the stack trace the error comes directly from Jackett.

Jackett is saying the indexer is not available and returning the data to Prowlarr.

**Comment by SuberSeb** [comment]
So how it can be a Jackett error if that error only appears when using Prowlarr? And not in Sonarr if I'm using that indexer directly from Jackett? Prowlarr fails every time when trying to grab the release and direct using of Jackett indexer works completely stable at the same time.

If that error in Jackett, indexer itself or whatever else except Prowlarr, then none of that services would working.

Please check that issue.

**Comment by bakerboy448** [comment]
All the error - and not logs - you provided indicates was that when Prowlarr made a valid torznab request that Jackett indicated the  indexer is down and not available.

Errors indicating that Jackett reporting the indexer is unavailable for a valid torznab request is an exception and not a bug. Nothing at all is broken in Prowlarr based on the error - again not logs - that you provided.

For the third time now - please provide the required trace logs of the issue.

Based on the error information provided so far there is no bug and nothing to fix or investigate.

**Comment by bakerboy448** [comment]
Cannot reproduce with a different indexer - BTN via Jackett

Prowlarr Torznab working as expected.  No bug with Prowlarr's torznab handling. 

Post the logs requested here, but otherwise for further discussion on this SUPPORT ISSUE seek out Jackett's support methods as it does not appear to be anything related to Prowlarr.

**Comment by SuberSeb** [comment]
I don't have any issues with another indexers either (12 indexers or so). Just Kinozal.

Add Kinozal from Jackett, then search something, hit Download button and you got error. If I download exact the same file from Jackett itself or from Sonarr using Jackett, it works fine. This can be easily reproduced.

I will provide logs soon.

**Comment by SuberSeb** [comment]
Check the logs https://privatebin.net/?4173b6fdefbfe166#HZEyYxLqoeVruKHEfaAJGL9SMTeeYouCqmWxNrJkfoey

**Comment by bakerboy448** [comment]
You're blocked by cloudflare and will not receive any updates.

> 2022-03-16 15:18:07.0|Warn|HttpClient|HTTP Error - Res: [GET] https://prowlarr.servarr.com/v1/notification?version=0.2.0.1448&os=linuxmusl&arch=X64&runtime=netcore&branch=develop: 403.Forbidden
error code: 1020

Your IP is being detected as Russia or from Belarus and this is blocked.  If your IP isn't from there then it's incorrectly geo-located by cloudflare's provider https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-Cloudflare-IP-Geolocation#12345683

—-- 

The issue is Jackett is returning a link with a redirect; Prowlarr follows that link and gets a magnet link which is not expected.

```
2022-03-16 15:18:27.6|Trace|Http|Req: 1031 [GET] /5/download?apikey=(removed)&link=ZHdFdmU4bkxyVFVTaVJFektPOWZCekxvYWRWWHp3TFNXN0JUZFZjYUIxdGd5cGlQRTUzZFBZZTcxNDZwVE5yU3VQcVBCTGxpdVkzaGZENTlNYXQ5L2p3czg4RThJemtFc2U0SVRyM3BhWTNDL2VkQTc2M1Ziam9mRmFvdkthUDhvM2F4VlhEaGZkcG5BWkFuTTJVa0VaRlhTeTROaWJuYzFVcDBjZVgwSWlYdEVZekdmV0NuVGZjM0syZ0w0NW1oeFBIczFsMWlvb1hadyttYWthR3phQjFjTDFDRDlQSnJCYVdCcURBV2EzZmNpSlhVZVpyQU83MUdDSG1GbjZ4dXN5MjRVakF3NGc5ODl0VjF0c0NyOSsrN2RmTWFnNnozSnZ3eUJ6RE9SNC9JQ09aNjBWbllkaVNNT0NrQ0UyaGtSeVFRclZxMHhFL0tCVjJtb1M0REJDWDJzczJiM0EvL3J6RmNFZ2EyY2IrZ2d3K3dFdWhRdkVFODZRNmVXd2pCTGlxQ2lzNG9iK2I2REY3V2YzK2dTWUtmaEFUS254SzIzSnVNUjZxcVQrS2taUVhwRVVuTXR2SWNtMG5PbUg1enNxSmp6RGc2VFIwYmMrZVBCaEN1RE94aFJzVTFMNGlqMC9RdDVJQ3BuRUpwS0ZlYWlFSnNmOW5GWm9ldDhUdnpJN1ZiUU5Jc1BxNXE4ZlhOckNabzFRPT0&file=++++Blue+Bloods+-+S10E1-19+-+rus++(ColdFilm)+WEBRip (from 192.168.1.47)
2022-03-16 15:18:27.6|Trace|IndexerHttpClient|Req: [GET] http://192.168.1.45:9117/dl/kinozal/?jackett_apikey=(removed)&path=Q2ZESjhQdmhhVC1xUGJSSGhILURRMUdpV3hVZElQRWxqMkk0bFhFb3lrXzhadGlERXBrajJ0bFd1Z0l0UVhiMml4ZV83bU5nTDdSUFJXQjE4Uy1hN1E0U3RJN2REa1lZWjZLeERHSXlLb2NnLUxRNlNjUlZicEFyZWRUTzlWT1hRbFA0dS05YkEzc0V2VzU4WVZZOGM5aUtjUXpkSGFOUUNET3VDWVJnVzgtWmpxRGw&file=++++Blue+Bloods+-+S10E1-19+-+rus++(ColdFilm)+WEBRip
2022-03-16 15:18:27.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-03-16 15:18:28.3|Trace|IndexerHttpClient|Res: [GET] http://192.168.1.45:9117/dl/kinozal/?jackett_apikey=(removed)&path=Q2ZESjhQdmhhVC1xUGJSSGhILURRMUdpV3hVZElQRWxqMkk0bFhFb3lrXzhadGlERXBrajJ0bFd1Z0l0UVhiMml4ZV83bU5nTDdSUFJXQjE4Uy1hN1E0U3RJN2REa1lZWjZLeERHSXlLb2NnLUxRNlNjUlZicEFyZWRUTzlWT1hRbFA0dS05YkEzc0V2VzU4WVZZOGM5aUtjUXpkSGFOUUNET3VDWVJnVzgtWmpxRGw&file=++++Blue+Bloods+-+S10E1-19+-+rus++(ColdFilm)+WEBRip: 302.Redirect (667 ms)
2022-03-16 15:18:28.3|Trace|IndexerHttpClient|Redirected to magnet:?xt=urn:btih:6AD7731C030B4A570081344158F6B60942E8F441&dn=Blue.Bloods.S10.400p.ColdFilm&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker1.itzmx.com%3A8080%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce
2022-03-16 15:18:28.3|Trace|IndexerHttpClient|Req: [GET] magnet:?xt=urn:btih:6AD7731C030B4A570081344158F6B60942E8F441&dn=Blue.Bloods.S10.400p.ColdFilm&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker1.itzmx.com%3A8080%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce
2022-03-16 15:18:28.3|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IIndexer>
2022-03-16 15:18:28.3|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> -> IndexerStatusController
2022-03-16 15:18:28.3|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> <- IndexerStatusController
2022-03-16 15:18:28.3|Error|Torznab|Downloading torrent failed
2022-03-16 15:18:28.5|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2022-03-16 15:18:28.3|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.2.0.1448] System.NotSupportedException: The URI prefix is not recognized.
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 129
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 145
```

If you enable Redirect for that tracker in Prowlarr it should work fine as it'll redirect the link to \*Arr and not try to grab and proxy it.

@Qstick This expected or what's the best way to handle this? 

Reopening / updating title for now pending further triage

**Comment by bakerboy448** [comment]
> Also what means that Servarr API is blocked?

What do you mean? The Team has decided due to current events to block Russian and Belarusian IPs.

Since you're blocked that means:

- no indexer definition updates
- no app updates 
- no server side messages if we push one

The latter two apply to Radarr/Readarr/Lidarr as well.
