### ISSUE TITLE
New Windows install fails with UnauthorizedAccessException

### ISSUE THREAD

**Issue by VulcanTourist** [Prowlarr/Prowlarr#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following a brand new Windows 11 x64 installation, attempting to run it results in

```
Epic Fail!
UnauthorizedAccessException: System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Prowlarr\config.xml' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at NzbDrone.Common.Disk.DiskProviderBase.WriteAllText(String filename, String contents) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 313
   at NzbDrone.Core.Configuration.ConfigFileProvider.SaveConfigFile(XDocument xDoc) in D:\a\1\s\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 372
   at NzbDrone.Core.Configuration.ConfigFileProvider.SetValue(String key, Object value) in D:\a\1\s\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 296
   at NzbDrone.Core.Configuration.ConfigFileProvider.<>c__DisplayClass73_0.<GetValue>b__0() in D:\a\1\s\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 267
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 103
   at NzbDrone.Core.Configuration.ConfigFileProvider.GetValue(String key, Object defaultValue, Boolean persist) in D:\a\1\s\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 250
   at NzbDrone.Core.Configuration.ConfigFileProvider.get_LogLevel() in D:\a\1\s\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 193
   at NzbDrone.Core.Instrumentation.ReconfigureLogging.Reconfigure() in D:\a\1\s\src\NzbDrone.Core\Instrumentation\ReconfigureLogging.cs:line 29
   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, ProwlarrErrorPipeline errorHandler) in D:\a\1\s\src\NzbDrone.Host\Startup.cs:line 224
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1 arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHos
```

### Expected Behavior

Application should have read/write access to ProgramData and be able to at least do *something*.

### Steps To Reproduce

1. In Windows, run the Prowlarr.develop.0.2.0.1448.windows-core-x64-installer.exe installer file;
2. choose to not install as a service or execute automatically;
3. when install is complete, allow application to launch;
4. see huge error dialog immediately.

### Environment

```markdown
- OS: Windows 11 64-bit build 22000.556
- Prowlarr: 0.2.0.1448
- Docker Install: n/a
- Using Reverse Proxy: no
- Browser: Firefox 98.0.1
```

### What branch are you running?

Develop

### Trace Logs?

prowlarr.txt contents:
```
2022-03-16 18:20:51.2|Info|Bootstrap|Starting Prowlarr - C:\ProgramData\Prowlarr\bin\Prowlarr.Console.exe - Version 0.2.0.1448
2022-03-16 18:20:52.4|Info|UtilityModeRouter|Application mode: UninstallService
2022-03-16 18:20:52.4|Info|ConsoleApp|Exiting main.
2022-03-16 18:21:03.9|Info|Bootstrap|Starting Prowlarr - C:\ProgramData\Prowlarr\bin\Prowlarr.Console.exe - Version 0.2.0.1448
2022-03-16 18:21:04.2|Info|UtilityModeRouter|Application mode: RegisterUrl
2022-03-16 18:21:04.6|Info|ConsoleApp|Exiting main.
2022-03-16 18:23:49.2|Info|Bootstrap|Starting Prowlarr - C:\ProgramData\Prowlarr\bin\prowlarr.console.exe - Version 0.2.0.1448
2022-03-16 18:23:49.4|Info|UtilityModeRouter|Application mode: UninstallService
2022-03-16 18:23:49.5|Info|ConsoleApp|Exiting main.
2022-03-16 18:27:18.6|Info|Bootstrap|Starting Prowlarr - C:\ProgramData\Prowlarr\bin\Prowlarr.Console.exe - Version 0.2.0.1448
2022-03-16 18:27:19.8|Info|UtilityModeRouter|Application mode: UninstallService
2022-03-16 18:27:19.8|Info|ConsoleApp|Exiting main.
2022-03-16 18:27:28.7|Info|Bootstrap|Starting Prowlarr - C:\ProgramData\Prowlarr\bin\Prowlarr.Console.exe - Version 0.2.0.1448
2022-03-16 18:27:28.9|Info|UtilityModeRouter|Application mode: RegisterUrl
2022-03-16 18:27:29.1|Info|ConsoleApp|Exiting main.
```

Config.xml contents:
```
<Config>
  <Port>9696</Port>
  <EnableSsl>False</EnableSsl>
</Config>
```

[AB#2801](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2801)

**Comment by bakerboy448** [comment]
> Report a new bug, if you are not 100% certain this is a bug please go to our Reddit or Discord first

Exceptions are not bugs.  This is also covered in the Installation docs in a large orange box.

https://wiki.servarr.com/prowlarr/installation#windows

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.
