### ISSUE TITLE
Lots of false positives

### ISSUE THREAD

**Issue by well0549** [Prowlarr/Prowlarr#902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I really like the idea of Prowlarr and want to switch from jacket... But i cannot because of th epoor results in prowlarr. Whgy do i get so many fals epositives compared to Jackett....
![prowlarr](https://user-images.githubusercontent.com/2751684/159548288-352e1a4c-880e-443e-b646-a960896618d2.png)
![Jackett](https://user-images.githubusercontent.com/2751684/159548323-ec4621ea-63ea-4560-9cc9-83b74075bab8.png)

### Expected Behavior

Well a list more to the point, matching the serach criteria -> Pablo Escobar el patron del mal 20212

### Steps To Reproduce

Well i have jackett container set up and a prowlarr container.
Type search in both and you get quite different results.

On the first page lot's of the fals eposives come from eztv, but this was included in the Jackett search as well

### Environment

```markdown
- OS: 
- Prowlarr:
- Docker Install: Yes
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

2022-03-22 20:20:12.9|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.1.2:8702/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2022-03-22 20:20:13.0|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.1.2:8702/api/v3/indexer]
2022-03-22 20:20:13.0|Info|ReleaseSearchService|Searching indexer(s): [The Pirate Bay] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2020, 2040, 2060]
2022-03-22 20:20:13.0|Info|Cardigann|Adding request: https://apibay.org/precompiled/data_top100_recent.json
2022-03-22 20:20:13.9|Warn|HttpClient|HTTP Error - Res: [PUT] http://192.168.1.2:8702/api/v3/indexer/3: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2022-03-22 20:20:13.9|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [PUT] at [http://192.168.1.2:8702/api/v3/indexer/3]
2022-03-22 20:20:13.9|Info|ReleaseSearchService|Searching indexer(s): [BigFANGroup] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2060, 2010, 2040, 2070]
2022-03-22 20:20:13.9|Info|Cardigann|Adding request: https://bigfangroup.org/browse.php?search=&cat=0&incldead=1&ajax=1&year=0&format=0&s=added&d=desc
2022-03-22 20:20:18.1|Info|ReleaseSearchService|Searching indexer(s): [BitSearch] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2022-03-22 20:20:18.1|Info|Cardigann|Adding request: https://bitsearch.to/search?q=&sort=date&order=desc
2022-03-22 20:20:31.7|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.1.2:8702/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2022-03-22 20:20:31.7|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.1.2:8702/api/v3/indexer]
2022-03-22 20:20:31.8|Info|ReleaseSearchService|Searching indexer(s): [Isohunt2] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2022-03-22 20:20:31.8|Info|Cardigann|Adding request: https://isohunt.tv/torrents?ihq=&iht=0&age=0&Torrent_sort=seeders
2022-03-22 20:20:32.4|Info|ReleaseSearchService|Searching indexer(s): [LimeTorrents] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2022-03-22 20:20:32.4|Info|Cardigann|Adding request: https://www.limetorrents.pro/latest100
2022-03-22 20:20:32.8|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.1.2:8702/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2022-03-22 20:20:32.8|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.1.2:8702/api/v3/indexer]
2022-03-22 20:20:32.9|Info|ReleaseSearchService|Searching indexer(s): [Rarbg] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2030, 2050, 2040, 2060, 2045]
2022-03-22 20:20:36.3|Info|ReleaseSearchService|Searching indexer(s): [kickasstorrents.to] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2022-03-22 20:20:36.3|Info|Cardigann|Adding request: https://kickasstorrents.to/new/?sortby=time&sort=desc
2022-03-22 20:20:36.4|Info|ReleaseSearchService|Searching indexer(s): [1337x, ACGsou, The Pirate Bay, AnimeTosho, BigFANGroup, BitSearch, BTSOW, EZTV, Isohunt2, LimeTorrents, Rarbg, kickasstorrents.to, Zooqle, YTS, showRSS, Torrentv, TorrentGalaxy, TorrentFunk, MovieTorrent, TorrentParadise] for Term: [pablo escobar el patron del mal 2012], Offset: 0, Limit: 0, Categories: []
2022-03-22 20:20:36.4|Info|Cardigann|Adding request: https://1337x.to/sort-search/pablo%20escobar%20el%20patron%20del%20mal%202012/seeders/desc/1/
2022-03-22 20:20:36.4|Info|Cardigann|Adding request: https://www.36dm.club/search.php?keyword=pablo%20escobar%20el%20patron%20del%20mal%202012
2022-03-22 20:20:36.4|Info|Cardigann|Adding request: https://apibay.org/q.php?q=pablo.escobar.el.patron.del.mal.2012&cat=
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://bigfangroup.org/browse.php?search=pablo+escobar+el+patron+del+mal+2012&cat=0&incldead=1&ajax=1&year=0&format=0&s=added&d=desc
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://bitsearch.to/search?q=pablo+escobar+el+patron+del+mal+2012&sort=date&order=desc
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://btsow.rest/search/pablo%20escobar%20el%20patron%20del%20mal%202012
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://eztv.yt/search/pablo%20escobar%20el%20patron%20del%20mal%202012
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://isohunt.tv/torrents?ihq=pablo+escobar+el+patron+del+mal+2012&iht=0&age=0&Torrent_sort=seeders
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://www.limetorrents.pro/search/all/pablo%20escobar%20el%20patron%20del%20mal%202012/date/1/
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://kickasstorrents.to/usearch/pablo%20escobar%20el%20patron%20del%20mal%202012/?sortby=time&sort=desc
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://zooqle.com/search?s=ns&v=t&sd=d&q=pablo%20escobar%20el%20patron%20del%20mal%202012
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://yts.mx/api/v2/list_movies.json?query_term=pablo+escobar+el+patron+del+mal+2012&limit=50&sort=date_added
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://showrss.info/other/all.rss
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://torrentv.org/search/pablo%20escobar%20el%20patron%20del%20mal%202012/s-1/
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://torrentgalaxy.to/torrents.php?search=pablo+escobar+el+patron+del+mal+2012&lang=0&sort=seeders&order=desc
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://www.torrentfunk.com/all/torrents/pablo-escobar-el-patron-del-mal-2012.html
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://movietorrent.co/?s=pablo%20escobar%20el%20patron%20del%20mal%202012
2022-03-22 20:20:36.6|Info|Cardigann|Adding request: https://torrentparadise.cc/searchA.php?f=pablo%20escobar%20el%20patron%20del%20mal%202012
2022-03-22 20:20:43.1|Warn|Cardigann|HTTP Error - Res: [GET] https://kickasstorrents.to/new/?sortby=time&sort=desc: 403.Forbidden
2022-03-22 20:20:43.2|Warn|Cardigann|https://kickasstorrents.to/new/?sortby=time&sort=desc

[v0.2.0.1448] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status Forbidden code from API request
   at NzbDrone.Core.Indexers.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannParser.cs:line 51
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174
RequestUri: https://kickasstorrents.to/new/?sortby=time&sort=desc;StatusCode: Forbidden;ContentType: text/html;ContentLength: 139;ContentSample: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

2022-03-22 20:20:43.2|Warn|HttpClient|HTTP Error - Res: [PUT] http://192.168.1.2:8702/api/v3/indexer/8: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2022-03-22 20:20:43.3|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [PUT] at [http://192.168.1.2:8702/api/v3/indexer/8]
2022-03-22 20:20:43.3|Info|ReleaseSearchService|Searching indexer(s): [Zooqle] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2022-03-22 20:20:43.3|Info|Cardigann|Adding request: https://zooqle.com/search?s=ns&v=t&sd=d&q=%20*%20category:movies,
2022-03-22 20:20:45.4|Warn|Cardigann|HTTP Error - Res: [GET] https://kickasstorrents.to/usearch/pablo%20escobar%20el%20patron%20del%20mal%202012/?sortby=time&sort=desc: 403.Forbidden
2022-03-22 20:20:45.6|Warn|Cardigann|https://kickasstorrents.to/usearch/pablo%20escobar%20el%20patron%20del%20mal%202012/?sortby=time&sort=desc

[v0.2.0.1448] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status Forbidden code from API request
   at NzbDrone.Core.Indexers.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannParser.cs:line 51
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174
RequestUri: https://kickasstorrents.to/usearch/pablo%20escobar%20el%20patron%20del%20mal%202012/?sortby=time&sort=desc;StatusCode: Forbidden;ContentType: text/html;ContentLength: 139;ContentSample: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

2022-03-22 20:20:47.7|Info|ReleaseSearchService|Searching indexer(s): [YTS] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2040, 2045, 2060]
2022-03-22 20:20:47.7|Info|Cardigann|Adding request: https://yts.mx/api/v2/list_movies.json?query_term=&limit=50&sort=date_added
2022-03-22 20:20:49.2|Info|ReleaseSearchService|Searching indexer(s): [Torrentv] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2022-03-22 20:20:49.2|Info|Cardigann|Adding request: https://torrentv.org/new.html
2022-03-22 20:20:49.5|Info|ReleaseSearchService|Searching indexer(s): [TorrentGalaxy] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2045, 2010, 2020, 2040, 2030]
2022-03-22 20:20:49.5|Info|Cardigann|Adding request: https://torrentgalaxy.to/torrents.php?c3=1&c46=1&c45=1&c42=1&c4=1&c1=1&search=&lang=0&sort=seeders&order=desc
2022-03-22 20:20:56.7|Info|ReleaseSearchService|Searching indexer(s): [TorrentFunk] for Term: [], Offset: 0, Limit: 100, Categories: [2000]
2022-03-22 20:20:56.7|Info|Cardigann|Adding request: https://www.torrentfunk.com/all/torrents/2022.html
2022-03-22 20:21:03.6|Info|ReleaseSearchService|Searching indexer(s): [MovieTorrent] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2040, 2080]
2022-03-22 20:21:03.6|Info|Cardigann|Adding request: https://movietorrent.co/?s=
2022-03-22 20:21:05.2|Info|Cardigann|Adding request: https://movietorrent.co/page/2/?s=
2022-03-22 20:21:07.3|Info|Cardigann|Adding request: https://movietorrent.co/page/3/?s=
2022-03-22 20:21:09.7|Info|ReleaseSearchService|Searching indexer(s): [TorrentParadise] for Term: [], Offset: 0, Limit: 100, Categories: [2000, 2070, 2040, 2060, 2030, 2045]
2022-03-22 20:21:09.7|Info|Cardigann|Adding request: https://torrentparadise.cc/searchA.php?f=%25
2022-03-22 20:21:14.3|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5040, 5030, 5070]
2022-03-22 20:21:14.3|Info|Cardigann|Adding request: https://1337x.to/cat/Movies/seeders/desc/1/

[AB#2839](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2839)

**Comment by bakerboy448** [comment]
- not a bug; Jackett does additional filtering in the UI after the results are returned, Prowlarr does not
- the root cause is your trackers returning poor or unrelated results for valid searches. Discuss with them that they need to improve their internal search methods.
- This is also typically only an issue with the public trackers you're using; all of which have a high tendency to lie about their seeds by huge factors when there are 0 seeds. That's in addition to their poor search support.
