### ISSUE TITLE
Radarr/Sonarr Trying to Grab release from 127.0.0.1:9696

### ISSUE THREAD

**Issue by shley008** [Prowlarr/Prowlarr#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Environment
Platform - Docker
All *arr servers on Docker running behind NGINX reverse proxy each with a root domain with contextual path.

Setup Prowlarr Apps with proper external settings as used from the internet as I do with most of the configs. Radarr/Sonarr picks up the Indexer configurations just fine, and can perform interactive/automatic searches. When trying to grab the release Radarr/Sonarr seems to be defaulted with trying to grab it from 127.0.0.1:9696 instead of any of the configured addresses.

EG configured URL paths are as follows -
Prowlarr Server
https://rootleveldomain.com/prowlarr

Sonarr Server
https://rootleveldomain.com/sonarr

When I changed the option of Prowlarr Server to the docker container's IP and port with the proper context path like http://172.17.0.8:9696/prowlarr

It works normally. 

Note that I am using Deluge. 

### Expected Behavior

When adding the indexers via prowlarr to be pushed to *arr, the release should be grabbed from https://rootleveldomain.com/prowlarr instead of 127.0.0.1:9696 which is nowhere in any config on any of the *arr servers. 

### Steps To Reproduce

Configure Environment as listed above.

Set prowlarr server option in Apps to
https;//rootleveldomain.com/prowlarr

Set *arr Server option to 
https://rootleveldomain.com/sonarr
https://rootleveldomain.com/radarr
ETC

### Environment

```markdown
- OS: Ubuntu 18.04.6
- Prowlarr: 0.2.0.1609
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: N/A
```

### What branch are you running?

Nightly

### Trace Logs?

Log from Radarr While having issue; Logs after changing the above referenced field are normal with nothing out of the ordinary. 

2022-03-24 14:46:35.9|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. Venom Let There Be Carnage 2021 720p BluRay HEVC x265

**[v4.0.5.5981] System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:9696)**
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.attemptConnection(AddressFamily addressFamily, SocketsHttpConnectionContext context, CancellationToken cancellationToken) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 296
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.onConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 272
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 186
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 99
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in D:\a\1\s\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76

[AB#2853](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2853)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

your reverse proxy is improperly configured and missing headers; see the wiki or better yet just use LSIO's SWAG instead
