### ISSUE TITLE
Value cannot be null. (Parameter 'fileKey')

### ISSUE THREAD

**Issue by MrTyton** [Prowlarr/Prowlarr#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot add in either SugoiMusic or JPopSuki - whenever I do, I get the error

```
Request Failed. POST /api/v1/indexer/test: Value cannot be null. (Parameter 'fileKey')
```

Which is rather odd - other indexers work.

### Expected Behavior

Be able to add in the indexers.

### Steps To Reproduce

OS: Unraid 6.10 rc4
Prowlarr: 0.2.0.1448
Docker Install: Yes, linuxserver
Browser: Chrome

### Environment

```markdown
- OS: 
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

```
System.ArgumentNullException: Value cannot be null. (Parameter 'fileKey')
   at NzbDrone.Core.IndexerVersions.IndexerDefinitionUpdateService.GetUncachedDefinition(String fileKey) in D:\a\1\s\src\NzbDrone.Core\IndexerVersions\IndexerDefinitionUpdateService.cs:line 214
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 104
   at NzbDrone.Core.IndexerVersions.IndexerDefinitionUpdateService.GetCachedDefinition(String fileKey) in D:\a\1\s\src\NzbDrone.Core\IndexerVersions\IndexerDefinitionUpdateService.cs:line 117
   at Prowlarr.Api.V1.Indexers.IndexerResourceMapper.ToModel(IndexerResource resource) in D:\a\1\s\src\Prowlarr.Api.V1\Indexers\IndexerResource.cs:line 117
   at Prowlarr.Api.V1.ProviderControllerBase`3.GetDefinition(TProviderResource providerResource, Boolean includeWarnings, Boolean validate) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 97
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 142
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by bakerboy448** [comment]
Please fill out the bug report properly - Especially trace logs which the bug report template links.  Just the error is not helpful nor a trace log that bug reports require.

there is also no `master` branch, so not sure how you're running a branch that doesn't exist.

**Comment by bakerboy448** [comment]
I think this was fixed in `nightly` with https://github.com/Prowlarr/Prowlarr/commit/94ef3ea88f5967b65e280b8d2214f7cce747f940

**Comment by MrTyton** [comment]
I can wait until it pushes to develop branch, see if it fixes, and then report back.
