### ISSUE TITLE
Yggtorrent change domain

### ISSUE THREAD

**Issue by Reupireup** [Prowlarr/Prowlarr#948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

yggtorrent request fail due to changed domain name :  yggtorrent.re becomes yggtorrent.la

### Expected Behavior

connection to yggtorrent working

### Environment

```markdown
- OS: 
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

[Error] Cardigann: An error occurred while processing indexer feed. https://www3.yggtorrent.re/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date 

[v0.2.0.1448] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Got redirected to another domain. Try changing the indexer URL to https://www3.yggtorrent.la/.

   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.CheckIfLoginIsNeeded(HttpResponse response) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 928

   at NzbDrone.Core.Indexers.Cardigann.Cardigann.CheckIfLoginNeeded(HttpResponse httpResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 153

   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 384

   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297

   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174

[AB#2963](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2963)

**Comment by damien2405** [comment]
Yup, need an URL Update

**Comment by Miko2708** [comment]
not work with https://yggtorrent.la ! 
you need to use https://www5.yggtorrent.la

on ubuntu you can change it manually in /var/lib/prowlarr/Definitions/yggtorrent.yml

<img width="663" alt="Capture d’écran 2022-04-11 à 15 12 01" src="https://user-images.githubusercontent.com/45120555/162746887-7a4aa1d3-8ffb-414e-bcd7-d108ff88281c.png">

**Comment by jncanches** [comment]
Even with https://www5.yggtorrent.la/, integration with sonarr is broken. Unable to get release info on manual search...

**Comment by jscoys** [comment]
Hello hello!

Is the change already available? I'm using the docker version and I don't see anything changed so far thx.

**Comment by bakerboy448** [comment]
Fixed - update your definitions 

https://github.com/Prowlarr/Indexers/commit/6e326ef61c56934a11dcc11b8bd0889cc9f01ae3
