### ISSUE TITLE
BeyondHD Error - Value was either too large or too small for an Int64

### ISSUE THREAD

**Issue by nipuna-perera** [Prowlarr/Prowlarr#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

BeyondHD tracker isn't working

### Expected Behavior

BeyondHD tracker works

### Steps To Reproduce

- Normal BeyondHD setup with API Key (Not one url)
- click on settings
- test
- Check logs to see error - Value was either too large or too small for an Int64

### Environment

```markdown
- OS: 
- Prowlarr: 0.2.0.1678
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

2022-04-16 09:30:50.1|Warn|BeyondHD|Unable to connect to indexer

[v0.2.0.1678] System.OverflowException: Value was either too large or too small for an Int64.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at NzbDrone.Core.Parser.ParseUtil.CoerceLong(String str) in D:\a\1\s\src\NzbDrone.Core\Parser\ParseUtil.cs:line 56
   at NzbDrone.Core.Indexers.Definitions.BeyondHDParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\BeyondHD.cs:line 208
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 456
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/8500117/prowlarr.txt)

[AB#2999](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2999)

**Comment by bakerboy448** [comment]
Info logs of just the error are invalid for bug reports

Need the trace logs and ideally with the indexer response on so we know the bad value as well

**Comment by Qstick** [comment]
The info is in discord @bakerboy448
