### ISSUE TITLE
HDTorrents indexer broken

### ISSUE THREAD

**Issue by LP0101** [Prowlarr/Prowlarr#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to add an hd-torrents account, it fails with the error "Unable to connect to indexer, check the log for more details"

### Expected Behavior

The indexer shouldn't fail to be added.

### Environment

```markdown
- OS: unRAID 9.2
- Prowlarr:0.2.0.1678
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Edge
```

### What branch are you running?

Master

### Trace Logs?

```
[v0.2.0.1678] NzbDrone.Common.Http.HttpException: HTTP request failed: [503:ServiceUnavailable] [POST] at [https://hdts.ru/login.php]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 115
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.ExecuteAuth(HttpRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 416
   at NzbDrone.Core.Indexers.Definitions.HDTorrents.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\HDTorrents.cs:line 68
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 388
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 456
<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style>
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
  </style>

      <meta http-equiv="refresh" content="35">
  <script>
    //<![CDATA[
    (function(){
      
      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "65256",
        cRay: "70089b823e238cb9",
        cHash: "9171f8b9f6eab86",
        cUPMDTk: "\/login.php?__cf_chl_tk=O8TcS7bOcBY_VtKDP6oL7IQ42.CxrEIcnzGzbjdRo.Y-1650737966-0-gaNycGzNBz0",
        cFPWv: "g",
        cTTimeMs: "1000",
        cRq: {
          ru: "aHR0cHM6Ly9oZHRzLnJ1L2xvZ2luLnBocA==",
          ra: "UHJvd2xhcnIvMC4yLjAuMTY3OCAoYWxwaW5lIDMuMTUuNCk=",
          rm: "UE9TVA==",
          d: "nRZruJMX3VyZ3/F0ylQsfnBI/SY+yslThKAbdzW18Xgzp259uTKnvE0j2zM7rpSC90U3R2hWgSRJTEvlXH5lyyY+cPBO/GFVwzTHKLE2uMzEzoR7R5hEL87LdCKRFx7seATiIRcLes+8pkYNd2hDwtMyLrMLs8G3JUa16dS+bXucBb24vWTnL2ws3Ht6Bat0JAKxaze92vPa3lsFJEF2+V9FQb8mLOnNGBph9To7uWeMpLejWpwlyPpI7dts3LO5GGs1oxXto55PZl8Jb31IcVeqwWzxY2MK50jkonoDzaLCOeFfuL00Q/Sq8UKTdWwesSrHQKYn8YYVXEncoqWACOm5H6zECP5S23k6eL+bXiWiS6cJKt8ZW7HoxbPVfYxq2tpmVIqqBdfDmdihlI9+wAnLBhW0TmcJnfCJTawAAkcUK8IuOYbg9Xr44eYWBTwS697CEURmKuhCxkV92qB0iI7aoKXDngIPZhO1LaTRKBvZQtMXekornpLwjrtB0ZXR9Fe7lfU3M4ABFGES0IOmxouWTs7ss5Qoi3RERdtRA4K+ouKYmsSy0kC0OhdXnGKk",
          t: "MTY1MDczNzk2Ni40MzkwMDA=",
          m: "ga5zhicm6CnCnVRBZeCsfom/vvTMEtaCdrLW/KJwXug=",
          i1: "lgmawPhNX+Mx5kOR7024rg==",
          i2: "BIEhucbX2/HB3Nbfig72SA==",
          zh: "nDNX0Y46m4k7nH75bqZpDG4IgrdjqpSYQXPH5rhWKhk=",
          uh: "2MeNdBxzlGB63VwT7qTugOBWGjo8d5epsszpcNv8FjY=",
          hh: "x5oSGAIo1KTNaK5enBBeFyD+cdk7jrOZ+lZTi+cB9lo=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};
      
    })();
    //]]>
  </script>
  

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id=(removed) style="display:none">
    
    <div id=(removed)      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> hdts.ru.</h1>
    
    <div id=(removed) class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id=(removed) >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id=(removed) style="display:none">Redirecting&hellip;</p>
  </div>
   
  <form class="challenge-form" id=(removed) action="/login.php?__cf_chl_f_tk=O8TcS7bOcBY_VtKDP6oL7IQ42.CxrEIcnzGzbjdRo.Y-1650737966-0-gaNycGzNBz0" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="md" value="G8FZugxOmg5BQ4YsaqpOrowsc.StZWVsL49z_BJm_z8-1650737966-0-AdrE6PuRC5NRv_hyneQPIM2YLAEFhL2mRPygNz94LWLNISKML9f6_gEAFgiml-COIty3pl3AXe3CFhSOrI2LN7HNk5Lq1N66irWUcl7lRq09wfKAY8qOEScBuk9lj4knS1fuq3qzWKnnZks7CNPx94Uy6ZC0iG3aIUFQcRyyNK-0uOVUCU1-8K2VKuvL4LSv_JMZBRFXe3trt8v_7byGmeLvxUc70IIrjq6h08iBaWqIdy0cgDSIfWbxppvTbmjHYG2X5PD45S1zgJ0iU9OsQ5d14VQpGgW2t1wqAM5ugBmJHjTF-bm_LfIRBOo2woYtXekp-xPjOkvgklXPq-uPyuDDQcO-DWfA0I1xZU47O_1R2rxVIB-Yap_ixyG7yhggmftwIrQRC1pP_Mf5iGz43yYksJjH9R_-lIfqL4Fqk1ioj9HpUJWoEWfoaCosiAHXIJtBzBvYtm-vgVg0efzxGB9onNq1VYQSmCNWvQrhMf-QsvwltH-vyf5hf5csq-wl6AEgMsewwu_A2cSwhpxpzpYGzCcfHIjmHl20BldoAHH7XFQbRLGgx9fNINu209VEiaKCArKOa2d7s8nDWesHLsQ3B1hWLeS8lMvPjHrBc7L6Vpt2ToaVKau8q_sWKx5Vdw" />
    <input type="hidden" name="r" value="iGFmnM.OeIkFu_ndbKB6XjeZ_FPPhCaXFSixaqhAPxs-1650737966-0-AXPq4UYAXRU32rzoazdKEpWWGA7eFDeVMucPd3IK3tou4ZN87TzR7MecnBxo0P6PZiteiNr/N/pxj3xye7PTlgckYArX04XWpJ66J3YVp9KaQIYavrtOqNMALS1M8NHdA+2DqwqVJnryp6NKsBjmlME8vL9SgACz66wmistJKKKyEEYbRusw+EqxrC9FEeXKBsWeiSwQNCXL7i3R638dT4p/un8XzwyIFd4z4V/yQmfbYxjFi1uiVCZSpKuuvxGn+12biyIytM3Wtvx1/s+crDYig8lltHYaor59LKW2FLEonrcL2XypAETkyQaGr5geREIH5vy1NCBTJrwflC/kIO+5Mkz7gg3FyM2AmCfuJk1kfB5ERt9wqFT/9/m5ju0WonyQ2bElvlWrF9FfA9kkU/s+VeF0wxVwWXp3pkKQbUsrhZssspIZHZlnymKx8Lr36SttEpqDjm6ZJ+DdK25/x+vX0p4Et3UY3X9EdJhMdcePZ862habYZJ/K73Y9rNSGdcPVPWACirBhtTS3eVxtK/xYslRuC3P/hxDIeShyL4Fmu9yHrkQCDjR8ZbLq6k2NBBUPQdCvc0jMccA8zeMydkbGI0gItA3+Pbc5o0In9dmKX8Ja9uFSWU5JIAJKQ9WR2JIfhOxJPOsly1eO9XERzWRNf6VNLZd3X61QjufxKW3kyL/zFpQl1UJO5ZjYq6bEAp5obIzRTAjCKY5ul/CyZxassx+O3QImHgUoFz+yWZCa1eid3nlxnEvzpwuELbXVkBn9VqBn2sCcZDIvBMPS2Nt7r/PqpDF21Hr0czs0pT5x9faFfECS7+8RrjdnBiZSmNlJkz3KxPaGkd25pbogLeO1GW8reP7skmeTE+yzXW94sta57ovsRRyajONsXD+dhMoB0wl35mZoT1T4WJgWjOHGmJjOjkg8P4/CzOSWn6NSmK5meVzKCVvHuG7cCyAIGlyIu/FGj1lWpvROZ9NkJZ+WU1PE0hV5+05KKN9LSQnVw39bkVMfGOPSSB0zQLGbFaqWP++/R9Kqmz3+1HTDPKCXrFPNGgi5NDlj/HVfGqDdIt2zGcnz8bxqbD8h9HSu0ecFVjqIOvaaTx4W1Xe8uB50Xjw2ghAiY0E233zUWN1IBHqRDw1lsY/kfYzMSwLRwfYrMD0LePGWuzhvytV8Pd7bOeFax4yP64iIJW97l0SS4przZ/N+IuaIdssVaociWXWmcPdQOtCNd42BQ8L2NqJ6wTYlh3OSZWIbXR6rKw7Uis/yBny+GXpDmbA6ao4x6cavuZCdp8fBBeKC8bD7k9WndOKBdL1BBrWYHC27gwTs8ica1RLUeWwmUzN+93naD1SVdA6vB2VPHvAku14/oHOMMcPCc1tMvGH+3fGVHHNXmhf8ifeBMRasz2ipgrFO0invCAuqqgxf61Y3Q+oBzYVJlRWR3p59hz4WtsVV+r45lPneBczmnh9SdiE6hDs5geCexGYuU9cNgFAM4cuY/7tM6P3KOHrsqungW08iz1vrAHe/bI2Yv2Dd4wbdSw0+TBsDU7+uK9KTxtvWpoJfFJpOtYiLgFCOdBkyQxqw4PQ45VURBoAr0gqZ/FLbJanPciV8fhZL65ug3uO8hFxmqMHtMLgZxifT6bR3OR08Wo60wYjffqErkykPdDG/axbwNiPbAsV7whV2RaR1Qqxi0O2P3Uz01yYRkHCnFwI5rm8NAaRN82dGITEhMAT7KiWkyvtSBUZVoxMXyjIRdQlfGjhHcvUx/7TSHfsFGPec4SZJhUH5G4Yt662WPXCZweZIpA=="/>
    <input type="hidden" value="cdc30a371ec664aadb8a706e97c19bfc" id=(removed) name="jschl_vc"/>
    <!-- <input type="hidden" value="" id=(removed) name="jschl_vc"/> -->
    <input type="hidden" name="pass" value="1650737967.439-ekATyWIJXG"/>
    <input type="hidden" id=(removed) name="jschl_answer"/>
  </form>
     
    <script>
      //<![CDATA[
      (function(){
          var a = document.getElementById('cf-content');
          a.style.display = 'block';
          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
          var trkjs = isIE ? new Image() : document.createElement('img');
          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=70089b823e238cb9");
          trkjs.id = "trk_jschal_js";
          trkjs.setAttribute("alt", "");
          document.body.appendChild(trkjs);
          var cpo=document.createElement('script');
          cpo.type='text/javascript';
          cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=70089b823e238cb9";
          
          window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.indexOf('?') !== -1 ? '?' : location.search;
          window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
          if (window._cf_chl_opt.cUPMDTk && window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/login.php?__cf_chl_rt_tk=O8TcS7bOcBY_VtKDP6oL7IQ42.CxrEIcnzGzbjdRo.Y-1650737966-0-gaNycGzNBz0" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
              history.replaceState(null, null, ogU);
            };
          }
          
          document.getElementsByTagName('head')[0].appendChild(cpo);
        }());
      //]]>
    </script>
  

  
  <div id=(removed) style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=70089b823e238cb9')"> </div>
</div>

          
          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>70089b823e238cb9</code></span>
          </div>
      </td>
     <a href="https://directoryblacklist.com/aslope.php?tid=828" style="display: none;">table</a>
    </tr>
  </table>
</body>
</html>



2022-04-23 14:19:26.8|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.2.0.1678] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-04-23 14:19:27.0|Warn|ProwlarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[v0.2.0.1678] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 195
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
[AB#3026](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3026)

**Comment by bakerboy448** [comment]
You're blocked by cloudflare and need flaresolverr

**Comment by LP0101** [comment]
> You're blocked by cloudflare and need flaresolverr

Odd, I never needed flaresolverr for HDTS in Jackett.

That solved it though, thank you :)
