### ISSUE TITLE
BroadcasTheNet URL is incorrect

### ISSUE THREAD

**Issue by ofolis** [Prowlarr/Prowlarr#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Prowlarr's BTN URL is set to `http://api.broadcasthe.net/` and is causing issues downstream with other programs. I do not have an option to select `https://api.broadcasthe.net/` (specified in the docs here: https://apidocs.broadcasthe.net/).

### Expected Behavior

I need a way to select `https://api.broadcasthe.net/`.

### Steps To Reproduce

1. Running Prowlarr 0.2.0.1678
2. Set up a BroadcasTheNet indexer
3. Add Sonarr as an app
4. Sync
5. Run an interactive search for season 11 of Bob's Burgers (full season)
6. See results from BroadcasTheNet
7. Click the download button for one of the BroadcasTheNet results
8. Error

I have additionally been able to get the downloads to work if I set up BTN directly in Sonarr (using HTTPS).

### Environment

```markdown
- OS: Windows 11
- Prowlarr: 0.2.0.1678
- Docker Install: N/A
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

This log is from Sonarr and is an example of the downstream issue:
```
[v3.0.8.1507] MonoTorrent.TorrentException: Invalid torrent file specified ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.MediaFiles.TorrentInfo.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\TorrentInfo\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteEpisode remoteEpisode, String torrentUrl) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 189
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteEpisode remoteEpisode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 117
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\DownloadService.cs:line 75
   at Sonarr.Api.V3.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:line 129
   at Sonarr.Api.V3.Indexers.ReleaseModule.<.ctor>b__10_2(Object x) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:line 65
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__22.MoveNext()
```

[AB#3100](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3100)

**Comment by bakerboy448** [comment]
plenty of users have no issue with torrents from BTN; seems this just stopped working on 5/1/2022

also for future reference:

- there is no master branch, so it's impossible to be running that branch
- Just the error spew is/are not valid for bug reports.

**Comment by ofolis** [comment]
Cool my bad, first report on this repo.

And yeah, everything was working for me before today. There is a workaround (setting it up in the individual apps), but figured you'd want to know.

Thanks!
